### PR TITLE
Fixes how Batch Processing Add/Set values behave when count of entries in AdjusterBehavior in options file does not match ADDSET_PARAM_NUM, #2710

### PR DESCRIPTION
**Pull request by Beep6581**

### CODE REVIEW

**Comment by Beep6581** [comment]
Please review this.

**Comment by Beep6581** [comment]
@heckflosse @Hombre57 @Floessie @agriggio reminder that this needs review.

**Comment by agriggio** [comment]
what exactly needs to be reviewed? The patch seems straightforward, if it works I'd say :+1:

**Comment by Beep6581** [comment]
Well I know nothing about C++ so the whole thing needs someone who speaks the language to take a look :)

It seems to work fine here.

Since you gave it a thumbs up (thank you), I'll merge.

**Pull request merged**
