### PR TITLE
 Add frames to lens profile panel & Bugfix batch mode

### PR DESCRIPTION
**Pull request by TooWaBoo**
unbenannt unbenannt2

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Fixed bug **Profiled Lens Correction does not seem to use (Unchanged) mode in Batch Edit**
https://github.com/Beep6581/RawTherapee/issues/5002

**Comment by Thanatomanic** [comment]
Good work! I'll give it a testrun tomorrow.

**Comment by TooWaBoo** [comment]
Found 3 other bugs.
1. Lensfun "Auto & Manuel mode" don't work in batch mode.
2. "Unchanged" radio does not get active when multiple images are selected.
3. If a profile is applied with active "Auto mode" on, it will always show the camara and lens from the profile.

Right now I could fix the Lensfun "Auto & Manuel mode". (Not uploaded yet)

**Comment by TooWaBoo** [comment]
`Batch mode` and` profile` and `Unchanged radio` are working now.
Changes: 
If `Lensfun Auto` is selected no lenses or camaras are saved to or read from the pp3 or profile. It's always fetched from the database.
`Lensfun Auto` in batch mode will not show the lens- and camera-combobox.

Ready for test.

**Comment by Beep6581** [comment]
Great! Will test in the evening.

**Comment by TooWaBoo** [comment]
Added inconsistent state to checkboxes.

**Pull request merged**
