### PR TITLE
fixes macOS autobuild

### PR DESCRIPTION
**Pull request by Benitoite**
Yields a vanilla `.dmg` and a woking `RawTherapee.app/Contents/MacOS/rawtherapee-cli`
No code-signature or notarization.

### CODE REVIEW

**Review by Benitoite — COMMENTED** [review]
The macOS *Catalina* default `zsh` has floating point numbers whereas `bash` does not. 🐙 The yaml must be bringing in `bash` as a rule. Since this runs on `Darwin 19` aka *Catalina* we could raise a `zsh` to get floating point...

**Comment by Benitoite** [comment]
The log now reports versions of `brew` pours.
```
2020-02-28T11:14:40.1385800Z Fri Feb 28 11:14:40 UTC 2020
2020-02-28T11:14:40.1388570Z ----====Pourage====----
2020-02-28T11:14:40.1419370Z ==> Pouring libtiff-4.1.0.catalina.bottle.tar.gz
2020-02-28T11:14:40.1419920Z ==> Pouring atk-2.34.1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1420340Z ==> Pouring gdk-pixbuf-2.40.0.catalina.bottle.tar.gz
2020-02-28T11:14:40.1420890Z ==> Pouring gsettings-desktop-schemas-3.34.0_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1421380Z ==> Pouring hicolor-icon-theme-0.17.catalina.bottle.tar.gz
2020-02-28T11:14:40.1421880Z ==> Pouring libepoxy-1.5.4.catalina.bottle.tar.gz
2020-02-28T11:14:40.1422290Z ==> Pouring fontconfig-2.13.1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1423110Z ==> Pouring lzo-2.10.catalina.bottle.tar.gz
2020-02-28T11:14:40.1424140Z ==> Pouring pixman-0.38.4.catalina.bottle.tar.gz
2020-02-28T11:14:40.1424610Z ==> Pouring cairo-1.16.0_2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1425020Z ==> Pouring fribidi-1.0.8.catalina.bottle.tar.gz
2020-02-28T11:14:40.1425420Z ==> Pouring graphite2-1.3.13.catalina.bottle.tar.gz
2020-02-28T11:14:40.1425800Z ==> Pouring harfbuzz-2.6.4.catalina.bottle.tar.gz
2020-02-28T11:14:40.1426200Z ==> Pouring pango-1.44.7.catalina.bottle.tar.gz
2020-02-28T11:14:40.1426600Z ==> Pouring gtk+3-3.24.14.catalina.bottle.tar.gz
2020-02-28T11:14:40.1426990Z ==> Pouring libsigc++@2-2.10.2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1427820Z ==> Pouring glibmm-2.62.0.catalina.bottle.tar.gz
2020-02-28T11:14:40.1428230Z ==> Pouring atkmm-2.28.0_2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1428630Z ==> Pouring cairomm-1.12.2_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1429020Z ==> Pouring pangomm-2.42.0_2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1429400Z ==> Pouring gtkmm3-3.24.2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1429810Z ==> Pouring gtk+-2.24.32_3.catalina.bottle.1.tar.gz
2020-02-28T11:14:40.1430230Z ==> Pouring gtk-mac-integration-2.1.3_3.catalina.bottle.tar.gz
2020-02-28T11:14:40.1430620Z ==> Pouring libcroco-0.6.13_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1431010Z ==> Pouring librsvg-2.46.4.catalina.bottle.tar.gz
2020-02-28T11:14:40.1431420Z ==> Pouring adwaita-icon-theme-3.34.3.catalina.bottle.tar.gz
2020-02-28T11:14:40.1431830Z ==> Pouring libsigc++-3.0.2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1432220Z ==> Pouring little-cms2-2.9.catalina.bottle.1.tar.gz
2020-02-28T11:14:40.1432610Z ==> Pouring libiptcdata-1.0.4_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1433030Z ==> Pouring hwloc-2.1.0.catalina.bottle.tar.gz
2020-02-28T11:14:40.1433430Z ==> Pouring open-mpi-4.0.2.catalina.bottle.tar.gz
2020-02-28T11:14:40.1433820Z ==> Pouring fftw-3.3.8_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1434210Z ==> Pouring lensfun-0.3.95_1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1434940Z ==> Pouring expat-2.2.9.catalina.bottle.tar.gz
2020-02-28T11:14:40.1435430Z ==> Pouring pkg-config-0.29.2.catalina.bottle.1.tar.gz
2020-02-28T11:14:40.1435830Z ==> Pouring libomp-9.0.1.catalina.bottle.tar.gz
2020-02-28T11:14:40.1436220Z ==> Pouring shared-mime-info-1.15.catalina.bottle.tar.gz
2020-02-28T11:14:40.1539860Z Completed installation of dependencies in 2.78 minutes
```

**Comment by Beep6581** [comment]
@Benitoite is this ready for merging? If so, do you want it just merged, or also squashed, to improve readability?

**Comment by Benitoite** [comment]
@Beep6581 Yes, you may squash and merge at this point.

**Pull request merged**
