### PR TITLE
Merge Pentax pixelshift into dev

### PR DESCRIPTION
**Pull request by heckflosse**
I want to merge this branch into dev.
But I also would like to get reviews from other contributors.

Some notes:

1. There are some parts of code which are #ifdefed by `PIXELSHIFTDEV`. This is needed because I wanted to give a clean gui to users but also we (Ilias and I) need the possibility to use more features for our tests and further development of pixelshift.
2. I made some changes to guiutils.h For this changes I greatly would appreciate a review from @Hombre57 and @Floessie because your skills are better than my skills for that kind of stuff!!!
3. I also absolutely don't mind to get reviews of code in pixelshift.cc (but please forgive me that there is one section (the one #ifdefed by  __OLDPS__) which does not need to be reviewed (I only need it to probably go back to faster code once pixelshift is completed) and also the #ifdefed by `PIXELSHIFTDEV` code does not need to be reviewed atm.

Ingo

### CODE REVIEW

**Comment by agriggio** [comment]
@heckflosse if you think I can be of help in some way, just let me know

**Comment by heckflosse** [comment]
@agriggio Some tests would be very welcome :)
Here are [two pixelshift files](https://filebin.net/c93hy8qmkghuupeb)
To use pixelshift, go to raw tab and select pixelshift instead of amaze.
There are three options for motion correction (Off, Automatic, Custom)
In custom mode you get a lot of new options. Just play a bit with all the stuff...

**Comment by agriggio** [comment]
@heckflosse I'll do my best to stress the code :smile:

**Comment by sguyader** [comment]
@heckflosse  Ingo, just for the heck of it, I compiled the psgtk3 branch and tested it with the 2 pixelshift files you uploaded (of course I can't review the code).
It seems to work fine, though I have a question: am I sight-impaired or did I miss something? Because I couldn't see the difference in detail in non moving areas between amaze and pixelshift.

**Comment by agriggio** [comment]
@heckflosse I also did some (limited) testing, and I agree with @sguyader. However, I'm totally unfamiliar with pixelshift, so I am not really sure about what is the expected output compared to amaze. Can you clarify please?

**Comment by heckflosse** [comment]
@sguyader In the file with the van look bottom left at the yellow threads to see the difference.

Here are two screen shots. Left is pixelshift, right is amaze
ps_001

ps_002

**Comment by agriggio** [comment]
@heckflosse can you post a pp3 and maybe a crop showing the difference? It seems I need some help, or a new pair of glasses :smile:

**Comment by heckflosse** [comment]
@agriggio I updated the screen shots. pp3 was neutral + pixelshift automatic / amaze. Edit: Auto-Levels in exposure was enabled too

Can't you see the difference?

**Comment by agriggio** [comment]
@heckflosse I see them now, thanks! (very easy to miss if you don't know what you are looking for...)

**Comment by heckflosse** [comment]
@agriggio Yes, I also have some better files but I'm not allowed to share them. For the files from above I have the rights to share them.

**Comment by agriggio** [comment]
@heckflosse :+1: 
I played a bit with the settings, mostly randomly. I did not see anything "strange" (keep in mind though that I  have no idea what most of the settings are supposed to do...). However, no crashes!

**Comment by heckflosse** [comment]
> keep in mind though that I have no idea what most of the settings are supposed to do...

That does mean I have to improve the tooltips...

**Comment by agriggio** [comment]
I think the tooltips are fine. What I meant is that I am not sure what visible effect the various options are supposed to show...

**Comment by heckflosse** [comment]
@agriggio I see. I have to document the whole thing in rawpedia asap. Thanks for testing :+1:

**Comment by agriggio** [comment]
one (unrelated) question: do you think the fast export mode should use amaze instead of pixelshift?

**Comment by heckflosse** [comment]
@agriggio Yes, for most use cases I think we can use Amaze instead of pixelshift for fast export. Though maybe use lmmse instead of Amaze when `use lmmse` in pixelshift options is enabled.

**Comment by agriggio** [comment]
:+1:

Il 14 Mar 2017 22:33, "Ingo Weyrich" <notifications@github.com> ha scritto:

**Pull request merged**
