### PR TITLE
Rtsurface cleanup

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

A month ago I did this minor cleanup branch. Maybe this should go into 5.7 as I found a little bug on the way.

Best,
Flössie

### CODE REVIEW

**Comment by heckflosse** [comment]
I tested today. Works fine here. :+1:

**Comment by Hombre57** [comment]
Ouch, forgot about it completely. Too late for today, so I'll have a look tomorrow.

**Comment by Floessie** [comment]
Woohoo! I can log in without "device verification code" again. :tada: Let's hope it stays that way...

@heckflosse Thanks! :+1: 
@Hombre57 No  problem.

**Review by Hombre57 — APPROVED** [review]

**Comment by Floessie** [comment]
@Hombre57 Thanks for the review. Merged.

**Pull request merged**
