### PR TITLE
5.11 Release Candidate 1

### PR DESCRIPTION
**Pull request by Lawrence37**

### CODE REVIEW

**Comment by Benitoite** [comment]
Has this included #7166 ?

**Comment by Lawrence37** [comment]
@Benitoite It does not. Let me know if that PR is ready and I will merge it into `release-5.11`.

**Comment by Benitoite** [comment]
@Lawrence37 it is ready, you may merge.

**Comment by Lawrence37** [comment]
It's time for release candidate 1. I will make an announcement after the builds are complete.

@Benitoite If you plan to provide a macOS package soon, let me know so I can wait before making the announcement.

**Comment by Benitoite** [comment]
@Lawrence37 I will be generating a build in the next hour.

**Comment by Benitoite** [comment]
@Lawrence37 My build is here: https://github.com/kd6kxr/RawTherapee-5.11-rc1/releases/download/5.11-rc1/RawTherapee_5.11-rc1_macOS_12.3_Universal.zip

**Comment by Lawrence37** [comment]
Thank you @Benitoite! I made the announcement here: https://discuss.pixls.us/t/rawtherapee-5-11-release-candidate-1/45076

**Pull request merged**
