### PR TITLE
Moved histogram working/output profile settings

### PR DESCRIPTION
**Pull request by okoncevoy**
Moved the histogram working/profile setting checkbox (in previous) from the preferences to an editor tool bar panel. Now it can be toggled by the dedicated toggle button and result can be seen on the fly.

### CODE REVIEW

**Comment by Beep6581** [comment]
@Hombre57 looks good to me, +1 for merge?

**Comment by Hombre57** [comment]
@Beep6581 I returned late from work and didn't even started my computer, I'll check the PR tomorrow.

**Comment by agriggio** [comment]
:+1: for merging

**Review by Beep6581 — APPROVED** [review]
:+1:

**Comment by Beep6581** [comment]
Hah, so that's what that does.

**Review by Hombre57 — CHANGES_REQUESTED** [review]
Please move `void histogramProfile_toggled ();` to Private section as event handler doesn't need to be called outside of the class. I know that we're not that pedantic in RT, but it's just to get good habits... ;)

**Comment by okoncevoy** [comment]
@Hombre57 Done. Placed this method near others toggle's in previous. Now it is private

**Review by Hombre57 — APPROVED** [review]

**Comment by Hombre57** [comment]
Anyone to press that "Merge" button ? 🙂

**Comment by Beep6581** [comment]
Thank you @lvreclp !

**Comment by okoncevoy** [comment]
@Beep6581 you are welcome.

**Pull request merged**
