### PR TITLE
Option for disabling noise reduction gain

### LINKED ISSUE #6759: Luminance Noise Reduction not applying to very dark images
**Short description**
I have noticed a consistent behaviour where the noise reduction in RT 5.9 does not apply to very dark images. In my example, the two images provided are shot with the same exposure settings, but with slightly different total brightness (due to the building lights). It appears to me that the image is sufficiently dark that the luminance slider, even at Gamma 1.0, doesn't affect the noise.

The screenshot below is a comparison of the 2 images provided, processed with the same settings.
image

**Steps to reproduce**
1. Navigate to the location you downloaded the provided images to
2. Apply the provided PP3 Profile to both images
4. Export each image as a TIFF file at full resolution.
5. Compare the noise between both images at 1:1. You will notice a big difference between the noise (in the dark areas in particular.)

**Expected behavior**
Given that the overall exposure appears to be similar between these two images, and the camera settings were exactly the same. I would expect the noise reduction to be similar.

**Additional information**

Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 12.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.6-341.x86_64 x86_64
Build date: Sun, 27 Nov 2022 18:38:56 +0000 UTC
Build epoch: 1669574336
Build UUID: 9d19d210-c668-4aa2-8af6-2d527fd55d1c

** Provided Files**
https://drive.google.com/drive/folders/1tyaGv_CVTk7fQThi9KhNov771hV20zv0?usp=sharing

### PR DESCRIPTION
**Pull request by Lawrence37**
The noise reduction tool has two ways to tune the overall noise reduction strength based on lightness. Gamma changes the distribution between light and dark areas and is user-adjustable. Gain strengthens or reduces the strength on the whole image. Gain is completely automatic, reducing strength for dark images and increasing it for light images.

This adds a checkbox for disabling the gain. The purposes are to improve noise reduction in cases where the automatic gain is far from ideal, and to provide a way to consistently apply a set amount of noise reduction to a series of similar images. The checkbox is enabled by default, which instructs RawTherapee to apply the automatic gain.

image

Closes #6759.

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 

I think, it's a good choice.

Jacques

**Comment by Lawrence37** [comment]
I will merge this soon.

**Comment by Beep6581** [comment]
@Lawrence37 could you also add a note to the docs?
http://rawpedia.rawtherapee.com/Noise_Reduction

**Comment by Congles** [comment]
Keenly awaiting this, thanks for your efforts in improving this.

**Comment by Beep6581** [comment]
@Lawrence37 if you merge, could you also include this in the 5.10 branch?

**Comment by Lawrence37** [comment]
I intended this for whatever comes after 5.10, but I'm willing to merge it to 5.10 if it's desirable. If I'm not quick enough to merge it before the release, I'm fine with leaving it out. This doesn't need to be a blocker.

**Comment by Lawrence37** [comment]
Merged to `dev` and cherry-picked to `release-5.10`.

**Comment by Beep6581** [comment]
Great.

**Pull request merged**
