### PR TITLE
added support for user-specific DCP and input ICC profiles dirs

### PR DESCRIPTION
**Pull request by agriggio**
Look for direcories `dcpprofiles/` and `iccprofiles/input/` under `Options::rtdir`
(typically something like `$HOME/.config/RawTherapee`)

### CODE REVIEW

**Comment by Floessie** [comment]
Alberto, I've fiddled in exactly the same region for #4500, so we should coordinate the merging a bit. I'd suggest, @Beep6581 tests this first, so you can quickly merge and I'll resolve the conflicts in my branch then.

**Comment by agriggio** [comment]
@Floessie thanks for the warning! As you wish though -- I don't mind merging later if you prefer

**Comment by Floessie** [comment]
@agriggio No problem, you can go first. :+1:

**Comment by iliasg** [comment]
Not sure which is the better solution but ..
There is a conflict with model names under different tags ..
In DNGs and DCPs
0xc614 | UniqueCameraModel
In DNGs 
0xc615 | LocalizedCameraModel
In Canon maker data each model is globally identified at "CanonModelID" tag 
0x0010 | CanonModelID | int32u
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html#CanonModelID
(where we can take a full list for use ..)
Dcraw.c makes use of this list in a table which we (RT) do not maintain any more .. :( 

Same with Sony 0xb001 | SonyModelID | int16u
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/Sony.html#SonyModelID

I failed to locate such a table for Panasonic ..

**Comment by Beep6581** [comment]
Please keep #3801 in mind. RT's metadata support is slowly rusting away and IMHO movement in any direction other than adopting an actively maintained external metadata library should be considered a temporary workaround.

**Comment by agriggio** [comment]
@Beep6581 ok, but this PR has nothing to do with metadata per se. It merely adds the option to replace an "auto matched" DCP/ICC profile with a custom one without overwriting the original, or to add custom DCP/ICC profiles that RT doesn't ship yet and have them play nicely with the existing "auto matching"

**Comment by gaaned92** [comment]
```
Look for direcories dcpprofiles/ and iccprofiles/input/ under Options::rtdir
(typically something like $HOME/.config/RawTherapee)
```
According to above, where these dirs should be located on W10?
I think they should be subdirs of the "config folder"?

**Comment by agriggio** [comment]
@gaaned92 I think so, yes, but I don't have a windows machine to test... the dirs are relative to the bundle dir I think

**Comment by gaaned92** [comment]
@agriggio 
I tested and effectively on W10 it is %LOCALAPPDATA%/\<config folder\>/dcpprofiles

**Comment by agriggio** [comment]
anyone against merging?

**Comment by Beep6581** [comment]
@agriggio no objections.

**Pull request merged**
