### PR TITLE
NR Median now works independently of lumiance details, #4208

### PR DESCRIPTION
**Pull request by Beep6581**

### CODE REVIEW

**Comment by Desmis** [comment]
@Beep6581 
I'm a little lost ... certainly I formatted the code with "astyle",... but should not it already be done (the changes are only "unpad-paren", except of course the current change) .

Why do all this? is it for educational purposes? or for something else?  :)

**Comment by Beep6581** [comment]
@Desmis I'm not sure I understand what you're asking. If it's why I cleaned up the commit, it's so that functional code changes are clearly visible when viewing the commit (today, a month from now, a year from now). Stylistic and formatting changes which don't make functional changes to the code, i.e. changes which are "guaranteed" to not introduce any bugs, can go into a separate commit.

Seeing what actually changed is much easier in [this diff](https://github.com/Beep6581/RawTherapee/compare/58c9f5a4da90f32fe334dfb55e76674c26cfab02...441c320375414ae49019f481840166e1c175fa6c) than in [this diff](https://github.com/Beep6581/RawTherapee/compare/58c9f5a4da90f32fe334dfb55e76674c26cfab02...3e76d861efb32a5dd9b29df9d7a20f47363e191a).

Apologies if I misunderstood you. Regards anyhow :)

**Comment by Desmis** [comment]
@Beep6581 

OK, now I understand :)

Thank you

**Comment by Desmis** [comment]
if no objections, I'll merge tomorrow :)

Jacques

**Comment by Beep6581** [comment]
@Desmis can we delete branches `mediandenoise` and `mediandenoise2`?
https://github.com/Beep6581/RawTherapee/branches/active

**Comment by Desmis** [comment]
Done :)

**Pull request merged**
