### PR TITLE
Suppress 'rtwindow.h' from main-cli.cc

### PR DESCRIPTION
**Pull request by Hombre57**
Should be safe, but I wouldn't mind a validation. Please thumbs up if ok to merge (for 5.6).

### CODE REVIEW

**Comment by Floessie** [comment]
Still builds fine on Linux. :+1:

**Comment by gaaned92** [comment]
W10, builds and runs

**Comment by Beep6581** [comment]
Builds fine in Linux, tested GUI and CLI, no problems.

**Comment by Floessie** [comment]
As it only shuffles includes a compile test is sufficient, IMHO.

**Pull request merged**
