### PR TITLE
Ciecam - re enable - curve brightness

### PR DESCRIPTION
**Pull request by Desmis**
This PR solve the problem in issue #6344 and issue #6348

I have move the code "tone curve brightness" upstream and  made some changes and simplifications.

Thanks to  @jade-nl  to have examined in detail Ciecam and found very old dysfunctions

Jacques

### CODE REVIEW

**Comment by ghost** [comment]
@Desmis

Does this also solve #3019?

**Comment by Desmis** [comment]
@jade-nl 

I think, probably, to verify... :)

In fact it was always the same bug...due to the position in the code....

jacques

**Comment by Desmis** [comment]
If nobody objects, I will merge this PR tomorrow :)

jacques

**Comment by ghost** [comment]
Thank you!

**Pull request merged**
