### PR TITLE
Try to fix thumbbrowser deadlock (#4576)

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

The title says it all. See #4576 for the details and reproduction.

Best,
Flössie

### CODE REVIEW

**Comment by heckflosse** [comment]
@Floessie As I never managed to reproduce this deadlock I can only try whether it works as before. Shall I?

**Comment by Floessie** [comment]
@heckflosse 
> As I never managed to reproduce this deadlock

Really? It's rather simple: Have let's say five (new, uncached) folders with 50 images each and switch between them while the thumbnails are rendering. It takes only a few seconds (<20) of trying until it deadlocks (on Linux). The original report was for Windows.

> I can only try whether it works as before. Shall I?

Yes, please. That at least would be encouraging.

Thanks,
Flössie

**Comment by ff2000** [comment]
I could easily reproduce it usually at the first time. Now I tried really hard and jumped through probably 30-50 folders. No deadlock. YEAH! The only suspicious thing was that once the label still said "Loading thumbnails" although it clearly was "Ready". Changing once again and everything was "Ready" ;) Probably that is just a small issue with a signal connection between the thumbnailer and the label.

(OT^2: But this test showed me that at least I have issues with memory consumption, usage grew over time from 4% to 25% (of 4GB), loading and closing a raw file will add the size of the raw file to the overall consumed memory of RT. It's not just cache as it will start to swap when I launch gimp from within RT and start creating layers and masks... Is it just me or is there a real issue I should report? Running RT under valgrind with this "slightly" underpowered machine is  close to impossible... This is not an issue this PR created, I struggle with it since quite some time already.)

**Comment by Floessie** [comment]
@ff2000 Thanks for testing!

Your memory problem reminds me of #4416. Please test @PkmX's workaround and see, if you experience the same problem. If so, report it there, otherwise create a new issue. Thanks!

**Comment by heckflosse** [comment]
@Floessie Could reproduce with dev after clearing thumbnail cache. Now building `fix-thumbbrowser-deadlock`...

**Comment by heckflosse** [comment]
@Floessie Can not reproduce anymore with your fix :+1:

**Comment by heckflosse** [comment]
@Floessie Please push

**Pull request merged**
