### PR TITLE
Lcp distortion alt match

### PR DESCRIPTION
**Pull request by agriggio**
fixes (well, tries to) some weird problems with some LCP files. more testing for regressions would be appreciated -- I only have 3 lenses with LCP profiles and they work fine, but that doesn't say much...

### CODE REVIEW

**Comment by Beep6581** [comment]
@agriggio shall we merge?

**Comment by agriggio** [comment]
How's the Google+ testing campaign going? -- If no issues have been found, ok for me to merge

**Comment by Beep6581** [comment]
@agriggio we got a bunch of shares and +1s but no replies:
https://plus.google.com/+rawtherapee/posts/5A8aFNZmvdC

It's your branch, so please do the honors when ready :)

**Comment by agriggio** [comment]
@Beep6581 from my POV, it is ready, as the new code doesn't give regressions for my lenses, and it seems to improve the situation for some users. I'll try to merge ASAP, probably next week when the storm is over at work :-)

**Comment by morosakubek** [comment]
Hi,
@agriggio  still a huge distortion comes out on compacts from Canon https://drive.google.com/open?id=0BzMK6gsaNS8wdmh2eG1fcXZtdmM

**Comment by agriggio** [comment]
@morosakubek I seem to recall having already looked at that picture/camera/profile, and the conclusion was that the LCP was probably not precise... I can't find the relevant issue right now though

**Comment by morosakubek** [comment]
@agriggio But this is a profile from Adobe. I have one more found on the internet (made by some user) and it also does not work on RawTherapee. In Adobe products there is no problem with these LCPs.

**Comment by agriggio** [comment]
thanks for the clarification. would it be possible to share also the other LCP profile?
unfortunately I don't have lightroom so I can't test with that. but I remember that I tried to import the LCP in lensfun and the results were equally poor. but I will check again

**Comment by morosakubek** [comment]
@agriggio Second profile is on google drive now: https://drive.google.com/open?id=0BzMK6gsaNS8wdmh2eG1fcXZtdmM

**Comment by agriggio** [comment]
Hi @morosakubek,
FYI I started working on lensfun integration. The branch is not yet ready to be merged, but it already works for your Canon camera. More info here:
https://github.com/Beep6581/RawTherapee/pull/4070

**Pull request merged**
