### PR TITLE
Font too large on Apple Retina/HiDPI & default font erroneously set to None

### PR DESCRIPTION
**Pull request by Benitoite**
@Hombre57's patch for font issues https://github.com/Beep6581/RawTherapee/issues/3984

### CODE REVIEW

**Comment by Beep6581** [comment]
Has this been tested to not break things when desktop scaling/HiDPI mode are enabled?
Break things could mean for example that RT's font and UI look tiny while all other programs look "normal".

**Comment by Benitoite** [comment]
@kapiliitr or maybe @fritzbo might be able to test how this patch works against their desktop scaling modes?
Here's the link to the build again:
https://filebin.net/u5cujuba4mwperg2/RawTherapee_OSX_10.9_64_5.2.1-2-gb5e76836.zip
(git tag was a test)

**Comment by Benitoite** [comment]
@reagle would you be able to try out this patched development build for its font performance?  You would need to delete your options file first.

**Comment by kapiliitr** [comment]
@Benitoite I think this works. I tried different resolutions as well and it scaled well.

**Comment by reagle** [comment]
@Benitoite I installed the patch and the fonts look good.

BTW: removing the RT directory in `.config` did nothing, I had to go into `~/Library/Application Support` so perhaps the [documentation](http://rawpedia.rawtherapee.com/File_Paths#Config) should be updated?

**Comment by Beep6581** [comment]
@Hombre57 since it's your patch, would you like to assign this issue to yourself and handle the merge when ready?

**Comment by Hombre57** [comment]
@Beep6581 @Benitoite Lines 258 to 260 from main.cc have to be removed before merging. Since it's @Benitoite's repository, how can I do that before merging ?

**Comment by Benitoite** [comment]
@Hombre57 I have removed those lines in my fork: https://github.com/Beep6581/RawTherapee/pull/3992/commits/7e05ea8827d59fa397312332ffcac2c56df211ef

**Comment by Hombre57** [comment]
PR merged.

**Pull request merged**
