### PR TITLE
mac: update of macosx_bundle.sh

### PR DESCRIPTION
**Pull request by Benitoite**
Fixes issues with sed -i not having a suffix, quote usage for string expansion, mktemp template needing some X's after the pid.

### CODE REVIEW

**Comment by Pandagrapher** [comment]
@Benitoite 
I have tested your script modifications using MacPorts environnement.

I got the following log: 
[macosx_bundle.log](https://github.com/Beep6581/RawTherapee/files/4728453/macosx_bundle.log)

From this log and my environnement, I have the following remarks:
```
#In: LOCAL_PREFIX:STRING=/opt
#Out: /opt
LOCAL_PREFIX="$(cmake .. -L -N | grep LOCAL_PREFIX)"; LOCAL_PREFIX="${LOCAL_PREFIX#*=}"
```
In RawPedia, it is indicated to define `LOCAL_PREFIX` this way: `-DLOCAL_PREFIX=PATH:"/opt"`. Due to this, the above script part returns `PATH:/opt`instead of `/opt` which causes more script errors. `LOCAL_PREFIX` shall be defined as `-DLOCAL_PREFIX="/opt"` to work.

```
# Copy the Lensfun database into the app bundle
mkdir -p "${RESOURCES}/share/lensfun"
ditto ${LOCAL_PREFIX}/local/share/lensfun/version_2/* "${RESOURCES}/share/lensfun"
```
With MacPorts, the lensfun package (v0.3.2_5) still uses `version_1` database. So, in bundle, lensfun folder is empty.

```
install -m 0644 "${PROJECT_SOURCE_DATA_DIR}/cliInfo.plist.in" "${LIB}/Info.plist"
```
`cliInfo.plist.in` does not anymore exist with your previous commits for Catalina.

When trying to launch the app in `/Applications` folder, RT crashes with the following output:
```
/Applications/RawTherapee.app/Contents/MacOS/rawtherapee

(rawtherapee:78556): GLib-GObject-WARNING **: 09:37:12.622: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(rawtherapee:78556): Gtk-CRITICAL **: 09:37:12.622: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
objc[78556]: Class GNotificationCenterDelegate is implemented in both /Applications/RawTherapee.app/Contents/Frameworks/libgio-2.0.0.dylib (0x10da07220) and /opt/local/lib/libgio-2.0.0.dylib (0x118da3220). One of the two will be used. Which one is undefined.

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(rawtherapee:78556): GdkPixbuf-CRITICAL **: 09:37:14.843: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(rawtherapee:78556): Gtk-WARNING **: 09:37:14.843: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(rawtherapee:78556): GLib-CRITICAL **: 09:37:14.843: g_propagate_error: assertion 'src != NULL' failed
zsh: segmentation fault  /Applications/RawTherapee.app/Contents/MacOS/rawtherapee
```

if you need more infos to investigate, do not hesitate.
Pierre

**Comment by Benitoite** [comment]
Many thanks for the test @Pandagrapher 
`cliInfo.plist.in` was part of an abandoned experiment.
You are ahead of me as I am in the middle of updating and rebuilding libraries.  I can generate a notarized fancy dmg now but the dependency chain is incomplete so I can't launch it yet.  I will check further later.

**Comment by Benitoite** [comment]
`-DLOCAL_PREFIX=PATH:"/opt"` was my syntax error–the colon and equal sign are transposed. Fixed in rawpedia.

**Comment by Benitoite** [comment]
Logic to test lensfun version with pkg-config added to macosx_bundle.sh

**Comment by Benitoite** [comment]
@Pandagrapher Please have a test at the bundle generation with these changes. Thanks.

**Comment by Pandagrapher** [comment]
@Benitoite 
Just tested. Here the log of `maxcos_bundle` script :
[macosx_bundle.log](https://github.com/Beep6581/RawTherapee/files/4737832/macosx_bundle.log)

Lensfun database is now correctly imported in bundle.
But I still can't launch the app (same errors as previously).

Pierre

**Comment by Benitoite** [comment]
@Pandagrapher Thank you for your test.  Could you post the system crash report crashed thread details?

**Comment by Pandagrapher** [comment]
@Benitoite 
Here the crash report:
[crash_report.txt](https://github.com/Beep6581/RawTherapee/files/4738363/crash_report.txt)
 
Pierre

**Comment by Benitoite** [comment]
@Pandagrapher do you also have a crash with current dev?

**Comment by Pandagrapher** [comment]
@Benitoite 
I often run the `dev` or `newlocallab2` branches directly using the binary (build with `-DOSX_DEV_BUILD="ON"` option to allow using relative path) for development purpose without any problem or error (confirmed with your `patch-13` branch).

I also tried to bundle automatically generated by the "macOS build" action. App also crashes but with a different output:
```
/Applications/RawTherapee.app/Contents/MacOS/rawtherapee

** (process:12310): WARNING **: 09:10:43.260: [Lensfun] /Applications/RawTherapee.app/Contents/Resources/share/lensfun/mil-sigma.xml:35:40: Error on line 35 char 40: Element “mount” was closed, but the currently open element is “”

(rawtherapee:12310): GLib-GObject-WARNING **: 09:10:43.520: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(rawtherapee:12310): Gtk-CRITICAL **: 09:10:43.520: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(rawtherapee:12310): Gtk-WARNING **: 09:10:45.244: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(rawtherapee:12310): Gtk-WARNING **: 09:10:45.968: Could not find the icon 'list-remove-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
zsh: abort      /Applications/RawTherapee.app/Contents/MacOS/rawtherapee
```
[crash_report_autobuild.txt](https://github.com/Beep6581/RawTherapee/files/4739507/crash_report_autobuild.txt)

Pierre

**Comment by Pandagrapher** [comment]
@Benitoite 
It seems that crashes are linked to pixbuf. When I look in the generated app bundles, in `etc/gtk-3.0` folder, both files `gdk-pixbuf.loaders` and `gtk.immodules` are empty.

So I guess it's due to the following script lines:
```
# Build GTK3 pixbuf loaders & immodules database
msg "Build GTK3 databases:"
"${LOCAL_PREFIX}"/local/bin/gdk-pixbuf-query-loaders "${LIB}/libpix*.so" > "${ETC}/gtk-3.0/gdk-pixbuf.loaders"
"${LOCAL_PREFIX}/local/bin/gtk-query-immodules-3.0" "${LIB}/im-*" > "${ETC}/gtk-3.0/gtk.immodules"
sed -i.bak "" -e "s|${PWD}/RawTherapee.app/Contents/|/Applications/RawTherapee.app/Contents/|" "${ETC}/gtk-3.0/gdk-pixbuf.loaders" "${ETC}/gtk-3.0/gtk.immodules"
sed -i.bak "" -e "s|/opt/local/|/Applications/RawTherapee.app/Contents/Frameworks/|" "${ETC}/gtk-3.0/gtk.immodules"
```
Which returns the following errors:
```
-- Build GTK3 databases:
g_module_open() failed for /Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/libpix*.so: dlopen(/Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/libpix*.so, 10): image not found
Cannot load module /Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/im-*: dlopen(/Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
/Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/im-* does not export GTK+ IM module API: dlopen(/Users/pierre/eclipse-workspace/mac/build/RawTherapee.app/Contents/Frameworks/im-*.so, 10): image not found
sed: -e: No such file or directory
sed: -e: No such file or directory
```
Moreover, for the following line, with MacPorts, `gtk-update-icon-cache`binary is named `gtk-update-icon-cache-3.0`:
```
ditto {"${LOCAL_PREFIX}/local","${RESOURCES}"}/share/icons/Adwaita/index.theme
"${LOCAL_PREFIX}/local/bin/gtk-update-icon-cache" "${RESOURCES}/share/icons/Adwaita"
ditto "${LOCAL_PREFIX}/local/share/icons/hicolor" "${RESOURCES}/share/icons/hicolor"
```

Pierre

**Comment by Benitoite** [comment]
@Pandagrapher I have seen that error before... gtk3 was upped to 3.24.20 a couple weeks ago and now I am also having empty immodules lists too.  One thing that bypasses the runtime error is to bake the input modules into gtk, which macports doesn't do, so we will have to figure out how to repair the script.

**Comment by Pandagrapher** [comment]
@Benitoite 
This patch allows not to have empty files for `gdk-pixbuf.loaders` and `gtk.immodules`:
```diff
diff --git a/tools/osx/macosx_bundle.sh b/tools/osx/macosx_bundle.sh
index 968872940..c75de3eaf 100644
--- a/tools/osx/macosx_bundle.sh
+++ b/tools/osx/macosx_bundle.sh
@@ -233,13 +233,13 @@ ditto {"${LOCAL_PREFIX}/local","${RESOURCES}"}/share/themes/Default/gtk-3.0/gtk-
 
 # Adwaita icons
 msg "Copy Adwaita icons"
-iconfolders=("16x16/actions" "16x16/devices" "16x16/mimetypes" "16x16/places" "16x16/status" "48x48/devices")
+iconfolders=("16x16/actions" "16x16/devices" "16x16/mimetypes" "16x16/places" "16x16/status" "16x16/ui" "48x48/devices")
 for f in "${iconfolders[@]}"; do
     mkdir -p ${RESOURCES}/share/icons/Adwaita/${f}
     ditto ${LOCAL_PREFIX}/local/share/icons/Adwaita/${f}/* "${RESOURCES}"/share/icons/Adwaita/${f}
 done
 ditto {"${LOCAL_PREFIX}/local","${RESOURCES}"}/share/icons/Adwaita/index.theme
-"${LOCAL_PREFIX}/local/bin/gtk-update-icon-cache" "${RESOURCES}/share/icons/Adwaita"
+"${LOCAL_PREFIX}/local/bin/gtk-update-icon-cache-3.0" "${RESOURCES}/share/icons/Adwaita"
 ditto "${LOCAL_PREFIX}/local/share/icons/hicolor" "${RESOURCES}/share/icons/hicolor"
 
 # fix libfreetype install name
@@ -249,8 +249,8 @@ done
 
 # Build GTK3 pixbuf loaders & immodules database
 msg "Build GTK3 databases:"
-"${LOCAL_PREFIX}"/local/bin/gdk-pixbuf-query-loaders "${LIB}/libpix*.so" > "${ETC}/gtk-3.0/gdk-pixbuf.loaders"
-"${LOCAL_PREFIX}/local/bin/gtk-query-immodules-3.0" "${LIB}/im-*" > "${ETC}/gtk-3.0/gtk.immodules"
+"${LOCAL_PREFIX}"/local/bin/gdk-pixbuf-query-loaders "${LIB}"/libpix*.so > "${ETC}/gtk-3.0/gdk-pixbuf.loaders"
+"${LOCAL_PREFIX}/local/bin/gtk-query-immodules-3.0" "${LIB}"/im-* > "${ETC}/gtk-3.0/gtk.immodules"
 sed -i.bak -e "s|${PWD}/RawTherapee.app/Contents/|/Applications/RawTherapee.app/Contents/|" "${ETC}/gtk-3.0/gdk-pixbuf.loaders" "${ETC}/gtk-3.0/gtk.immodules"
 sed -i.bak -e "s|/opt/local/|/Applications/RawTherapee.app/Contents/Frameworks/|" "${ETC}/gtk-3.0/gtk.immodules"
```
Note: `gtk-query-immodules-3.0` is binary name for MacPorts package.

Now I can launch the app bundle but some (Adwaita?) icon seems to be missing:
RT_view

Edit: Previously edited patch now fixes the missing icon issue (seems like some Adwaita library icons have been moved to another folder).

I now only get the following error when running app bundle (seems like `/Applications/RawTherapee.app/Contents/Frameworks/share/locale` folder is missing for `gtk.immodule`file?):
```
(rawtherapee:54216): Gdk-WARNING **: 20:52:46.969: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
Gtk-Message: 20:52:46.971: Failed to load module "/Applications/RawTherapee.app/Contents/Frameworks/im-quartz.so"

(rawtherapee:54216): GLib-GObject-WARNING **: 20:52:47.147: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(rawtherapee:54216): Gtk-CRITICAL **: 20:52:47.147: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
```

Pierre

**Comment by Beep6581** [comment]
Hey @Benitoite @Pandagrapher what is the status and intention with this PR?

**Comment by Benitoite** [comment]
I'm currently working on rebuilding the deps in macOS 11β4 "Big Sur Public Beta" / appleclang 12.  I am almost up to gtk+3, then I can test these again.

**Comment by Benitoite** [comment]
@Beep6581 @Pandagrapher etc,  I have generated with this PR patched in and some other clean-ups not yet committed a new build for macOS 11.1 *Big Sur*.
It must be installed in `/Applications`.  
....

**Comment by Pandagrapher** [comment]
@Benitoite Is this build specific to _Big Sur_? Otherwise, I can't test it: I am still on _Catalina_.

Pierre

**Comment by Benitoite** [comment]
> @Benitoite Is this build specific to _Big Sur_? Otherwise, I can't test it: I am still on _Catalina_.
> 
> Pierre

@Pandagrapher Yes 11.1, and there is a file save problem (some utf8/iconv/ustring issue) with that bundle.  Attempting to recreate the bundle with the 10.11 SDK currently.

**Comment by Beep6581** [comment]
Hi @Benitoite is this required for 5.9?

**Comment by Benitoite** [comment]
@Beep6581 
Yes, these fixes also included something to gain an ARM-native build as processor no. 10 in the cmake phase, but the ARM people seem to have worked something out on another PR for that, so I guess it should be reverted.

**Comment by Benitoite** [comment]
I have generated this latest build for macOS 10.12 *Sierra* or above, with intel® code only.
....
 Lensfun seems to work now that I found the config/options file to delete, which are located in `~/Library/Containers/RawTherapee/Data/Library/Application\ Support/RawTherapee5-dev/config/options`
@pandagrapher's fix for icons, etc, incorporated.

**Comment by Pandagrapher** [comment]
Hello @Benitoite,
I have tested your app bundle in MacOS Big Sur 11.2. All seems to work fine.

But I have noted the following minor issues:
- Splash screen is not shown at first startup and has some missing tabs (authors, release note and copyright ones) when you force to show it using `About` button in Preferences. I have investigated and it seems to be due to incorrect paths in `config.h` file. `CREDITS_SEARCH_PATH` and `LICENCE_SEARCH_PATH` are located in `Ressources` folder whereas files are located in `Ressources\share` folder in app bundle. I have also noted two different `AboutThisBuild.txt` files in the app bundle.

- User language automatic detection does not work in an app bundle (it works correctly when I run dev build outside app bundle). Apparently `LANG` variable is not accessible in an app bundle: https://stackoverflow.com/questions/57130968/how-to-use-c-stdlocale-in-macos-bundle-application. I gonna try to see if I can find a workaround for this.

- When running app with Terminal (setting environmental variables first), I get the following additionnel warning/error:
```
The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
Gtk-Message: 11:12:05.897: Failed to load module "/Applications/RawTherapee.app/Contents/Frameworks/im-quartz.so"
```
- - `GDK_NATIVE_WINDOWS` variable is obsolete in Gtk3 and should not be set in `Info.plist` file.
- - For the last warning, I am wondering if it is not due to missing folders `/opt/local/share/locale` which are not copied into app bundle. I have checked and they are for Gimp or Inkscape.

Regards,
Pierre

**Comment by Benitoite** [comment]
@Pandagrapher Thanks for your test.
https://stackoverflow.com/a/39256898/8258079 this c++ code uses CoreFoundation to get the user's language and potentially other locale info.

**Comment by Benitoite** [comment]
I have just built https://kd6kxr.keybase.pub/RawTherapee_OSX_10.12_64_5.8-2813-gbb08b6bed.zip
notes: To get a first-launch, the RawTherapee folder must be deleted in `~/Library/Containers`.  
The about-splash should show its elements with *CMakeList.txt*'s `creditsdir` variable pointing to `/Resources/`.
GDK_NATIVE_WINDOWS is removed, Fixed UpdateInfo command

**Comment by Benitoite** [comment]
Language detection is fixed.  After some trial and mostly error, I decided to simply have the OS read out the AppleLocale to a file, and then stream that into a string. 
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.12_64_5.8-2813-gbb08b6bed.zip is updated.

**Comment by Pandagrapher** [comment]
@Benitoite 
I have tested your last app bundle: I can confirm that splash screen and automatic language detection is fixed 👍 

I still get the following warning at startup:
```
Gtk-Message: 11:12:05.897: Failed to load module "/Applications/RawTherapee.app/Contents/Frameworks/im-quartz.so"
```
I am not sure it's useful to define `GTK_MODULES` environment variable as this module path is already listed in the `gtk.immodules` (not very clear when doing some research on this warning but removing `GTK_MODULES` variable avoids the warning). I have also noted that `locale` folder path in `gtk.immodules` file are not correct.

**Comment by Pandagrapher** [comment]
@Benitoite 
To solve app language problem on MacOS, I worked on this patch:
[lang.patch.txt](https://github.com/Beep6581/RawTherapee/files/6136956/lang.patch.txt)

The main changes are:
- Automatic language detection is based on CoreFoundation API
- When detecting or manually setting a language, a check is done if the language is available in UTF-8 format then all locale environment data are set accordingly. This way it solves issue #4394 allowing manipulating files with special characters in their names.

Pierre

**Comment by Beep6581** [comment]
@Benitoite shall we merge?

**Comment by Pandagrapher** [comment]
@Benitoite 
Using MacPorts environment, I have tested app bundle generation and how generated app works (I used a self-signed certificate to codesign app and enable sandboxing). I discovered some issue with language auto-discovering using `CFlocale` in a sandbox app. As described [here](https://bugreports.qt.io/browse/QTBUG-63324?focusedCommentId=371735&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel), `CFlocale` only gets user settings in a merged list between user prefered language list and language defined in `CFBundleLocalizations` array key... However, this implies to update the array key each time a new language is added in RT. As we use a specific localization mechanism in RT, I have activated in `info.plist` the `CFBundleAllowMixedLocalizations` key which easily solves the issue.

The following patch contains that:
[patch.txt](https://github.com/Beep6581/RawTherapee/files/6254264/patch.txt)

In that patch, I also solves the following issue:
- Two `CFStringRef` weren't released
- By default, according to Apple documentation, all language supports UTF-8 so I simplified some line of codes
- The added `DroidSansMonoSlashed` font doesn't handle some special character (such as `ç`). So file names containing these characters aren't displayed correctly in RT. Using default system font solves that

IMHO with this last review, the pull request can be merge 👍 

Regards,
Pierre

**Comment by Thanatomanic** [comment]
@Benitoite Can you indicate a timeframe in which you can complete this PR for merge?

**Comment by Benitoite** [comment]
Okay, I have been able to have this run in Big Sur and Monterey (intel).  
https://kd6kxr.keybase.pub/RawTherapee_OSX_12.0_64_5.8-2854-g2f206d518.zip
I should be able to incorporate pandagrapher's solution in some hours...

**Comment by Benitoite** [comment]
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.12_64_5.8-3048-gc901f644a.zip
 This build should work in 10.14-15, 11, and 12 - the three most recent macOS versions.  
The dependencies are 98% from `brew`, everything there is now based on 10.14 minimum. 
~~There is a possibility of using 10.14-- libomp is using a load command only available since 10.15.~~ Also libomp from llvmorg-12 did not work on macOS. llvmorg-11.1.0 is working ok.
The possibility of running down to 10.12 depends on from-scratch building of dependencies, much of which I have formulated:

https://github.com/Benitoite/RTdeps/blob/master/macbuildRT.sh

**Comment by Thanatomanic** [comment]
Great work @Benitoite ! Would you say this PR is ready for a merge? Or perhaps you can ask a few people on Pixls to test this branch?

**Comment by Benitoite** [comment]
@Thanatomanic https://discuss.pixls.us/t/test-of-rawtherapee-on-macos-10-15-11-12-catalina-big-sur-monterey-intel-code/26017 currently testing the bundle generated by this on pixls.  I'm agreeable to merge at this point.

**Comment by Pandagrapher** [comment]
@Benitoite
Just tested your last bundle on MacOS 11.4: all seems to work :)
For me, it's ok to merge 👍 

Pierre

**Comment by Benitoite** [comment]
For some reason I and others are not able to see the Spot Removal tool in the Detail tab, which appears nominal on the kd6kxr/rawtherapee-dev docker build.  I realize this tool is not used often yet...  Built with `gtk+3.24.30`.

**Comment by Pandagrapher** [comment]
> For some reason I and others are not able to see the Spot Removal tool in the Detail tab, which appears nominal on the kd6kxr/rawtherapee-dev docker build. I realize this tool is not used often yet... Built with `gtk+3.24.30`.

You built the app bundle from this branch? If yes, it seems that your last merge from dev was  made on March and Spot Removal tool has been introduced in dev in May

Pierre

**Comment by Benitoite** [comment]
@Pandagrapher Thanks, overlooked updating.

**Comment by Benitoite** [comment]
https://kd6kxr.keybase.pub/RawTherapee_OSX_10.12_64_5.8-3048-gc901f644a.zip
Ok, new features showing up now.

**Comment by Benitoite** [comment]
The only issue I am having with the mac build is probably in gtk+3-24: it is not possible to grab the slider buttons in macos 12β (*Monterey*).   The gtk is from homebrew, 3.24.30, with nominal sliders on 10.14 *Mojave*.  This issue was not reported by testers on pre-12β macos.

**Comment by Pandagrapher** [comment]
> The only issue I am having with the mac build is probably in gtk+3-24: it is not possible to grab the slider buttons in macos 12β (_Monterey_). The gtk is from homebrew, 3.24.30, with nominal sliders on 10.14 _Mojave_. This issue was not reported by testers on pre-12β macos.

@Benitoite I found this GTK3 issue on MacOS which can be linked to your issue on _Monterey_:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3992
Perso I can't reproduce it on _Big Sur_ but I guess you are testing _Monterey_ beta on a Virtual Machine so maybe induced latency can make this issue appear more easily.

As this Pull Request brings a lot of improvements, what about merging it to `dev` for RT5.9?
Pierre

**Comment by Benitoite** [comment]
@Pandagrapher Thanks, you may merge this.

I'm running virtual 10.14 on my 12β installation. I may try merging the mentioned PR into gtk although oddly Big Sur testers didn't report any slider problems.  Being as 12 is a major version bump it wouldn't surprise me if things like hi-DPI mousing behavior is happening differently that in Big Sur.

**Comment by Thanatomanic** [comment]
@Benitoite @Pandagrapher Thanks for the work! 😃 

Please squash-and-merge to keep the main commit log cleaner.

**Comment by Benitoite** [comment]
@Thanatomanic Squashed it down to 3, although the original commits didn't disappear...  If you merge with the UI you can probably squash them all together as well.

**Comment by Thanatomanic** [comment]
Not sure what you did there, because in effect you added three more commits to this PR. If this PR is now merged regularly, there is a total of 40 commits that will show up in the `dev` commit log. Bit messy if you ask me.

The GitHub website has a squash and merge option that condenses everything in this PR down to 1 commit when merging.

**Comment by Benitoite** [comment]
@Thanatomanic I tried unsuccessfully to reset back to upstream/dev but if needed I can close and open a new PR - merely a contributor.

**Comment by Thanatomanic** [comment]
No worry, I can squash+commit it for you as well. Just a sec.

**Pull request merged**
