### PR TITLE
Local adjustements - Color appearance Cam16 and Log encoding - Harmonize Abstract Profile

### PR DESCRIPTION
**Pull request by Desmis**
I had some problems with the lacam16 branch merging with dev, which led me to change the pull request

I put the previous PR in draft mode.

The content is the same

### CODE REVIEW

**Comment by Desmis** [comment]
I'm waiting for 5.10 to start evaluating this new version. However, if this lasts too long, this evaluation could begin soon.

Main changes brought by this PR

The changes affect 2 LA modules:
* Log encoding
* Color Appearance – only Cam16

For the 2 modules I introduced:
* the notion of “whites distribution” and “blacks distribution” that allows you, in Automatic, when the dynamic range (DR) of the image is high, to change the distribution of lights in whites and deep blacks. Can be used with Log encoding or Sigmoid with Black Ev and White Ev enabled. The algorithm does not change the basic data, but acts on the components necessary to calculate the Dynamic range, Black Ev, White Ev and the Gray point
* the notion of “Brighness compression” (partly inspired by ART). This concept is simple to implement in “Log encoding” because the data used to calculate the DR and that used in the code are the same. This is not the case with Cam16. Indeed, on the one hand, when we use “absolute luminance” the data are not limited, and on the other hand Cam16 modifies the distribution of tones in particular the “Gray point” necessary for the calculations.

In the case of Cam16, I introduced the notion of "Sigmoid Q" - already present in previous versions - but which now works significantly better (at least I think so).
* this addition of Sigmoid in Cam16 was in no way a necessity, because the Cam16 tools (brightness, lightness, contrast J and Q, curves, etc.) make it possible to deal with the situations. Rather, it should be seen as a personal challenge – the code is simple.
* the improvement lies in the evaluation of the inflection point which cannot be a simple interpolation. These problems are due to 2 difficulties :
** the code can hardly be called again, because it implements 6 dimensional variables.
** in principle the absolute luminance values are variable.

I also added upstream of Cam16 an ultra-simplified “abstract profile” module allowing before Cam16 to modify, if necessary, the distribution of shadows and lights (TRC) and the primaries.

I also revised the GUI to make it more consistent, notably by including Sigmoid and Log encoding in Cam16 image adjustments.

Additionally, mask contains more tools.

jacques

**Comment by Desmis** [comment]
@Lawrence37 

I would like to carry out a "Pre-dev build" for this current PR, because I think that the modifications made can be tested more widely.

I see that the "Pre-dev build" directory has been cleaned.

I modified the 2 files "appimage.yml" and "windows.yml" with the :  publish_pre_dev_labels instruction: '["lacam16n"]'
I made a commit (merge with dev). The system compiles correctly, but nothing happens in "Pre-dev builds".

Am I acting correctly? or this functionality is no longer possible.

Thank you.

Jacques

**Comment by Lawrence37** [comment]
The repository owner/organization must be included. For example: `'["Beep6581:lacam16n"]'`

**Comment by Desmis** [comment]
@Lawrence37 

Thank you... 
I'm really dizzy :)

Jacques

**Comment by Desmis** [comment]
@Lawrence37 

Do you know why the executables are no longer made? A priori problem with Lensfun. 7 hours ago (11 a.m. in France), I pushed a change without problem. Now Appimage and Windows give an error message.

Is this coming from me (my configuration...must I update Msys2 ?) or something else (a problem on Github ?). For me, as you know, these are things that I don't control.

Thank  you very much.

Jacques

Jacques

**Comment by Lawrence37** [comment]
There was a problem with the `lensfun-update-data` script. `http://wilson.bronger.org/lensfun-db/versions.json` didn't not work. The https version does. I think it just started working again, so I'll re-run the failed builds.

**Comment by Desmis** [comment]
@Lawrence37 

Thank you, I am reassured, I thought I had done something stupid  :)

Jacques

**Comment by Desmis** [comment]
I see that now everything works

Thank you
Jacques

**Comment by Desmis** [comment]
@Lawrence37 

I come to you because I think, unless there is an error on my part, or my configuration (which is nothing special), that there is a malfunction in the last "merge" #6769 - under Windows (I am with Windows 11). But maybe it's something else ?
I tried it - without realizing it - but only with one screen because I was on the move (I have a laptop). Everything seemed to be working normally.

Yesterday morning I did a merge with "dev" and my 2 screen configuration. As soon as I started it I saw something wrong. 
This is why I created another PR "lacam16n2" without this merge.

The problem also appears in my latest "Dev" version and is therefore not linked (I think) to lacam16
What is happening ? You know I'm not at all an expert on this sort of thing:
* in Preferences: Editor Layout , only 2 selections possibles -  Single Editor tabs Mode, Vertical Tabs - Multiple editor Tabs mode. The other choice are selected the first time, then ignored.
* Position of curve copy & paste buttons : ignored

it seems that the 'option' file is corrupted and the only solution, when I take a version that works correctly is to delete the 'options' file
When you activate "2 screen" mode : Multiple editor Tabs ..own Window mode"... The image is curious, superimposing in the preview, that of the file browser, vertically on the left.
I attach a screenshot
The file browser with Multiple editor Tabs ..own Window mode"..
image

The preview  (2 snd screen)
image

I know you don't have Windows natively. If you tell me what to look at, retouch, no problem.
but I don't think I'm the only one??

Thank you very much 

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @sgotti 

I think you fixed the bug...
All seems to work fine 

Thank you very much

Jacques

**Comment by Desmis** [comment]
@Lawrence37 
The numerous tests carried out on the challenge and before the challenge, revealed several bugs (7 I think). The system seems stable now.
https://discuss.pixls.us/t/rawtherapee-processing-challenge/42647/78

Asking you for a review seems difficult, as the code has undergone some major changes over the past 1 year.
I think this challenge is a good way of validating the code itself.

Of course I don't forbid you to "look" and make a review. I propose a merge early next week (within 7 to 8 days).

Thank you very  much

Jacques

**Comment by Lawrence37** [comment]
It is reassuring that several people have tried it. I would like to try it myself, but I have been busier than usual and there are also a few other open PRs to look at.

**Comment by Desmis** [comment]
@Lawrence37 

With all branches open... I made a mistake, the branch to evaluate and merge is lacam16n2

Sorry

Jacques

**Pull request closed without merging**
