### PR TITLE
localisation deutsch 5.11

### PR DESCRIPTION
**Pull request by marter001**
hope, i am not too late to the party

### CODE REVIEW

**Comment by marter001** [comment]
how comes, there is an old commit added, which i deleted before?

**Comment by Lawrence37** [comment]
Thanks @marter001! If you don't mind, I will do some cleanup to the file.

**Comment by marter001** [comment]
great, i dont mind, pls cleanup.
btw:

there is one history msg i dont understand why it changed, may be you can corrrect:

HISTORY_MSG_BLSHAPE;(Erweitert - Wavelet)\nUnschärfeebenen\nUnschärfe nach Ebenen
was changed to
HISTORY_MSG_BLSHAPE;(Erweitert - Wavelet)\nUnschärfeebenen\nUnschärfe nach Ebenena
by mistake.

could you pls change back to:
HISTORY_MSG_BLSHAPE;(Erweitert - Wavelet)\nUnschärfeebenen\nUnschärfe nach Ebenen

thanks a lot!

**Comment by Lawrence37** [comment]
Done!

**Comment by marter001** [comment]
great, thank you!

**Pull request merged**
