### PR TITLE
Rcd improvements

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I will have a look :)

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I tested on 2 images:  the first "normal", the second "noisy"

Speed-up on the 2 images about 45%

No visible difference at 1600% zoom
Small differences in structures, very small differences in flat areas

Good job

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques,

> Speed-up on the 2 images about 45%

that's huge. On my machine it's only ~25%

Thanks for testing :+1: 

Ingo

**Comment by Desmis** [comment]
@heckflosse 

Ingo
First image - Old 224800 us  New 127120 us
Denoise image - Old 439440 us - New 238460 us

jacques

**Pull request merged**
