### PR TITLE
Speedup for color propagation

### PR DESCRIPTION
**Pull request by heckflosse**
This is a first mockup to speed up hl reconstruction color propagation.
The speedup depends on the image. In worst case there is no speedup, but on average there are reasonable speedups.

There are small differences in output.
@Floessie please no code review atm. I first want to know if it works as expected.

### CODE REVIEW

**Comment by heckflosse** [comment]
About memory usage:

In current version there is a console output writing out a factor.
Memory usage is reduced by (1 - (1 / factor)) * (width * height * 28 byte)

**Comment by Desmis** [comment]
@heckflosse 
I have tested with Amsterdam.pef

Thank you

jacques

**Comment by Desmis** [comment]
@heckflosse 
I just tested new commit with "yellow_poppy"

No differences in TIF
Huge speedup 
* without 370ms
* with 18ms

good job

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I just tested this new commit
For me no speedup with patch above, or very small

No differences in TIF

jacques

**Comment by heckflosse** [comment]
@Desmis Thanks for testing. The (really minor) speedup this time was in last loop, where I could make `totwt` a bool. Formerly it was a float, and was used above and below the fraction line. This way I could turn some divisions into multiplications and also eliminate some divisions completely.

**Comment by heckflosse** [comment]
Too bad that I can not fix typos in commit comments :frowning_face:

**Comment by heckflosse** [comment]
@Floessie I think it's a good time for a code review now :)

**Comment by Desmis** [comment]
@heckflosse 
I tested last commit, all works fine :)

jacques

**Review by Floessie — APPROVED** [review]
Good work, Ingo. Builds and runs fine.

Cleanup done.

**Pull request merged**
