### PR TITLE
Makes Preferences window scrollable

### PR DESCRIPTION
**Pull request by Beep6581**
- The Preferences window is now scrollable.
- Cleanup of arcane variable names and obsolete comments.
- Issue #3994

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Tested, works fine. 👍

**Comment by afr-e** [comment]
Thanks, it works!

One nitpick is that the window starts with the smallest size possible. However, that is _much_ better than having an edge off-screen or hidden behind another object, or not being able to resize.

image

**Comment by heckflosse** [comment]
Can we close?

**Comment by Floessie** [comment]
@afr-e I stumbled upon this problem, too. It's only visible when deleting the options file.

This should kind of fix it:

```patch
diff --git a/rtgui/options.cc b/rtgui/options.cc
index dcba775b6..205dae821 100644
--- a/rtgui/options.cc
+++ b/rtgui/options.cc
@@ -331,7 +331,7 @@ void Options::setDefaults()
     dirBrowserHeight = 350;
     dirBrowserSortType = Gtk::SORT_ASCENDING;
     preferencesWidth = 800;
-    preferencesHeight = 0;
+    preferencesHeight = 600;
     toolPanelWidth = 400;
     browserToolPanelWidth = 465;
     browserToolPanelHeight = 600;
```

HTH,
Flössie

**Comment by Beep6581** [comment]
Reproduced (had to turn my "remember previous window state" override off in KDE for RawTherapee), fix confirmed, committed.

**Comment by Floessie** [comment]
Ah, the beauty of F/LOSS: Speed! :+1:

**Pull request merged**
