### PR TITLE
Noise reduction fails when image contains a large uniform (i.e. overe…

### PR DESCRIPTION
**Pull request by heckflosse**
…xposed) area

### CODE REVIEW

**Comment by Hombre57** [comment]
Wasn't this already committed ? Do we close ?

**Comment by heckflosse** [comment]
@Hombre57 Noone except me tested it (though maybe @Beep6581 did, don't remember). It's not committed for that reason.

**Comment by Hombre57** [comment]
Oh... I'll test today then.

**Comment by Hombre57** [comment]
I've tried to detect a problem with the dev branch, but w/o success. What's the linked issue ? Do we have a test shot and pp3 to reproduce ?

**Comment by heckflosse** [comment]
@Hombre57 There is(was) an issue. I wouldn't have tried to solve it without. I'll search it and post the link...

**Comment by heckflosse** [comment]
@Hombre57 Easier written than done :( So much time past after this change. Maybe @Beep6581 can help out. Still trying to find the issue and the sample files...

**Comment by Hombre57** [comment]
I guess it's issue #3469. I'll test tomorrow.

**Comment by heckflosse** [comment]
@Hombre57 \o/ yes, that's the issue! Thanks a lot :+1:

**Comment by heckflosse** [comment]
I created a new branch denoise_uniform_dev which is up to date with dev

**Pull request closed without merging**
