### PR TITLE
Spot removal tool fixes

### PR DESCRIPTION
**Pull request by Lawrence37**
I fixed two issues with the spot removal tool: a missing history message and a crash when removing a spot.

This PR is mostly about discussing what we want to do with the spot removal tool. I think it we should add this tool as-is for 5.9 and possibly add more features such as detail preservation from ART in a later release. Please note this PR is set to merge into the `spot-removal-tool` branch. I can change it to `dev` if we agree to have this feature in 5.9.

Related to: #2239

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 

I think it's a good feature for 5.9

Jacques

**Comment by Thanatomanic** [comment]
@Lawrence37 I'm not sure why the commit log for this PR is so huge. When I go to the 'Commit' tab I don't even see your own commits, which makes the whole thing very obscure. Is it possible to rebase your changes?

**Comment by Lawrence37** [comment]
I'm not familiar enough with rebase to know how to make that work. All of my commits are at the end, so what I can do is create another branch with just the merged commits and make that the destination branch. Alternatively, I can also fast forward the original branch to include the merge commits.

**Comment by Lawrence37** [comment]
@Thanatomanic I only made 3 commits, all at the end. The first is the merge commit with no merge conflicts. The other two can be viewed here: https://github.com/Beep6581/RawTherapee/pull/6162/files/7e436a44d646fe514c561ffdcc44115613d9b6b2..f958074d9bd5ece66aeb79a79424c978995940e0

**Comment by Lawrence37** [comment]
I would like to have spot removal in 5.9. As I recall, @Thanatomanic and @Desmis have also expressed interest in having it in 5.9. Can I merge this into `dev` (after review and approval, of course)?

**Comment by Thanatomanic** [comment]
Hi @Lawrence37 please merge this into `spot-removal-tool` so that we can have a proper PR for testing the spot removal tool.

**Pull request merged**
