### PR TITLE
Add support for Panasonic DC-GH5M2

### LINKED ISSUE #6297: RAW support for Panasonic GH5M2
I have uploaded RAW reference images taken with the Panasonic GH5 Mark II to <https://raw.pixls.us/>. I hope those are helpful in the process of adding support for that (brand-new) camera.

### PR DESCRIPTION
**Pull request by sgotti**
* dcraw: add 12 bit raw handling to panasonic v6 decoder.
   Port panasonic v6 decoder handling of 12 bit raw from libraw

* dcraw: add Panasonic DC-GH5M2 to adobe_coeffs

Fixes #6297

### CODE REVIEW

**Comment by erentar** [comment]
I managed to build this and open raw files.
however color looks slightly off compared to jpeg twin of the raw file from camera.

**Comment by sgotti** [comment]
> I managed to build this and open raw files. however color looks slightly off compared to jpeg twin of the raw file from camera.

@erentar http://rawpedia.rawtherapee.com/Editor#Eek.21_My_Raw_Photo_Looks_Different_than_the_Camera_JPEG

**Comment by sgotti** [comment]
@Lawrence37 Updated the PR to update the dcraw adobe_coeffs table instead of a camconst entry.

**Comment by Lawrence37** [comment]
Looks good to me!

**Comment by Lawrence37** [comment]
@sgotti I think you haven't added yourself to AUTHORS.txt. Feel free to do so when you get the chance.

**Pull request merged**
