### PR TITLE
Reduce start time and memory usage by removing redundant lookup table…

### PR DESCRIPTION
**Pull request by heckflosse**
…s and fillig remaining lookup tables in parellel

I'll make some further changes tomorrow

### CODE REVIEW

**Comment by adamreichold** [comment]
Certainly a good change not just for performance but also for maintainability. I wonder if the gamma-related look-up tables from `rtthumbnail.cc` shouldn't also be moved to `color.cc` to have everything in one place? (Also not sure why these are dynamically allocated?) There also seems to be a leftover `BENCHFUN` in `init.cc`?

**Comment by heckflosse** [comment]
@adamreichold I followed your suggestions about rtthumbnail.cc, made some additional small changes and removed benchmark code

**Comment by heckflosse** [comment]
Any objections to merge?

**Comment by adamreichold** [comment]
Sorry, forgot the thumbs up... +1 for merge from me.

**Pull request merged**
