### PR TITLE
Use full range in `ImageDatas::convertTo<>` (#3429)

### PR DESCRIPTION
**Pull request by Floessie**
This is a fix for #3429 (courtesy of @mmmtok).

Please have a look. Thanks.

### CODE REVIEW

**Comment by heckflosse** [comment]
Compiles and works fine here. :+1:

**Comment by heckflosse** [comment]
@Floessie In rtengine/iplab2rgb.cc can you please replace the Lab2xyz conversions in the loops with the >> 8 conversion by Color::Lab2XYZ the same way I did please before merge? I forgot that with my commit.

e.g. the part from [here](https://github.com/Beep6581/RawTherapee/commit/2d0e5e4feeac9801994d82c5931531f508deb2e9) to [here](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/iplab2rgb.cc#L112) can be replaced by

`Color::Lab2XYZ(rL[j], ra[j], rb[j], x_, y_, z_ );`

**Comment by Floessie** [comment]
@heckflosse No problem, I'll do that with my next commit. Thanks for testing.

**Comment by Floessie** [comment]
@Beep6581 @heckflosse @mmmtok @iliasg 

Ready for testing now. :)

**Comment by Beep6581** [comment]
No issues here.

**Comment by heckflosse** [comment]
Builds and works fine here. :+1:

**Pull request merged**
