### PR TITLE
Clean up thread utilities

### PR DESCRIPTION
**Pull request by adamreichold**
The thread utilities are currently used to abstract away some differences in the implementation of the Glib threading primitives on POSIX systems and Windows, however interface and implementation and hardly separate and so it is hard to read or reason about.

This is not something I would try to merge without review, but this pull request tries to improve the situation somewhat and also aims fix a few shortcomings of the current implementation:
* The instrumentation of the strict implementation of mutexes is definitely nice for the programmer, but we don't need to pay the performance cost of a recursive mutex in release builds where crashing and freezing is equally bad IMHO. (For debug builds nothing is changed and violating strict locking discipline will drop one into the debugger immediately.)
* The custom read-write lock implementation actually had a race condition insofar the static lock counters where updated concurrently without synchronization. (Only the specific locks mutex was taken, but they all share the same static counter.) Since file and line number already provides a lot of options to debug issues IMHO, this pull requests removes these counters. It also makes the `acquire` and `release` methods separately compiled as they seem too large to be obvious candidates for inlining. (If there are any performance regressions, the non-tracing implementation can certainly be inlined again.)
* It removes the `PROTECT_VECTORS` option and always locks the shared data structures. I do not know the full back story on this, but I think a program is either correct without locking or it is not. I also never heard of a thread-safe implementation of `std::vector` on any major platform, so I think this only clutters up the code and would be one more configuration to test or which users could report bugs against.

### CODE REVIEW

**Comment by adamreichold** [comment]
I also find the implementation of the read-write lock adventurous insofar readers a double-counted as writers instead of the other way around? But I did not opt to change anything in the algorithm as to concentrate on the maintainability and performance issues.

**Comment by gaaned92** [comment]
builds and runs on WXP. no noticeable impact

**Comment by Hombre57** [comment]
I made this class to help find location of freeze, and created MyMutex to solve a difference in platform implementation that was behaving differently (see issue #1668).

I don't have the knowledge of reviewing your patch, so I trust you and the other devs on this. But I agree that PROTECT_VECTORS is pointless.

**Comment by adamreichold** [comment]
@Hombre57 The working of `MyMutex` - i.e. resolving the difference between the POSIX and Windows implementations of `Glib::Threads::Mutex` - would still be the same if `STRICT_MUTEX = 0`. If `STRICT_MUTEX = 1` (which however seems to be default), then `MyMutex` already is non-recursive on both platforms.
This patch mainly does away with paying a recursive mutex in the implementation to raise `SIGINT` on failing to following locking discipline. (Which will only benefit the POSIX platforms since their default Glib mutex was non-recursive to being with to explain @gaaned92's observation.) For debug builds, everything basically stays as it is, but hopefully with an easier to maintain implementation.

**Comment by Beep6581** [comment]
Please ding me when merging so I will upload to coverity.

**Comment by Beep6581** [comment]
Compilation of `adamreichold/clean-up-threadutils` after merging into master is successful and the build runs fine. Gentoo, GCC-5.3.0.

**Comment by Beep6581** [comment]
@adamreichold do we merge?

**Comment by adamreichold** [comment]
@Beep6581 I would feel better if there was some definite yes or no from a code review and I also don't think time is pressing for this change. If nobody currently has time to review, I'd suggest to upload to Coverity without this change. If we are feeling adventurous we can merge now and handle any fallout as it happens since it did see testing from at least two people besides me.

**Comment by Beep6581** [comment]
It's true that we're not pressed for time, but I also know from history that waiting longer won't get it more testing, it will just go stale. As such, if @heckflosse gives the thumbs up, I would go ahead with the merge so that all users can help catch issues (which I'm happy to see is becoming easier all the time, now that we regularly ship debug builds which include gdb.exe).

**Comment by heckflosse** [comment]
Looks ok for me though build of the branch fails:

```
/batchqueue.cc:221:25: error: variable 'std::ofstream file' has initializer but incomplete type
     std::ofstream file (fileName, std::ios::trunc);
```

**Comment by adamreichold** [comment]
@heckflosse That is the same issue we had on master due to the missing `#include <fstream>`. I rebased the branch on the current master which should fix this among other things.

**Comment by heckflosse** [comment]
@adamreichold Thank you! Builds and works fine. :+1: for merge

**Comment by Beep6581** [comment]
Done. If things explode, blame me :)

**Pull request merged**
