### PR TITLE
Review idle register calls

### PR DESCRIPTION
**Pull request by Floessie**
Happy New Year,

Here is another review of the `IdleRegister` facility with major simplifications. There were a lot of merge conflicts, I hope I resolved them correctly. Please test.

Best,
Flössie

### CODE REVIEW

**Comment by Floessie** [comment]
Ping. I'm currently using this branch for my edits and haven't had a problem yet.

**Comment by heckflosse** [comment]
@Floessie I will compile and test

**Comment by heckflosse** [comment]
@Floessie Builds and works fine here :+1:

**Comment by Floessie** [comment]
Merged for broader audience.

**Pull request merged**
