### PR TITLE
make improcfun.cc cppcheck and -Wextra clean

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by adamreichold** [comment]
Changes look good to me. (I did wonder whether pulling out `mult` could have effects on the accuracy but did not see an obvious difference to the previous implementation.)

**Comment by heckflosse** [comment]
We could even rewrite this
```
    const float mult = gamm / maxL;
#ifdef _OPENMP
    #pragma omp parallel for
#endif
    for (std::size_t i = 0; i < N; i++)
    {
        L[i] = (L[i] - minL) * mult;
    }
```

to this:

```
  const float mult = gamm / maxL;
  const float add = -minL * mult;
#ifdef _OPENMP
    #pragma omp parallel for
#endif
    for (std::size_t i = 0; i < N; i++)
    {
        L[i] = L[i] * mult + add;
    }
```
That would turn the calculation inside the loop into an FMA instruction (on archs which support FMA)

**Comment by Thanatomanic** [comment]
You can always count on @heckflosse to scrape off one more instruction 😉 

image

**Comment by adamreichold** [comment]
:thinking: We have

> Do not use -ffast-math, it will not make RawTherapee faster but will introduce artifacts.

in `RELEASE_NOTES.txt` and

```c++
#error Using the -ffast-math CFLAG is known to lead to problems. Disable it to compile RawTherapee.
```
in `main.cc` and I think this is good advice as floating-point arithmetic is for example not associative or distributive which is why these transformation are not trivially correct. Does the compiler explorer yield the same result without that flag?

In the case of manually massaging this into a multiply-add, I would worry about cancellation effects, at least without a better understanding of the range of `L[i]`.

**Comment by Thanatomanic** [comment]
Without `-mfma -ffast-math` but keeping `-O3` I get a very different result, but something which is actually _the same for both cases_. So the compiler knows how to handle this, and we don't need to optimize in code if we don't rely on `-ffast-math`.

```asm
fun(float*):
        movaps  xmm2, XMMWORD PTR .LC0[rip]
        movaps  xmm1, XMMWORD PTR .LC1[rip]
        lea     rax, [rdi+2000]
.L2:
        movups  xmm0, XMMWORD PTR [rdi]
        add     rdi, 16
        mulps   xmm0, xmm2
        addps   xmm0, xmm1
        movups  XMMWORD PTR [rdi-16], xmm0
        cmp     rax, rdi
        jne     .L2
        ret
.LC0:
        .long   1072858812
        .long   1072858812
        .long   1072858812
        .long   1072858812
.LC1:
        .long   -1130678398
        .long   -1130678398
        .long   -1130678398
        .long   -1130678398
```

**Comment by adamreichold** [comment]
> Without -mfma -ffast-math but keeping -O3 I get a very different result, but something which is actually the same for both cases.

But shouldn't we keep the `-mfma` flag to allow the compiler to use that instruction and see if it is able to use it in the second but no the first case? If we drop the flag, it seems understandable that codegen is the same as the instruction is not on the table so to speak.

**Comment by heckflosse** [comment]
Neither using `-mfma` nor using `-ffast-math` is what we want.
Either we make generic builds, where `-mfma` is not set, or native builds, where the compiler sets the correct flags for the target architecture.

For my personal usage, I always make native builds, which in my case equals to -march=bdver2.

Here's the assembly for that case.
grafik

The compiler uses fma instrucions, knows, that using avx on a Bulldozer is not good, unrolls the loop and even inserts a prefetch instruction.

Conclusion: Trust the compiler.

**Comment by adamreichold** [comment]
> Either we make generic builds, where -mfma is not set, or native builds, where the compiler sets the correct flags for the target architecture.

I think the discussion was purely within the context of using the compiler explorer to look into the resulting codegen, not which flags to use to create release builds. In this particular context, using only `-mfma` instead of `-march` makes it possible to avoid changing all the other machine parameters which influence codegen to allow a more targeted comparison.

In any case, I am glad we are sticking to `mult` without `add`...

**Comment by heckflosse** [comment]
> In any case, I am glad we are sticking to mult without add...

I'm curious why...

**Comment by adamreichold** [comment]
> I'm curious why...

As written in https://github.com/Beep6581/RawTherapee/pull/6128#issuecomment-783963759

> In the case of manually massaging this into a multiply-add, I would worry about cancellation effects, at least without a better understanding of the range of L[i].

**Comment by Thanatomanic** [comment]
@adamreichold `L[i]` should be limited to 0..1 floats afaik.

**Comment by adamreichold** [comment]
> L[i] should be limited to 0..1 floats afaik.

I think this could still be affected: If `maxL` is close to zero, this means that `mult = gamma / maxL` would be very large and could loose precision. `add = -minL * mult` would then mirror that loss precision into the negative direction so `L[i] * mult + add` could have cancellation artefacts.

I am not completely certain that this will actually happen because `minL <= maxL` should also hold and maybe this prevents any issues. Maybe keeping in line with what was written above, my default conclusion is to _not_ trust algebraic manipulations of floating-point arithmetic.

**Comment by heckflosse** [comment]
> my default conclusion is to not trust algebraic manipulations of floating-point arithmetic.

your conclusion would require to define what's correct in first step...

e.g. : is (a + b) * c correct or is a * c + b * c correct in a certain use case?

In my opinion, for simple calculations like this, it does not matter.
For other cases (large summations for example) we have to care about cancelation effects for sure.

**Comment by heckflosse** [comment]
Anyway, any objections to merge this?

**Comment by Thanatomanic** [comment]
Not from me :+1:

**Comment by heckflosse** [comment]
@adamreichold Adam, to show you, that I also care about accuracy, have a look at this old issue ;-)

https://github.com/Beep6581/RawTherapee/issues/4338

**Comment by adamreichold** [comment]
> your conclusion would require to define what's correct in first step...

I think that when changing a shipping code base, we need to prove that our changes are improvements. Either by showing the current implementation is defective somehow. Or by showing how the new implementation is superior. Or more succinct, the current implementation is considered correct until we can reasonably argue that it is not.

> Adam, to show you, that I also care about accuracy, have a look at this old issue ;-)

I think that I have never said anything to the contrary.

> Anyway, any objections to merge this?

No.

**Comment by heckflosse** [comment]
> I think that I have never said anything to the contrary.

I agree. But I also think, that small arithmetic changes (replacing a division with a mult or for example replacing a divisison by 65535 with a division by 65536 (which turns the division into a multiplication at -O3) can be worth it for faster processing without getting worse results.

**Comment by heckflosse** [comment]
@adamreichold A good example for changing calculations is the current RCD code, which is much faster than the old code. This was a collaboartion of the original rcd author (Luis Sanz Rodríguez), Hanno from darktable, and me. We worked that out in a private communication without discussing the details on RT github because not only RT was involved, but also darktable, and the new code is now also in Siril and librtprocess. We didn't write a paper why the new code is simpler and faster. We simply agreed about it while collaborating...

**Pull request merged**
