### PR TITLE
Changed "Processing profile operations -> Custom Profile Builder" to "Reset to default"

### PR DESCRIPTION
**Pull request by agriggio**
The behaviour has changed slightly, so that clicking the menu item now resets
to the default processing profile specified in the preferences. If this
involves calling the custom profile builder, the behaviour is the same as
before. But this is a bit more general, in that it might also simply reapply
the static default profile, or regenerate the dynamic one (depending on the
user's settings)

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Tested and works fine.

Suggestion: Instead of a separate context menu item put it into the profile combobox like (Neutral) and (Last Saved). Then it's also available in the edit window.

**Comment by agriggio** [comment]
@TooWaBoo sounds reasonable to me. Anyone else has an opinion? @Beep6581 ?

**Comment by Beep6581** [comment]
"(Default)" is fine with me. @Hombre57?

Compiles and works fine.

**Comment by TooWaBoo** [comment]
Bug:
If (Neutral) is set as default in the preferences (e.g. for jpg) "Reset to Default" doesn't switch to (Neutral). Custom profiles are working fine.

**Comment by Beep6581** [comment]
Bug confirmed using (Neutral). (Dynamic) worked fine (I have no rules, so the result was neutral).

**Comment by agriggio** [comment]
@TooWaBoo thanks, confirmed. I just pushed a fix.

**Comment by TooWaBoo** [comment]
Tested and works fine. 👍

**Comment by agriggio** [comment]
Adding this to the profile combo box is a bit more work than I thought... I propose to keep it in the context menu for now, and merge as is. Anyone against?

**Comment by heckflosse** [comment]
:+1: for merge

Edit: and also :+1:  to mark it as fixed [here](https://github.com/Beep6581/RawTherapee/issues/3687#issue-207088602) :)

**Pull request merged**
