### PR TITLE
Dehaze

### PR DESCRIPTION
**Pull request by agriggio**
I think this is ready for consideration (and I'd propose to merge this before #4893)

### CODE REVIEW

**Comment by ff2000** [comment]
Great addition!
Just one thing, could you extend the slider to negative values? So that I can add a tiny bit more haze to an image already full of atmosphere?

**Comment by agriggio** [comment]
I think that won't work with the current implementation, sorry. it might be possible but would require more tweaking... I'd prefer to have a basic version merged first

**Comment by agriggio** [comment]
can this go in for 5.5? what's the tentative release date?

**Comment by heckflosse** [comment]
@agriggio no objection from me for 5.5

**Comment by Beep6581** [comment]
@agriggio no objection from me either.

**Comment by Beep6581** [comment]
I just noticed that the `default` language file is [also](https://github.com/Beep6581/RawTherapee/pull/4893) corrupt here.

**Comment by agriggio** [comment]
sorry about the corruptions, I need to be more careful...

**Pull request merged**
