### PR TITLE
faster sigmoid function to create the contrast mask used in dual demo…

### PR DESCRIPTION
**Pull request by heckflosse**
…saic and capture sharpening, #6386

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I just tested on 2 images from Z6-2 with  - "Amaze + VNG4" and contrast threshold about 25


Gain in processing time - about 5 to 10%
No visible difference in TIFF
Very small differences in layers difference 16 bits

Good improvment :)

Jacques

**Comment by Floessie** [comment]
@heckflosse Somehow the GitHub interface for reviews has changed or I'm too dumb to find the right button... Nonetheless, I'd like to approve the change code-wise. I test-built it on PPC with Clang 13: not worse than before. :wink:

**Review by Floessie — APPROVED** [review]
Found the button at last. :facepalm:

**Comment by Thanatomanic** [comment]
Hi @heckflosse, to alleviate the mismatch between the original function and the faster one, you might want to consider to change the factor 16.0 to something more around 9.58. Over the entire range of threshold values, this is what my simple find-fit function gives me as a pretty decent fitting parameter. As you already predicted, the behavior near the edge cases is different.

image

**Comment by heckflosse** [comment]
> to change the factor 16.0 to something more around 9.58

The factor 16.0 was (is) just an optimization thing, see here, where 0.0625 = 1 / 16

https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/rt_algo.cc#L105

**Comment by heckflosse** [comment]
@Thanatomanic I have to think a bit more about your comment...

**Comment by heckflosse** [comment]
@Thanatomanic 

I don't understand what you mean, because you refer to the threshold.

The current formula is:

`x = -16.f + (16.f / threshold) * val`

If `threshold == val` that leads to x = 0, which leads to a value of 0.5 in both sigmoid functions.

**Comment by Thanatomanic** [comment]
@heckflosse I tried to find a different value for the `16.f` in order to make the two curves match each other more closely (least-squares minimization). If the 16 has a specific origin, no change is necessary of course, I cannot judge that.

My 'more optimal' suggestion would be to use
`x = -9.58f + (9.58f / threshold) * val`
Which still gives `x=0` when `threshold = val`.

**Comment by Thanatomanic** [comment]
An example of how the curve matches more closely (threshold = 0.8)
image

threshold = 0.4
image

Or if you want to play yourself: https://www.desmos.com/calculator/gdrzan4ubk

**Comment by heckflosse** [comment]
@Thanatomanic 

Ok, now I know what you mean. Factor 9.58 matches better in the mid range, but it converges worse against 0 or 1

**Comment by heckflosse** [comment]
@Thanatomanic Honestly I can not say, which of the sigmoid functions is better suited for the purpose.
`Original` was already an arbitrary choice in the sense that it is one of a lot of possible sigmoid functions.

**Comment by Thanatomanic** [comment]
Sure, it may not matter at all in the end. Feel free to keep it as is, I just had some fun with maths :-)

**Comment by heckflosse** [comment]
> I just had some fun with maths

same here :-)

**Comment by jenshannoschwalm** [comment]
I cross checked this in dt before doing the pr. I would think a "as close as possible to 1 / 0 in the flat regions" is desired for minimal blending cross-over. So i would opt for taking 16.

**Pull request merged**
