### PR TITLE
Add a brighter TooWaBlue theme

### PR DESCRIPTION
**Pull request by TooWaBoo**
Bright
bright

Standard
normal

Dark
dark

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Is there anything wrong with this theme?

**Comment by agriggio** [comment]
I haven't tested it and I have nothing against it in principle, but aren't the three variants a bit too close to each other? The differences seem fairly minimal to me (but maybe they look more similar in the screenshots than in actual use?)

**Comment by TooWaBoo** [comment]
The differences aren't big but big enough that some people like the brighter theme more. :smile:
In the old Gtk2 version there exists much more themes with less differences but it's up to you if you want to add the theme.

**Comment by agriggio** [comment]
well, it's not up to me but more choices are good, if people find these
useful then :+1: for me

**Comment by Beep6581** [comment]
Agreed that they are so similar one wonder's whether it's worth it, but then the file is only 3kB, so...

**Pull request merged**
