### PR TITLE
Tool panel vertical scrollbar bug in Linux #3413

### PR DESCRIPTION
**Pull request by Beep6581**
When the vertical scrollbar is set to hidden, one cannot scroll the
toolbox vertically using the mouse scrollwheel in Linux. This patch
works around the problem by forcing the scrollbar to always be visible
in Linux.

### CODE REVIEW

**Comment by Beep6581** [comment]
Any objections?

**Comment by agriggio** [comment]
No objections, but FWIW I scrolling works here (gtk+ 3.18.0)

**Comment by Beep6581** [comment]
@agriggio which Linux distro is that?
Please answer in #3413

**Comment by sguyader** [comment]
I see the same issue as described by @Beep6581 when hiding the vertical scrollbar in Manjaro (Gtk+ 3.22.2).
By the way, is really useful to have the option of hiding the scrollbar? Who finds it essential?

**Comment by heckflosse** [comment]
@sguyader It's not essential to hide the scrollbar, but it's useful to hide it if scrolling works without it (as it does on windows builds) ;-)

**Pull request merged**
