### PR TITLE
Local expo - improve exposure with Laplacian PDE

### PR DESCRIPTION
**Pull request by Desmis**
Exposure (derived from algorithm main) give often curious results...due to mix of algorithms

To improve, I add a Laplacian and Retinex_pde, before call to exposure

Also, I set "highlight compression" to 20
And change "scope"

@heckflosse 
Ingo
Could you have a look to code, but also, of course, to the result :)

jacques

### CODE REVIEW

**Comment by heckflosse** [comment]
@Desmis Jacques, I will have a look when your changes are completed ;-)

**Comment by Desmis** [comment]
@heckflosse 
I think they are :)

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I will make some small commits soon

**Comment by heckflosse** [comment]
@Desmis My changes for this pr are completed. Please test

**Comment by Desmis** [comment]
@heckflosse 

I tested, all seems to work fine :)

jacques

**Comment by heckflosse** [comment]
:+1: for merge

**Comment by Desmis** [comment]
OK thank you very much :)

jacques

**Pull request merged**
