### PR TITLE
Speedup for perceptual curve, #2817

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by Hombre57** [comment]
I've tried your patch and found a slight difference in reds close to the gamut. It's late now, I'd like to test more tomorrow, but is this something already noticed and should we care ? I'll try to report some processing time if you tell me where to put the timer.

**Comment by heckflosse** [comment]
Hombre, Michael also reported differences. There are differences in calculations between ciecam02 from rt and ciecam02 from lcms. So some differences in output are expected. But I don't know which one is 'better' or whether the differences matter at all.

Ingo

**Comment by Hombre57** [comment]
I built the HEAD version in release mode, but don't have numbers to provide (no console window). Anyway, I guess that the speedup is consistent with what you generally achieve :) So :+1 to commit this patch on my side.

**Comment by heckflosse** [comment]
Hombre, for information: Processing time of rgbproc() on my machine for full processing a D800 file
was 26700 ms before changes
is 4700 ms after changes.

Ingo

**Comment by Hombre57** [comment]
well, it's an improvement, indeed :)

Is there any known issue that prevent committing this ?

**Comment by heckflosse** [comment]
Yes, the differences in output. I would be glad to get a review from Anders because he implemented the original version. I also want to try further speedup using partly SSE coding (rt ciecam02 functions are already available for SSE)

**Comment by Beep6581** [comment]
I tested it thoroughly before the github switch and noticed only changes in strong purple hues. The changes were of such a nature that they didn't matter. I'll test head later today. +1 for commit.

**Comment by Hombre57** [comment]
The difference are in deep reds too (when reaching the gamut), e.g. with a rose under bright sunny day. Maybe we should take a deeper look ?

**Comment by heckflosse** [comment]
Ok, two +1 for commit should be enough ;-)
I'll remove StopWatch stuff, clean the code and merge later in the evening

**Comment by heckflosse** [comment]
Ok, I'll push cleaned code later today and then you can merge it or not ;-)

**Comment by heckflosse** [comment]
I cleaned the code and pushed

**Comment by atorger** [comment]
Sorry for not having been able to contribute on this, been choked with other stuff, and I'm entering a period now when I can't contribute as much. I'm sure it's fine though :-), the perceptual curve is no exact science anyway.

**Comment by heckflosse** [comment]
Anders, glad to see you here on github and thank you for commenting. I'll try further speedup using SSE ciecam02 functions later.

Ingo

**Comment by heckflosse** [comment]
For information, https://github.com/Beep6581/RawTherapee/commit/df13fb8b1b7b5fc4f4ee1304cfb974221fa6ff84 should fix the differences bug

**Comment by heckflosse** [comment]
I'm working on an additional speedup for perceptual curve (using SSE). I need some days to complete work.

**Pull request merged**
