### PR TITLE
modifications for portability to librtprocess

### PR DESCRIPTION
**Pull request by CarVac**
Here are the minimum changes needed specifically for amaze_demosaic.

I'll be doing one pull request per function made portable to break things up.

### CODE REVIEW

**Comment by Floessie** [comment]
@heckflosse Ingo, what's the intention of the `demosaic_source_folder` branch? Is it just a playground or intended to go mainline? If the latter, I'd like `cfarray` to be reconsidered and `setProgCancel` passed by `const&`.

**Comment by heckflosse** [comment]
@Floessie The latter. My intention was to get more structure in that part of source code. What do you suggest for `cfarray`?

**Comment by Floessie** [comment]
@heckflosse 
> What do you suggest for `cfarray`?

Either a `std::array<>` or a `CfArray` base class (interface) with virtual getters, if that's feasible.

Sorry for asking such a noob question, but what does `CF` and `FC` exactly stand for?

**Comment by heckflosse** [comment]
@Floessie 
`CF` is Colour Filter.
`FC` is from dcraw. Don't know what it means

**Comment by CarVac** [comment]
I think FC stands for Filter Color. I used CFarray because that corresponds to the acronym CFA for color filter array.

**Pull request merged**
