### PR TITLE
camconst.json add Fujifilm X-T200

### PR DESCRIPTION
**Pull request by noelbautista91**
Same sensor, been using X-T100 configs for my X-T200 and results work fine to me.

### CODE REVIEW

**Comment by Lawrence37** [comment]
Unfortunately, cameras with the same sensors can have different color filters. Have you objectively verified the color matrix is correct for the X-T200?

**Comment by noelbautista91** [comment]
I have not done any objective testing, and I have only copied this spec based on a [different PR](https://github.com/Beep6581/RawTherapee/pull/6990)

I'm merely trying to get RawTherapee to use the right profile, getting a little tired of manually picking out X-T100 :)

**Comment by kmilos** [comment]
Both RawSpeed and LibRaw have these down as different sensors:

https://github.com/LibRaw/LibRaw/blob/d3cbbd0e9934898eb28e4963ee99b51928e2acaa/src/tables/colordata.cpp#L542

**Comment by Lawrence37** [comment]
Closing this in favor of #7098.

**Pull request closed without merging**
