### PR TITLE
Strip Nikon ShotInfo tag when saving to JPEG as it bloats Exif block beyond 64kB limit

### LINKED ISSUE #5698: Nikon Z-series: The exif-tags from the raw file does not carry over to the exported jpeg file
# Version details
```
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: cc 9.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.95.0
Build type: Release
Build flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c++11  -Werror=unused-label -Werror=delete-incomplete -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
OpenMP support: ON
MMAP support: ON
```
# Operating system
```
Linux falcon 5.5.11-arch1-1 #1 SMP PREEMPT Sun, 22 Mar 2020 16:33:15 +0000 x86_64 GNU/Linux
```

# Problem

The exif-tags from the raw file does not carry over to the exported jpeg file

tmp_007

Exported jpeg:
2020-04-02_18-22-42_nikon z 6_dsc_0941

### PR DESCRIPTION
**Pull request by purew**
as it is 52Kb large on Nikon Z-series cameras, which results in
jpeg exif tags being larger than allowed 65Kb limit.

Fixes https://github.com/Beep6581/RawTherapee/issues/5698

### CODE REVIEW

**Comment by heckflosse** [comment]
@PureW 
Anders, thanks for the fix :+1: 
We will wait until the usual checks you can see below are completed before merge.

Ingo

**Comment by Thanatomanic** [comment]
A very quick and brief search led me to this: https://exiftool.org/TagNames/Nikon.html#ShotInfo
Doesn't seem really vital to keep.

However, keeping out the ShotInfo entirely, may be troublesome for other camera brands: https://exiftool.org/TagNames/Canon.html#ShotInfo

**Comment by heckflosse** [comment]
@Thanatomanic 
> However, keeping out the ShotInfo entirely, may be troublesome for other camera brands: 

Damn, good point, Do you have an example raw from Canon to test?

Edit: I looked at a lot of CR2 files for this tag, but didn't find one...

**Comment by purew** [comment]
Should I make it conditional for only Nikon models?

**Comment by heckflosse** [comment]
> Should I make it conditional for only Nikon models?

Maybe a good idea for the first step to avoid breaking stuff.

**Comment by purew** [comment]
> > Should I make it conditional for only Nikon models?
> 
> Maybe a good idea for the first step to avoid breaking stuff.

Agreed. Code updated. Would you want some kind of unittest for this change?

**Comment by Floessie** [comment]
@PureW What if any of the tags or directories doesn't exist? Wouldn't it segfault?

What about this (only compile-tested)?

```patch
diff --git a/rtexif/rtexif.cc b/rtexif/rtexif.cc
index c0038c067..917a2c3bd 100644
--- a/rtexif/rtexif.cc
+++ b/rtexif/rtexif.cc
@@ -3248,7 +3248,48 @@ int ExifManager::createJPEGMarker (const TagDirectory* root, const rtengine::pro
     TagDirectory* cl;
 
     if (root) {
-        cl = (const_cast<TagDirectory*> (root))->clone (nullptr);
+        cl = root->clone(nullptr);
+
+        // Drop unwanted tags before exporting
+        // For example, Nikon Z-series has a 52Kb MakerNotes->ShotInfo tag
+        // which does not fit into the 65Kb limit on JPEG exif tags
+        const Tag* const make_tag = cl->getTag(271);
+        if (make_tag && !std::strncmp((const char*)make_tag->getValue(), "NIKON CORPORATION", 17)) {
+            [cl]()
+            {
+                Tag* const exif_tag = cl->getTag(34665);
+
+                if (!exif_tag) {
+                    return;
+                }
+
+                TagDirectory* const exif_dir = exif_tag->getDirectory();
+
+                if (!exif_dir) {
+                    return;
+                }
+
+                Tag* const make_notes_tag = exif_dir->getTag(37500);
+
+                if (!make_notes_tag) {
+                    return;
+                }
+
+                TagDirectory* const maker_notes_dir = make_notes_tag->getDirectory();
+
+                if (!maker_notes_dir) {
+                    return;
+                }
+
+                Tag* const shot_info_tag = maker_notes_dir->getTag(145);
+
+                if (!shot_info_tag) {
+                    return;
+                }
+
+                shot_info_tag->setKeep(false);
+            }();
+        }
     } else {
         cl = new TagDirectory (nullptr, ifdAttribs, INTEL);
     }
```

I used the anonymous lambda as a modern alternative to `do { if (true) break; } while (false);`.

HTH,
Flössie

**Comment by Thanatomanic** [comment]
@PureW I'm also curious: how does e.g. Adobe Lightroom handle the transfer of the metadata for these files? Do you have the option to test that?

**Comment by purew** [comment]
> What if any of the tags or directories doesn't exist? Wouldn't it segfault?  What about this (only compile-tested)?

Ahh of course. Your code works for me so I pushed that update.

> @PureW I'm also curious: how does e.g. Adobe Lightroom handle the transfer of the metadata for these files? Do you have the option to test that?

Sorry, I'm pretty new to after-processing and have never used the Adobe products. I have used Darktable a little and it exports a jpeg with the following tags

```bash
$ ExifTool Version Number         : 12.00
File Name                       : 2020-03-28_12-12-25_nikon z 6_dsc_0745.jpg
Directory                       : .
File Size                       : 11 MB
File Modification Date/Time     : 2020:06:22 08:10:01-04:00
File Access Date/Time           : 2020:06:22 08:10:11-04:00
File Inode Change Date/Time     : 2020:06:22 08:10:01-04:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Reduced-resolution image
Make                            : NIKON CORPORATION
Camera Model Name               : NIKON Z 6
Orientation                     : Horizontal (normal)
X Resolution                    : 300
Y Resolution                    : 300
Resolution Unit                 : inches
Software                        : darktable 3.0.2
Modify Date                     : 2020:06:22 08:10:00
Artist                          : ANDERS BENNEHAG
Reference Black White           : 0 255 0 255 0 255
Rating Percent                  : 20
Exposure Time                   : 1/160
F Number                        : 4.0
Exposure Program                : Manual
ISO                             : 1250
Sensitivity Type                : Recommended Exposure Index
Recommended Exposure Index      : 1250
Create Date                     : 2020:03:28 12:12:25
Offset Time                     : -04:00
Offset Time Original            : -04:00
Offset Time Digitized           : -04:00
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Light Source                    : Unknown
Flash                           : No Flash
Focal Length                    : 54.0 mm
VR Info Version                 : 0200
Vibration Reduction             : On
VR Mode                         : On (1)
Picture Control Version         : 0300
Picture Control Name            : Monochrome
Picture Control Base            : Monochrome
Picture Control Adjust          : Quick Adjust
Picture Control Quick Adjust    : n/a
Mid Range Sharpness             : 2.00
Clarity                         : 1.00
Brightness                      : Normal
Hue                             : n/a
Filter Effect                   : Off
Toning Effect                   : B&W
Toning Saturation               : n/a
Time Zone                       : -05:00
Daylight Savings                : Yes
Date Display Format             : Y/M/D
ISO Expansion                   : Off
ISO2                            : 1270
ISO Expansion 2                 : Off
Multi Exposure Version          : 0101
Multi Exposure Mode             : Off
Multi Exposure Shots            : 0
Multi Exposure Auto Gain        : Off
AF Info 2 Version               : 0300
Contrast Detect AF              : On (2)
AF Area Mode                    : Auto (198)
Phase Detect AF                 : Off
Primary AF Point                : C6 (Center)
AF Points Used                  : (none)
AF Image Width                  : 6048
AF Image Height                 : 4024
AF Area X Position              : 5246
AF Area Y Position              : 2003
AF Area Width                   : 130
AF Area Height                  : 134
File Info Version               : 0100
Memory Card Number              : 0
Directory Number                : 100
File Number                     : 0745
AF Fine Tune                    : Off
AF Fine Tune Index              : n/a
AF Fine Tune Adj                : 0
AF Fine Tune Adj Tele           : 0
Maker Note Version              : 2.11
Quality                         : RAW
White Balance                   : Auto1
Focus Mode                      : AF-C
Flash Setting                   : 
Flash Type                      : 
White Balance Fine Tune         : 0 0
WB RB Levels                    : 1.72265625 1.296875 1 1
Program Shift                   : 0
Exposure Difference             : -1.8
External Flash Exposure Comp    : 0
Flash Exposure Bracket Value    : 0.0
Exposure Bracket Value          : 0
Crop Hi Speed                   : FX Uncropped (6064x4040 cropped to 6064x4040 at pixel 0,0)
Exposure Tuning                 : 0
Active D-Lighting               : Off
Vignette Control                : Normal
Auto Distortion Control         : On
Shutter Mode                    : Unknown (81)
Mechanical Shutter Count        : 681
Black Level                     : 1008 1008 1008 1008
Crop Area                       : 8 8 6048 4024
Color Temperature Auto          : 5320
Lens Type                       : AF
Lens                            : 24-70mm f/4
Flash Mode                      : Did Not Fire
Shooting Mode                   : Continuous
Lens F Stops                    : 5.00
Contrast Curve                  : (Binary data 578 bytes, use -b option to extract)
Warning                         : Can't decrypt Nikon information (no ShutterCount key)
Noise Reduction                 : Off
NEF Linearization Table         : (Binary data 46 bytes, use -b option to extract)
Raw Image Center                : 3032 2020
Retouch History                 : None
Shutter Count                   : 743
Flash Info Version              : 0108
Flash Source                    : None
External Flash Firmware         : n/a
External Flash Zoom Override    : No
External Flash Status           : Flash Not Attached
External Flash Ready State      : n/a
Flash Compensation              : 0
Flash GN Distance               : 0
Flash Group A Control Mode      : Off
Flash Group B Control Mode      : Off
Flash Group C Control Mode      : Off
Flash Group A Compensation      : 0
Flash Group B Compensation      : 0
Flash Group C Compensation      : 0
Vari Program                    : 
High ISO Noise Reduction        : Normal
Power Up Time                   : 2020:03:23 18:20:15
Retouch Info Version            : 0200
Retouch NEF Processing          : Off
Compression                     : JPEG (old-style)
Preview Image Length            : 69133
Y Cb Cr Positioning             : Co-sited
Sub Sec Time                    : 01
Sub Sec Time Original           : 01
Sub Sec Time Digitized          : 01
Color Space                     : sRGB
Exif Image Width                : 2664
Exif Image Height               : 3999
Sensing Method                  : One-chip color area
File Source                     : Digital Camera
Scene Type                      : Directly photographed
CFA Pattern                     : [Red,Green][Green,Blue]
Custom Rendered                 : Custom
Exposure Mode                   : Manual
Focal Length In 35mm Format     : 54 mm
Scene Capture Type              : Standard
Gain Control                    : Low gain up
Contrast                        : Normal
Saturation                      : Normal
Sharpness                       : Normal
Subject Distance Range          : Unknown
Serial Number                   : 3054814
Lens Info                       : 24-70mm f/4
Lens Make                       : NIKON
Lens Model                      : NIKKOR Z 24-70mm f/4 S
Lens Serial Number              : 20112047
Date/Time Original              : 2020:03:28 12:12:25
TIFF-EP Standard ID             : 1 0 0 0
XMP Toolkit                     : XMP Core 4.4.0-Exiv2
Camera Profile                  : Camera Monochrome
Color Noise Reduction           : 10
Color Noise Reduction Detail    : 50
Color Noise Reduction Smoothness: 50
Contrast 2012                   : 0
Exposure 2012                   : 0.00
Highlights 2012                 : 0
Luminance Noise Reduction Contrast: 0
Luminance Noise Reduction Detail: 75
Luminance Smoothing             : 36
Shadows 2012                    : 0
Sharpen Detail                  : 25
Sharpen Edge Masking            : 0
Sharpen Radius                  : 2.00
Creator Tool                    : NIKON Z 6 Ver.03.00
Rating                          : 1
Derived From                    : 2020-03-28_12-12-25_nikon z 6_dsc_0745.nef
Xmp version                     : 3
Raw params                      : 0
Auto presets applied            : 1
History end                     : 10
Iop order version               : 5
Creator                         : ANDERS BENNEHAG
Masks history                   : 
History Num                     : 0
History Operation               : rawprepare
History Enabled                 : 1
History Modversion              : 1
History Params                  : 00000000000000000000000000000000f003f003f003f003a03c0000
History Multi name              : 
History Multi priority          : 0
History Iop order               : 1.0000000000000
History Blendop version         : 9
History Blendop params          : gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ=
Profile CMM Type                : Little CMS
Profile Version                 : 2.1.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2020:06:22 12:08:50
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Embedded, Independent
Device Manufacturer             : 
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Little CMS
Profile ID                      : 0
Profile Description             : sRGB
Profile Copyright               : Public Domain
Media White Point               : 0.3127 0.32899 1
Chromatic Adaptation            : 1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
Red Matrix Column               : 0.43604 0.22249 0.01392
Blue Matrix Column              : 0.14305 0.06061 0.71391
Green Matrix Column             : 0.38512 0.7169 0.09706
Red Tone Reproduction Curve     : (Binary data 8204 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 8204 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 8204 bytes, use -b option to extract)
Chromaticity Channels           : 3
Chromaticity Colorant           : Unknown (0)
Chromaticity Channel 1          : 0.64 0.33
Chromaticity Channel 2          : 0.3 0.60001
Chromaticity Channel 3          : 0.14999 0.06
Media Black Point               : 0 0 0
Device Model Desc               : sRGB
Device Mfg Desc                 : Darktable
Image Width                     : 2664
Image Height                    : 3999
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Aperture                        : 4.0
Blue Balance                    : 1.296875
Image Size                      : 2664x3999
Megapixels                      : 10.7
Red Balance                     : 1.722656
Scale Factor To 35 mm Equivalent: 1.0
Shutter Speed                   : 1/160
Create Date                     : 2020:03:28 12:12:25.01-04:00
Date/Time Original              : 2020:03:28 12:12:25.01-04:00
Modify Date                     : 2020:06:22 08:10:00.01-04:00
Auto Focus                      : On
Lens Spec                       : 24-70mm f/4 AF
Circle Of Confusion             : 0.030 mm
Field Of View                   : 36.9 deg
Focal Length                    : 54.0 mm (35 mm equivalent: 54.0 mm)
Hyperfocal Distance             : 24.26 m
Light Value                     : 7.7
```

**Comment by Thanatomanic** [comment]
I've tried out what other RAW processing software does with the metadata for a Nikon Z 6 file. This is the result: https://filebin.net/0gavub55gry2sv0d

I have not yet compared the contents to see what we should/could keep. One thing is sure, everybody does something else.

**Comment by purew** [comment]
> see what we should/could keep. One thing is sure, everybody does something

Keep in mind that the current situation results in _no tags at all_ in the exported image which is a pretty bad result for Z-series users of RawTherapee.

**Comment by purew** [comment]
@Thanatomanic What do you think about merging this PR as dropping a useful `ShotInfo` property is much less serious than completely dropping all exif tags for Nikon Z users as is the current situation.

**Comment by heckflosse** [comment]
> What do you think about merging this PR as dropping a property too much in ShotInfo is much less serious than completely dropping all exif tags for Nikon Z users?

:+1: from me for merge

**Comment by Thanatomanic** [comment]
So, currently this PR would affect all Nikon camera metadata, right? Is this necessary, harmful or is there a way to limit this to the Nikon mirror less camera's?

**Comment by heckflosse** [comment]
I inspected some NEF files. The ShotInfo Tag seems to be binary and not being used by RawTherapee at all (except of that default handling of this tag in rtexif/nikonattribs.cc, which just shows the values without interpretation)

**Comment by Thanatomanic** [comment]
And what about other applications? Some people export TIFFs from RT for further editing in other software. The chances are probably small that the other software uses these tags, but how small? 😉 

Otherwise, let's merge.

**Pull request merged**
