### PR TITLE
Fix incompatibility with glibmm 2.50 (#3440)

### PR DESCRIPTION
**Pull request by Floessie**
Kudos to @Hombre57 for the suggestion.

### CODE REVIEW

**Comment by Floessie** [comment]
@Beep6581 @heckflosse Could (one of) you have a look, if it also compiles with an older version of glibmm-2.4?

**Comment by Beep6581** [comment]
I don't have access to 2.50 yet.

**Comment by Floessie** [comment]
@Beep6581 That's what I meant. :smile:

**Comment by Beep6581** [comment]
Compiled and runs fine using glibmm-2.46.4.

**Comment by innir** [comment]
The gkt3 branch uses `dir->get_parse_name()` (see https://github.com/Beep6581/RawTherapee/blob/gtk3/rtgui/dirbrowser.cc#L62). What's the difference? And shouldn't it be the same in both cases?

**Comment by Floessie** [comment]
@innir Good point, although I don't think it really matters, as it's about an error message on `stderr`. But yes, that's an inconsistency.

@Hombre57 As you did the fix in the GTK3 branch and suggested the solution here: What is closer to the original message? `get_parse_name()` or `get_basename()`?

**Comment by Beep6581** [comment]
I need to choose one or the other when merging, so I'd like to know too.

**Comment by Hombre57** [comment]
@Floessie @Beep6581 Well, you're right, `get_basename` is a better option as it gives the full path instead of the last folder only. I didn't cared too much wen fixing it, sorry.

**Comment by Floessie** [comment]
@Beep6581 I'll care about this one directly on master tonight.

**Comment by Floessie** [comment]
@Hombre57 I guess you meant `get_parse_name()` and corrected that in the master branch. Now master and gtk3 are the same in this regard.

**Comment by Hombre57** [comment]
I probably need some hollyday :-/

**Comment by Floessie** [comment]
@Hombre57 Probably everyone needs some time to breathe when RT5 is out.

**Pull request merged**
