### PR TITLE
cleanups for locallab periphery

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 
I tested
Compile no problem :)
Run in preview , no problem :)

Crash in output TIF 

Here a pp3....I tried with various Raw, same crash....
[_MG_3029.CR2.txt](https://github.com/Beep6581/RawTherapee/files/4839969/_MG_3029.CR2.txt)


I completed tested....crash even with no curves...Crash (in Output TIF) when create a RT-spot, with nothing inside

jacques

**Comment by Desmis** [comment]
@heckflosse 

After several tested, it seems that crash disapears when **"sharpening inverse"** is enable

If I enable "sharpening inverse", and I compare with the pp3   _MG_3029.CR2.txt, no differences in TIF with your commits and without



jacques

**Comment by heckflosse** [comment]
I will have a look now

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I tested, all works fine :)

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I tested last commit.
All seems to work fine :)

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing :+1: 

I have a question about some LUT<float> you use for locallab.
For example here
https://github.com/Beep6581/RawTherapee/blob/cleanup_locallab_periphery/rtengine/improccoordinator.cc#L190

`lllocalcurve(65536, 0)`

That means, the LUT is created with 65536 entries, the LUT behaviour is set to not clip above or below and the LUT entries are not initialized at the time of the creation of the LUT.
I have the impression, you thought, the second argument (the 0) is for initializing the LUT entries, but that's not the case.
So, what's the intended behaviour of this LUTs? Should they clip above or below or not? I will change them then to make that more clear in code.

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I think they should not clip above and below

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I tested last commit
All seems to work fine :)

Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, shall I wait with merging this branch until you merged you localmask branch or shall I just merge this into dev and then merge dev into localmask?

**Comment by Desmis** [comment]
@heckflosse 

I think, the "order" would be
* merge localmask
* then merge this branch

I think I have finished all my improvments on "localmask" :)
Have you finished your review on localmask ?

So, when can I push the "pull request" for "localmask" ?

jacques

**Comment by heckflosse** [comment]
@Desmis 
> So, when can I push the "pull request" for "localmask" ?

I partly reviewed it. Just push the merge button for localmask :+1: and I will continue my review of iplocallab.cc

**Comment by Desmis** [comment]
@heckflosse 

Ok

Thank you
I push
jacques

**Comment by heckflosse** [comment]
@Desmis I will work on solving the merge conflicts now. Will need a while...

**Comment by Desmis** [comment]
@heckflosse 
Ingo

Ok, thank you :)
jacques

**Comment by heckflosse** [comment]
@Desmis, Jacques, I tried to solve the merge conflicts for this branch. That's quite a lot of work. I will continue tomorrow and have a glass of good wine now. Please do not push any changes to simpleprocess.cc, improccoordinator.* and dcrop.cc meanhwile

**Comment by Desmis** [comment]
@heckflosse 

I have already drink good wine :)

No problem, I push nothing

Thank you again :)

Good night

jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I tested "merge"...all works fine :)

Good job

jacques

**Pull request merged**
