### PR TITLE
RGB Curves Luminosity mode: ~ 40% speedup

### PR DESCRIPTION
**Pull request by heckflosse**
Here's a speedup for RGB Curves Luminosity mode.
Processing tome for ImProcFunctions::rgbProc went down from 1027 ms to 772 ms measured with my usual D800 file and neutral profile + RGB green curve in Luminosity mode.
That's a gross speedup of ~25%, but rgbproc does a lot of other things too which take ~394 ms, so after subtracting the 394 ms from the above mentioned values we get a net speedup of ~40% for the RGB Curves Luminosity mode part of the function.

Ingo

### CODE REVIEW

**Comment by Floessie** [comment]
:+1: for also streamlining the code. Now it's a pleasure to read.

**Comment by heckflosse** [comment]
I added a modification which reduces the number of atan2 calculations. Processing time is reduced to ~720 ms.

**Comment by heckflosse** [comment]
I added an experimental modification to equalize the effect of R, G and B curve in luminosity mode.
For reference: #3266

**Comment by heckflosse** [comment]
@Desmis @michaelezra @Beep6581  What's your opinion about the experimental change?

Ingo

**Comment by michaelezra** [comment]
Hi Ingo, great to have such speedups. Since migration to git I've lost ability to compile rt.. If there is an exe, I 'd be glad to test:)

**Comment by heckflosse** [comment]
Hi Michael, my question was about the last (experimental) change (equalizing strength of rgv curves in luminosity mode). That will break backward compatibility for R and B curves in luminosity mode but will also increase usability.

Ingo

**Comment by michaelezra** [comment]
Hi Ingo, if it will improve action of the blue curve, which is basically absent right now, then it is certainly a welcome change:)



-------- Original message --------From: Ingo Weyrich <notifications@github.com> Date: 8/26/16  4:50 PM  (GMT-05:00) To: Beep6581/RawTherapee <RawTherapee@noreply.github.com> Cc: Michael Ezra <michael@michaelezra.com>, Mention <mention@noreply.github.com> Subject: Re: [Beep6581/RawTherapee] RGB Curves Luminosity mode: ~ 40% speedup
  (#3404) 
Hi Michael, my question was about the last (experimental) change (equalizing strength of rgv curves in luminosity mode). That will break backward compatibility for R and B curves in luminosity mode but will also increase usability.

Ingo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Beep6581/RawTherapee","title":"Beep6581/RawTherapee","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Beep6581/RawTherapee"}},"updates":{"snippets":[{"icon":"PERSON","message":"@heckflosse in #3404: Hi Michael, my question was about the last (experimental) change (equalizing strength of rgv curves in luminosity mode). That will break backward compatibility for R and B curves in luminosity mode but will also increase usability.\r\n\r\nIngo"}],"action":{"name":"View Pull Request","url":"https://github.com/Beep6581/RawTherapee/pull/3404#issuecomment-242848074"}}}

**Comment by heckflosse** [comment]
@michaelezra It will also change the action of red curve (all are equal after the change and almost independent on working colour space).

**Comment by michaelezra** [comment]
Even better;) Thank you Ingo!



-------- Original message --------From: Ingo Weyrich <notifications@github.com> Date: 8/26/16  5:27 PM  (GMT-05:00) To: Beep6581/RawTherapee <RawTherapee@noreply.github.com> Cc: Michael Ezra <michael@michaelezra.com>, Mention <mention@noreply.github.com> Subject: Re: [Beep6581/RawTherapee] RGB Curves Luminosity mode: ~ 40% speedup
  (#3404) 
@michaelezra It will also change the action of red curve (all are equal after the change and almost independent on working colour space).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Beep6581/RawTherapee","title":"Beep6581/RawTherapee","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Beep6581/RawTherapee"}},"updates":{"snippets":[{"icon":"PERSON","message":"@heckflosse in #3404: @michaelezra It will also change the action of red curve (all are equal after the change and almost independent on working colour space)."}],"action":{"name":"View Pull Request","url":"https://github.com/Beep6581/RawTherapee/pull/3404#issuecomment-242856192"}}}

**Comment by heckflosse** [comment]
I merged to get more tests for the new behaviour of rgb red and blue curve in Luminosity mode.

**Pull request merged**
