### PR TITLE
Bug #6329: Variable done should be set to true inside loop, otherwise one fail w…

### LINKED ISSUE #6329: Saving profile to directory without permission results in blocked UI
System:
Windows 10 Home, Version 20H2, Build 19042.1110

RawTherapee:
Version: 5.8-3014-g94b5f7232
Branch: dev
Commit: 94b5f7232
Commit date: 2021-07-27

**Steps to reproduce**
- open a photo (raw)
- move any slider or just
- press save profile
- **NOW:** choose a folder in which you dont have the rights to save a file
(here preset i found: c:\Program Files\RawTherapee\RawTherapee_dev_5.8-3014-g94b5f7232_W64_Skylake_210727)
- Click "ok"
- Get informed by an infobox you dont have rights to save a file here
- Close this infobox by clicking „ok“
(From now on, it doesnt matter, if you save the profile to another folder or not)
- Choose a different folder and save the file anywhere or
- Just click „cancel“
- The Box „save a profile“ wont close anymore there is no chance to get back to the editor
- Finally shut down Raw Therapee by using the taskmanager.

**Expected behavior**
After saving a profile, the box „save profile“ should close.
After clicking „cancel“ the box „save profile“ should close.
Raw Therapee should come back to the editor

**Additional information**
Saving the profile in a different folder and overwriting an existing file will show the buttons YES / NO in english, seems they are not getting translated by the default-file.

### PR DESCRIPTION
**Pull request by ghost**
…ill cause to stay in loop forever.

Bug will be caused by setting done to false and never resetting it to be true.

### CODE REVIEW

**Comment by Lawrence37** [comment]
Nice catch. The loop could be refactored to make the intention more clear and reduce the scope of the exit condition variable, but of course that's optional.

**Comment by ghost** [comment]
> Nice catch. The loop could be refactored to make the intention more clear and reduce the scope of the exit condition variable, but of course that's optional.

I refactored the code just to be more readable. Buuuut, more readable to my prefs. And sometimes I like to write a little but more code, but make it better readable for me to let the code explain what it does. That is subjective for sure.

So please review whether the change is ok for everyone here.

**Review by Lawrence37 — APPROVED** [review]
There's always more to refactor, but this is ok.

**Comment by Lawrence37** [comment]
Thanks for these pull requests @Christian-Kr!

**Pull request merged**
