### PR TITLE
Rgbroc speedup

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by heckflosse** [comment]
Branch stays open for further speedups and cleanups

**Comment by TooWaBoo** [comment]
With the latest version all my pictures became a slightly pink color cast.

```
Version: 5.3-370-g4c3e7b8e
Branch: dev
Commit: 4c3e7b8e
Commit date: 2017-12-31
Compiler: gcc 7.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -Wno-aggressive-loop-optimizations -DNDEBUG -O3 -ftree-vectorize
Link flags: -m64 -mthreads -static-libgcc -march=native -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment]
@TooWaBoo Thanks for reporting. Can you share an image and the pp3?

**Comment by TooWaBoo** [comment]
Here it is: https://filebin.net/72iyoffk6xwhq9e3

**Comment by heckflosse** [comment]
@TooWaBoo Thank you. Issue confirmed. Looking

**Comment by heckflosse** [comment]
@TooWaBoo I commited a fix

**Comment by TooWaBoo** [comment]
@heckflosse , It's fixed, thanks
Happy New Year :-)

**Pull request merged**
