### PR TITLE
FFTW blur radius fix

### LINKED ISSUE #7225: Selective Editing blur radius different in preview
**Short description**
When using Selective Editing > Blur/Grain & Denoise > Blur & Noise > Radius, the preview gives an inaccurate preview of the blur amount at zoom <100%.

**Steps to reproduce**
1. Enable Selective Editing, add a new spot, and add the Blur/Grain & Denoise tool.
2. Increase the blur radius.
3. Observe the blur amount at different zoom levels.

**Expected behavior**
The blur in the preview is close to the amount in the saved image.

Preview at 20% zoom:
image

Exported image, scaled down to 20%:
image

Quick tests show that the blur amount is inversely proportional to the zoom, e.g. double the radius at 50%, triple the radius at 33%, quadruple the radius at 25%, etc.. It seems the radius is not scaled to compensate for the zoom factor.

### PR DESCRIPTION
**Pull request by Lawrence37**
Closes #7225.

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 

This PR also fix #7226.
Change in iplocallab.cc  = > ImProcFunctions::BlurNoise_Local

**Comment by Desmis** [comment]
@Lawrence37 

It's good for me.

I will be away from home for 15 days or 3 weeks. But I think I can be reached.

**Comment by Lawrence37** [comment]
Thanks for reviewing @Desmis.

**Comment by Desmis** [comment]
It is ok for me for this part (fftw).

In my proposition (fixbug-blur), there was also the solution to issue 7226, as well as a notable improvement for the user when he wants to blur a background. I changed the way the "Recovery based on luminance mask" function works. Now this function works with "Gaussian blur (noise and grain) , Median, and Guided Filter instead of only Guide Filter.

I assume that these proposals will be dealt with later, separately from this PR.

**Comment by Lawrence37** [comment]
Since this pull request also handles the pp3 compatibility, I will merge it and see if the other fixes and improvements can be incorporated directly from your branch @Desmis.

**Pull request merged**
