### PR TITLE
Update Deutsch locale

### PR DESCRIPTION
**Pull request by TooWaBoo**

### CODE REVIEW

**Comment by Beep6581** [comment]
@TooWaBoo see the other changes:
https://github.com/TooWaBoo/RawTherapee/commits/dev/rtdata/languages/default

**Comment by Beep6581** [comment]
I pushed a commit.

**Comment by Beep6581** [comment]
@TooWaBoo I just pushed a commit, see Deutsch.

**Comment by TooWaBoo** [comment]
Closing PR and create a new translation.

**Pull request closed without merging**
