### PR TITLE
Delayed GUI updates

### PR DESCRIPTION
**Pull request by Floessie**
Hello fellow RawTherapists,

I've added a little facility in `rtgui/delayed.h` as a generic solution to #5813. I started with something for `adjuster.h`, that's why the branch is called `delayed_connection`.

The interesting thing was to come up with an idea on how to store and especially replay a function call. While it was relatively clear that a `std::tuple<>` was the right "container" to store the parameters, a bit of research was necessary for the replaying. I've added the references in the code. Should we ever switch to C++17, the solution is already there, namely [`std::apply()`](https://en.cppreference.com/w/cpp/utility/apply).

Hope you like it,
Flössie

### CODE REVIEW

**Review by Thanatomanic — APPROVED** [review]
I see no real downsides. The CPU usage is measurably lower, which is nice.

**Review by Pandagrapher — APPROVED** [review]
Really nice work 👍 I haven't seen side effect while testing.

Just a general question:
Should we generalize it to `adjuster` class by default instead of only using it for heavy algorithms (maybe with a smaller delay compared to heavy algorithms)?

**Comment by heckflosse** [comment]
@Pandagrapher 

> Should we generalize it to adjuster class by default instead of only using it for heavy algorithms (maybe with a smaller delay compared to heavy algorithms)?

There already are two delays (one for the heavier and one for the not so heavy algorithms)

**Comment by Floessie** [comment]
@Thanatomanic @Pandagrapher @heckflosse Thanks for the review. :+1: I'll merge the branch to `dev`.

**Pull request merged**
