### PR TITLE
Multiple External Editors

### LINKED ISSUE #6114: Multiple Custom External Editors
The current external editor feature has some limitations.
- GIMP and Photoshop are hard-coded as options.
- Other editors cannot be easily added.
- There is only one custom command line option.
- Switching between editors can only be done by opening preferences.

I would like to address the limitations by changing the UI. I'm thinking about replacing the radio selector with an editable list (similar to the dynamic profile rules). This will allow multiple command line options and application options which are set through GTK 3's AppChooserDialog. The export to external editor button will be replaced with a RT PopUpButton. The popup is used to change the selected editor. Pressing the button will export the image to the currently selected editor. Additionally, the popup could have an "other" option which will open an AppChooserDialog and immediately export the image to the chosen application.

Similar to #2900

### PR DESCRIPTION
**Pull request by Lawrence37**
This makes it possible to add any number of external editors.
Features:
- Add editors from a list of installed programs.
- Customize the name and command. (Note: By design, the icon will disappear if the command is changed.)
- Select an editor from the main editor window using the "Send to external editor" button. The current editor is indicated with the program's icon. Also, the name appears in the tooltip.
- Export to *any* installed program by selecting the "Other" option.
- "Caches" the most recent image sent to the external editor. If the temporary image from the previous export exists and the processing parameters have not changed, that image will be used instead of re-processing.

External editors are customized in preferences. Entries can be added and removed. The name and command can be manually entered, or automatically populated by pressing the "Change Application" button and selecting from a list of installed programs. It is possible to re-order entries by drag-and-drop.
image

The "Send to external editor" button in the editor window allows the editor to be selected. The "Other" option is always available, allowing any installed program to be selected upon pressing the "Send to external editor" button.
image

There are some OS-dependent parts which have not been tested. They affect the reading of the old external editor preferences, allowing migration to the new one. The first time RT launches with the new version, GIMP, Photoshop, and the custom command are added to the list of editors (if applicable) and the selected editor is reflected in the "Send to external editor" button. The following need to be tested:

**MacOS**: I have made no attempt to detect the availability of GIMP and Photoshop, so these programs will be added as external editors even if not installed. If someone knows a simple way to detect the programs, please let me know.
- There should be 2 GIMP entries. In the old external editors feature, RT will try to open one of two GIMP versions, so I've added them both here.
  - The first entry should be normal GIMP.
    - Name: GIMP
    - Icon: The GIMP icon.
    - Command: `open -a GIMP` (Please make sure this actually opens GIMP!)
  - The second entry is GIMP dev. (Should this even be included?)
    - Name: GIMP-dev
    - Icon: The GIMP icon.
    - Command: `open -a GIMP-dev`
  - If GIMP was selected as the external editor, the selected editor in the new version should be (normal) GIMP.
- There should be a Photoshop entry.
  - The entry should have the following:
    - Name: Photoshop
    - Icon: None. (Maybe I can add the Photoshop icon, but I can't test.)
    - Command: `open -a Photoshop`
  - If Photoshop was selected as the external editor, the selected editor in the new version should be Photoshop.
- If a custom editor was set, an entry should be added for it.
  - The entry should have the following:
    - Name: -
    - Icon: None.
    - Command: Exactly the same as what the user had set.
  - If the custom editor was set and was selected as the external editor, the selected editor in the new version should be this editor.

**Windows**
- If the GIMP directory is (properly) set, there should be a GIMP entry.
  - If the `bin\gimp-win-remote` executable exists in the directory, it will be used.
  - If a `bin\gimp-2.##.exe` executable exists in the directory, it will be used.
  - The entry should have the following:
    - Name: GIMP
    - Icon: The GIMP icon.
    - Command: The path of the executable.
  - If GIMP was selected as the external editor, the selected editor in the new version should be GIMP.
- If the Photoshop directory is (properly) set with the `Photoshop.exe` executable inside, there should be a Photoshop entry.
  - The entry should have the following:
    - Name: Photoshop
    - Icon: None.
    - Command: The path of the executable.
  - If Photoshop was selected as the external editor, the selected editor in the new version should be Photoshop.
- If a custom editor was set, an entry should be added for it.
  - The entry should have the following:
    - Name: -
    - Icon: None.
    - Command: Exactly the same as what the user had set.
  - If the custom editor was set and was selected as the external editor, the selected editor in the new version should be this editor.

Linux has already been tested. I could also test Windows, although I do all my RT development in Linux. I can test the MacOS code to some extent, but obviously it can only be fully tested by someone who has MacOS. To aid with testing multiple scenarios, you can uncomment [this line](https://github.com/Beep6581/RawTherapee/blob/72fe8d6049ddf315c43518a904c7716b63d13db3/rtgui/preferences.cc#L37) to expose the old UI. Then, you can set the old preferences, close RT, remove the new keys from the `options` file (look under `[External Editor]` for `Names`, `Commands`, `IconNames`, and `EditorIndex`), open RT, and verify the old preferences are properly converted.

Any help and feedback is much appreciated.

Closes #6114.

### CODE REVIEW

**Comment by heckflosse** [comment]
> I could also test Windows

I will test on Windows

**Comment by heckflosse** [comment]
I tested on Windows.

In dev build I had set a custom editor this way:

```
C:\Program Files\Digital Light & Color\Picture Window Pro 7.0\pw70.exe
```

which worked fine in dev build

I built your branch and started RT. Got this in console:

```
gtk_icon_info_load_icon: assertion 'icon_info != NULL' failed
```

I opened a nef in RT and clicked on the `send to editor` Icon:

```
Segmentation fault
```

I started again, opened a nef in RT and clicked on the `send to editor` Icon:

```
terminate called after throwing an instance of 'Glib::SpawnError'
```

I will make a debug build now...

**Comment by heckflosse** [comment]
Unfortunately a debug build did not help :-(

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'Glib::SpawnError'
[Thread 1172.0x1c98 exited with code 3]
[Thread 1172.0x1de8 exited with code 3]
[Thread 1172.0x1190 exited with code 3]
[Thread 1172.0x7a8 exited with code 3]
[Thread 1172.0x1df4 exited with code 3]
[Thread 1172.0x1fd0 exited with code 3]
[Thread 1172.0x1ee0 exited with code 3]
[Thread 1172.0x4f0 exited with code 3]
[Thread 1172.0x1f80 exited with code 3]
[Thread 1172.0x1f8 exited with code 3]
[Thread 1172.0x1d38 exited with code 3]
[Thread 1172.0x1868 exited with code 3]
[Thread 1172.0x1fa0 exited with code 3]
[Thread 1172.0x1dc4 exited with code 3]
[Thread 1172.0x1e64 exited with code 3]
[Inferior 1 (process 1172) exited with code 03]
(gdb) bt full
No stack.
(gdb)
```

**Comment by heckflosse** [comment]
@Thanatomanic Could you give this a try?

**Comment by Thanatomanic** [comment]
My preferences look like this
image
Two things of note:
1. If there should be icons in front of the application names, it doesn't work (GIMP has an exclamation mark)
2. The right panel is oddly stretched vertically.

My editor window looks like this
image
The lack of icon for GIMP and consequently empty button doesn't seem right. Selecting either option from the dropdown and clicking the button to open the file externally crashes RT (no segfault in my case).

Edit: @Lawrence37 regardless, great to see you work on this! :+1:

**Comment by Lawrence37** [comment]
@heckflosse @Thanatomanic Thanks for testing!

> The right panel is oddly stretched vertically.

Oops. Forgot to push a commit.

@Thanatomanic Can you add GIMP (and Photoshop) using the "+" and "Change Application" buttons, save the preferences, and share the values under `[External Editor]` in the options file?

**Comment by Thanatomanic** [comment]
@Lawrence37 When I press "Change Application" I get a window with the message 'No applications found for "image/tiff filetype" files'. There is a button 'View All Applications', but that gives a weird list of registry keys, apps and processes..  Neither GIMP nor Photoshop is in this list.

image

**Comment by Lawrence37** [comment]
That's not a good sign. I will need to do some research on how this app chooser works on Windows.

**Comment by Lawrence37** [comment]
I think the crash and icons are fixed. There's definitely something weird with the application chooser which leads to another crash. It could be a GTK/GIO bug, but I'll need to investigate further. The MacOS version needs some testing, seeing how Windows turned out.

**Comment by Lawrence37** [comment]
[This](https://gitlab.gnome.org/GNOME/glib/-/issues/1104) bug causes the app chooser crash on Windows. I will need to write a custom app chooser to work around it or use a file chooser instead.

**Comment by Lawrence37** [comment]
I will let people do one last round of testing before merging this.

Documentation which will need to be integrated into the appropriate RawPedia page(s):

---

http://rawpedia.rawtherapee.com/Preferences#External_Editor

### External Editor
The list of external editors can be set here. All saved external editors are selectable from the [Edit Current Image in External Editor](http://rawpedia.rawtherapee.com/Edit_Current_Image_in_External_Editor) button in the Editor. To get started, click the plus button. This will add a new entry to the list. Then, click Change Application or Change Executable to select the external editor. The Change Application button opens a list of installed applications to choose from, while the Change Executable button opens an executable file selector. Multiple external editors can be added this way. To remove an editor, select the entry in the list and click the minus button.

The external editor names and commands can be edited directly by double clicking the text. Command formats depend on the operating system.
*insert the existing documentation for custom command line here*

---

http://rawpedia.rawtherapee.com/Edit_Current_Image_in_External_Editor

*this page needs to be edited to say that the editor of choice can be selected. there is also outdated information due to the ability to change the temporary directory (see #6232)*

When the button is clicked, the currently selected external editor will be opened to edit the processed image. The button's icon and tooltip reflect the current external editor. To change the editor, click on the arrow and choose from the list (this list is configurable from [Preferences](http://rawpedia.rawtherapee.com/Preferences#External_Editor)). Note that the last entry in the list is "Other". If this options is selected, clicking the button will open a list of installed applications. RawTherapee will then send the processed image to the chosen application.

---

A note to myself: Remove the old external editor code before merging.

**Comment by Beep6581** [comment]
I will help with the docs, :+1: for keeping them in mind.

**Comment by Thanatomanic** [comment]
👍  For merge. Would you do the honours @Lawrence37 ?

**Comment by Lawrence37** [comment]
Merged. Thanks @Thanatomanic!

**Comment by Beep6581** [comment]
@Lawrence37 I have added the documentation to RawPedia.

http://rawpedia.rawtherapee.com/Preferences#External_Editor
http://rawpedia.rawtherapee.com/Edit_Current_Image_in_External_Editor

In my testing (in Manjaro) I found that quoting should no longer be of concern to the user, as flags/options are correctly passed to the called program without any quotes. In fact, using single or double quotes as before no longer works. If this is not the case for Windows or macOS, please open an issue, describe the quote situation, and tag me.

**Comment by Floessie** [comment]
@Lawrence37 There is a new warning on Clang 15:

```
In file included from /home/user/src/rawtherapee/rtgui/batchqueuepanel.cc:22:
/home/user/src/rawtherapee/rtgui/rtwindow.h:36:1: warning: class 'ExternalEditor' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class ExternalEditor;
^
/home/user/src/rawtherapee/rtgui/options.h:55:8: note: previous use is here
struct ExternalEditor {
       ^
/home/user/src/rawtherapee/rtgui/rtwindow.h:36:1: note: did you mean struct here?
class ExternalEditor;
^~~~~
struct
1 warning generated.
```

Should be easy to fix. :wink:

**Comment by Lawrence37** [comment]
@Beep6581 The command format for Windows and macOS is the same as Linux. They all use Gio AppInfo. The command, if it's a path, uses the [OS encoding](https://docs.gtk.org/gio/type_func.AppInfo.create_from_commandline.html#parameters). That's the only difference. Handling of special characters is supposedly identical to the [Exec key in desktop files](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html), although quotes do not appear to be required.

**Pull request merged**
