### PR TITLE
Fix some Clang warnings reported by @Partha1b

### PR DESCRIPTION
**Pull request by Floessie**
This is a follow-up branch to #3501. @Partha1b provided us with some more warnings, two of which (the most imminent) are fixed here.

### CODE REVIEW

**Comment by Floessie** [comment]
@Partha1b Could you please check this branch with your setup?

**Comment by Partha1b** [comment]
@Floessie Got the following warnings:
```
[  7%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dcraw.cc.o
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:989:4: warning: add explicit braces to avoid dangling else [-Wdangling-else]
          else ip[col][c] = (ip[col-width][c] + ip[col+width][c] + 1) >> 1;
          ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:48: warning: taking the absolute value of unsigned type 'unsigned int' has no effect
      [-Wabsolute-value]
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                               ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:48: note: remove the call to 'abs' since unsigned values cannot be negative
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                               ^~~
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:75: warning: taking the absolute value of unsigned type 'unsigned int' has no effect
      [-Wabsolute-value]
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                          ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:75: note: remove the call to 'abs' since unsigned values cannot be negative
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                          ^~~
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:102: warning: taking the absolute value of unsigned type 'unsigned int' has no effect
      [-Wabsolute-value]
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                                                     ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:102: note: remove the call to 'abs' since unsigned values cannot be negative
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                                                     ^~~
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:129: warning: taking the absolute value of unsigned type 'unsigned int' has no effect
      [-Wabsolute-value]
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                                                                                ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:2014:129: note: remove the call to 'abs' since unsigned values cannot be negative
                    ushort dist = (ushort)sqrt(abs(corners[i][0] - row) * abs(corners[i][0] - row) + abs(corners[i][1] - col) * abs(corners[i][1] - col));
                                                                                                                                ^~~
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:8570:30: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
      is_raw += (i = get4()) && 1;
                             ^  ~
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:8570:30: note: use '&' for a bitwise operation
      is_raw += (i = get4()) && 1;
                             ^~
                             &
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:8570:30: note: remove constant to silence this warning
      is_raw += (i = get4()) && 1;
                            ~^~~~
6 warnings generated.
[  7%] Building CXX object rtengine/CMakeFiles/rtengine.dir/iccstore.cc.o
...
[ 14%] Building CXX object rtengine/CMakeFiles/rtengine.dir/procparams.cc.o
In file included from /Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/procparams.cc:20:
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:223:20: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/procparams.cc:7657:33: note: in instantiation of member function
      'rtengine::procparams::Threshold<int>::operator==' requested here
        && sharpening.threshold == other.sharpening.threshold
                                ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:223:20: note: use function 'std::abs' instead
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^~~~
                   std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:224:23: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[1] - rhs.value[1]) < 1e-10
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:224:23: note: use function 'std::abs' instead
                   && fabs(value[1] - rhs.value[1]) < 1e-10
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:225:23: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[2] - rhs.value[2]) < 1e-10
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:225:23: note: use function 'std::abs' instead
                   && fabs(value[2] - rhs.value[2]) < 1e-10
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:226:23: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[3] - rhs.value[3]) < 1e-10;
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:226:23: note: use function 'std::abs' instead
                   && fabs(value[3] - rhs.value[3]) < 1e-10;
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:228:20: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:228:20: note: use function 'std::abs' instead
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^~~~
                   std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:229:23: warning: using floating point absolute value function
      'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[1] - rhs.value[1]) < 1e-10;
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/../rtgui/../rtengine/procparams.h:229:23: note: use function 'std::abs' instead
                   && fabs(value[1] - rhs.value[1]) < 1e-10;
                      ^~~~
                      std::abs
6 warnings generated.
[ 14%] Building CXX object rtengine/CMakeFiles/rtengine.dir/rawimagesource.cc.o
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/rawimagesource.cc:879:16: warning: enumeration values 'ST_NONE' and 'ST_FOVEON' not handled in
      switch [-Wswitch]
        switch(ri->getSensorType()) {
               ^
1 warning generated.
[ 15%] Building CXX object rtengine/CMakeFiles/rtengine.dir/demosaic_algos.cc.o
...
[ 41%] Building CXX object rtgui/CMakeFiles/rth.dir/paramsedited.cc.o
In file included from /Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/paramsedited.cc:19:
In file included from /Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/paramsedited.h:24:
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:223:20: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/paramsedited.cc:608:94: note: in instantiation of member function
      'rtengine::procparams::Threshold<int>::operator==' requested here
        colorToning.shadowsColSat = colorToning.shadowsColSat && p.colorToning.shadowsColSat == other.colorToning.shadowsColSat;
                                                                                             ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:223:20: note: use function 'std::abs' instead
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^~~~
                   std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:224:23: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[1] - rhs.value[1]) < 1e-10
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:224:23: note: use function 'std::abs' instead
                   && fabs(value[1] - rhs.value[1]) < 1e-10
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:225:23: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[2] - rhs.value[2]) < 1e-10
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:225:23: note: use function 'std::abs' instead
                   && fabs(value[2] - rhs.value[2]) < 1e-10
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:226:23: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[3] - rhs.value[3]) < 1e-10;
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:226:23: note: use function 'std::abs' instead
                   && fabs(value[3] - rhs.value[3]) < 1e-10;
                      ^~~~
                      std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:228:20: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:228:20: note: use function 'std::abs' instead
            return fabs(value[0] - rhs.value[0]) < 1e-10
                   ^~~~
                   std::abs
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:229:23: warning: using floating point absolute value
      function 'fabs' when argument is of integer type [-Wabsolute-value]
                   && fabs(value[1] - rhs.value[1]) < 1e-10;
                      ^
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/../rtengine/../rtexif/../rtengine/procparams.h:229:23: note: use function 'std::abs' instead
                   && fabs(value[1] - rhs.value[1]) < 1e-10;
                      ^~~~
                      std::abs
6 warnings generated.
[ 42%] Building CXX object rtgui/CMakeFiles/rth.dir/cropwindow.cc.o
...
[ 50%] Building CXX object rtgui/CMakeFiles/rth.dir/filebrowserentry.cc.o
/Users/partha/projects/src/graphics/RT/RawTherapee/rtgui/filebrowserentry.cc:566:13: warning: 6 enumeration values not handled in switch: 'CropWinButtons',
      'CropToolBar', 'ColorPicker'... [-Wswitch]
    switch (a) {
            ^
1 warning generated.
[ 51%] Building CXX object rtgui/CMakeFiles/rth.dir/filebrowser.cc.o
```

**Comment by Floessie** [comment]
@Partha1b Thanks for testing. Those warnings are all uncritical except for

```
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:8570:30: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
      is_raw += (i = get4()) && 1;
```

which should be evalutated by @heckflosse.

@Beep6581 I could easily fix `procparams.h` here, but it's not that critical. What do you suggest?

Best
Flössie

**Comment by Beep6581** [comment]
@Floessie we have a few days till the release, make the best of it ;)

**Comment by Floessie** [comment]
@Beep6581 Then I'll introduce some last minute breaks tonight. :)

**Comment by heckflosse** [comment]
@Floessie 
```
/Users/partha/projects/src/graphics/RT/RawTherapee/rtengine/dcraw.cc:8570:30: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
      is_raw += (i = get4()) && 1;
```
is correct. I testd with a Fuji S5Pro file.
With my file get4() returns 499898 which probably is an indicator that there is a second frame in that file.
In this case 1 has to be added to is_raw (because is_raw is the number of raw frames) which is what the above code does. Typical dcraw code ;)

**Comment by Partha1b** [comment]
@Floessie Yes, I agree that most are uncritical. Hopefully in the future, we can take care of these warnings. :)

BTW, if there is any interest, I am happy to provide builds for both Mac and Windows. 

(As an aside, I'll comment on the main branch about launching of external programs if I may.)

**Comment by Floessie** [comment]
@heckflosse 
> In this case 1 has to be added to is_raw (because is_raw is the number of raw frames) which is what the above code does. Typical dcraw code ;)

:frowning: Oh well... Must be the C way of writing `+= bool(get4())`. Thanks for your explanation. I thought it had one `&` too much.

@Partha1b 
> Yes, I agree that most are uncritical. Hopefully in the future, we can take care of these warnings. :)

I'll fix `procparams.h` tonight, but leave `dcraw.cc` and the missing `enum` value as is.

> (As an aside, I'll comment on the main branch about launching of external programs if I may.)

Please do so (preferably in a new issue).

**Comment by Beep6581** [comment]
@Partha1b it would be most appreciated if you could provide OS X builds. Which versions can you cover? 10.10 upwards would be great.

**Comment by Floessie** [comment]
@heckflosse Yeah, let's break things! :wink:

**Comment by Partha1b** [comment]
@Floessie, happy to. :)

**Comment by Floessie** [comment]
@heckflosse @Partha1b Thanks for testing!

I tried to find an even better solution last night, but could not get the syntax right. Now I groked it:

```c++
diff --git a/rtengine/procparams.h b/rtengine/procparams.h
index 868a565..7c2d71a 100644
--- a/rtengine/procparams.h
+++ b/rtengine/procparams.h
@@ -218,21 +218,22 @@ public:
         return *this;
     }
 
-    bool operator ==(const Threshold<T> &rhs) const
+    template<typename U = T>
+    typename std::enable_if<std::is_floating_point<U>::value, bool>::type operator ==(const Threshold<U> &rhs) const
     {
         if (_isDouble) {
-            return std::abs(value[0] - rhs.value[0]) < 1e-10
-                   && std::abs(value[1] - rhs.value[1]) < 1e-10
-                   && std::abs(value[2] - rhs.value[2]) < 1e-10
-                   && std::abs(value[3] - rhs.value[3]) < 1e-10;
+            return std::fabs(value[0] - rhs.value[0]) < 1e-10
+                   && std::fabs(value[1] - rhs.value[1]) < 1e-10
+                   && std::fabs(value[2] - rhs.value[2]) < 1e-10
+                   && std::fabs(value[3] - rhs.value[3]) < 1e-10;
         } else {
-            return std::abs(value[0] - rhs.value[0]) < 1e-10
-                   && std::abs(value[1] - rhs.value[1]) < 1e-10;
+            return std::fabs(value[0] - rhs.value[0]) < 1e-10
+                   && std::fabs(value[1] - rhs.value[1]) < 1e-10;
         }
     }
 
-    template<typename U = T, typename = typename std::enable_if<std::is_integral<U>::value>::type>
-    bool operator ==(const Threshold<T> &rhs) const
+    template<typename U = T>
+    typename std::enable_if<std::is_integral<U>::value, bool>::type operator ==(const Threshold<U> &rhs) const
     {
         if (_isDouble) {
             return
```

I'll commit it tonight, but it's here so you can try it. I think, it's more concise than the first solution. Tested with GCC 4.9.2.

Best
Flössie

**Comment by Partha1b** [comment]
@Flossie Should I continue to pull fix-clang-warnings or has this been
merged with master?

Thanks,
Partha

**Comment by heckflosse** [comment]
@Floessie Your patch compiles and works fine. Thank you!

**Comment by Floessie** [comment]
@Partha1b No, it has not yet been merged. Also, the branch is missing the patch I posted, so either you wait until I've committed that change and then pull `fix-clang-warnings`, or you paste the patch above into a file and run `git patch [FILENAME]`.

@heckflosse Thanks for testing. I'll wait for @Partha1b's test with Clang before merging to master.

**Comment by Partha1b** [comment]
@Flossie, OK. I applied the patch and it compiles and works fine. Caveat: I
didn't test extensively. I opened one test image and worked on it.

**Comment by Floessie** [comment]
@Partha1b Yes, please do so.

BTW: GitHub has this wonderful graph when you click on the number besides the "Fork" label on top (currently is says ["53"](https://github.com/Beep6581/RawTherapee/network)).

**Pull request merged**
