### PR TITLE
increased precision of the channel mixer (allow 1 decimal figure)

### PR DESCRIPTION
**Pull request by agriggio**
I'd like to have a bit more precision in the channel mixer. This PR adds one significant figure. 
I hope there are no objections...

### CODE REVIEW

**Comment by heckflosse** [comment]
:+1: from me

**Comment by iliasg** [comment]
@agriggio Alberto, thanks for the precision increase
I would also like an increase in the range from -200..200 to a much bigger (say -500..500) because the current range is many times restrictive when we want to apply a 3X3 color correction matrix via the channel mixer ..

**Comment by agriggio** [comment]
@iliasg that's exactly my use case :-) though for me -200,200 has been enough so far. but I can definitely increase the range if needed :+1:

**Comment by iliasg** [comment]
@agriggio Alberto, I've met a lot of cases where -200,200 is not enough
To summarize my experience .. maybe less than 80% of cases are fine with -200,200 .. -300,300 will cover more than 95% .. some extreme cases (say underwater) may need more .. 

BTW I always wondered why this base 100 is used instead of 1.000 .. will changing it at the present situation arise compatibility issues ??.

**Comment by agriggio** [comment]
@iliasg understood! changing the base to 1000 is exactly what I did, except that the gui shows 100.0 instead :-) I think this is less confusing for people used to the old way. I'll extend the range to -500,500 when I get back tomorrow night

**Pull request merged**
