### PR TITLE
Update Chinese (Simplified)

### PR DESCRIPTION
**Pull request by hyyz17200**
Update translations, fix some wrong words.

### CODE REVIEW

**Comment by Beep6581** [comment]
@hyyz17200 I merged your changes and regenerated the language files - you will find all strings that still need translating at the end of the file. Note that some of the already-translated strings actually still have a lot of English text.

**Comment by hyyz17200** [comment]
Yeah I know. I will try to keeping translating unfinished items farther.
Should I keep the half already-translated part clean (without mixed with untranslated strings)?

**Comment by Beep6581** [comment]
@hyyz17200 remove the exclamation mark and do the translation in-place, i.e. at the end of the file. I will take care of the sorting.

**Comment by hyyz17200** [comment]
got it!

**Pull request merged**
