### PR TITLE
Speedups and cleanups for newlocallab

### PR DESCRIPTION
**Pull request by heckflosse**
I will make a series of commits to speedup and cleanup newlocallab.
First one was for mean_fab()
@Desmis Please review but don't merge yet.

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 
I will test, thank you...and of course, no commit.

jacques

**Comment by heckflosse** [comment]
@Desmis Of course you can commit. I meant, please don't press the merge button of this branch ;-)

**Comment by Desmis** [comment]
@heckflosse 
Ingo
OK
The only problem (actually) to solved, is the crash report in Pixl.us....
I think I have "finished" (provisory) the work on "newlocallab"

jacque

**Comment by heckflosse** [comment]
@Desmis Jacquse, I will commit a change tomorrow, A serious speedup and cleanup for the newlocallab exclude case. Still working on it.
Ingo

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I test the first "speedup" (mean_fab)
Compile without problem
Run whitout problem - no crash
Same result as whithout change

Good work
Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I need a bit more time for the next commit. I will push at the weekend. Currently I'm at a ~40% speedup for the exclude case.

**Comment by heckflosse** [comment]
@Desmis Jacques, please review if your time permits.

**Comment by Desmis** [comment]
@heckflosse 
I just compile, no problem

I lauch Rawtherapee.exe , no problem

I open in "Preview" one image, no problem
If I add a "Spot" or if I open an image with Spot inside, the system crash after some manipulatiions

For example when the spot is ouside the preview, or for example with "Colorspace_flowers.pef

[colorspace_flowers.pefjdc0.pp3.txt](https://github.com/Beep6581/RawTherapee/files/3000537/colorspace_flowers.pefjdc0.pp3.txt)

**Comment by heckflosse** [comment]
@Desmis Does it crash also when the spot is set to hidden?

**Comment by Desmis** [comment]
@heckflosse 
Same crash....with or whithout the 2 spots are hidden
When I click on thumbnail, just before opening in preview, immedialetly crash

I verfiy, with last version 11587e7 and other 25841f7
jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I am compiling "newlocallab-speedup" in a new clone....
I will try  again in 10 or 15 mn

**Comment by heckflosse** [comment]
@Desmis Does it also happen on https://github.com/Beep6581/RawTherapee/commit/25841f7dbcc9bc66c7e4610bf6a76088c395af4d ?

**Comment by heckflosse** [comment]
@Desmis ok

**Comment by Desmis** [comment]
@heckflosse 
Just finished to compile
Run rawtherapee.exe no problem
Open an image whitout Spot, no problem
if I try to open "colorspace_flower.pef", immedialtely crash
jacques

**Comment by Desmis** [comment]
@heckflosse 
Version: 5.5-850-g23c140048
Branch: newlocallab-speedup
Commit: 23c140048
Commit date: 2019-03-24
Compiler: gcc 8.2.1
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Desmis** [comment]
@heckflosse 
Run fine with 25841f7

**Comment by heckflosse** [comment]
@Desmis I can reproduce. Looking...

**Comment by heckflosse** [comment]
@Desmis Should be fixed.

**Comment by Desmis** [comment]
@heckflosse 
Ingo
I tested....
No crash, no crash :)
I look at your modifications -
a) good clean - old variables - that served during the development - are suppressed
b) good optimization
c) good improvment (OMP, etc.) - system is faster!

No visible differences.
Very very small differences with layers differences (but they are going in the right direction)

I continue to verify....in case of!
Very goog job

When do you merge this "Pull request" ?
Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing. I would like to merge now but keep the branch open for further improvements. Objections?

Ingo

**Comment by Desmis** [comment]
@heckflosse 
You can merge, and keep the branch open
Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Merged

**Pull request merged**
