### PR TITLE
Generalize perspective correction

### PR DESCRIPTION
**Pull request by Lawrence37**
As suggested by @Thanatomanic, this is a pull request containing the modifications I referenced in #5568. The changes made allow the perspective tool to use the image's field of view and makes the horizontal transformation dependent on the vertical transformation.

### CODE REVIEW

**Comment by heckflosse** [comment]
@Lawrence37 Thanks for your work :+1: 
I found an issue: Currently backwards compatibility is broken
I applied perspective correction in rt dev
grafik

and opened the same file in your branch
grafik

**Comment by Thanatomanic** [comment]
I think these changes will probably require a toggle between two modes in the perspective correction module.

**Comment by Lawrence37** [comment]
The units are different between the two versions. The new one uses degrees while the current one uses a unit equal to 0.45 degrees/unit. If I can find the exact field of view used by the current tool, I think it is possible to match the current output using the new implementation. I will work on making the new version backward compatible.

**Comment by heckflosse** [comment]
@Lawrence37 
> If I can find the exact field of view used by the current tool, I think it is possible to match the current output using the new implementation.

That would be perfect :+1:

**Comment by Thanatomanic** [comment]
@Lawrence37 Thanks for this contribution! I just tested your additions and I must say they look powerful. I'm sure this is a very good start to further development of the perspective tool. From a user pov I would always prefer to have some visual way to select straight lines, to set some parameters. We may still learn a little from darktable in that regard.

1. Setting the focal length and crop factor should ideally be taken from the image (if available). But I guess that's something for the future.
2. Vertical shift and Horizontal shift sliders should be limited to -50 and +50, otherwise you end up with a black frame.
3. How should I use the 'Recovery' tools?
4. The Post-correction 'Scale' tool doesn't seem functional.
5. Horizontal comes first, except for the 'Vertical' and 'Horizontal' sliders in the Correction block.

FWIW

**Comment by Lawrence37** [comment]
Thanks for your feedback, @Thanatomanic.

> Setting the focal length and crop factor should ideally be taken from the image (if available). But I guess that's something for the future.

I agree. I will see if I can implement this soon.

> Vertical shift and Horizontal shift sliders should be limited to -50 and +50, otherwise you end up with a black frame.

This is with Auto-fill enabled. When disabled, values up to +-100 can be used before the image completely goes off the canvas. Values beyond +-50 or +-100 may also be useful depending on what the other parameters are set to.
Regardless, I'm not confident in the current limits for all adjusters. I've made them quite large with the intent of trying them out before choosing more sensible limits. I'm considering using +-60 for the vertical/horizontal adjusters and +-45 for rotation. I don't know about focal length, crop factor, shift, and scale.

> How should I use the 'Recovery' tools?

They introduce perspective distortion. I think the most common use case will be for making buildings "lean" slightly for a more natural look. It's different from backing off the correction in two ways. One is that recovery is the inverse of correction. If you look at how the image changes with Auto-fill disabled, you can see that correction stretches the image while recovery compresses it. The second is that recovery is applied after all other adjustments (you should only use them after you are finished with correction and post-correction adjustments). This produces more natural/expected results when horizontal perspective/shift is applied.
If only horizontal or vertical correction is applied, using the corresponding recovery adjuster is not much different from backing off the correction.

> The Post-correction 'Scale' tool doesn't seem functional.

Auto-fill undoes the scale. Perhaps the scale adjuster should be greyed out when Auto-fill is enabled?

> Horizontal comes first, except for the 'Vertical' and 'Horizontal' sliders in the Correction block.

The behavior of horizontal correction depends on the value of Vertical. It should be more intuitive to adjust Vertical before Horizontal. Since recovery is the inverse of correction, the order is reversed in the recovery section. After playing with the recovery adjusters, however, it seems more intuitive for me to change Vertical then Horizontal. I will switch their order in the GUI if others feel the same way. Finally, the adjusters for the simple method is ordered the same way as the original tool.

**Comment by Thanatomanic** [comment]
@Lawrence37 I was processing a few architectural images recently and I found your modifications very useful. What would still be a really awesome addition is to have a more visual way of making corrections. For that I really like the way darktable handles the keystoning correction: there are four lines and corners that you can drag that determine what transformation is applied.
Would such a thing be possible with your tool?

**Comment by Lawrence37** [comment]
I'm not familiar with such a tool in darktable. What you describe is similar to either GIMP's perspective transform or PhotoFlow's perspective correction. The first cannot be implemented using the new tool. The second one can. I would like this feature myself, but with lines instead of a cage: https://github.com/Beep6581/RawTherapee/issues/4505#issuecomment-380807285

**Comment by Thanatomanic** [comment]
image

So you're saying something like this is impossible? Too bad :)

**Comment by Lawrence37** [comment]
It is possible.

**Comment by Lawrence37** [comment]
This pull request is ready for merging. I'm happy with current implementation and I don't plan on making further changes (aside from addressing bugs and code reviews). If I want to add additional features, I'll open a separate pull request.

**Comment by Thanatomanic** [comment]
@Lawrence37 Since your modifications change the language file too, I think it is still blocked by #5664 for now. @Beep6581 can you comment?

**Comment by Thanatomanic** [comment]
Since #5662 got merged and made changes to `rtdata/languages/default`, I suppose we can also safely merge this and ignore #5664 for now? @heckflosse, final opinion?

**Comment by Lawrence37** [comment]
I'm working on a UI which allows you to draw lines and use them for perspective correction. I wonder if I should include it in this PR or open a new one after this is merged.

**Comment by heckflosse** [comment]
I just tested again and found a bug. Using horiz. and vertic. shift together sometimes the preview is not updated while the navigator is updated. Count the number of windows on left and right in navigator and preview in this screenshot to verify ;-)
grafik

**Comment by heckflosse** [comment]
> @heckflosse, final opinion?

:+1: for merge. Bugs can be fixed also when it's in dev. The earlier we merge the more tests we get.

**Comment by heckflosse** [comment]
@Lawrence37 Feel free to add your name to contributors section of Authors.txt

**Comment by Lawrence37** [comment]
I have no idea why the preview doesn't update. It seems to only happen with auto-fill enabled.

**Comment by heckflosse** [comment]
@Lawrence37 I will try to reduce the case to the necessary steps to reproduce it. Maybe that helps.
At least, as now your branch is merged into dev, it might be easier to get feedback from other people ;-)

**Comment by Lawrence37** [comment]
I can reliably reproduce the bug like this:
1. Set horizontal shift to 20 (or some other sufficiently large value).
2. Set vertical shift to any value between +-(horizontal shift value) by typing the number. -> Preview doesn't update.
3. Set vertical shift to some value outside the range. -> Preview updates correctly.

**Comment by heckflosse** [comment]
Great, that you can reliably reproduce the bug. That's the first step to fix it :)

**Comment by heckflosse** [comment]
@Lawrence37 
Maybe worth to think about why the navigator preview (improccoordinator.cc) is updated while the main preview (dcrop.cc) is not updated...

**Pull request merged**
