### PR TITLE
Fixes for build with C++11 flags and sigc++ >= 2.5.2

### PR DESCRIPTION
**Pull request by mbajor**

### CODE REVIEW

**Comment by heckflosse** [comment]
Tested on Win7/64. Builds and works fine

**Comment by Beep6581** [comment]
I'll take this and merge once I test it on GCC-4.9 and 5.2. It would be good if it was also tested by those using older GCC versions - sguyander et al.

**Comment by mbajor** [comment]
@heckflosse, @Beep6581  Build tested on:
Arch (gcc 5.2.0 + C++11 flags, libsigc++ 2.6.1)
CentOS 7 (gcc 4.8.2, libsigc++ 2.3.1)
Debian 7 (gcc 4.7.2, libsigc++ 2.2.10
Debian 8 (gcc 4.9.2, libsigc++ 2.4.0)
Fedora 20 (gcc 4.8.2, libsigc++ 2.3.1)
Fedora 21 (gcc 4.9.2, libsigc++ 2.4.0)
Fedora 22 (gcc 5.1.1, libsigc++ 2.4.1)
ScientificLinux 7 (gcc 4.8.2, libsigc++ 2.3.1)
Univention 4.0 (gcc 4.7.2, libsigc++ 2.2.10)
SLE 12 (gcc 4.7.2, libsigc++ 2.2.10)
openSUSE 13.1 (gcc 4.8.1, libsigc++ 2.3.1)
openSUSE 13.2 (gcc 4.8.3, libsigc++ 2.4.0)
openSUSE Factory (gcc 5.1.1, libsigc++ 2.4.1)
openSUSE Factory ARM/ (gcc 5.1.1, libsigc++ 2.4.1)
openSUSE Factory PowerPC (gcc 4.8.5, libsigc++ 2.3.1)
openSUSE Leap 42.1 (gcc 4.8.5, libsigc++ 2.3.1)
openSUSE Tumbleweed (gcc 5.1.1, libsigc++ 2.4.1)

Run tested on openSUSE Tumbleweed

**Comment by sguyader** [comment]
I'm going to test for Win32, with gcc 4.6.1 and libsigc++ 2.3.2

**Comment by sguyader** [comment]
BTW, I'm new to git/github, what's the quickest way to test this pull
request?

**Comment by heckflosse** [comment]
@sguyader git clone https://github.com/mbajor/RawTherapee.git \rt_test123
then build as usual

**Comment by sguyader** [comment]
Thanks Ingo, that's what I was doing, but the cloning is painfully slow
right now (about 25 ki=B/s)...

**Comment by Beep6581** [comment]
```
git remote add mbajor https://github.com/mbajor/RawTherapee
git fetch mbajor master
git merge mbajor/master
```

**Comment by sguyader** [comment]
The test was succesful (Win 32 bit build, gcc 4.6.1 and libsigc++ 2.3.2)

**Comment by heckflosse** [comment]
Sebastien, thanks for testing :-)
I'll merge the PR now and then push the modified dcraw.patch file

**Comment by Beep6581** [comment]
Fine here with GCC-4.9.3. Can't test 5.* for the time being.

**Pull request merged**
