### PR TITLE
Sony pixel shift

### PR DESCRIPTION
**Pull request by agriggio**
Any reason to not merge this?

### CODE REVIEW

**Comment by Beep6581** [comment]
@agriggio 
This sneaked in: `rtengine/procparams.cc.save-failed`

**Comment by agriggio** [comment]
thanks, deleted

**Comment by Beep6581** [comment]
Compiles and runs fine using GCC-5.4.0.

**Comment by heckflosse** [comment]
@agriggio Shall we keep `pixelshift: Optionally use one green instead of averaging two greens` or not?

**Pull request merged**
