### PR TITLE
Exiv2 updates

### PR DESCRIPTION
**Pull request by Lawrence37**

### CODE REVIEW

**Comment by Lawrence37** [comment]
I addressed some of the comments I left in #5889 and cherry-picked metadata related commits from ART (excluding ExifTool).

**Comment by Thanatomanic** [comment]
Excellent work @Lawrence37! This is a pretty heavy beast that requires careful testing. But I assume you would only want to do that after this PR is merged into `metadata-exiv2`, right?

**Comment by Lawrence37** [comment]
Yes. The main branch has an incomplete implementation. It's just copying all the data to the output image. The commits here finish the metadata handling and add some additional features. I opened this PR to allow comments on which commits we want in the initial Exiv2 integration.

**Comment by Lawrence37** [comment]
Any opinions on whether we should merge just the bare minimum for metadata handling or include some or all additional commits?

**Comment by Lawrence37** [comment]
I intend to merge this to the main Exiv2 branch soon.

**Pull request merged**
