### PR TITLE
Cherry-picked fixes for 5.10

### PR DESCRIPTION
**Pull request by Lawrence37**
I propose to have these fixes in 5.10:
- Commit 97e181bd58061f0d9d8b2746bbfc9bd144823850 (automatic distortion correction crash)
- Pull request #6842 (debug build crash)
- Pull request #6850 (`ProcParams` undefined behavior crash when compiled with Clang 15)

### CODE REVIEW

**Review by Floessie — APPROVED** [review]
Quickly tested a release build with Clang 16. It doesn't crash. :+1:

**Comment by Lawrence37** [comment]
I added recent commits from `dev`.
- Rephrase AWB label and tooltip
- Fix hidden color toning layers
- GitHub Actions workflows cleanup
- Fix noise reduction crash
- Fix temperature correlation AWB in batch editor
- Remove logs when verbose mode is off
- Fix white balance reset button
- Hide unusable adjusters in Local Adjustments Exposure

**Review by Beep6581 — APPROVED** [review]
Great, approved! Please merge.

**Comment by Lawrence37** [comment]
Thanks @Beep6581, merged!

**Pull request merged**
