### PR TITLE
diagonalcurves: replace cubic splines with (centripetal) Catmull-Rom splines

### PR DESCRIPTION
**Pull request by agriggio**
See https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline

This is my proposed fix for #4343.
It makes the "custom" curves much more controllable, IMHO at least.

### CODE REVIEW

**Comment by Beep6581** [comment]
Hi @agriggio !
I remembered that you wanted me to test a patch (the patch was to avoid having the curve leave the top edge once it hits it) and actually wanted to do that later today as it's weekend and I have a few photos to process. Is your latest commit the same as the patch? Anything specific to look out for when testing the branch?

**Comment by agriggio** [comment]
forget about the patch, just test the latest commit

**Comment by agriggio** [comment]
sorry for my brevity before. the latest commit should improve the situation with auto matching, and in general the accuracy of the new curve. everything should work more or less as in dev (minor differences are unavoidable) but the custom curves should be much easier to edit

**Comment by Beep6581** [comment]
@agriggio no problem. I tested it and found two things worth noting:
1. Regarding the auto-matched tone curve, the shadows in this branch are generally lighter than in `dev` and in the embedded JPEG. I think these screenshots were from `blackcat.dng`
screenshot_20180810_224430
screenshot_20180810_224437
2. Regarding the behavior of the curve itself, the dip in the curve once it touches the top and then pulls down away again is still there and causes artifacts (solarize effect):
screenshot_20180810_224753
screenshot_20180810_224759
[soderasen_1.hdr.dng.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2279428/soderasen_1.hdr.dng.pp3.txt)

**Comment by agriggio** [comment]
thanks a lot for testing! still some work to do then :+1:

**Comment by agriggio** [comment]
@Beep6581 I pushed further tweaks, let me know if they improve the situation.

**Comment by Beep6581** [comment]
@agriggio the tweaks are good. It is now easy to get the white end to stick to the upper edge.

There is one issue. When the white point is in the corner and the second right-most point makes the curve touch the top, things are fine:
screenshot_20180812_144546
However, when you move the white point away from the corner, to the left, a dip appears
screenshot_20180812_144557
This can be easily prevented by adding a new corner node:
screenshot_20180812_144605

It's not a significant problem since the fix is so easy, but thought it was worth pointing out.

**Comment by Beep6581** [comment]
Here is a better example, since in the previous example you would wonder why have three nodes when the middle one does nothing. Here the middle one does something:
screenshot_20180812_144854
screenshot_20180812_144903
screenshot_20180812_144908

**Comment by Beep6581** [comment]
What are your thoughts on adding this new mode while still keeping the previous one?

**Comment by agriggio** [comment]
thanks for the feedback! I'll see what I can do. I'm :-1: on adding this as an extra mode, I think RT is already over complicated and I'm only interested in making it simpler, sorry :-)
I'm fine with rejecting this pr though if it's not convincing

**Comment by gaaned92** [comment]
- with last 5.4-634-g0d7d1cfc8, with amsterdam.pef and [amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2281121/amsterdam.pef.pp3.txt), using Adobe DCP, I get 
screen-2018-08-12_18-44-24

The two last points are not connected. It does'nt happen with RT DCP. 


- I much prefer this new method as it avoids pathological curves and is easier to use.

- effectively, due to different interpolation, result of auto matched feature can be slightly different. But I really don't mind as, when I use it, I consider this only as a starting point. Thus  :-1: for extra mode and  :+1: to commit

**Comment by agriggio** [comment]
@gaaned92 this is unexpected and most definitely a bug. I'll investigate

**Comment by agriggio** [comment]
@gaaned92 I don't have the adobe profile at the moment: can you maybe upload it to filebin?

**Comment by agriggio** [comment]
@Beep6581 the weird behaviour you reported in your last comment was due to a typo -- it should be fixed now

**Comment by gaaned92** [comment]
- the adobe Pentax K10D DCP is here; https://filebin.net/rtr42latbwus5edj

- I don't know if it is useful, but I notice that the auto match in this branch generates a lot more points than in the dev branch.

**Comment by agriggio** [comment]
@gaaned92 thanks! It should be ok now. Yes, the generated curve has more points than current dev, but that's expected with these new splines. It should still be easier to modify by hand though

**Comment by gaaned92** [comment]
@agriggio it's ok now. Thanks.

**Comment by Beep6581** [comment]
@agriggio the curve behaves very well now!

I want to be certain that when I move the white-point left, all areas to the right of it really are clipped, and that there is no reversal in brightness (solarisation) due to the catmull math.
screenshot_20180816_230259
I think that is the case (good), but...

A similar curve shape using different curve types should lead to a similar output, however something odd happens here (`overexposed_sky.pef`), NURBS:
screenshot_20180816_224955
Catmull (notice Tone Curve 1 has 4 points)
screenshot_20180816_225001
Why does a NURBS curve show clipped white while a similar Catmull curve does not, and why does adding an extra point which seems to make no difference in the curve lead to a funky difference in the preview? (notice Tone Curve 1 now has 5 points)
screenshot_20180816_225403
[overexposed_sky 4701.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2295209/overexposed_sky.4701.pp3.txt)

The thing is, I can only reproduce that when the second curve is set to weighted mode. In all other modes, the two curve types lead to an almost identical result without solarisation, so I'm thinking this odd behavior is unrelated to your code and could be a bug in the weighting code. Besides, in this example the NURBS result seems incorrect - yes the first curve does clip the highlights, but the second curve drags those highlights down, so the highlights should be gray (as they are with the Catmull curve), but instead with NURBS they're clipped, as if the second curve's white point had no effect.

What do you make of this?

**Comment by agriggio** [comment]
@Beep6581 thanks for testing! I have to think about what this means in practice... I assume that the behaviour in `dev` is different, right?

**Comment by Beep6581** [comment]
@agriggio in `dev` using the custom curve with 4 points leads to clipped highlights, with 5 points still clipped highlights, but if I move the 5th point from 100.000 to 99.999 then I get gray highlights. What happens inside RT is a black box to me, but the fact that 100.000 leads to white while 99.999 leads to gray makes me worry that the allegedly-100.000 node in catmull is not really 100.000, since it too leads to gray at allegedly-100.000.

screenshot_20180817_110456
screenshot_20180817_110506

I worry about this because I often work with HDR images, and sometimes I output them to 32-bit TIFF files for stitching and subsequent post-processing in LHDR and RT. To HDR software the difference between 1 and 0.999999 can be significant. It would be bad if RT introduced solarisation in the highlights in the first step if I want to rely on the highlights being correct when tone-mapping in the second step. I want to be certain that when the curve touches the ceiling, the values really are maxed-out.

But I also want to re-state that there's a good chance that everything's fine here and it's the weighting code which leads to those odd results, though that doesn't account for why adding a 5th node to Catmull changes the result.

**Comment by agriggio** [comment]
ok, I'll see what is going on

**Comment by agriggio** [comment]
@Beep6581, I just took a look. There were two different issues here:

1. There was indeed a problem in the Catmull-Rom evaluation, due to the inherent imprecision of floating-point ops. Specifically, in your case even if the control point was set at (say) `[0.7, 1]`, the curve at that point was evaluated to something like `[0.7, 0.99999]`

2. it could still happen that the curve was a bit "wobbly" between two control points `[x1, 1]` and `[x2, 1]`, leading to some intermediate values to be strictly smaller than 1.

I have now fixed 1, and added a special case for 2 to make sure that segments between two control points at 0 or 1 evaluate to straight lines. Now everything seems to work as you expected, but can you please double check? Thanks!

**Comment by Beep6581** [comment]
Thank you for looking into this @agriggio , I will test promptly.

**Comment by Beep6581** [comment]
@agriggio it works fine now as far as I can tell. Just one thing... :]
screenshot_20180817_165500
The line appears to be reversing and going down as it flows into the node. Is that just a graphical glitch?

**Comment by Beep6581** [comment]
@agriggio the behavior above is a symptom of this:
imgur-2018_08_17-17 38 33
It just looks odd when it happens at the ceiling.

I played more with this and it seems to have no visible effect on the image, I see no sudden step nor any solarisation. For certainty's sake it could be worth testing whether feeding that curve with values 0-1000 returns only increasing values, or whether any value is larger than any previous value.

[4701.rtc.txt](https://github.com/Beep6581/RawTherapee/files/2297850/4701.rtc.txt)

**Comment by agriggio** [comment]
@Beep6581 as briefly explained on IRC, this is due to the placement of the (hidden) last control point needed by catmull-rom. I can try tweaking the behaviour, but first you'd have to tell me why it is wrong... :-)

**Comment by Beep6581** [comment]
@agriggio I don't know whether it's wrong, but it was worth pointing out. The curve screenshot from two posts ago was of a very typical shape which users are sure to reproduce, and the curve line makes a small dip right before the node so I wanted to make sure it has no unexpected side-effects. I noticed none in the image.

Being the masters of the universe, some things we can improve, while others we just learn to live with :]

I'm happy with the way the curve now behaves, +1 for merge.

**Comment by agriggio** [comment]
@Beep6581 I just tweaked the placement of the hidden points, here is a quick screenshot of the difference:

* old one:
old

* new one:
new

See if you like this better (notice it might slightly change the shape of the overall curves, since the two hidden points are put in a different place, and I also tweaked the weight of the "centripetal" factor alpha).

One thing (at least) before merging is deciding how to handle old pp3's that were using the cubic spline curves. If we just import them "as is", the curves will most definitely be different than what the user set. My proposal is to insert extra control points upon importing old pp3's, to make sure that the new curve is close to the old one. The code for this is already there (currently in `histmatching.cc`) so it should not be too hard to implement. The downside is that users will see more control points than what they entered, but at least they will get the curves they wanted... what do you think?

**Comment by Beep6581** [comment]
> deciding how to handle old pp3's that were using the cubic spline curves. If we just import them "as is", the curves will most definitely be different than what the user set

I tested for that a few commits ago and found that the results were not identical but similar-enough, even when I used quite extreme curve adjustments. But I wouldn't object to more CPs to get an exact match. I'm neutral on the subject.

**Comment by Beep6581** [comment]
I compared `5.4-638-g`ef57c5da0 to `5.4-640-g`e3ea0926c 
They're both fine. The former makes rounder curve segments near the ends, the latter makes flatter segments. I can't say which is better, feels more like just something one needs to adapt to one way or the other.

ef57c5da0
screenshot_20180818_140744

e3ea0926c
screenshot_20180818_140749

Odd things happen in both cases when two nodes are dragged onto each other, but odd things happen in `dev` too. https://filebin.net/tkwbcibsw40a3lv5/vid1-2018-08-18_14.12.40_x264_crf23.mp4?t=c5nhlk0u

**Comment by Beep6581** [comment]
I don't like the cursor when editing a node, it obscures too much of what's happening underneath. Will change it in `dev` if no objections.

**Comment by agriggio** [comment]
> I tested for that a few commits ago and found that the results were not identical but similar-enough, even when I used quite extreme curve adjustments

Even better then :-) I didn't test, so I trust you on this. Unless there are further objections, for me we can merge then.

**Comment by agriggio** [comment]
@Beep6581 if you want to play with this, you can try tweaking the `alpha` value  [here](https://github.com/Beep6581/RawTherapee/blob/e3ea0926c22792edda2e4dffee3d59c9a7fb7c30/rtengine/diagonalcurves.cc#L292), keeping in mind it must be between `0` and `1`. (FYI, the previous version had `alpha = 0.25`, the current one `0.5`).

**Comment by Beep6581** [comment]
No I'm fine :)

**Comment by agriggio** [comment]
Here's a patch that makes the curves rounder (closer to the old version):

```diff
diff --git a/rtengine/diagonalcurves.cc b/rtengine/diagonalcurves.cc
--- a/rtengine/diagonalcurves.cc
+++ b/rtengine/diagonalcurves.cc
@@ -289,7 +289,7 @@
                              double xi, double yi,
                              double xj, double yj)
 {
-    static constexpr double alpha = 0.5;
+    static constexpr double alpha = 0.375;
     return pow(sqrt(pow2(xj-xi) + pow2(yj-yi)), alpha) + ti;
 }
 
@@ -374,10 +374,18 @@
 inline void catmull_rom_reflect(double px, double py, double cx, double cy,
                                 double &rx, double &ry)
 {
+#if 0
     double dx = px - cx;
     double dy = py - cy;
     rx = cx - dx;
     ry = cy - dy;
+#else
+    static constexpr double epsilon = 1e-5;
+    double dx = px - cx;
+    double dy = py - cy;
+    rx = cx - dx * 0.01;
+    ry = dx > epsilon ? (dy / dx) * (rx - cx) + cy : cy;
+#endif    
 }
 
 
```

**Comment by Beep6581** [comment]
@agriggio the patch is a great compromise between the two.
+1 for merge :)

**Pull request merged**
