### PR TITLE
Merge dev into newlocallab

### PR DESCRIPTION
**Pull request by Pandagrapher**
@Desmis 
Compared to @Hombre57 modifications, I just re-added `Arcellipse` object. It compiles and seems to work fine

In a future commit, I will replace `Arcellipse` object by an `Ellipse` one. This way code will be easiest: one graphical object to manage instead of four for `controlspotpanel`

Pierre

### CODE REVIEW

**Comment by Desmis** [comment]
@Pandagrapher 
I just merge your pull request, all seems to work fine

Thank you
jacques

**Comment by Desmis** [comment]
@Pandagrapher
je t'adresse le log que j'ai obtenu avec difficultés
[log.txt](https://github.com/Beep6581/RawTherapee/files/2999282/log.txt)

J'ai réellement fait beaucoup, beaucoup de simulations, en scurtant "L"  avec "printf"... en essayant de borner L par LIM ou CLIP, mais il semble que ce soit peut être NAN ou hors je ne sais quoi ?
ou aussi
  Id   Target Id         Frame 
  1    Thread 13272.0x333c 0x000007fd131c2bea in ?? ()
  2    Thread 13272.0x2588 0x000007fd131c466b in ?? ()
  4    Thread 13272.0xa64 0x000007fd131c315b in ?? ()
  5    Thread 13272.0x2d14 0x000007fd131c315b in ?? ()
  6    Thread 13272.0x28e4 0x000007fd131c315b in ?? ()
  7    Thread 13272.0x2e48 0x000007fd131c315b in ?? ()
  8    Thread 13272.0x2e40 0x000007fd131c315b in ?? ()
  9    Thread 13272.0x2c1c 0x000007fd131c315b in ?? ()
  10   Thread 13272.0x468 0x000007fd131c315b in ?? ()
  11   Thread 13272.0x2838 0x000007fd131c315b in ?? ()
  12   Thread 13272.0x2e88 0x000007fd1274152a in ?? ()
  183  Thread 13272.0x2864 0x000007fd131c2bea in ?? ()
  184  Thread 13272.0x29ec 0x000007fd131c2bea in ?? ()
* 185  Thread 13272.0x165c LUT<float>::operator[]<float, float, void> (this=0x215219d0, index=-nan(0x400000)) at G:/code/repo-rtlocal2/rtengine/LUT.h:456
  186  Thread 13272.0x178c 0x000007fd131c2bea in ?? ()
  187  Thread 13272.0x1d60 rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1807
  188  Thread 13272.0x2e00 0x000000000090d612 in rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1821
  189  Thread 13272.0x3148 0x000007fd131c4740 in ?? ()
  191  Thread 13272.0x1a8c 0x0000000000d5f3eb in LUT<float>::operator[]<float, float, void> (this=0x21521970, index=9449.14551) at G:/code/repo-rtlocal2/rtengine/LUT.h:456

Thread 191 (Thread 13272.0x1a8c):
#0  0x0000000000d5f3eb in LUT<float>::operator[]<float, float, void> (this=0x21521970, index=9449.14551) at G:/code/repo-rtlocal2/rtengine/LUT.h:456
        idx = 9449
        diff = 0.145507812
        p1 = inf
        p2 = -nan(0x400000)
#1  0x000000000090d67e in rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1820
        L = 4724.57275
        tonefactor = -nan(0x400000)
        j = 248
        tj = 24
        i = 58
        ti = 58
        ii = 0
        jj = 224
        vasy = false
        buffer = 0x25222300 ""
        atemp = 0x2522e800
        jstart = 224
        tH = 112
        btemp = 0x2523ae00
        istart = 0
        data = 0x25222300 ""
        Ltemp = 0x25222300
        tW = 296
        maxran = 0
        exp_scale = 0
        comp = 3.42546245e-019
        shoulder = 0
        hlrange = 1.63338763e-016
#2  0x000000006360cf78 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 189 (Thread 13272.0x3148):
#0  0x000007fd131c4740 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 188 (Thread 13272.0x2e00):
#0  0x000000000090d612 in rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1821
        L = 109.155937
        tonefactor = -nan(0x400000)
        j = 184
        tj = 72
        i = 86
        ti = 86
        ii = 0
        jj = 112
        vasy = false
        buffer = 0x24bea660 "\rð­º\rð­º\rð­º\rð­º\rð­º\rð­º\rð­º\rð­º"
        atemp = 0x24bf6b80
        jstart = 112
        tH = 112
        btemp = 0x24c03180
        istart = 0
        data = 0x24bea680 ""
        Ltemp = 0x24bea680
        tW = 224
        maxran = 0
        exp_scale = 0
        comp = 3.42546245e-019
        shoulder = 0
        hlrange = 1.6329387e-016
#1  0x000000006360cf78 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 187 (Thread 13272.0x1d60):
#0  rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1807
        j = 9
        tj = 9
        i = 198
        ti = 86
        ii = 112
        jj = 0
        vasy = false
        buffer = 0x25247470 "\rð­º\rð­º\rð­º\rð­º"
        atemp = 0x25253980
        jstart = 0
        tH = 224
        btemp = 0x2525ff80
        istart = 112
        data = 0x25247480 ""
        Ltemp = 0x25247480
        tW = 112
        maxran = 0
        exp_scale = 0
        comp = 3.42546245e-019
        shoulder = 0
        hlrange = 1.632854e-016
#1  0x000000006360cf78 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 186 (Thread 13272.0x178c):
#0  0x000007fd131c2bea in ?? ()
No symbol table info available.
#1  0x000007fd131d776a in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 185 (Thread 13272.0x165c):
#0  LUT<float>::operator[]<float, float, void> (this=0x215219d0, index=-nan(0x400000)) at G:/code/repo-rtlocal2/rtengine/LUT.h:456
        idx = -2147483648
        diff = -nan(0x400000)
        p1 = inf
        p2 = -nan(0x400000)
#1  0x000000000090d530 in rtengine::ImProcFunctions::exlabLocal(rtengine::local_params const&, int, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&) [clone ._omp_fn.3] () at G:/code/repo-rtlocal2/rtengine/iplocallab.cc:1831
        Y = -nan(0x400000)
        L = -nan(0x400000)
        tonefactor = 5.55084407e-016
        j = 0
        tj = 0
        i = 0
        ti = 0
        ii = 0
        jj = 0
        vasy = false
        buffer = 0x253465b0 "\rð­º\rð­º\rð­º\rð­º"
        atemp = 0x25352ac0
        jstart = 0
        tH = 112
        btemp = 0x2535f0c0
        istart = 0
        data = 0x253465c0 ""
        Ltemp = 0x253465c0
        tW = 112
        maxran = 0
        exp_scale = 0
        comp = 3.42546245e-019
        shoulder = 0
        hlrange = 1.63212343e-016
#2  0x000000006360cf78 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 184 (Thread 13272.0x29ec):
#0  0x000007fd131c2bea in ?? ()
No symbol table info available.
#1  0x000007fd131d776a in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 183 (Thread 13272.0x2864):
#0  0x000007fd131c2bea in ?? ()
No symbol table info available.
#1  0x000007fd131d776a in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 12 (Thread 13272.0x2e88):
#0  0x000007fd1274152a in ?? ()
No symbol table info available.
#1  0x000007fd127536f0 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 11 (Thread 13272.0x2838):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 10 (Thread 13272.0x468):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 13272.0x2c1c):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 8 (Thread 13272.0x2e40):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 13272.0x2e48):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 6 (Thread 13272.0x28e4):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 13272.0x2d14):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 4 (Thread 13272.0xa64):
#0  0x000007fd131c315b in ?? ()
No symbol table info available.
#1  0x000007fd1019129e in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 13272.0x2588):
#0  0x000007fd131c466b in ?? ()
No symbol table info available.
#1  0x000007fd131c76d3 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 13272.0x333c):
#0  0x000007fd131c2bea in ?? ()
No symbol table info available.
#1  0x000007fd131d776a in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by Pandagrapher** [comment]
@Desmis 
J'ai remarqué un truc intéressant. Des changements de ranges ont été fait pour certains paramètres (ex : `expcomp` qui est passé de [-200 ; 400] à [-2.0 ; 4.0]). En chargeant le fichier .pp3, les paramètres existants sont chargés tels quels sans tenir compte du nouveau range et envoyés à `improccordinator` pour traitement de l'image, ce qui explique peut-être les NaN que tu finis par avoir dans le backtrace. Il suffit ensuite d'un changement de visibilité d'un spot, d'un de ses paramètres pour procéder à la mise à jour suivant les nouveaux ranges. Est-ce que cela pourrait expliquer tes crashs ?

Exemple sur le fichier spidermonkey :
- Première génération de l'image après chargement :
```
Expcomp 0: 246.000000
Expcomp 1: 71.000000
Expcomp 2: 71.000000
```
- Après changement de visibilité du spot n°3 :
```
Expcomp 0: 246.000000
Expcomp 1: 71.000000
Expcomp 2: 4.000000
```

Si c'est bien cela, il faudrait dorénavant indiquer aux testeurs de la branche de réinitialiser leurs traitements faits avec des anciennes versions à chaque fois que l'on change des ranges de paramètres déjà existants. Tant que le travail n'est pas mergé dans dev, ça me parait inutilement compliqué de prévoir une logique pour maintenir ces "vieux" fichiers pp3...

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 

OK tu as fait la bonne découverte....depuis 2 mois, j'ai changé les valeurs du range qui étaient en en "integer" dans l'intervalle -200 + 400, par "double" dans l'intervalle  -2.0 +4.0
Quand le machin trouve 400....cela fait une valeur réelle de 400.0 soit 100 fois plus.
J'ai essayé de remplacer dans le pp3 en cause et plus de crash.... à vérifier.
Mais tu as raison on ne va pas bricoler pour une situation temporaire
Donc je vais aviser sur le forum....

J'en ai profité pour revoir la fonction "exlabalocal" - j'ai supprimé les TILES qui ne servaient à rien et corrigé une erreur.
Je vérifie et commit ce change....

merci
jacques

**Comment by heckflosse** [comment]
@Desmis @Pandagrapher 

Sorry for hijacking this thread. I just detected a race condition in newlocallab
https://github.com/Beep6581/RawTherapee/blob/newlocallab/rtengine/iplocallab.cc#L6930

The variable rch has to be declared inside the parrellel region (or inside the loop).

Can I push a fix directly to newlocallab?

**Comment by Desmis** [comment]
@heckflosse 
Ingo

No problem you can :)

Thank you
jacques

**Comment by heckflosse** [comment]
@Desmis Done

**Pull request merged**
