### PR TITLE
Wavelet levals :Change sensitivity sliders wavelet levels denoise

### PR DESCRIPTION
**Pull request by Desmis**
Since many years, sliders wavelet level denoise are too strong.

Thanks to  @XavAL

This patch change this behavior 

jacques

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo
How are you ?
I see you are going to review this pull request

Can you tell me when you think I can merge ?

Thank you

Jacques

**Comment by heckflosse** [comment]
@Desmis 
Hi Jacques, I'm fine. Hope you're fine as well.

I will start review in the evening, maybe already in the afternoon

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo
Here all is fine....except limited outings :)

Ok fot the review.

Thank you

Jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Can I push a change or where should i wait for you to finish :)
No problem for waiting 

This change (after work with @xaval) is about:
* in ipwavelet.cc  ==> cp.numlevS , change "direction" (then change behavior and label and tooltip) for contrast shadows levels

* in ipwavelet.cc  ==> egde = 1 instead of edge = 4 for call to Ftblockdn.cc big stupidity on my part

* in wavelet.cc same change for slider threshold2 (shadows level)

* in language defaults : change labels and tooltip

Thank you

Amicalement

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo
To complete I replaced the 2  sliders "threshold" and "threshold2" by a flat curve
Low impact on ipwavelet code

Also, in "wavelet denoise", I change the limit between 1 shrink and 2 shrink

Here the patch (in txt)

jacques




[wav7-05.txt](https://github.com/Beep6581/RawTherapee/files/4593816/wav7-05.txt)
New patch

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I made some minor changes to the patch,  it concerns the curve waOpacityCurveSH
* in procparams.cc line 2204 replace 0.6 by 0.5
* in ipwavelet.cc line 3790 add && level <= 6
* in ipwavelet.cc line 3804 add && level >= 3
* in languages/default change tooltip for TP_WAVELET_FINCOAR_TOOLTIP

[wav8-05.txt](https://github.com/Beep6581/RawTherapee/files/4597498/wav8-05.txt)

jacques

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo

After exchanges with @XaVaL I change the order of 2 sliders in wavelet.cc (strength and  Damper)

I also made the same change as in dev (leeds to crash in some cases) for size of madL madL[8][3] ==>  madL[10][3]  line 910 in ipwavelet.cc

[wav10-05.txt](https://github.com/Beep6581/RawTherapee/files/4605303/wav10-05.txt)

**Comment by heckflosse** [comment]
@Desmis 

Hello Jacques,

sorry for the delay :( I will have another look at your changes tomorrow. Promised!

Ingo

**Comment by Desmis** [comment]
Ok, thank you very much

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, cppcheck found some of this:

```
(cp.chromfi > 0.f || cp.chromfi > 0.f)
```
Should that be 
```
(cp.chromfi > 0.f || cp.chromco > 0.f)
```
instead? If so, I can change it

**Comment by heckflosse** [comment]
There are two unused functions in ipwavelet.cc:

```
ImProcFunctions::Compresslevels2()
ImProcFunctions::softproc2()
```
Ok to remove them?

**Comment by Desmis** [comment]
@heckflosse 
Ingo

Ok, for the 2 propositions :)

But where have you found
(cp.chromfi > 0.f || cp.chromfi > 0.f) ?

With my code, and patch I have not :)

jacques

**Comment by heckflosse** [comment]
> But where have you found
(cp.chromfi > 0.f || cp.chromfi > 0.f) ?

I merged dev into wavtm. Maybe that caused it?

**Comment by Desmis** [comment]
Ok, perhaps :)
Thank you

**Comment by heckflosse** [comment]
@Desmis I just checked dev.
```
(cp.chromfi > 0.f || cp.chromfi > 0.f) 
```
is from dev.

Please do no commit to wavtm today. I will commit some changes in the evening

**Comment by Desmis** [comment]
OK, no problem, I am waiting for your changes ?
I suppose, you will push a change to wavtm  ?

Jacques

**Comment by heckflosse** [comment]
Yes, to wavtm

**Comment by heckflosse** [comment]
@Desmis Jacques. I just pushed. For now I think it's fine to merge this branch. Though there are a lot of code cleanups possible to ipwavelet.cc we can do after the merge.

@Floessie @Thanatomanic @Beep6581

**Comment by Desmis** [comment]
@heckflosse 

Ingo
All the changes introduced by the patch wav10-05.txt have been forgotten
* changes to ipwavelet
* changes to wavelet
* changes to curves
* changes to dcrop, improccoordinator, simpleprocess
* changes to languages

Probably du to the merge with dev.

I rebuild today
But no problem :)

jacques

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I just finished to rebuild "wavtm", manually....
Before I push this commit, could you verify

Thank you
And no problem for this mistake, its allows me to control my own work :)

jacques

**Comment by heckflosse** [comment]
@Desmis 
> All the changes introduced by the patch wav10-05.txt have been forgotten

Strange, sorry for the trouble. I did :

```
git checkout dev
git pull
git checkout wavtm
git pull
git merge dev
```
and the merge did not complain...

**Comment by Desmis** [comment]
@heckflosse 
Ingo

No problem at all. As I say above, with that, I could review my owmn code  :)

**Comment by Desmis** [comment]
@heckflosse 
I just clean code
If no problem, I will commit tomorrow
:)

jacques

**Pull request merged**
