### PR TITLE
Correctly apply LCP "distortion" correction for Fisheye lenses

### PR DESCRIPTION
**Pull request by agriggio**
Note: as discussed e.g. at http://lensfun.sourceforge.net/manual/corrections.html, this is really a combination of distortion correction and change of projection (from fisheye to rectilinear), but "distortion correction" is how the Adobe camera model calls it, and this is how it appears in the RT gui

### CODE REVIEW

**Comment by agriggio** [comment]
See also #3788

**Comment by Beep6581** [comment]
+1 for merge.

**Comment by agriggio** [comment]
I've fixed a corner case when you would get a wrong view for detail windows placed close to the corners. Now it should be ready for merging. If there are no objections, I'll do it either later tonight or tomorrow

**Comment by morosakubek** [comment]
Hi, @agriggio,  there is still a problem with Canon's compact cameras. For example, with the Canon PowerShot G1 X model (RAW+lcp: https://drive.google.com/drive/folders/0BzMK6gsaNS8wdmh2eG1fcXZtdmM?usp=sharing)

**Comment by agriggio** [comment]
thanks for reporting, I'll have a look ASAP

**Comment by agriggio** [comment]
Hi @morosakubek, after some investigation, the distortion correction code is fine. The problem with your camera is that there is no entry for it in `camconst.json`, so RawTherapee can't determine the correct raw crop. You can fix it by using the following `camconst.json` (to put in your user configuration directory for RawTherapee -- see the comment at the beginning of the global `camconst.json` for more info):

```json
{"camera_constants": [
    {
        "make_model": "Canon PowerShot G1 X",
        "raw_crop": [ 200, 144, 4168, 3128 ], // Optional official 4/3 frame 4160x3120, 4pix  borders, Left Border 204-4, Top Border 148-4
        "masked_areas": [ 148, 2, 3340, 78 ],
        "ranges": { "white": 16300 }
    }    
]}
```

**Comment by agriggio** [comment]
@Beep6581 might make sense to include the above in RT's `camconst.json`? (after polishing probably...). I just copied it from the entry for the G1 X MKII, but it seems to work

**Comment by Beep6581** [comment]
@agriggio sure, are all of the values correct?

**Comment by agriggio** [comment]
you can probably ignore the white value, it was a leftover from cut&paste. As for the rest, I'm not 100% sure but the result looks the same as the embedded JPEG of the camera and that created by the Adobe DNG converter.

**Comment by morosakubek** [comment]
This value is bad. Too much crop compared to CameraRaw (D1 X and D1 X Mark II are two different cameras). Another issue is that I still have distorsia. I recently checked the Canon G7 Mark II on RawTherapee, and the same was on the narrower focal length. The difference occurs between CameraRaw and RT before applying LCP to CameraRaw, so it may be a problem reading the .CR2 files themselves in RawTherapee?

**Comment by agriggio** [comment]
@morosakubek you are right -- I think yesterday I messed up the pp3 and came to a wrong conclusion. The LCP doesn't correct the distorsion properly, but I have no idea why. As a workaround, the automatic distortion correction does a good job here.

**Comment by heckflosse** [comment]
@agriggio Alberto, maybe the correction is a bit off because RT passes 0 as focusDistance to the lcp code?

I also compared the FocusDistance values in the lcp file with the values in other lcp files. I don't know which unit FocusDistance is, but if it's `m` then the lcp covers only the range >= 64.4 m while for example
`PENTAX_smc_PENTAX-DA_18-55mm_F3.5-5.6_AL_-_RAW.lcp` covers the range >= 0.25 m

**Comment by agriggio** [comment]
@heckflosse I just tried with the git master of LensFun, using [this script](https://github.com/lensfun/lensfun/blob/master/apps/lensfun-convert-lcp) to import the LCP profile, and then the example application `lenstool` that comes with lensfun, like this:

```
./lenstool --database=/home/alb/.local/share/lensfun/_lcps.xml -C"Canon PowerShot G1X" -L"fixed lens" -d /home/alb/Downloads/IMG_4077.png -o /home/alb/Downloads/out.png
```

I get the exact same result as RT. So, I'd say the LCP file is not precise for some reason, *or maybe* ACR is applying some transformation that is not documented in the Adobe lens model...

**Comment by morosakubek** [comment]
I do not know if this info will help but Darktable has the ability to correct for canon g1x.

**Comment by agriggio** [comment]
yes, darktable uses lensfun, which does a good job. eventually, also RT
will be able to use lensfun, hopefully in a not too distant future :-)
in the meantime, you can try auto distortion correction, it seemed ok to me

**Comment by heckflosse** [comment]
@agriggio 

> eventually, also RT will be able to use lensfun, hopefully in a not too distant future :-)

Alberto, I started that long ago but stopped it for reasons. Maybe now is a good point to restart lensfun integration. Working together at lensfun integration would surely speedup the task :)

Ingo

**Comment by agriggio** [comment]
:+1: yes, let's do that!

**Pull request merged**
