### PR TITLE
Cleanup: removed unused function; also murder instead of call for sui…

### PR DESCRIPTION
**Pull request by heckflosse**
…cide (delete this)

### CODE REVIEW

**Comment by heckflosse** [comment]
There are some more suicides `delete this` in RT code, but they are not encapsulated in a method, so a bit harder to fix...

**Comment by Floessie** [comment]
:+1: This is so much better than before.

**Review by Floessie — APPROVED** [review]
Didn't realize, that you wanted a review. :expressionless: 

Here you are.

**Comment by heckflosse** [comment]
@Floessie 
> Here you are.

I know where I am. Though I do not see a review ;-)

**Comment by heckflosse** [comment]
@Floessie Got it. Forget my last comment

**Comment by heckflosse** [comment]
Just for the record: On a native AMD FX 8350 win64 build, size of executable reduced by ~8 kb with the changes from this pr

**Comment by Floessie** [comment]
Awesome! Two pages saved. :grin:

**Pull request merged**
