### PR TITLE
Fix filtered horizontal thumbs

### PR DESCRIPTION
**Pull request by Floessie**
Take two images, the first in portrait, the second in landscape
orientation. Mark the second with a red dot and filter for red.
Now open that image in SETM. The top tumb is too slim.

### CODE REVIEW

**Comment by heckflosse** [comment]
@Floessie May I push a change to `ThumbBrowserBase::arrangeFiles()` ?

**Comment by heckflosse** [comment]
@Floessie

Here's a patch instead of a push ;-)

```
diff --git a/rtgui/thumbbrowserbase.cc b/rtgui/thumbbrowserbase.cc
index 5983f1c3..abb8ec68 100644
--- a/rtgui/thumbbrowserbase.cc
+++ b/rtgui/thumbbrowserbase.cc
@@ -575,6 +575,9 @@ void ThumbBrowserBase::arrangeFiles()
             if (!fd[i]->filtered && colsWidth + fd[i]->getMinimalWidth() <= availWidth) {
                 colsWidth += fd[numOfCols]->getMinimalWidth();
                 ++numOfCols;
+                if(colsWidth > availWidth) {
+                    break;
+                }
             }
         }
 
```

**Comment by Floessie** [comment]
@heckflosse Yes, please push directly. 👍 

Was that a bug or is it an optimization?

**Comment by heckflosse** [comment]
@Floessie It is an optimization which reduces another small O(n²) part to O(n)

Edit: Though it's still O(n²) when a filter is used which filters out a lot of files. But when no filter is used, breaking the loop when the max width of the row is reached should lead to O(n)

**Comment by heckflosse** [comment]
@Floessie
I just pushed it

**Comment by heckflosse** [comment]
@Floessie I must miss something. I tried to reproduce the bug, but could not...

**Comment by Beep6581** [comment]
Without the patch, I get this:
imgur-2017_07_08-00 31 20

**Comment by Beep6581** [comment]
And the patch fixes it.

**Comment by heckflosse** [comment]
Bug and fix confirmed. :+1: from me for merge

**Comment by Floessie** [comment]
@Beep6581 @heckflosse Fine. I'll merge.

**Pull request merged**
