### PR TITLE
Removes Noise Reduction settings from Preferences

### LINKED ISSUE #3299: TP_RETINEX_GAINTRANSMISSION_TOOLTIP
@Desmis hello, I'm revising some labels and this one is unclear to me:

`TP_RETINEX_GAINTRANSMISSION_TOOLTIP;Amplify or reduce transmission map to achieve luminance.\nAbscissa: transmission -min from 0, mean, and values (max).\nOrdinate: gain.`

Could you please explain the "Abscissa: transmission -min from 0, mean, and values (max)." part?

### PR DESCRIPTION
**Pull request by Beep6581**
- Noise Reduction settings removed from
  Preferences > Performance & Quality
- Performance & Quality renamed to Performance, container frame renamed
  to Threads, since it applies to more than just the NR tool.
- Localization keys removed.
- TP_RETINEX_GAINTRANSMISSION_TOOLTIP key revised, closes #3299

### CODE REVIEW

**Comment by Beep6581** [comment]
I will merge tomorrow if no objections.

**Comment by TooWaBoo** [comment]
What happens to all these NR-settings?

e.g. the "Tool Mode" is still working.
unbenannt

**Comment by Beep6581** [comment]
@TooWaBoo let's discuss this in the issue, #4327

**Comment by Beep6581** [comment]
Now the hard-coded defaults are used, instead of reading them from the `options` file. Will merge tomorrow if no objections.

**Pull request merged**
