### PR TITLE
5.10 Release Candidate 1

### PR DESCRIPTION
**Pull request by Lawrence37**

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 

All seems to work fine :)
A great day!

Just a warning, 
E:/code/repo-rt/rtengine/simpleprocess.cc:290:16: warning: unused variable 'tempitc' [-Wunused-variable]
  290 |         double tempitc = 5000.f;
which can be completely removed.

Jacques

**Comment by waynesutton50** [comment]
compiled successfully on Ubuntu 22.04. For info, the attached warning messages were displayed in the console: 
[RawTherapee_5.10_rc1_warning messages.zip](https://github.com/Beep6581/RawTherapee/files/14164810/RawTherapee_5.10_rc1_warning.messages.zip)

**Comment by Benitoite** [comment]
BTW, the broken macos auto build was fixed for `dev` in https://github.com/Beep6581/RawTherapee/pull/6936

**Comment by Desmis** [comment]
@Lawrence37 
In this topic in Pixl.us @nosle (thanks to him) found bad behavior when processing highlights...It can also occur if the settings are pushed to high limits
https://discuss.pixls.us/t/local-adjustments-color-appearance-and-log-are-incompatible-with-highlight-correction/41940/12

The change is very simple, change the default value in:
* procparams =>     avoidgamutMethod("XYZ"),
* controlspotpanel =>     avoidgamutMethod_->set_active(2);

The increase in processing time is reasonable, around 200ms on average, but the gain in quality is significant, especially for images with highlights.

This change is made in the lacam16n branch. I suggest you do it for 5.10.
If you agree and if this change is validated by the users (in progress) where should I push this change
* in Dev
* in v5.10-rc1
* the two
* nothing...

Thank you

Jacques

**Comment by Lawrence37** [comment]
@Desmis You can create a pull request for this branch. Is the second change necessary? The GUI is not getting the value from the procparams?

**Comment by Desmis** [comment]
@Lawrence37 
Procparams is enough
Jacques

**Comment by Desmis** [comment]
@Lawrence37 
It is not clear for me when you say this branch ?
Is it release-5.10 with à New PR
Or v5.10-rc1 with à New PR
Or just a commit to v5.10rc1
Thank you

**Comment by Lawrence37** [comment]
v5.10-rc1

**Comment by Desmis** [comment]
@Lawrence37 
Therefore, à PR to v5-10.rc1

**Comment by Lawrence37** [comment]
I've added the avoid color shift default change, the macOS build fix, the updated AUTHORS.txt, and a fix for the compiler warnings introduced since the last release.

**Pull request merged**
