### PR TITLE
Add Japanese and Danish translations

### LINKED ISSUE #6454: Translation update
Updated the translation in Japanese （such as LA and etc).
[Japanese.txt](https://github.com/Beep6581/RawTherapee/files/8438761/Japanese.txt)

### LINKED ISSUE #6461: Danish translation
I would like to have my translation of the RawTherapee added to the project.
But I cannot find out how to upload it to the project - please helt
Sincerely mogens jæger

### PR DESCRIPTION
**Pull request by Lawrence37**
Japanese translations by Yz2house.
Danish translations by mogensjaeger.

Replaces #6462.

### CODE REVIEW

**Comment by Lawrence37** [comment]
The `generateTranslationDiffs` script incorrectly removes some keys ending with "0", such as FILEBROWSER_POPUPCOLORLABEL0 and FILEBROWSER_POPUPRANK0.

**Comment by Entropy512** [comment]
generateTranslationDiffs was on my list of things to do after my pull request was done.

Will try and take a look at this tonight too.

**Comment by Entropy512** [comment]
@Lawrence37 I just tried running generateTranslationDiffs against the results of my cleanup and I'm not seeing it delete FILEBROWSER_POPUPRANK0

**Comment by Entropy512** [comment]
I've pushed my genTranslationDiffs results to a separate branch - I'll PR it once my other languages PR is merged:
https://github.com/Entropy512/RawTherapee/commit/3bd9fee057dc2b640466e4a3a7541aa1f4ef83f9

**Comment by Lawrence37** [comment]
@Entropy512 I guess it's a bug with my sort command.
```bash
$ echo "key;foo
key0;bar" | sort -Vu -t ';' --key=1,1
key;foo
```

```bash
$ sort --version
sort (GNU coreutils) 9.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
```

**Comment by Beep6581** [comment]
@Lawrence37 @Entropy512 @Thanatomanic
Apparently `sort` dropping lines is not a bug, who would have thought :see_no_evil:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=58153

**Pull request merged**
