### PR TITLE
Compiling with -Wall shows a large amount of warnings which should be fixed , fixes #3790

### LINKED ISSUE #3790: Compiling with -Wall shows a large amount of warnings which should be fixed
I want to try to make rt a bit more `-Wall`-clean.
I will start with compilation units in rtengine
Checked means it's clean. Unchecked means it's not clean or not tested yet.

- [x] colortemp.cc
- [x] curves.cc
- [x] flatcurves.cc
- [x] diagonalcurves.cc
- [x] dcraw.cc (fixed some warnings and disabled the remaining ones)
- [x] iccstore.cc
- [x] color.cc
- [x] dfmanager.cc
- [x] ffmanager.cc
- [x] gauss.cc
- [x] rawimage.cc
- [x] image8.cc
- [x] image16.cc
- [x] imagefloat.cc
- [x] imagedata.cc
- [x] imageio.cc
- [x] improcfun.cc
- [x] init.cc
- [x] dcrop.cc (Ingo)
- [x] loadinitial.cc
- [x] procparams.cc
- [x] rawimagesource.cc (Ingo)
- [x] demosaic_algos.cc (Ingo)
- [x] shmap.cc (Ingo)
- [x] simpleprocess.cc (Ingo)
- [x] refreshmap.cc
- [x] fast_demo.cc (Ingo)
- [x] amaze_demosaic_RT.cc (Ingo)
- [x] CA_correct_RT.cc (Ingo)
- [x] cfa_linedn_RT.cc (Ingo)
- [x] green_equil_RT.cc (Ingo)
- [x] hilite_recon.cc (Ingo)
- [x] expo_before_b.cc
- [x] stdimagesource.cc (nothing)
- [x] myfile.cc (Ingo)
- [x] iccjpeg.cc (nothing)
- [x] improccoordinator.cc (Ingo)
- [x] pipettebuffer.cc (Flössie)
- [x] coord.cc (Flössie)
- [x] processingjob.cc (Flössie)
- [x] rtthumbnail.cc (Flössie)
- [x] utils.cc (jacq)
- [x] labimage.cc (jacq)
- [x] slicer.cc (jacq)
- [x] cieimage.cc (jacq)
- [x] iplab2rgb.cc (jacq)
- [x] ipsharpen.cc (jacq)
- [x] iptransform.cc (jacq)
- [x] ipresize.cc (jacq)
- [X] ipvibrance.cc (jacq)
- [x] icons.cc (jacq)
- [x] imagedimensions.cc (jacq)
- [x] jpeg_ijg/jpeg_memsrc.cc
- [x] jdatasrc.cc (jacq)
- [x] iimage.cc (jacq)
- [x] EdgePreservingDecomposition.cc (jacq)
- [x] cplx_wavelet_dec.cc (jacq)
- [x] FTblockDN.cc (jacq)
- [x] PF_correct_RT.cc (jacq)
- [x] previewimage.cc (jacq)
- [x] ipwavelet.cc (jacq)
- [x] dirpyr_equalizer.cc
- [x] calc_distort.cc
- [x] lcp.cc
- [x] dcp.cc
- [x] ipretinex.cc
- [x] cJSON.c
- [x] camconst.cc
- [x] klt/convolve.cc
- [x] klt/error.cc
- [x] klt/klt.cc
- [x] klt/klt_util.cc
- [x] klt/pnmio.cc
- [x] klt/pyramid.cc
- [x] klt/selectGoodFeatures.cc
- [x] klt/storeFeatures.cc
- [x] klt/trackFeatures.cc
- [x] klt/writeFeatures.cc
- [x] clutstore.cc
- [x] ciecam02.cc (Ingo)
- [x] pixelshift.cc

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by agriggio** [comment]
@heckflosse  thanks for finalizing this! One suggestion (feel free to ignore): if you are enabling `-Wall` by default, maybe you can also add `-Wno-unused-result` to silence the warnings about `fread` and `fwrite` on glibc?

**Comment by heckflosse** [comment]
Yes, good idea :+1: 
Any objections from other devs to silence this warnings?

**Comment by heckflosse** [comment]
Any objections to merge?

**Comment by heckflosse** [comment]
I let the branch open for a while because it's possible that we get some fallout in non SSE builds.

**Pull request merged**
