### PR TITLE
Mac: Set RgbDenoiseThreadLimit = 2 to avoid crash

### PR DESCRIPTION
**Pull request by Benitoite**
Changes the options keyfile for mac to avoid a crash.
https://discuss.pixls.us/t/rawtherapee-dev-apple-m1-test/26596/41

### CODE REVIEW

**Comment by heckflosse** [comment]
@Benitoite Can you give some informations about the machine on which it crashes at setting 0 (RAM, number of cores)?

**Comment by Benitoite** [comment]
@heckflosse   8 core, 16 thread `__aarch64__` with 32GB RAM 
also 4 core, 8 thread `__x86_64__` with 64GB RAM

**Comment by heckflosse** [comment]
In the pixls.us thread I read that the crashes occur when using `Dynamic range compression` and in `Noise reduction`, but there only when using `Luminance Noise reduction`. Both use fftw3 library...

**Comment by Benitoite** [comment]
@heckflosse Dynamic Range Compression is always crashing for me, right upon activation, with a missing symbol error, but on my macos 12 system crash report, I can't see which module or symbol the dynamic loader `dyld` is talking about missing. FFTW used is from this: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fftw.rb

**Comment by Benitoite** [comment]
````
Crashed Thread:        73

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
missing symbol called
(terminated at launch; ignore backtrace)

Application Specific Information:
missing symbol called

Thread 73 Crashed:
0   dyld                          	       0x110ffcc6e 0x110fb7000 + 285806
1   dyld                          	       0x111012d7f 0x110fb7000 + 376191
2   dyld                          	       0x111012db1 0x110fb7000 + 376241
3   dyld                          	       0x110fc1543 0x110fb7000 + 42307
4   dyld                          	       0x110fdd9c0 0x110fb7000 + 158144
5   rawtherapee                   	       0x10838a549 0x107ae2000 + 9078089
6   rawtherapee                   	       0x1080c41bb 0x107ae2000 + 6169019
7   rawtherapee                   	       0x1080c15ac 0x107ae2000 + 6157740
8   libglibmm-2.4.1.dylib         	       0x108b35c13 0x108b23000 + 76819
9   libglib-2.0.0.dylib           	       0x10938cec2 0x10931e000 + 454338
10  libsystem_pthread.dylib       	    0x7ff811a6e5b8 0x7ff811a68000 + 26040
11  libsystem_pthread.dylib       	    0x7ff811a6a0d3 0x7ff811a68000 + 8403


Thread 73 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x000070000c8a7518  rdx: 0x000070000c8a7980
  rdi: 0x0000000000000006  rsi: 0x0000000000000004  rbp: 0x000070000c8a7560  rsp: 0x000070000c8a7518
   r8: 0x000070000c8a7580   r9: 0x0000000000000000  r10: 0x0000000000000014  r11: 0x0000000000000246
  r12: 0x0000000000000014  r13: 0x000070000c8a7980  r14: 0x0000000000000004  r15: 0x0000000000000006
  rip: 0x0000000110ffcc6e  rfl: 0x0000000000000246  cr2: 0x00007fbf40060000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133
````

**Comment by Benitoite** [comment]
and on `__aarch64__` a bit more info:
````
Thread 54 Crashed:
0   dyld                          	       0x1053d7084 __abort_with_payload + 8
1   dyld                          	       0x1053de044 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1053de078 abort_with_payload + 16
3   dyld                          	       0x105396564 dyld4::halt(char const*) + 328
4   dyld                          	       0x1053b4b24 dyld4::APIs::_dyld_missing_symbol_abort() + 44
5   rawtherapee                   	       0x104c2496c rtengine::ImProcFunctions::ToneMapFattal02(rtengine::Imagefloat*, rtengine::procparams::FattalToneMappingParams const&, int, int, float**, int, int, int) + 4944
6   rawtherapee                   	       0x104a04d94 rtengine::ImProcCoordinator::updatePreviewImage(int, bool) + 6076
7   rawtherapee                   	       0x104a02b40 rtengine::ImProcCoordinator::process() + 380
8   libglibmm-2.4.1.dylib         	       0x1055b253c (anonymous namespace)::call_thread_entry_slot(void*) + 44
9   libglib-2.0.0.dylib           	       0x105b62900 g_thread_proxy + 68
10  libsystem_pthread.dylib       	       0x18886d5a8 _pthread_start + 148
11  libsystem_pthread.dylib       	       0x18886838c thread_start + 8
````

**Comment by Pandagrapher** [comment]
> @heckflosse Dynamic Range Compression is always crashing for me, right upon activation, with a missing symbol error, but on my macos 12 system crash report, I can't see which module or symbol the dynamic loader `dyld` is talking about missing. FFTW used is from this: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fftw.rb

Made some test on my Mac (Intel 8 cores 16 threads, 16GB, Big Sur 11.5.2): I can't reproduce the crash with Dynamic Range Compression module (library packages from MacPorts)

Pierre

**Comment by Benitoite** [comment]
Here's what 10.14 gives me when activating Dynamic Range Compression:
```
Thread 30 Crashed:
0   dyld                          	0x0000000115b643ba __abort_with_payload + 10
1   dyld                          	0x0000000115b63bac abort_with_payload_wrapper_internal + 82
2   dyld                          	0x0000000115b63bde abort_with_payload + 9
3   dyld                          	0x0000000115b23a9d dyld::halt(char const*) + 343
4   dyld                          	0x0000000115b23bc7 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 167
5   libdyld.dylib                 	0x00007fff7582d32e dyld_stub_binder + 282
6   ???                           	0x000000010f23c000 0 + 4548968448
7   com.rawtherapee.RawTherapee   	0x000000010ed6a1bb rtengine::ImProcCoordinator::updatePreviewImage(int, bool) + 7675
8   com.rawtherapee.RawTherapee   	0x000000010ed675ac rtengine::ImProcCoordinator::process() + 444
9   libglibmm-2.4.1.dylib         	0x000000010fb54c13 (anonymous namespace)::call_thread_entry_slot(void*) + 35
10  libglib-2.0.0.dylib           	0x000000010fc9fec2 g_thread_proxy + 66
11  libsystem_pthread.dylib       	0x00007fff75a352eb _pthread_body + 126
12  libsystem_pthread.dylib       	0x00007fff75a38249 _pthread_start + 66
13  libsystem_pthread.dylib       	0x00007fff75a3440d thread_start + 13
```

**Comment by Benitoite** [comment]
@Pandagrapher @heckflosse `updatePreviewImage` is seen calling `ImProcFunctions::ToneMapFattal02`  Perhaps this contains a function my copy can't handle?

**Comment by heckflosse** [comment]
> Perhaps this contains a function my copy can't handle?

As I mentioned above, it calls fftw3 library, as does Denoise (if luminance denoise is enabled)

**Comment by Benitoite** [comment]
I gather my fftw is missing a required symbol then?

**Comment by Benitoite** [comment]
Building fftw3f from scratch with same result.  arm64 - macOS 12β

```
Thread 44 Crashed:
0   dyld                          	       0x105c0f084 __abort_with_payload + 8
1   dyld                          	       0x105c16044 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x105c16078 abort_with_payload + 16
3   dyld                          	       0x105bce564 dyld4::halt(char const*) + 328
4   dyld                          	       0x105becb24 dyld4::APIs::_dyld_missing_symbol_abort() + 44
5   rawtherapee                   	       0x10556496c rtengine::ImProcFunctions::ToneMapFattal02(rtengine::Imagefloat*, rtengine::procparams::FattalToneMappingParams const&, int, int, float**, int, int, int) + 4944
6   rawtherapee                   	       0x105344d94 rtengine::ImProcCoordinator::updatePreviewImage(int, bool) + 6076
7   rawtherapee                   	       0x105342b40 rtengine::ImProcCoordinator::process() + 380
8   libglibmm-2.4.1.dylib         	       0x105e8e53c (anonymous namespace)::call_thread_entry_slot(void*) + 44
9   libglib-2.0.0.dylib           	       0x10643e900 g_thread_proxy + 68
10  libsystem_pthread.dylib       	       0x187c8d5a8 _pthread_start + 148
11  libsystem_pthread.dylib       	       0x187c8838c thread_start + 8
```

Also getting this after app exit:
```
Termination Reason:    Namespace DYLD, Code 4 Symbol missing
missing symbol called
(terminated at launch; ignore backtrace)

Application Specific Information:
missing symbol called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   dyld                          	       0x105157084 __abort_with_payload + 8
1   dyld                          	       0x10515e044 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10515e078 abort_with_payload + 16
3   dyld                          	       0x105116564 dyld4::halt(char const*) + 328
4   dyld                          	       0x105134b24 dyld4::APIs::_dyld_missing_symbol_abort() + 44
5   rawtherapee                   	       0x1043ea380 main + 3756
6   dyld                          	       0x1051110f4 start + 520

```

**Comment by Benitoite** [comment]
I have found the culprit.  I was missing the linking flags for fftw3f *in the openmp flavor*:
```
-lfftw3f_omp -lfftw3f -lfftw3 -lm
```

The actual culprit is CMakeLists.txt not being able to deliver on those flags.

**Pull request closed without merging**
