### PR TITLE
LA - new tool - Color appearance (Cam16 & JzCzHz)

### PR DESCRIPTION
**Pull request by Desmis**
**LA - new tool - Color appearance (Cam16 & JzCzHz)**

Introducing a new tool for the Local Adjustments module: **Color appearance** .

This tool consists of the following two parts, which can be used stand-alone, combined or be integrated into some of the other already available tools:

* **CAM 16** - A CIECAM 16 based tool.
https://rawpedia.rawtherapee.com/CIECAM02#Local_Adjustemnts_-_Color_Appearance_.28Cam16_.26_JzCzHz.29
* **Jz Cz Hz** - A Jzazbz based tool (**experimental**).
https://rawpedia.rawtherapee.com/CIECAM02#Jzazbz_-_a_new_CAM_.3F

The following enhancements to the LA tools have also been implemented:

* Better processing for images with low La (Absolute luminance) and low Yb (Mean Luminance) when using Cam16, Jzazbz and Log encoding,
* For several of the LA modules there is the possibility to change the logarithmic part of the gamma (3.0 in Lab), either to preserve the DR (dynamic range) or to change the response of the algorithm,
* Possibility to act on the light/shadow balance in LA wavelet residual, with a TRC (Tone Response Curve - linear and logarithmic part) to preserve the DR.

This preservation of the DR is one of the keys to access the virtuous processing of HDR images and the underlying reason for this PR.

During the development of the Color Apperance modules, insufficiencies or bugs appeared concerning parts of the modules common to LA, specifically related to masks and curves. The following issues have been corrected:

* masks
** Improvements to "Recovery based on luminance mask" and "Denoise chroma mask" to improve selection and reduce artefacts in LC(h) and C curves.
https://rawpedia.rawtherapee.com/Local_Adjustments#What_can_you_do_when_the_mask_has_a_salt-and-pepper_appearance.3F_.28under_development.29
** What can you do when the mask has a salt-and-pepper appearance? (under development)

* curves
** Better correspondence for C curves (masked or not) between the values of the x axis and the real values of the chrominance of the image
** Better follow-up between the references (Hue, chroma, luma) of each RT-spot and the displayed values.

This PR was developed with the active participation of   Wayne  @Wayne_Sutton and Jacques   @Jade_NL . Thank you to them.

Jacques

### CODE REVIEW

**Comment by ghost** [comment]
Nice that this one now sees the light of day and can be tested by more people then just the 3 of us. I'm sure this new LA tool will be seen as a welcome addition.

Thanks, Jacques, for all the work you put into this one.

BTW: Tagged as being one for RT v6.0, here's me just hoping that it might be part of v5.9.....

**Comment by Floessie** [comment]
@Desmis Thanks a lot for your continued work on LA! :+1: I often use them for basic tasks and I wish I understood them better. :sweat_drops: 

> This preservation of the DR is one of the keys to access the virtuous processing of HDR images and the underlying reason for this PR.

Maybe there will be a presentation of this virtuous processing for beginners some day... :smiley: 

Best,
Flössie

**Comment by Floessie** [comment]
@Demis Build on Debian PPC failed. There seems to be a missing parameter in non-SSE code:

```
/home/user/src/rawtherapee/rtengine/improcfun.cc: In member function 'void rtengine::ImProcFunctions::ciecam_02float(rtengine::CieImage*, float, int, int, rtengine::LabImage*, const rtengine::procparams::ProcParams*, const rtengine::ColorAppearance&, const rtengine::ColorAppearance&, const rtengine::ColorAppearance&, LUTu&, LUTu&, LUTf&, LUTf&, float&, int, int, bool, float&, float&, float&, int, bool)':
/home/user/src/rawtherapee/rtengine/improcfun.cc:1460:60: error: no matching function for call to 'rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, const float&, float&, float&, float&, float&, float&, float&, int&)'
 1460 |                             Ciecam02::jch2xyz_ciecam02float(xx, yy, zz,
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
 1461 |                                                             J,  C, h,
      |                                                             ~~~~~~~~~
 1462 |                                                             xw2, yw2,  zw2,
      |                                                             ~~~~~~~~~~~~~~~
 1463 |                                                               c2, nc2, pow1n, nbbj, ncbj, flj, czj, dj, awj, c16);
      |                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/src/rawtherapee/rtengine/improcfun.cc:30:
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note: candidate: 'static void rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int, float)'
   79 |     static void jch2xyz_ciecam02float ( float &x, float &y, float &z,
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note:   candidate expects 20 arguments, 19 provided
/home/user/src/rawtherapee/rtengine/improcfun.cc:1769:56: error: no matching function for call to 'rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float&, const float&, float&, float&, float&, float&, float&, float&, const float&, float&, float&, float&, float&, float&, float&, int&)'
 1769 |                         Ciecam02::jch2xyz_ciecam02float(xx, yy, zz,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
 1770 |                                                         ncie->J_p[i][j],  ncie_C_p, ncie->h_p[i][j],
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1771 |                                                         xw2, yw2,  zw2,
      |                                                         ~~~~~~~~~~~~~~~
 1772 |                                                           c2, nc2, pow1n, nbbj, ncbj, flj, czj, dj, awj, c16);
      |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/src/rawtherapee/rtengine/improcfun.cc:30:
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note: candidate: 'static void rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int, float)'
   79 |     static void jch2xyz_ciecam02float ( float &x, float &y, float &z,
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note:   candidate expects 20 arguments, 19 provided
/home/user/src/rawtherapee/rtengine/iplocallab.cc: In member function 'void rtengine::ImProcFunctions::ciecamloc_02float(const rtengine::local_params&, int, rtengine::LabImage*, int, int, int, int, const LUTf&, bool, const LUTf&, bool, const LUTf&, bool, const LUTf&, bool, const LUTf&, bool, const rtengine::LocCHCurve&, const rtengine::LocHHCurve&, const rtengine::LocLHCurve&, bool, bool, bool, const rtengine::LocwavCurve&, bool)':
/home/user/src/rawtherapee/rtengine/iplocallab.cc:3975:52: error: no matching function for call to 'rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, const float&, float&, float&, float&, float&, float&, float&, int&)'
 3975 |                     Ciecam02::jch2xyz_ciecam02float(xx, yy, zz,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
 3976 |                                                 J,  C, h,
      |                                                 ~~~~~~~~~
 3977 |                                                 xw2, yw2,  zw2,
      |                                                 ~~~~~~~~~~~~~~~
 3978 |                                                 c2, nc2,  pow1n, nbbj, ncbj, flj, czj, dj, awj, c16);
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/src/rawtherapee/rtengine/iplocallab.cc:48:
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note: candidate: 'static void rtengine::Ciecam02::jch2xyz_ciecam02float(float&, float&, float&, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int, float)'
   79 |     static void jch2xyz_ciecam02float ( float &x, float &y, float &z,
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/user/src/rawtherapee/rtengine/ciecam02.h:79:17: note:   candidate expects 20 arguments, 19 provided
```

**Comment by Desmis** [comment]
@Floessie 
Yes a parameter "plum" was missing...curious no warning on Windows...

I think, It is solve now (I hope)

Jacques

**Comment by Desmis** [comment]
@Floessie 

for the "presentation" you can start with the documentary presentations in Rawpedia

https://rawpedia.rawtherapee.com/CIECAM02#Documentation

And also, of course the link above on CAM16 and Jzczhz

But I admit, it is not enough, because the subject is complex

jacques

**Comment by Floessie** [comment]
@Desmis 
> I think, It is solve now (I hope)

Yes, all builds fine now! :+1: 

> But I admit, it is not enough, because the subject is complex

That's what I thought when reading the links you posted in your introductory text. :grinning: 

Thanks,
Flössie

**Comment by Thanatomanic** [comment]
@Desmis Thanks for this! Yet another extensive addition to the LA toolset. I'll give it a test run soon-ish (life is a bit busy atm).

Does anyone know how to disable the bot that keeps triggering after every commit? It's really annoying and messy...

**Comment by Desmis** [comment]
@heckflosse 

Ingo
lgtm-com send message for this part of code in iplocallab.cc (about lines 415)


===========
float igammalog(float x, float p, float s, float g2, float g4)
{
    return x <= g2 ? x / s : pow_F((x + g4) / (1.f + g4), p);//continuous
}

#ifdef __SSE2__
vfloat igammalog(vfloat x, vfloat p, vfloat s, vfloat g2, vfloat g4)
{
  //  return x <= g2 ? x / s : pow_F((x + g4) / (1.f + g4), p);//continuous
    return vself(vmaskf_le(x, g2), x / s, pow_F((x + g4) / (F2V(1.f) + g4), p));
}
#endif

float gammalog(float x, float p, float s, float g3, float g4)
{
    return x <= g3 ? x * s : (1.f + g4) * xexpf(xlogf(x) / p) - g4;//used by Nlmeans
}

#ifdef __SSE2__
vfloat gammalog(vfloat x, vfloat p, vfloat s, vfloat g3, vfloat g4)
{
  //  return x <= g3 ? x * s : (1.f + g4) * xexpf(xlogf(x) / p) - g4;//continuous
    return vself(vmaskf_le(x, g3), x * s, (F2V(1.f) + g4) * xexpf(xlogf(x) / p) - g4);//improve by Ingo - used by Nlmeans
    
}
#endif
}


===========
This is the code you created and modified for "gammalog" (for SSE) . I did the same thing for igammalog  (for SSE).
my question : is this change the right one, what is the right code ? Or is it the code with comment // which is the right one


I think the "good" solution is with  ==> return vself(

Thank you

Jacques

**Comment by heckflosse** [comment]
@Desmis 

>I think the "good" solution is with ==> return vself(

Yes, that's the good code in terms of compiler support.

**Comment by Desmis** [comment]
@heckflosse 

Hello Ingo

Thank you

I will make a change to dev, to avoid wrong message in this PR

Thank you again :)

jacques

**Comment by Thanatomanic** [comment]
@Desmis Since you're still working a lot on improvements, I've change this PR to Draft status. Please let us know when you think it is time for a thorough check of the code and functionality.

**Comment by Desmis** [comment]
@Thanatomanic 
I think it would have been more elegant to ask my opinion before change this PR to Draft.


Excuse my bad english :)

The work with Wayne @waynesutton50 and Jacques @jade-nl (thanks to them) made it possible to develop this module, which one could also call "Color Apperance model and HDR". We spent a lot of time together to fix the bugs, but especially to make "Jz" work, which was not an easy task considering the little documentation. This work was the occasion to exchange on why and how it works. Of course we can share the knowledge we have acquired, (especially for @Floessie who is asking).

Just a remark, this module is important in "volume" because it takes into account the HDR logic (which is not limited to a monitor, and it is not a question here of elaborating HDR images...but to treat them with SDR compatible processes). 

There is no sense in splitting this module to "simplify". As a consequence, since the creation of the PR, I have made some modifications, often of detail or of the GUI, which do not change anything in the functioning and the principle , and which do not prevent from trying it.

During a review of the "Log encoding" part of which a part of the code is also used in Cam16 and Jz, I updated from ART the code used in RGB mode to simulate the luminance without interferences (wish) with the colors. 
 Some of you know this discussion  
https://discuss.pixls.us/t/finding-a-norm-to-preserve-ratios-across-non-linear-operations

Some of the solutions mentioned can be found in ART "Log encoding" and in "Filmic". But it seems to me much easier to use an HDR module, which by design separates the brightness channels from the chroma and Hue.  Its name "Jzazbz" (or Jz Cz Hz).
I started working on "Log encoding Jz" 4 days ago, and we can consider (even if we can make adjustments) that it works correctly...The results are at least on the same level as the RGB.... module and simpler.

I will not give again the links of Rawpedia (of course the documentation on Log encoding Jz is absent, in the same way a work is probably to continue on the Labels and Tooltips).

But in summary :
* LA Cam16 seems to me more powerful than the main module (because of the LA features) and simpler (admittedly it has less features...)
* LA JzCzHz has enough features to be evaluated (I think RT is one of the few software to have such a feature)...

A part of this code is necessarily in "double" precision (required on the one hand by the conversion matrices and the PQ - Perceptual quantizer function which leads to the use of data in very small ranges).

And of course you can check the code and functionnality. And of course you can modify the code to make it "cleaner" or "more efficient" without asking me, as long as it doesn't change the results.

Now, what is the future of this PR? And how will it fit in the RT updates (5.9, 6.0...). More precisely, what is RT becoming? 

Reminder I am an old man in bad health, and I'll make sure I have some free time

Jacques

**Comment by Thanatomanic** [comment]
@Desmis I made the change only because you were still committing code changes on a regular basis. To me that indicated the PR is not yet ready for review or merge. Perhaps I was mistaken, but please understand that I had no other motive for the change. Please change it back and request a review whenever you wish.

And concerning your question "What is RT becoming?": I still want to move forward and get 5.9 out, but I have very little time irl to really make that work.

**Comment by Desmis** [comment]
Hello everybody

you can check the code and functionnality.

jacques

**Comment by Desmis** [comment]
Hello
I just did a commit with 2 things
1) Wayne @waynesutton50 made a review of all the tooltips, thanks to him
2) I slightly modified two variables so that the results (for the same image) of 'LA log encoding' and 'Jz log encoding' are closer
3) I updated Rawpedia with Wayne's help, to take into account Jz log encoding
https://rawpedia.rawtherapee.com/CIECAM02#Implementation

This small (code) change can be an opportunity to exchange on the functionalities ?

Jacques

**Comment by Lawrence37** [comment]
Since this is good for processing HDR images, would it make sense to increase the maximum value for "dE scope threshold" in "Shape detection" for the spot settings? Even with a value of 10 and scope 100, I find this is not large enough for some images with a large DR.

**Comment by Desmis** [comment]
Hello @Lawrence37 

Excuse my very bad english....The HDR subject is complex, already trying in French, but for me in English it is like an obstacle course

HDR images are difficult to process (and to explain the algorithms) for several reasons. But one of the major difficulties is that of the image display monitor.... I think you are like me, not having a screen capable of « HDR » and « wide color gamut » images … 
The best screens (around 60000€) are able to switch to « Rec2020 » colors and « DR » from 0.001cd/m2 to 5000cd/m2.
The majority of the users have monitors with reduced range - in color often sRGB some times more and in « DR » of 0.1cd/m2 until 120cd/m2.

And even if you were to connect a super-monitor, the ICC profiles would still have to follow - today, for historical reasons, they are in 8-bit Lab (this is the main limitation)... ICC is working on this by making it possible (when?) to use Jzazbz as PCS. The use of Lab in RT in process does not limit the DR but makes difficult the evaluation of the highlights because of the gamma 3.0... Hence the implementation of alternatives such as the PQ function (perceptual quantizer)

The term DR (Dynamic Range) is often used, but it only reflects part of the problem, because it is essential to take into account "Absolute luminance" (call also « La »)  - something that Lab cannot evaluate, but which is found in Ciecam and Jz.

DR reflects the amplitude (often expressed in EV) between the most pronounced shadows and highlights. "Absolute Luminance" reflects the amount of light (in cd/m2) at the time of shooting. 

You can have high DR values of 12 or 13 and a rather low "La" for example 10cd/m2, but you can have images with comparable DR values but "La" of 5000 cd/m2 or more.... These images will be very difficult to visualize correctly (with a large budget...).

The evaluation of the « DR » as well as "La" are subject to controversy, because some data are not provided by the manufacturers (Canon, Nikon, Sony,...), nevertheless the approximation is sufficient - at least until the day when everyone will have a "super-monitor" (at 60000€).

You can find the code that calculates these 2 values (a part of it is from ART...) with my comments.
 Void « getAutoLogloc » in iplocallab.cc (line 2112 and after...). 
I have rather chosen minimal values, the reality can be (a little higher in the order of 0.5 for the DR and 10% for "La").

To come to the question that you ask with all the reserves that I have just stated, yes for the images with strong dynamics (DR) and with strong "La" it is desirable to modify a little the evaluations of deltaE. That's why I modified internally (I don't change GUI) 3 parameters when the user choose to use "Log encoding" or "Cam16 & Jz » . In this cases : « DeltaE scope threshold », « DeltaE decay » and the taking into account  of the luminance in the deltae are increased by 20%. but beware there will be no miracles....
I push a commit with this change.


Jacques

**Comment by Thanatomanic** [comment]
Hi @Desmis I gave this a quick testrun and didn't find any immediate errors. Looks good overall.
One comment: if I set the tool on 'Basic' or 'Standard' mode and choose 'Jz Cz Hz' as CAM model, no options appear at all. Is that intentional? It looks a bit suspicious. CAM 16 has many more 'Basic' options already.

**Comment by Desmis** [comment]
@Thanatomanic 

Thank you very much for testing :)

Yes, for "Jz" it is intentional, because of the complexity of this module. 
I am writing several explanations so that the user (and the developer) understand better why we arrived there.
I started this writing yesterday, but due to my bad English it takes time. I think I can edit the first "page" this morning.

Thank you again

Jacques

**Comment by Desmis** [comment]
**Some more thoughts on JzCzHz and Cam16**

**Part 1. Jz and its environment (experimental module)**

The development of the "Jz" part was delicate for several reasons. Indeed, the reading of the various tests and comments of researchers would let think that it is enough (as for Lab) to take the described procedure to convert from XYZ to Jzazbz and vice versa.

This is what I did, and from the first tests I could see, like other "testers" various problems that seemed to me to go against what was presented as a flagship product, combining the best of both Lab, Cam16 and more allowing HDR processing.

What are these problems (partly described in Rawpedia)?
With the code strictly following the described procedure
* the colors present a flagrant saturation defect
* the use of simple treatments (contrast curve, slider brightness,...) is accompanied in some cases by very strong artifacts, as well as unusual responses to various tools.

Looking at these first results, I found that the values of "Jz" that are expected in the range [0.1] (and those of "az" and "bz" expected in the range [-0.5 + 0.5]) are including for HDR images generally in the range [0...0.18] or less with an average value close to 0.001. These values were also found by other testers who questioned the researchers without getting an answer (at least from what I could find on the web). These low values are due to the use in the matrix of the iPQ and PQ function.
Several testers proposed workarounds that I tried without much success.
On the other hand it turned out that given the precision of the calculations required and the use of certain constants (for example Jzazbz_d0 which is 1.6295499532821566e-11), working in double precision is essential at least at the level of the conversion matrices and before remapping.
Note that an optimization of the code must be possible @heckflosse . This has not been the main objective until now, because the main thing was to make it work correctly (colorimetry) and without bugs

I did several searches on the web and found a thesis by a researcher that compared various HDR products and obtained a metric to validate the results. This thesis also contains valuable information about HDR and the various gamma and Lab substitution treatments.
https://tel.archives-ouvertes.fr/tel-02378332/document

I proceeded by trial and error, taking into account my experience of Ciecam development, as well as information on the Web and in the Darktable forum and code.

**What have I done to make it work**: at least in SDR, by projecting the HDR action in a hypothetical way? because I don't have the money to acquire an HDR monitor (around 30000 to 60000€), nor the profiles and software (LCMS) to drive it. These modifications are of my conception, hence the term "experimental" and the voluntary limitation of "Jz" to "advanced".

1) I used the notion of "remapping" so that the value of Jz takes into account the characteristics of the original image, especially "Absolute luminance La". In short, the higher "La" is, the higher the values of Jz (in the code, and of course az and bz) will be
2) I allowed the code to vary the Peak Luminance in the PQ function (Perceptual Quantizer) which is by default set to 10000 in the 2 original matrices. This variation is made possible between 100cd/m2 and 10000cd/m2, the usual values of SDR monitors on the one hand and the maximum potential of future HDR monitors on the other. Try to vary PQ, you will see even in SDR an action in the shadows and highlights. 
3) I also modified - only at the time of their use - the values of Jz, az, bz, to put them in the interval [0..1] or [-0.5 0.5] so that the various tools (sliders, curves, wavelet, etc.) are in a usual interval of use. 
4) I also - in front of the dysfunctions of Zcam (version of Cam16 for Jz, adapted by the researchers who initiated Jzazbz) - "adapted" some processes of Cam16 to make them usable in "Jz" like for example - and only for the part "Scene conditions", to take into account the notions of " Yb " (Mean luminance), " La " (Absolute luminance - based on Exif data) and Surround (Average, Dim, Dark), Lightness instead of Brightness and to take into account the "saturation" in addition to the "chroma". 

With these changes "Jz" behaves quite correctly in a comparable way to Cam16, without artifacts and with the possible opening to HDR....HDR functions can only be really tested/validated when: a) HDR monitors are available, b) ICC profiles and tools are available.

Note however that (due to the design of the matrix?) the use of the curves based on Hz brought significant artifacts problems that I solved by limiting the possible ranges of settings.


**The XYZ-Jzazbz conversion**
It is based on 
a) a dissymmetry giving to the blue channel a different importance compared to the red and green
b) obtaining "Jz" is done only from 2 channels "L" (red) and "M" (green) which again gives the blue channel "S" a different part.
During the various tests we ended up with crashes. In a first step I thought it was due to the "pow" functions used by PQ with negative values. I tried to incorporate a std:max(val, 0.) function wherever there was "pow", but crashes persisted (in rare cases). I have since replaced "std::max", with "isnan" and now no more problems. 


"Jz" is equipped with a panel of tools which seems to me sufficient to evaluate it: Brightness / lightness , contrast, chroma, saturation, Hue rotation, curves Jz(Jz), Cz(Jz), Cz(Cz), Hz(Hz), Hz(Cz), Hz(Jz), Shadows/Highlight, Wavelet (local contrast and Clarity), as well as two functions " Log encoding Jz " and " Sigmoid Jz "


**Log encoding Jz and Sigmoid Jz**
The advantage of these modifications is to allow for example the use of a function "Log encoding Jz" by using Jz (Brightness) as a reference thus avoiding any distortion of colors that can bring the RGB mode. 

Sigmoid Jz, looks like a " Tone curve " with 3 components
* "strength" which acts on the slope of the sigmoid, thus modifying the contrast
* "threshold " which allows to offset the action towards the shadows or the lights
* "blend " which combines this variation with the original image

To make it easier to understand the sigmoid, I enclose a graph made by @Thanatomanic  for the use of the sigmoid by Ingo in Dual-demosaic. This example has been posted to facilitate discussion on the choices of parameter 16…(in the case of dual demosaic)  
https://www.desmos.com/calculator/gdrzan4ubk 

In this example, you can replace in the first formula 16 by another coefficient (example - L and make vary L between 1.5 and 27) : “t” corresponds to “threshold”, “L” corresponds to “strength”.
* In the case of “LA” if strength is 0, it corresponds to a value of 26.4 for “L”. “L” acts on the “slope” of the curve, the higher it is (26.4) , the less effect the sigmoid will have. The flatter it is (for “LA” 1.4), the more the sigmoid will modify the basic function.
* “t” in “LA” is different and take into account the abscissa…but the principle is here. “t” moves the action of the sigmoid either to the shadows (low values) or to the highlights (high values)
* note the flatness of the curve near 0 or 1, which is very difficult to control with a tone-curve. This “flatness” is the guarantee of a correct response in HDR. (at least that’s what I think).


In both cases, " Log encoding " and " Sigmoid " the possible control of the chroma will be done preferentially, either with the  "saturation" slider which differentiates the action between the shadows and the lights, or the Cz(Jz) curve.

**Thanks**
I would like to thank Wayne @waynesutton50 and Jacques @jade-nl  again for their cooperation, the many tests I asked them. Without them the tool would not be usable today.

And excuse my bad english :)

Jacques

**Comment by Desmis** [comment]
If nobody objects, I will merge this PR tomorrow :)

https://github.com/Beep6581/RawTherapee/issues/5632

Jacques

**Comment by Thanatomanic** [comment]
No objections from me, as long as you please 'squash and merge' to keep the commit log cleaner. :+1:

image

**Comment by Floessie** [comment]
@Desmis 

`dev` builds fine, but there is an interesting warning about bad indentation from Clang in [`rtengine/iplocallab.cc:12753`](https://github.com/Beep6581/RawTherapee/blob/1e4f41bc0509149a55a95d29e15e4c5d69e65234/rtengine/iplocallab.cc#L12753). This is indeed fishy, as the `for` loop [above](https://github.com/Beep6581/RawTherapee/blob/1e4f41bc0509149a55a95d29e15e4c5d69e65234/rtengine/iplocallab.cc#L12733) doesn't have braces. Could you check?

Then there are two little "fixes" (to warnings at least):

```diff
diff --git a/rtgui/locallabtools2.cc b/rtgui/locallabtools2.cc
index e37e657d7..4dc5deb43 100644
--- a/rtgui/locallabtools2.cc
+++ b/rtgui/locallabtools2.cc
@@ -6321,7 +6321,7 @@ void LocallabLog::updateAutocompute(const float blackev, const float whiteev, co
 {
     if (autocompute->get_active()) {
         idle_register.add(
-        [this, blackev, whiteev, sourceg, sourceab, targetg, jz1]() -> bool {
+        [this, blackev, whiteev, sourceg, sourceab, targetg]() -> bool {
             GThreadLock lock; // All GUI access from idle_add callbacks or separate thread HAVE to be protected
 
             // Update adjuster values according to autocomputed ones
@@ -8739,7 +8739,7 @@ void Locallabcie::updateAutocompute(const float blackev, const float whiteev, co
 
     if (Autograycie->get_active()) {
         idle_register.add(
-        [this, blackev, whiteev, sourceg, sourceab, targetg, jz1]() -> bool {
+        [this, blackev, whiteev, sourceg, sourceab, jz1]() -> bool {
             GThreadLock lock; // All GUI access from idle_add callbacks or separate thread HAVE to be protected
 
             // Update adjuster values according to autocomputed ones
```

HTH,
Flössie

**Comment by Desmis** [comment]
@Floessie 

Ok, thank you, good catch :)

I push a commit with these 3 changes .

Jacques

**Pull request merged**
