### PR TITLE
Make WB-Picker button look like other toolbuttons

### PR DESCRIPTION
**Pull request by TooWaBoo**
Replaced `hbox` with `grid` and added the classes `grid-spacing` and `grid-row-separator`.
The PR contains light and dark `color-picker-small.png` images which have to be replaced with generated ones.

unbenannt

### CODE REVIEW

**Comment by Beep6581** [comment]
Would be good to remove the placeholder PNGs and squash the commits before merge.

**Comment by TooWaBoo** [comment]
Maybe someone wants to test it and therefore the placeholder PNGs are necessary.
I will remove them and merge dev into my fork when the `color-picker-small.png` are generated.
_________________________________________________________________________
I've found a bug on higher dpi settings. When the width of the `Size-Combobox` is increasing, the label will not move to the left. The bug doesn't affect the RT-theme
unbenannt

To fix this I've put the combobox in it's owen grid container as a child. Sizing can be done with this grid container. I've set an ID `#WB-Size-Helper` for css.
unbenannt2

**Comment by TooWaBoo** [comment]
If anybody wants to test it. You can download a compiled Windows version from here.
https://filebin.net/ve9z7d7cf0z5na20

**Comment by TooWaBoo** [comment]
@Beep6581 
Removed `color-picker-small.png` and merged dev into my branch.
Before you merge, please create the `color-picker-small.png` in dev. Without these RT will crash.

**Comment by TooWaBoo** [comment]
@Beep6581 
This has to be merged too. It contains the theme for the curves.

**Comment by Beep6581** [comment]
Will test, squash and merge tonight.

**Pull request merged**
