### PR TITLE
Fix for issue https://github.com/Beep6581/RawTherapee/issues/3751

### PR DESCRIPTION
**Pull request by TooWaBoo**

### CODE REVIEW

**Comment by heckflosse** [comment]
@Floessie @agriggio @Hombre57  I'm still on gtk 3.18 and can't test the fix. @Beep6581 is afk for about a week and can't test. So I have to rely on you to test and confirm the fix :+1:

**Comment by Floessie** [comment]
@heckflosse Tested with GTK 3.22.8. Works. Thanks, @TooWaBoo! Ready for merge. :+1:

**Comment by agriggio** [comment]
I'm also on 3.18, sorry

**Comment by Beep6581** [comment]
@TooWaBoo thank you for the fix, I confirm it works.

In addition to mentioning the issue number please also describe the problem in the commit - otherwise browsing a commit log requires looking up each issue which makes it hell to e.g. write a changelog when dealing with hundreds or thousands of commits.

I will merge this into dev once the critical cli issue (I will open one in a moment) is fixed.

**Pull request merged**
