### PR TITLE
Applying geometric transformations leads to dark artifacts in combina…

### LINKED ISSUE #5588: Applying geometric transformations leads to dark artifacts in combination with capture sharpening
The bicubic interpolation we use for geometric transformations leads to artifacts in combination with capture sharpening especially in areas with high contrast. I will create a pr soon to avoid that.
Here's a first screenshot. Left with current code, right with new code:
grafik

### PR DESCRIPTION
**Pull request by heckflosse**
…tion with capture sharpening, fixes #5588

### CODE REVIEW

**Comment by heckflosse** [comment]
Current implementation of logarithmic transform increases the processing time for geometric transformations by ~ factor 5.1
With next commit the factor will be ~ 1.7

**Comment by heckflosse** [comment]
Just for information. Currently the log transform is fully backwards compatible to 5.7 as it's only used if Capture sharpening is enabled, which is not available for 5.7.

**Comment by heckflosse** [comment]
Factor now is ~ 1.5

**Comment by Thanatomanic** [comment]
I think I found a segfault when enabling profiled chromatic abberation correction... I'll investigate further tomorrow.

**Comment by Thanatomanic** [comment]
To reproduce:
1. Load RAW file that has a profiled CA correction
2. Apply Neutral
3. Set to linear mode (should already be the case for Neutral)
4. Turn off all corrections
5. Go to 100% zoom mode (seems to matter...)
6. Set to logarithmic mode
7. Enable CA correction. SEGFAULT in `lut.h`

Here's a stacktrace: https://filebin.net/011vn748erxv8gx3

**Comment by heckflosse** [comment]
@Thanatomanic I pushed a fix

**Comment by Thanatomanic** [comment]
Fix confirmed 👍

**Comment by heckflosse** [comment]
@Thanatomanic 
> Set to linear mode (should already be the case for Neutral)

Currently the default is `Logarithmic`. For existing pp3 files `Linear` is used for backwards compatibility.
I prefer `Logarithmic` as default because in my experience it gives less artifacts. The downside of `Logarithmic` is that it's slower.

What do you think?

**Comment by Thanatomanic** [comment]
@heckflosse 
I agree with you observations: Logarithm gives better results overall and I like it much better, but not in darker regions near the black clipping point. You get nasty pixel artifacts then... 

Like this: 
image


But actually, in both cases it's very hard to see any difference when viewing at 100% or less.

**Comment by heckflosse** [comment]
@Thanatomanic Can you provide an example file to test? Maybe there's a way to improve the loharithmic mode...

**Comment by Thanatomanic** [comment]
@heckflosse Take a look at this picture for example: https://discuss.pixls.us/t/play-raw-nightscape-from-orange-free-state
Using `Logarithmic` is better for the stars, but gives blocky artifacts in the dark and noisy horizon.

**Comment by heckflosse** [comment]
@Thanatomanic Thanks for the example. Confirmed.

**Comment by heckflosse** [comment]
I would like to merge this for 5.8 as
1) it is backwards compatible
2) `logarithmic` gives better results overall
3) `linear` can still be used

Objections?

**Pull request merged**
