### PR TITLE
Improvments to LA Sigmoid - LA Log encoding Cam16  and ICC profile creator

### PR DESCRIPTION
**Pull request by Desmis**
Hello

This PR brings various improvements to Dev
* better response of the 2 Sigmoid curves (Jz and Cam16), ensuring a more progressive work
 * addition to Cam16 of a “Log encoding Q” function which brings a response taking completely into account the colorimetry (CAM). This function is from my point of view superior to that of “Jz” which requires a correction of the saturation, and superior to that of “LA log encoding” which works in RGB mode (which does not fully control the linearity of the hue) .
  * Addition to “Cam16”, as for “Jz”, to take into account “BlackEv” and “WhiteEv” for Sigmoid Q
   * add to ICCprofile creator the ICC profile - DCI-P3. DCI-P3 is the new standard for recent monitors and Oled TVs, which allow at least HDR images.

@waynesutton50 and I have been updating Rawpedia… The Colorimetry module has been completely revised, the ones on Jz a little simplified
https://rawpedia.rawtherapee.com/Toolchain_Pipeline#Colorimetry

https://rawpedia.rawtherapee.com/CIECAM02#Jzazbz_-a_new_experimental_CAM.3F 1

https://rawpedia.rawtherapee.com/Local_Adjustments#An_experimental_JzCzHz_module 1

Jacques

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37

For my informations, where are the builds of this pull-request? Linux, MacOS, Windows ?

Thank you 

Jacques

**Comment by Thanatomanic** [comment]
@Desmis Ici: https://github.com/Beep6581/RawTherapee/actions

**Comment by Thanatomanic** [comment]
@Desmis Would it be okay to merge this right now, instead of waiting until 6.0?

**Comment by Desmis** [comment]
For me no problem. If you agree, I can merge soon  :)

Thank you

Jacques

**Comment by Thanatomanic** [comment]
I've merged this pro-actively already, let's get some things done again in RT 🙂

**Comment by Desmis** [comment]
@Thanatomanic 

Thank you very much :)

Jacques

**Pull request merged**
