### PR TITLE
curves: restore old DCT_Spline, add new DCT_CatmullRom type

### PR DESCRIPTION
**Pull request by agriggio**
Hopefully this will make everybody happy. The new curve type (which I simply called "Custom new" in the GUI -- better names are welcome) is used only for histogram matching by default. Existing pp3's should pick up the old cubic splines without issues. 

I coded this in about half an hour, so please test before merging (if you decide to merge)

### CODE REVIEW

**Comment by Beep6581** [comment]
We could call the cubic spline "Rigid" and the Catmull-Rom "Flexible", that would be pretty user-friendly.
Or... "Stiffy" and "Floppy" :smile:

**Comment by agriggio** [comment]
As discussed on IRC, my vote for names goes to "Standard" for the old cubic splines and "Flexible" for the new ones. Regarding "Standard", I think cubic splines are sort of the de-facto standard when you talk about spline interpolation. In the photography/retouching world, it could be argued that "standard" is what the more popular tools do by default. I have never used Photoshop or Lightroom, but I just found this:

https://feedback.photoshop.com/photoshop_family/topics/point_editing_mode_for_tone_curve_control_hard_to_use_because_of_non_local_effects

Which makes me believe that the "point curves" are indeed cubic splines

**Comment by agriggio** [comment]
after a night of sleep, I think I can live with "smooth"/"sharp" if std/Flexi has no fans :-)

**Comment by agriggio** [comment]
OTOH, another argument in support of "Standard". Quoting from https://discuss.pixls.us/t/curves-behaviour-changed-in-development-version/10141:

> In V5.4 stable release, it behaves like any other curves adjustment tool I’ve used, most notably Photoshop

**Comment by Thanatomanic** [comment]
Just my 2 cents here, I would call the old version 'Standard' and the new one 'Precise' or 'Detailed'.

**Comment by TooWaBoo** [comment]
I suggest to use a different curve icon too.

**Comment by Beep6581** [comment]
- Photoshop CS2
curve photoshopcs2
- RT cubic spline
curve rt custom
- RT Catmull-Rom spline
curve rt catmullrom
- GIMP-2.8.10
curve gimp

As the Photoshop curve resembles RT's cubic spline, I'm fine with "Standard" for cubic spline and "Flexible" for the centripetal Catmull-Rom spline.

I committed a new icon, `curve-catmullrom.png` and `curve-catmullrom-small.png`

**Comment by agriggio** [comment]
Can this be merged? If so, should I merge on `releases` first and then port to `dev`?

**Comment by Beep6581** [comment]
@agriggio please merge to `dev`, then I'll cherry-pick to `release-5.5`.

**Comment by agriggio** [comment]
pushed

**Pull request closed without merging**
