### PR TITLE
Backport fix for #3794 from ART

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

On behalf of @heckflosse I backported ART's solution for #3794 to RT. Please test.

Best,
Flössie

### CODE REVIEW

**Comment by Thanatomanic** [comment]
@Floessie For when you're back from vacation: I've tested the branch but managed to get easy crashes while opening a folder that contains the two gradient files from the OP in #3794. There seem to be a few division by zero issues. Looking...

**Comment by Thanatomanic** [comment]
I pushed two fixes. Thumbnail generation for extremely thin images (1px) now works as well.

**Comment by Thanatomanic** [comment]
Ping @brussell1 @teplit, since you commented on the original issue #3794. If you can, please test this PR locally.

@agriggio You way be interested to apply the division by zero prevention fixes to ART as well.

**Comment by ff2000** [comment]
There are several integer operations with implied rounding errors.
What do you think about enforcing floating point arithmetics (convert one value to double instead of size_t)?
And always round the resulting value up (using cmath.ceil) before converting back to int to avoid 0 as a result?

**Comment by Thanatomanic** [comment]
@ff2000 Could work as well. I have no strong preference, also not in terms of computational efficiency (though I think integer operations and a simple _if_ could be faster than a double conversion and rounding - not that you would probably notice in this case). There may also be cases where a `ceil` is not the desired outcome, so as a general solution I don't think it's desirable.

Another alternative solution would be to always enforce a minimum image size of 1×1 in the constructor of an image class.

**Comment by Floessie** [comment]
@Thanatomanic Thanks for testing and the fix! I would have used `x = std::max(1, x)` but that's a matter of taste. Hit the merge button, if you feel it's ready. :smile:

**Pull request merged**
