### PR TITLE
get rid of 'copypasta' in translation files

### PR DESCRIPTION
**Pull request by da-phil**
`$ find rtdata/languages/ -type f -exec sed -i -e 's/copypasta/copypaste/g' {} \;`

;)

### CODE REVIEW

**Comment by heckflosse** [comment]
Oh, copypasta is a bit like [Szeva](https://github.com/Beep6581/RawTherapee/search?q=szeva&type=Issues&utf8=%E2%9C%93)

**Comment by da-phil** [comment]
but I guess Szeva is not as tasty as copypasta :laughing:

**Comment by Beep6581** [comment]
You must be joking, I love copypasta :P

**Comment by Floessie** [comment]
So, whether we merge or not is a matter of (our) taste. Good luck. ;)

**Comment by da-phil** [comment]
Are you saying that you chose that name deliberately? :o

**Comment by Floessie** [comment]
No, we were just kidding. As Szeva is long dead, I propose we flush the copypasta down the toilet, just before @Beep6581 gets an upset stomach.

@Beep6581 @heckflosse Okay to merge?

**Comment by Beep6581** [comment]
Not OK to merge. If we are to change this, then the change should be grammatically correct, and "copypaste" is not. I'll close this PR and make the correct change directly to the source tomorrow when I'm on my home laptop.

**Comment by heckflosse** [comment]
Sorry about being too late. I would have voted for not changing it ;)

**Comment by Beep6581** [comment]
I like it too, as I do "szeva". Puts a smile on my face when I see it.

**Comment by heckflosse** [comment]
Exactly :)

**Pull request closed without merging**
