### PR TITLE
Initial support for GX680 digital back

### LINKED ISSUE #4204: FUJIFILM DBP for GX680 RAF support
I recently received a Fujifilm DBP for GX680 digital back. When I converted the raw file to JPG file, I got strange output as below image. It seems like RawTherapee does not recognize the file.
I have uploaded a RAF raw file and a JPG file both saved by the digital back at:
http://www.weldpass.com/upload/Fujifilm-DBP.zip

Thanks,

Wen

dscf0001-s

### PR DESCRIPTION
**Pull request by Thanatomanic**
Fixes #4204

Not a very common camera by any means, but LibRaw could decode it, and now we can too.
@wtanmdt If you have the ability to test and/or provide additional shots, that would be really helpful.

In particular it would help to have:
* A shot with the lens cap on (fully black)
* A reuploaded shot of color charts (tungsten light and daylight), as were provided before but are now unavailable

### CODE REVIEW

**Comment by wtanmdt** [comment]
@Thanatomanic Here is the daylight file:
[Fujifilm-DBP-for-GX680-daylight.zip](https://github.com/Beep6581/RawTherapee/files/10330229/Fujifilm-DBP-for-GX680-daylight.zip)

**Comment by wtanmdt** [comment]
@Thanatomanic 
Here is the tungsten file:
[Fujifilm-DBP-for-GX680-tungsten.zip](https://github.com/Beep6581/RawTherapee/files/10330233/Fujifilm-DBP-for-GX680-tungsten.zip)

**Comment by wtanmdt** [comment]
@Thanatomanic 
Here is the fully black file:
[Fujifilm-DBP-for-GX680-fully-black.zip](https://github.com/Beep6581/RawTherapee/files/10330236/Fujifilm-DBP-for-GX680-fully-black.zip)

**Comment by Thanatomanic** [comment]
Hi @wtanmdt thanks for the quick response. After a lot of digging and manually checking things in the raw file, I can now say that your digital GX680 is now properly supported in RawTherapee including a double illuminant DCP profile. That should load automatically if you have selected "Auto-matched camera profile" under Color management. 
After this PR is merged, it should show up in the nightly builds and will definitely be part of version 5.10.

The only thing I noticed is that the default 'camera' white balance is pretty whack. E.g. your daylight shot gives T = 5860 K and tint = 0.686. Properly matching it to a grey patch gives T = 6451 K and tint = 0.904. So, even with a DCP profile, you will most likely need to white balance things manually.

**Comment by wtanmdt** [comment]
@Thanatomanic Thanks a lot for your help.

**Comment by Beep6581** [comment]
> the default 'camera' white balance is pretty whack. E.g. your daylight shot gives T = 5860 K and tint = 0.686

@Thanatomanic I haven't looked at the files here but wanted to point out that this usually happens when the illuminants are not in the expected order. RawTherapee expects `CalibrationIlluminant1=Standard Light A` and `CalibrationIlluminant2=D65` while a few modern cameras, especially smartphone ones, have them reversed. Last I checked this order was not enforced by the standard, so RawTherapee is at fault.

**Pull request merged**
