### PR TITLE
Show lens used on Panasonic cameras

### LINKED ISSUE #2998: Lenses are not recognized on Panasonic cameras
Lenses are not recognized on Panasonic cameras. I tried with new and old Panasonic models with new and old (4.2.0) RT versions.
I cannot find any Panasonic lens data in xxx.. atribs.cc files. Although I found Panasonic lens data in Olympusattribs.cc 
Is RT supposed to read the lens info for Panasonic bodies from exif ?.

### PR DESCRIPTION
**Pull request by t0pu**
To fix #2998

### CODE REVIEW

**Comment by heckflosse** [comment]
@t0pu Thanks for the pr. I tested using some Panasonic files. It works fine for DMC-GH2, DMC-G5, DMC-GM1, DMC-GX7, DC-GH5 :+1: Maybe it works for other Panasonic cams as well but I don't have more files to test.
To avoid complications @Beep6581 should review your changes as he's currently working at the exif stuff in rt code.

**Comment by Beep6581** [comment]
Hello @t0pu , thank you for the PR! I tested it and it works well. Some Panasonic raw files shows "Unknown" or "N/A", but ExifTool confirmed that they either had no lens tag or the tag's value was actually "N/A".

+1 for merge after PR #3827 is merged.

@t0pu I'm curious, how did you create the stuff in `panasonicAttribs[]`, manually? And what source did you use for the info?

**Comment by t0pu** [comment]
Hello @heckflosse, hello @Beep6581, I also tested it with some files. "Unknown" or "N/A" can occur on files from point & shoot cameras, for example, which have no exchangeable lens, but i think thats fine. It can also be "NO-LENS" if you take a photo with no lens attached. 

@Beep6581 For the info in `panasonicAttribs[]` I used exiv2 for reference. They have a table of Panasonic makernote tags on their website which I put into a spreadsheet and created a formula to give me the contents for `panasonicAttribs[]` .

**Comment by Beep6581** [comment]
@t0pu ah, I do basically the same thing, only using ExifTool and xmlstarlet to parse ExifTool's XML output and Bash to put that into our .cc file format. Issue #3801 is the proper long-term solution.

I'll try to merge your PR now.

**Pull request merged**
