### PR TITLE
mac: optionally make a generically-named copy of the zip

### PR DESCRIPTION
**Pull request by Benitoite**
with -DOSX_NIGHTLY=ON will produce copies of the zip with generic names: `RawTherapee_macOS_arm64_latest.zip` for the purpose of hyperlinking.

### CODE REVIEW

**Comment by Benitoite** [comment]
Automatic builds have upgraded operating systems; will fix with another commit.

**Comment by Benitoite** [comment]
The github action appears to produce a green check mark with the last pair of fixes.

**Comment by Benitoite** [comment]
And with this series the patch automates the Universal packaging.

**Comment by Benitoite** [comment]
And with this series, the package now reports minimum macOS versions to Launch Services per Architecture for the universal app.

**Comment by Thanatomanic** [comment]
Hi @Benitoite, you had been gradually adding fixes to this PR until last month. Is it okay to merge?

**Comment by Benitoite** [comment]
Yes this is working and ready.

**Pull request merged**
