### PR TITLE
New Locallab GUI

### PR DESCRIPTION
**Pull request by Pandagrapher**
@Desmis 
I just finished the cleanup and merge :)

This pull request adds a new GUI to Locallab tools. Main changes:
- Several control spots can now be managed together
- Interactions between rtengine and rtgui for Locallab have been reviewed (better performance)
- Locallab tools parameters are now saved directly in .pp3 file

### CODE REVIEW

**Comment by heckflosse** [comment]
That sounds really good. I will test tomorrow :+1:

**Comment by Desmis** [comment]
@Pandagrapher 
All seems to work fine :) I have not all verified...
a) It would be desirable that the point evoked in issue #4094 (visible / hidden) for the spots is treated
b) By default, I think "shape method", must be to "independant (mouse)" - it seems easy to do

Other points
As you know I am not at all a Github specialist; this "pull request"  what is it about ? 
1) does it merge "newlocallab" from the main fork with "newlocallab" from the fork Pandagrapher
2) does it merge "dev" (base branch ??) from the main fork with "newlocallab" from the fork Pandagrapher...in this case, if I click on "Merge pull request", "dev" will be update with locallab ?

I will be away since friday 28 september, to monday 7 october
Jacques

**Comment by sguyader** [comment]
I tried it, it looks great!
There's a strange behaviour though, when there's an activated crop: sometimes when you click in the image , RT "thinks" you're trying to modify the crop area, and then the local lab control points disappear from the the GUI (they still exist), and you have to click on another tab (Color, or Exposure for example) and come back to the local lab tab to see the control points appear again.

**Comment by Pandagrapher** [comment]
For the next days, I have planned to continue working on improving the GUI:
- Firstly, I want to improve the robustness of the `LocallabParams` structure as suggested by @Floessie. @Desmis I will consider your request to change the default values when creating a spot. Morevover I have read in your wiki page you used int values to manage the data instead of double which contributes to imprecision. If you want, it's possible to use double value for locallab parameters instead
- Secondly I want to review the spot management panel (duplication and visibility)
- Thirdly I want to improve the mouse actions on control spot (for instance, using scroll wheel on center will increase/decrease its size) and correct the bug with right click

@Desmis What do you think about this roadmap?

@gaaned92 I corrected the bug you reported with "Color & Light" or "Retinex" panel

**Comment by Desmis** [comment]
@Pandagrapher 

I agree with your roadmap :)
For the second point (spot management panel), it would be desirable that if "Normal spot" is selected, "scope" must be hidden.
And of course as says @sguyader , correct the behaviour of "Visible" for Control spot (eg if you click right, all Spot disappears on the preview...but they are always here)

But, first of all, congratulations for this remarkable work :)
jacques

**Comment by gaaned92** [comment]
Windows 64 build available.

**Comment by Beep6581** [comment]
Hello

I'm following this from a distance so I may have missed something. It seems that @Pandagrapher made changes which are ready to be integrated into @Desmis 's `newlocallab` branch. If that's the case, 
@Desmis please hit the "Merge pull request" button once the conflicts are resolved. I'm happy to do that for you if need be, but the conflicts must be resolved first.

**Comment by Pandagrapher** [comment]
@Beep6581 @Desmis 
I will try to resolve the conflicts on tomorrow if available time

**Comment by Desmis** [comment]
@Beep6581 
Excuse my bad comprehension of Github, for me for example "Pull Request" is a mistery,  as also working with 2 forks.

I just try to merge newlocallab  in panda\newlocallab  but system says me "déjà à jour" (already updated), or not able to merge

What I missed. ? Probably ==> git pull with Beep6581:newlocallab ???

Can you give me step by step what to do
1) when in the same fork I want to merge, I used
a) git checkout newlocallab
b) git reset --hard HEAD
c) git checkout dev
d) git pull
e) git checkout newlocallab
f) git merge dev -m "merge with dev"
g) if conflicts, I used ==>  git mergetool
g1) git commit -m "merge with dev" -a
h) git push...

In this cases, what are the differents steps ?

@Pandagrapher 
I will let you merge, because of "improccoordinator" and my old code for mip files, I do not want to be stupid  :)
Now you can merge with Beep6581:newlocallab, I have solve conflicts with "dev" and add some code ignored (of course) by merge in improccoordinator.cc . I add 
            || params.locallab != nextParams.locallab
line 4459, otherwise nothing works

jacques

**Comment by Beep6581** [comment]
Hi @Desmis 

To merge @Pandagrapher's changes manually (i.e. not using the big green "Merge pull request" button in GitHub, which is currently grayed-out because of merge conflicts), the steps as explained by GitHub follow.
1. Step 1: From your project repository, check out a new branch and test the changes.
    ```
    git checkout -b Pandagrapher-newlocallab newlocallab
    git pull https://github.com/Pandagrapher/RawTherapee.git newlocallab
    ```
1. Step 2: Merge the changes and update on GitHub.
    ```
    git checkout newlocallab
    git merge --no-ff Pandagrapher-newlocallab
    git push origin newlocallab
    ```

But I think it's best if we wait for @Pandagrapher to resolve the conflicts, then there will be no need to merge manually - I'll just click the button.

**Comment by Pandagrapher** [comment]
@Beep6581 @Desmis 
Conflicts resolved

**Comment by Beep6581** [comment]
Compiled and ran successfully - merging `Pandagrapher:newlocallab` into `Beep6581:newlocallab`

**Comment by Beep6581** [comment]
Really good work!

**Comment by Desmis** [comment]
@Beep6581 
I am satisfied with your work (merge panda into Beep6581), even if certain functions are (temporarily) uninsured (dupilcated spot).

Thank you very much :)

jacques

**Comment by Beep6581** [comment]
@Desmis it was all @Pandagrapher 's work, I just merged it.

**Comment by Desmis** [comment]
@Beep6581 
Yes of course, @Pandagrapher  works is remarkable :)
But, on the principle of updating the "main" branch, thanks :)

jacques

**Comment by Pandagrapher** [comment]
@Desmis
Don’t worry: I am currently working on improvements ;)

**Comment by Desmis** [comment]
@Pandagrapher 
Je ne suis pas inquiet, bien au contraire très confiant :)

**Comment by Desmis** [comment]
@Pandagrapher 
Hier j'ai fusionné "newlocallab" avec "dev", mais ceci m'a obligé à modifier les fichiers sur lesquels tu travailles
locallab.h locallab.cc controlspotpanel.h controlspotpanl.cc
suite à une modification opérée il y a dix jours sur les listeners
Ceci m'a amené à ajouter dans les 2 fichiers "h"
    void adjusterAutoToggled(Adjuster* a, bool newval);
    void adjusterChanged(ThresholdAdjuster* a, double newBottom, double newTop);
    void adjusterChanged(ThresholdAdjuster* a, double newBottomLeft, double newTopLeft, double newBottomRight, double newTopRight);
    void adjusterChanged(ThresholdAdjuster* a, int newBottom, int newTop);
    void adjusterChanged(ThresholdAdjuster* a, int newBottomLeft, int newTopLeft, int newBottomRight, int newTopRight);
    void adjusterChanged2(ThresholdAdjuster* a, int newBottomL, int newTopL, int newBottomR, int newTopR);
et leur équivalent dans les fichiers "cc"

jacques

**Comment by Pandagrapher** [comment]
@Desmis 
Merci pour l’info : je ferai attention lors de mon merge
Pour info, j’ai fini de modifier la structure procparams de Locallab pour plus de robustesse. En ce moment, je m’attaque à reprendre le code pour mieux supporter les copier/coller de paramètres, la gestion des profiles ainsi que du traitement par lot avec Locallab
Une fois fini je remonterai une pull request avec ce package

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 

OK, merci :)

**Comment by Desmis** [comment]
@Pandagrapher 
Il y a pas mal de temps.. même beaucoup... que j'essaie d'améliorer l'algorithme de détection de forme.
Je l'ai appelé comme cela même si cela prête à confusion. Mais :)

Toujours est-il que cet algo est la base en termes d'algorithmes de locallab. Comment ne retoucher que les zones souhaitées, en évitant les détourages à la Photoshop... qui d'ailleurs sont très imparfaits et qui par exemple interdisent les modifications de feuillages....de manière élégante..

 J'ai en fait "renoncé" à SobelCanny (même si le code reste présent), et j'ai:
a) amélioré l'algorithme de base fondé sur delta Hue, delta Chroma et delta Luma. J'ai implanté cela dans Color & Light "curves type", ainsi que dans "exluding spot"
b) utilisé la procédure mise au point par Ingo, "contrast threshold" pour dfférencier l'action selon la "structure" de l'image (dans le même esprit que SobelCanny), c'est implanté dans "Color & Light" . Cela fonctionne mais amène au niveau de la transition un assez important liserai... qui peut ne pas être gênant.

Pour cela je n'ai quasiment rien changé à ton code sinon
1) changer la valeur par défaut de "sensiexclu" (12 au lieu de 19) dans locallab.cc et controlspotpannel.cc
2) ajouté 3 choix  à la méthode "qualitycurveMethod" dans locallab.cc et bien sûr iplocallab.cc
3) et bien sûr adapté les algos dans "Lab_local"  

De mon point de vue dans les cas critiques (notamment lorsque les variations de Hue sont faibles) l'amélioration est importante, voire essentielle.

Plutôt qu'un long discours, il suffit d'essayer...
Mais avant de faire un commit sur Beep6581/RawTherappe, je souhaite ton accord.

Merci

Jacques

**Comment by Pandagrapher** [comment]
@Desmis 
Cool si tu as pu améliorer l'algorithme de détection de forme :)
Tu peux remonter tes modifications : je les reprendrai avec la nouvelle structure de `procparams` lors de mon merge avec la branche (j'espère avant mes vacances en fin de semaine prochaine)

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 

Merci...
Je vais encore améliorer le truc, j'examine encore un poil pour affiner les différents cas avant de commit.
En fait j'ai modifié "Color and light" avec accès par le menu
Pour les autres modules, l'utilisateur pourra activer ou non une variable "detectshape"

J'ai trouvé un miniscule "bug" dans Locallab, pour inverser "Retinex" (erreur de copier / coller)

jacques

**Comment by Pandagrapher** [comment]
@Desmis 
Par curiosité : pourquoi avoir implémenté ton nouvel algorithme de détection dans "Color & Light" uniquement au lieu de "qualityMethod" pour que ça profite à tous le spot ? "detectshape" sera donc une nouvelle CheckBox par traitement (exposure, Color & Light, ...) ?

Tu me dis si je me trompe mais j'ai l'impression que "qualityMethod" ne s'applique pas à tous les traitements (ex : "Blur & Noise" semble prendre la forme du spot sans détection de forme). Est-ce que ça ne serait pas plus visible d'indiquer ces particularités au niveau de l'"expander" du traitement (de la même façon que "1:1") ?


> J'ai trouvé un miniscule "bug" dans Locallab, pour inverser "Retinex" (erreur de copier / coller)

Où cela ? Tu corriges avec tes modifications ou tu préfères que je le prennes de mon côté ?

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 
Le mini bug est dans "void Locallab::inversretChanged()" au lieu de expreti->getEnabled(), il y a actuellement expsharp->getEnabled(). Je vais le changer avec mon patch

En fait il y a plusieurs améliorations qui tiennent compte de chaque module
* le plus complexe "color ans light" qui reprend en gros"l'historique " de locallab avec mes divers essais (les premiers il y a presque 4 ans !!! il faut sacrément être patient, je te dois un immense merci pour avoir un produit "commitable" :))
* j'ai ajouté aux contrôles actuels surtout fondés sur les écarts de teinte (hue), ainsi que de luma et de chroma, 2 autres critères prenant en compte le deltaE global avec 2 objectifs
a) éviter les artefacts lorsque le spot est grand et inclus de nombreuses autres couleurs dont les aplats
b) éviter les bavures lorsque les delta Hue sont très faibles
je ne dis pas qu'il n'y a plus d'artefacts, mais ils sont considérablement réduits

*j'ai également ajouté une fonction proche de "contrast threshold" qui est en théorie séduisant mais en pratique bof...
Donc, les 3 lignes ajoutées sont là pour tester  , après il n'en restera qu'un (j'espère) : le "super" actuel
La variable "Detectshape" dans options (manuellement, pas de checkbox) est elle aussi provisoire, pour permettre de tester et revenir aux réglages d'avant au cas où.

L'autre module qui prend en compte ces deltaE c'est "exposure"
Ces 2 modules "Color and Light" et "exposure" sont les plus complexes. Pour les autres à la limite il n'y en avait pas besoin

Le "exclude" a lui aussi bénéficié : 
a) suppression de 2 bugs (mauvais paramètres ou variables) présents depuis ???
b) amélioration de deltaE

Pour répondre à ta question:
* il n'y a que "denoise" et "sharp" qui ont une détection simplifiée
* burr and noise, est le seul à avoir un "inverse"  qui peut prendre en compte les hueref, lumaref, chromaref (mode "symétrique")
* lorsque tout sera au point, il doit être possible de simplifier le code avec des modules en commun, pour ce qui est autre que "color and light".... mais cela pourra être réalisé ensuite...Je préfère pour l'instant garder, même si cela complexifie le code, le contrôle de chaque module.

Jacques

**Comment by Desmis** [comment]
@Pandagrapher

je pense mettre à jour "newlocallab" demain après midi, je vais re-tester avec diverses images "difficiles"

jacques

**Comment by Desmis** [comment]
@Pandagrapher 
J'ai fait la mise à jour sur Beep6581! J'espère ne pas m'être trop planté :)
Je vais faire un commentaire d'ici quelques heures, expliquant sommairement les changements, sur le forum PIXL.US rubrique "Local lab build"

Jacques

**Comment by Pandagrapher** [comment]
@Desmis 
Merci pour tes explications :) Je comprends mieux certaines différences observées entre les outils
Pour ma part, j'ai quelques complications pour adapter le traitement par lot avec locallab (j'aimerai bien garder la "philosophie" de base sans trop de complexités en plus). J'espère remonter à la fin de la semaine après avoir mergé avec tes évolutions (ce qui me permettra de les tester au passage :))

Pierre

**Comment by Desmis** [comment]
@Pandagrapher 

Ok :)
Merci
Jacques

**Pull request merged**
