### PR TITLE
Update TooWaBlue v2.66 / Update Deutsch locale

### PR DESCRIPTION
**Pull request by TooWaBoo**

### CODE REVIEW

**Comment by TooWaBoo** [comment]
ping @heckflosse

**Comment by heckflosse** [comment]
@TooWaBoo with a bit of luck you can add translations for two new combined demosaic methods in the evening ;-)

**Comment by TooWaBoo** [comment]
@heckflosse
If you don't merge now, there would be a merge conflict and I have to do the stuff again.

**Comment by heckflosse** [comment]
Ok :+1:

**Pull request merged**
