### PR TITLE
Internal LibRaw

### LINKED ISSUE #4462: Replace dcraw with actively maintained raw decoding engine (e.g. LibRaw)
While in the past I would occasionally communicate with Dave Coffin, author of dcraw, I have not received any replies or seen any signs of progress on dcraw for over a year. It seems the project is abandoned, and we need a plan to move forward.

Options:
* RawSpeed https://github.com/darktable-org/rawspeed
* [LibRaw](https://www.libraw.org/) https://github.com/LibRaw/LibRaw
* [libopenraw](https://libopenraw.freedesktop.org/wiki/) https://github.com/hfiguiere/libopenraw

### LINKED ISSUE #6226: Sony A1 lossless compressed files not supported
New lossless compressed format of sony A1 is not supported. I can only open the dng files converted from ACR but this results in a black layout on the bottom and right of the image which requires cropping for every single photo.

### LINKED ISSUE #6626: Lumix GH5 Mark 2 RW2 raw format support
The Lumix GH5 mark 2 is about 1.5 years since announcement and the .rw2 files have never worked for me. Was hoping it would in Version 5.9 but it is still not. Here is a sample file together with the associated pp3 and screen shot. Really appreciate all the work that went into RawTherapee over the years. 

https://filebin.net/ddfuwvosqf7r1ihq

### LINKED ISSUE #6726: Support for Sony A7R V lossless compressed RAW files
The current official release (5.9) doesn't support the lossless compressed RAW files generated by Sony A7R V cameras (SONY ILCE-7RM5). The camera supports these in three different resolutions:

Large: 61MP (9504×6336 pixels)
Medium: 26M (6240×4160 pixels)
Small: 15M (4752×3168 pixels)

RawTherapee cannot read these at all. https://raw.pixls.us/ contains sample images in these formats.

These files are significantly smaller than the uncompressed option, and allow selecting different resolutions as well, which is quite convenient. I have found no solutions capable of handling these files on Linux, though Lightroom for example does support them on Android.

### PR DESCRIPTION
**Pull request by Lawrence37**
As an experiment for #4462, I've added LibRaw directly into RawTherapee and borrowed heavily from ART for the implementation. It is functional and can potentially be adopted as the solution for replacing dcraw. I chose to go this route to familiarize myself with the raw image decoding part of the code. It didn't take much time or effort and at least I gained relevant knowledge if we decide to go with another route.

The LibRaw source code is included via [git-subtree](https://manpages.debian.org/bullseye/git-man/git-subtree.1.en.html) at [`rtengine/libraw`](https://github.com/Lawrence37/RawTherapee/tree/d8252ad89aa89864458dda0f98befdf68c23c37f/rtengine/libraw). Like git submodules, git-subtree facilitates git subprojects, but tracks the commits in the parent project. The first two commits here add the LibRaw code to RawTherapee. Having our own copy of LibRaw allows us to make tweaks to it just as we have done with dcraw. There are no modifications to the LibRaw code yet in this pull request.

LibRaw has its own configuration script to generate the Makefile. At some point, it may be worth it to directly configure and build LibRaw through CMake. For now, I simply have CMake run the configuration script and added a task to call `make`. It works seamlessly except for the clean target. There's no way to modify the clean target, so cleaning the LibRaw build requires a second command: `make clean-libraw`. That means a full clean requires `make clean` *and* `make clean-libraw`.

The integration is fairly simple with most of the changes contained within the `RawImage` class. LibRaw is the first decoder. If it fails or does not support decoding the image, it falls back to dcraw. Since the code is adapted from ART, it accumulated some edge-case handling during the time it lived in ART.

### CODE REVIEW

**Comment by mattiaverga** [comment]
From a Fedora Linux packager POV, going from bundling (almost) a single file to bundling an entire project like libraw is an horrible idea... and it will cause a real pain for me to continue providing RT as a Fedora official package.
Can you consider linking to libraw as an external library and propose patches upstream, if that become necessary?

**Comment by Lawrence37** [comment]
I'm not familiar with the packaging process, so could you explain why adding many files is a burden? Is there anything that would help make it easier? It could be an issue if we decide to go with rawspeed instead. rawspeed is intended to be built into the program. A quick search in repositories for several distributions shows no results for rawspeed.

**Comment by kmilos** [comment]
> LibRaw has its own configuration script to generate the Makefile. At some point, it may be worth it to directly configure and build LibRaw through CMake.

You have https://github.com/LibRaw/LibRaw-cmake 

Re bundling - we had the same issue w/ packaging darktable for distros, so there is a CMake option to either use the system LibRaw library, or the in-tree copy.

**Comment by mattiaverga** [comment]
> I'm not familiar with the packaging process, so could you explain why adding many files is a burden? Is there anything that would help make it easier? It could be an issue if we decide to go with rawspeed instead. rawspeed is intended to be built into the program. A quick search in repositories for several distributions shows no results for rawspeed.

It is a pain because Fedora "highly discourage" bundling libraries, so I will probably have to ask an exception for that.
More generally, bundling a library means that if a security issue is found and addressed upstream, it is not true that will be fixed in the bundled version, at least in a timely manner. I have already to deal with several CVEs filed for dcraw and I need every time to check if the bundled version is affected or not (see for example #4061, #4084, #5722).

> Re bundling - we had the same issue w/ packaging darktable for distros, so there is a CMake option to either use the system LibRaw library, or the in-tree copy.

Sure, having the option to use system libraries or the bundled one would be acceptable. But if the bundled one is going to be modified to adapt to RT code, that would not be a feasible option.

**Comment by Lawrence37** [comment]
Ok, that makes more sense. So it's not about the structure of the code, but having to resolve problems across multiple copies. Libraw is fortunately a proper library and I was planning on adding a compile-time option to use the RT version or the system library. The same is not true of rawspeed and dcraw (mostly).

> But if the bundled one is going to be modified to adapt to RT code, that would not be a feasible option.

Do you mean if there is a custom LibRaw in the codebase, it's not feasible to implement the ability to choose which LibRaw to use, or not feasible to maintain a package of RawTherapee for Fedora? In either case I don't see the issue.

**Comment by mattiaverga** [comment]
> Do you mean if there is a custom LibRaw in the codebase, it's not feasible to implement the ability to choose which LibRaw to use, or not feasible to maintain a package of RawTherapee for Fedora? In either case I don't see the issue.

Referring to what you wrote above: "Having our own copy of LibRaw allows us to make tweaks to it just as we have done with dcraw". If the custom library here and the vanilla upstream are going to differ, trying to use the system provided library might become broken.

**Comment by Lawrence37** [comment]
That won't be an issue. We don't need to make any fundamental modifications that would affect the API or ABI.

Edit: Actually, I think only the API matters since the program is linked to one or the other LibRaw, not both. That means everything will work if we don't touch libraw.h, which we have no need to do.

**Comment by Lawrence37** [comment]
Some updates since my last comment:

1. Fixed DNG gain map detection and reading when using LibRaw.¹
2. Added option Preferences > Image Processing > Raw Decoder > Use LibRaw. If enabled (default), LibRaw will be used to decode raw files except if the file is known not to work or work sub-optimally.
3. Fixed crash when loading some multi-frame files.
4. Used proper `#include` statement in case the system LibRaw has an incompatible API.
5. Updated internal LibRaw to v0.21.2 (from v0.21.1).
6. Fixed Sony Pixel Shift loading with a LibRaw implementation.
7. Added a few missing camera constants.²
8. Fixed DNG bad pixels detection and reading when using LibRaw.¹
9. Fixed application of camera constants for Hasselblad cameras.
10. Implement levels and flat-field correction for Hasselblad cameras when using LibRaw.²

I went through the RawTherapee edits to dcraw and checked if LibRaw addresses them. For those that LibRaw does not address, I made the necessary changes to bring the decoding in line with our custom dcraw decoder. I hope I didn't miss anything. This pull request is now ready for consideration.

---

¹ Originally implemented in our custom dcraw. The dcraw implementation has been removed as it now works with any raw decoder.
² Changes to the internal LibRaw. Not available if compiled for the system LibRaw.

**Comment by kmilos** [comment]
> Changes to the internal LibRaw.

Please consider upstreaming any relevant changes. (I guess you can skip the new camera constants as those are presumably already lined up for the next public snapshot.)

**Comment by epadepa** [comment]
I compiled and gave this a run, am I the only one seeing a considerable performance penalty? I can barely compile so the problem may well lie behind the keyboard. Any suggestions how I can get performance metrics?

I downloaded https://raw.pixls.us/getfile.php/2474/nice/Pentax%20-%20K-1%20-%2014bit%20(3:2).DNG and opening + any operation is extremely slow.

```
Version: 5.9-477-g67da8a963
Branch: libraw
Commit: 67da8a963
Commit date: 2024-01-11
Compiler: cc 13.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.8
Lensfun: V0.3.4.0
Build type: Debug
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.3.0-1-amd64 x86_64
Build date: Sun, 04 Feb 2024 22:15:51 +0000 UTC
Build epoch: 1707084951
Build UUID: 
```
edit: did som simple time runs with two of my local builds
First libraw build
 ```
time ~/programs/rt-libraw/rawtherapee-cli -o /tmp/rt-libraw.jpg -p ~/.cache/RawTherapee5-libraw/profiles/Pentax\ -\ K-1\ -\ 14bit\ \(3\ 2\).DNG.bca3bd1b22bdab560fb70ce264c3358f.pp3   -c ~/dwn/Pentax\ -\ K-1\ -\ 14bit\ \(3\ 2\).DNG
RawTherapee, version 5.9-477-g67da8a963, command line.
Output is 8-bit integer.
Processing: /home/epadepa/dwn/Pentax - K-1 - 14bit (3 2).DNG
  Merging procparams #0

real    1m42.062s
user    9m37.321s
sys     0m2.618s

```
Then a lacam16n branch build (sorry for not being a release)
```
time ~/programs/rt-lacam/rawtherapee-cli -o /tmp/rt-lacam.jpg -p ~/.cache/RawTherapee5-libraw/profiles/Pentax\ -\ K-1\ -\ 14bit\ \(3\ 2\).DNG.bca3bd1b22bdab560fb70ce264c3358f.pp3   -c ~/dwn/Pentax\ -\ K-1\ -\ 14bit\ \(3\ 2\).DNG
RawTherapee, version 5.9-718-gd1750e827, command line.
Output is 8-bit integer.
Processing: /home/epadepa/dwn/Pentax - K-1 - 14bit (3 2).DNG
  Merging procparams #0

real    0m18.669s
user    1m48.271s
sys     0m6.243s
```

**Comment by Lawrence37** [comment]
Your build type is debug. Try changing it to release. The RawPedia page for compiling on Linux should explain how, in case you need it.

**Comment by Desmis** [comment]
@Lawrence37 

Hello

I would like to inform you of my feedback to install this PR under Windows (some will say that it is enough to be under Linux...), the fact remains that I am not there, and probably not the alone...and in any case it is necessary to be able to do it in the 3 systems (Windows, Mac, Linux).
Plus as you know, I'm bad at computers, I work like a monkey copying what people tell me.

As soon as I wanted to compile, while my version of Msys2 was up to date (done on February 17, 2024). I got this compiler errors.

**"autoreconf"** is unknown in Msys.

After searching on google I found this command to enter on Msys2.
**$ pacman -S autotools**

Then in "Mingw64" I run "cmake --build . --target install"

I was **a little scared by all the messages from the compiler**... it's quite impressive, but in the end **everything works**.

Just a detail. When I change a file in my editor, and re-run cmake, **I get this message "Building LibRaw"**  which lasts a few seconds (about 4 to 10 sec)

jdesm@PCSPECIALIST01 MINGW64 /e/code/repo-rt3/build
$ cmake --build . --target install
[1/7] Creating AboutThisBuild.txt and other version-dependent files
-- git command found: C:/msys64/usr/bin/git.exe
-- Git checkout information:
--     Commit description:    5.9-477-g67da8a963
--     Branch:                libraw
--     Commit:                67da8a963
--     Commit date:           2024-01-11
--     Commits since tag:     477
--     Commits since branch:  477
--     Version (unreliable):  5.9.477
-- Build information:
--     Build OS:              MINGW64_NT-10.0-22635 3.4.10.x86_64 x86_64
--     Build date:            Thu, 22 Feb 2024 14:41:23 +0000 UTC
--     Epoch:                 1708612883
--     UUID:                  b4959f48-d5c6-46ea-bfbe-5b44b4c173a4
-- CACHE_NAME_SUFFIX is "5-dev"
**[2/7] Building LibRaw**
make: Nothing to be done for 'all'.
[6/7] Install the project...-- Install configuration: "release"
-- Up-to-date: E:/code/repo-rt3/build/release/./AUTHORS.txt
-- Up-to-date: E:/code/repo-rt3/build/release/./LICENSE
-- Installing: E:/code/repo-rt3/build/release/./AboutThisBuild.txt
-- Up-to-date: E:/code/repo-rt3/build/release/./RELEASE_NOTES.txt
-- Up-to-date: E:/code/repo-rt3/build/release/./share/man/man1/rawtherapee.1
-- Up-to-date: E:/code/repo-rt3/build/release/./licenses
-- Up-to-date: E:/code/repo-rt3/build/release/./licenses/DroidSansMonoDotted.txt
etc.

Thank you for this work...because Dcraw is almost dead :)

Jacques

**Comment by Lawrence37** [comment]
Right, the documentation for compiling in macOS and Windows will need to be updated. In the workflow .yml files, you can see that macOS needs automake and Windows (msys2) needs autotools. By default, the build process for LibRaw does emit many messages. As long as there are no warnings or errors, everything should be fine. When rebuilding, LibRaw will take some time to check if any source files have been changed. It's the same for rtengine, rtgui, etc.

**Comment by Desmis** [comment]
@Lawrence37 
OK thank you
Jacques

**Comment by kmilos** [comment]
> After searching on google I found this command to enter on Msys2.
> **$ pacman -S autotools**

Actually, you want `pacman -S --needed mingw-w64-x86_64-autotools` (or mingw-w64-ucrt-x86_64-autotools if you're building in the UCRT64 environment) [to ensure other dependencies are there as well](https://packages.msys2.org/package/mingw-w64-x86_64-autotools?repo=mingw64).

Btw, libraw is available in msys2 so there is no real need to build it...

**Comment by Desmis** [comment]
@kmilos 

OK, thank you, I update Msys2 with pacman -S --needed mingw-w64-x86_64-autotools, and libraw

Jacques

**Comment by Desmis** [comment]
@Lawrence37 
Apart from a lot of warnings during compilation (decoders_dcraw.cpp, libraw,...), this took place without problems and upon execution everything seems (from what I can verify) to work correctly.

Thank you

Jacques

**Comment by Lawrence37** [comment]
Now that a new LibRaw snapshot is out, I wonder if it is a good idea to use snapshot or stick to releases. Snapshots have a few limitations stated on the website. There will also be additional effort required to merge minor releases into the snapshots.

**Comment by Lawrence37** [comment]
Given LibRaw's long release cycle, I will go with using the public snapshots.

**Comment by Lawrence37** [comment]
Any opinions regarding when to merge this? There's an option to disable LibRaw in case anyone experiences issues. I could make it disabled by default and enable it in a future release.

**Comment by sgotti** [comment]
@Lawrence37 I'm all for merging it to permit testing from all people using RT dev and to fix issues before next release. For this reason and also since libraw will probably be the default decoder for the future with dcraw as fallback It'll be better to keep it enabled by default.

P.S. I'd like to report few issues I found on some old and not so common raw files that I have in my test images collection. Merging it will make it easier to open new issues and PRs.

For example sigma DP1 merril x3f files opens correctly with current dev but has wrong output (look heavily misaligned) with this PR also with libraw disabled in preferences (issue just noticed, not yet analyzed).

**Comment by Lawrence37** [comment]
I consider any changes to the dcraw results to be significant and should be fixed before merging. Please do bring up any other issues as soon as they are discovered.

**Comment by Lawrence37** [comment]
I will merge this soon. If there are any concerns or issues, please let me know so they can be addressed before the release.

**Comment by 0fbcb238c0** [comment]
@Lawrence37 
Did you build LibRaw with adobesdk for DNG version 1.7 with JPEG XL compression?

**Comment by Lawrence37** [comment]
You mean the Adobe DNG SDK? I have not.

**Comment by 0fbcb238c0** [comment]
Would you be able to do so? Otherwise raw images with JPEG XL compression following the DNG 1.7 spec cannot be opened by RawTherapee.
I will gladly provide a DNG if needed.
Thanks

**Comment by Lawrence37** [comment]
Are you asking for personal use or for it to be included in the official RawTherapee? If the former, I unfortunately have no need for such a feature so it's very low on my list of priorities. If the latter, I was not able to find the license for Adobe DNG SDK. Therefore, I have no idea if we are allowed to use it.

**Comment by 0fbcb238c0** [comment]
I am asking for it to be included in the official RawTherapee since DNGs with JPEG XL compression are slowly becoming more common.
The license can be found [here](https://www.adobe.com/support/downloads/dng/dng_sdk_eula_win.html) on adobe's website.
No idea whether this license makes inclusion possible or not.

**Comment by Benitoite** [comment]
For the DNG SDK: https://scancode-licensedb.aboutcode.org/adobe-dng-spec-patent.html
For the DNG Patent: https://scancode-licensedb.aboutcode.org/adobe-dng-sdk.html

Adobe is part of the GPL Cooperation Commitment https://gplcc.github.io/gplcc/
which indicates enforcement compliance with GPLv3.

**Comment by nomar500** [comment]
Hi, 
I saw this case and that one: https://github.com/Beep6581/RawTherapee/pull/7132
I'm now struggling when attempting to compile on my M1 mac.

This is what I get: 
```
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Release
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'gtk+-3.0>=3.24.3'
--   Found gtk+-3.0, version 3.24.43
-- Checking for module 'gtkmm-3.0>=3.24'
--   Found gtkmm-3.0, version 3.24.9
-- Checking for module 'glib-2.0>=2.48'
--   Found glib-2.0, version 2.80.4
-- Checking for module 'glibmm-2.4>=2.48'
--   Found glibmm-2.4, version 2.66.7
-- Checking for module 'cairomm-1.0'
--   Found cairomm-1.0, version 1.14.5
-- Checking for module 'gio-2.0>=2.48'
--   Found gio-2.0, version 2.80.4
-- Checking for module 'giomm-2.4>=2.48'
--   Found giomm-2.4, version 2.66.7
-- Checking for module 'gthread-2.0>=2.48'
--   Found gthread-2.0, version 2.80.4
-- Checking for module 'gobject-2.0>=2.48'
--   Found gobject-2.0, version 2.80.4
-- Checking for module 'sigc++-2.0>=2.3.1'
--   Found sigc++-2.0, version 2.10.8
-- Checking for module 'lensfun>=0.2'
--   Found lensfun, version 0.3.4.0
-- Checking for module 'librsvg-2.0>=2.52'
--   Found librsvg-2.0, version 2.58.2
-- Checking for module 'exiv2>=0.24'
--   Found exiv2, version 0.28.3
-- searching for library exiv2 in /opt/homebrew/Cellar/exiv2/0.28.3/lib
--   result: /opt/homebrew/Cellar/exiv2/0.28.3/lib/libexiv2.dylib
-- Checking for module 'lcms2>=2.6'
--   Found lcms2, version 2.16
-- Checking for module 'expat>=2.1'
--   Found expat, version 2.2.8
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.10
-- Checking for module 'libiptcdata'
--   Found libiptcdata, version 1.0.4
-- Found TIFF: /opt/homebrew/lib/libtiff.dylib (found suitable version "4.6.0", minimum required is "4.0.4")
-- Found JPEG: /opt/homebrew/lib/libjpeg.dylib (found version "80")
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libz.tbd (found version "1.2.12")
-- Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.43")
-- Checking for module 'libjxl'
--   Found libjxl, version 0.10.3
-- Checking for module 'libjxl_threads'
--   Found libjxl_threads, version 0.10.3
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
-- Binutils version detected as less than 2.29 - setting CMake parameters to enable LTO linking:
    CMAKE_AR="/usr/bin/ar"
    CMAKE_RANLIB="/usr/bin/ranlib"
-- Found OpenMP_C: -Xpreprocessor -fopenmp /opt/homebrew/lib/libomp.dylib -I/opt/homebrew/include (found version "5.0")
-- Found OpenMP_CXX: -Xpreprocessor -fopenmp /opt/homebrew/lib/libomp.dylib -I/opt/homebrew/include (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- Performing Test _fftw3f_multithread
-- Performing Test _fftw3f_multithread - Failed
-- searching for library lensfun in /opt/homebrew/Cellar/lensfun/0.3.4/lib
--   result: /opt/homebrew/Cellar/lensfun/0.3.4/lib/liblensfun.dylib
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY
-- Performing Test LENSFUN_HAS_LOAD_DIRECTORY - Success
-- Configuring LibRaw
'cp' '-p' '-R' '/Users/cynamon/programs/code-rawtherapee/rtengine/libraw' '.'
'/bin/zsh' '-l' '-c' 'autoreconf -v --install'
zsh:1: command not found: autoreconf
CMake Error at rtengine/LibRaw.cmake:51 (message):
  Could not generate LibRaw configuration script
Call Stack (most recent call first):
  rtengine/CMakeLists.txt:268 (include)


-- Configuring incomplete, errors occurred!
make: *** No rule to make target `install'.  Stop.
```

- Is this related to this PR? 
- What should I do about the compilation to make it functional again?

I suppose I'm missing some flags in here:

```bash
#!/bin/bash

mkdir -p build 
cd build
pwd
sudo rm -r *

which brew || exit 2

eval $(/opt/homebrew/bin/brew shellenv)

local_prefix="$(brew --prefix)" 

cmake -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_OSX_ARCHITECTURES="arm64" \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=14.5 \
      -DPROC_TARGET_NUMBER="2" \
      -DCACHE_NAME_SUFFIX="5.10-dev" \
      -DPROC_LABEL="arm64" \
      -DOSX_DEV_BUILD="ON" \
      -DWITH_LTO="ON" \
      -DCMAKE_C_COMPILER="clang" \
      -DCMAKE_CXX_COMPILER="clang++" \
      -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" \
      -DLOCAL_PREFIX:STRING="${local_prefix}" \
      -DLENSFUNDBDIR="/Applications/RawTherapee.app/Contents/Resources/share/lensfun" \
      -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG=1 -I${local_prefix}/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -Wno-pass-failed -arch arm64 -Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11" \
      -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG=1 -I${local_prefix}/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -Wno-pass-failed -arch arm64 -Wno-deprecated-register -Wno-unused-command-line-argument" \
      -DCMAKE_EXE_LINKER_FLAGS="-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch arm64" \
      -DOpenMP_C_FLAGS="-fopenmp=lomp" \
      -DOpenMP_CXX_FLAGS="-fopenmp=lomp" \
      -DOpenMP_C_LIB_NAMES="libomp" \
      -DOpenMP_CXX_LIB_NAMES="libomp" \
      -DOpenMP_libomp_LIBRARY="${local_prefix}/lib/libomp.dylib" \
      -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp ${local_prefix}/lib/libomp.dylib -I${local_prefix}/include" \
      -DOpenMP_CXX_LIB_NAMES="libomp" \
      -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp ${local_prefix}/lib/libomp.dylib -I${local_prefix}/include" -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -DFANCY_DMG:BOOL=ON \
      -DOSX_NIGHTLY:BOOL=OFF \
      -DOSX_UNIVERSAL:BOOL=OFF \
      -S .. 

make -j$(sysctl -n hw.ncpu) install && sudo make macosx_bundle
```

Thanks for your feedback.

**Comment by Benitoite** [comment]
@nomar500 

> zsh:1: command not found: autoreconf

There are two additionally required build-time dependencies.  automake and libtool

`brew install automake libtool`

**Comment by 0fbcb238c0** [comment]
@Lawrence37 
According to Alex Tutubalin, a member of LibRaw LLC and one of the main contributors to libraw, the DNG SDK is BSD licensed.
See last comment in [this thread](https://www.libraw.org/node/2787)

**Comment by Lawrence37** [comment]
Hmm... that contradicts the license in the link from your previous comment. If it is BSD, there is more than one BSD license.

**Pull request merged**
