### PR TITLE
GitHub Action for building AppImage

### PR DESCRIPTION
**Pull request by Lawrence37**
This is meant as a secondary way to build AppImages in case the official build is not working.

### CODE REVIEW

**Comment by Lawrence37** [comment]
The GitHub Action is automatically triggered every time `dev` is updated or a pull request against `dev` is updated. It can also be manually triggered on any branch. It is not meant to be a replacement for the automated nightly builds and has several differences/issues:

* The AppImage people [recommend](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#creating-appimages-that-are-compatible-with-many-systems) building on an old operating system to maximize compatibility. The official AppImages are built in CentOS 7 (released in 2014). GitHub Actions for Linux can only be run on still-supported Ubuntu LTS releases. Currently, the oldest is 18.04 which was released in 2018. A workaround could be to build the AppImage in a Docker container (the Travis CI builder does this).
* This is my first time building AppImages. The script is shorter than the Travis CI one. I may have missed something important although everything seems to work alright.
* I'm seeing an issue with the RawTherapee themes where some widgets are outlined in white. For some reason, the official AppImage doesn't run on my computer, so I don't know if this problem is due to the way I'm packaging the AppImage. The TooWa* themes have no issue.
* The cache directory is `5-<branch>-AppImage`. The official AppImage uses `5-<branch>-ai`.
* Everything, including the configuration, build scripts, and outputs, are in this repository. Downloads are accessed after choosing a successful build run from https://github.com/Beep6581/RawTherapee/actions/workflows/appimage.yml.

**Comment by Thanatomanic** [comment]
Great to see @Lawrence37! I'll try to find some time the coming days to test it and provide some feedback.

**Comment by ghost** [comment]
@Lawrence37 

Not sure if  you are aware of the following (might this be on purpose for now?): The produced appimage is only downloadable when you are logged in.

---

This appimage does run nicely on my Debian box.

I do see the following in the terminal, but it doesn't seem to have any negative effect:

> /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
> Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
> /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
> Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so

---

BTW: Nice initiative and a very welcome (fallback) addition to the nightly builds!

**Comment by Lawrence37** [comment]
Library issues usually prevent AppImages from starting up at all. This one seems to be optional. I can't find much information about GIO volume monitor, but it looks like it's not used in RawTherapee. I hope that is the case.

Nice catch on the download issue. I will see if I can create a "release" and add the dev AppImage as an asset. That way, it will be the same as the nightly builds. I'll keep the artifacts on the GitHub Actions page so that anyone who is signed in can download older versions as well as builds from pull requests.

**Comment by ghost** [comment]
> I'll keep the artifacts on the GitHub Actions page so that anyone who is signed in can download older versions

Please do, that would be a nice-to-have.

**Comment by Lawrence37** [comment]
I've added an additional step in the workflow to publish the AppImage to [a release](https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions). This is only done for the `dev` branch (to reduce clutter from all future PRs). No AppImages will be available for download there until this is merged because the `dev` build cannot be triggered until then.

**Comment by Lawrence37** [comment]
I will (squash) merge this shortly. There are no code changes and any issues can be resolved with a new PR.

**Comment by Thanatomanic** [comment]
Hi @Lawrence37 so much thanks for this! One small request (I could make a separate issue if it turns out not very small): can you include the version number in the asset name? I think that would help people to figure out what build they are downloading. This has also been common practice for the unofficial builds by Andre and our own.

**Comment by Lawrence37** [comment]
I considered adding the version to the file name. The reason I left it out was because the workflow needs some extra steps to remove the old file. By leaving out the version, the AppImage is automatically replaced because the file name is the same. I don't know how complicated the logic would be to remove the old AppImage, but it should be doable.

FYI, there is a text file containing the version.

**Pull request merged**
