### PR TITLE
Local adjustments - Blur and noise radius > 1.5 increase saturation issue #6117

### PR DESCRIPTION
**Pull request by Desmis**

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 
Ingo

Could you review ? :)

Thank you

Jacques

**Comment by Desmis** [comment]
@heckflosse  @Lowkus

I re-enable a slider I have hide (to simplify)...: scalegr

All the code "grain" come from Darktable  (ported by ART)

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I will review in the evening.

**Comment by heckflosse** [comment]
@Desmis I didn't review yet. I viewed the livestream of mars landing instead. Will review tomorrow.

**Comment by heckflosse** [comment]
@Desmis Jacques, unless I'm doing something wrong, the issue is not fixed.
Left Radius 1.6, right Radius 1.5
grafik

**Comment by Desmis** [comment]
@heckflosse 
I don't understand !

Can you give me your raw and pp3

Jacques

**Comment by heckflosse** [comment]
Here's the raw
http://rawtherapee.com/shared/test_images/clematis_vitalba.nef

and the pp3
[clematis_vitalba.nef.pp3.zip](https://github.com/Beep6581/RawTherapee/files/6009551/clematis_vitalba.nef.pp3.zip)

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I am confused....the commit was not the good....
I missed some brackets....that were on my version, on my computer... and not on Github...

I think now it's solved... I hope  :)

Jacques

**Comment by heckflosse** [comment]
Fix confirmed. :+1: for merge

**Comment by Desmis** [comment]
I just merge 
Thank you

but I'm a little bit head over heels  :)

jacques

Jacques

**Pull request merged**
