### PR TITLE
Various improvment to Local adjustments

### PR DESCRIPTION
**Pull request by Desmis**
These improvments are sommary
* mask and curve Hue for denoise local
* curve hue and Local contrast for "Guided Filter"
* fixed bug Hide show for common mask
* fixed bad behavior when opening   "dynamic range compression  and exposure"
* simplify GUI
* best labels and tooltips
* change combobox by checkbox in settings
* etc.

### CODE REVIEW

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Could  you have a look ?

Thank you

Jacques

**Comment by heckflosse** [comment]
@Desmis 

> Could you have a look ?

Jacques, I will have a look tomorrow.

**Comment by Desmis** [comment]
@heckflosse 
Ingo, thank you very much :)

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, I will need some time because for example https://github.com/Beep6581/RawTherapee/pull/5903/commits/5bb1efd334c9cb1a34c640455ba92cbb09872a59 has a lot of code formating changes which makes it really hard to find the relevant code changes...

**Comment by Desmis** [comment]
@heckflosse 

Ok I understand: sorry for formatting the code, but it becomes unreadable  :)

jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo

To help you, In iplocallab.cc main changes are near
* for Guidedfilter : lines 10590 - 10913
* for denoise : lines 8630 - 8687  and 9200 - 9283

Sorry 

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, can you please also post a .pp3 to test?

**Comment by Desmis** [comment]
@heckflosse 
Here a pp3 with a file from Andy 

This pp3 allows mask (build in mask and modifications - smooth blur and denoise) to improve denoise in flat areas

In this case, I don't use "Hue curve", and I push sope to 100, in order to allow to see the action of the mask and only the mask

I think we can geatly improve memory usage with "noisevalum", "noisevarmask" and "noisevarhue"...But it does not change the result

Good afternoon

Jacques


[_D4D1775.NEF (1).txt](https://github.com/Beep6581/RawTherapee/files/5179548/_D4D1775.NEF.1.txt)

**Comment by heckflosse** [comment]
I applied your .pp3 to a D850 NEF and got a segfault in full (queue) processing. Making debug build now...
Please don't commit to this branch today

**Comment by heckflosse** [comment]
@Desmis Jacques, can you pleast test my commit before I continue with review?

**Comment by heckflosse** [comment]
@Desmis Jacques for my review I applied this pp3
[Nikon - D850 - 14bit compressed (Lossless) (3_2).NEF.pp3.txt](https://github.com/Beep6581/RawTherapee/files/5179704/Nikon.-.D850.-.14bit.compressed.Lossless.3_2.NEF.pp3.txt)
 to [this raw](https://raw.pixls.us/getfile.php/1840/nice/Nikon%20-%20D850%20-%2014bit%20compressed%20(Lossless)%20(3:2).NEF):

The peak memory usage when processing this in queue is ~12 GB. Way too much imho. I will have a look whether this can be reduced. Please don't try on your 8GB machine ;-)

**Comment by Desmis** [comment]
@heckflosse 
Ingo

I comme back from the beach :)

Well seen for the segfault...and its solution...as always !

For memory peak, I think we can with no problem (if it is the cause...) change maxlevel for denoise from 7 to 6, it must be enough...except if you have another solution

This change must be done in iplocallab.cc and of course in Ftblockdn.cc

jacques

**Comment by Desmis** [comment]
@heckflosse 

I test with the Andy file
All seems to work well :)
With this image I have a peak at about 5.6GB

Thank you

Jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing. I will try to improve memory usage and processing time. Give me at least two days

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Thank you, no problem for waiting :)

I just made more test, and I see a difference between "preview" (where I see clearly the incidence of the mask), and TIF where difference mask / no mask are small...Perhaps a problem between GW, bfw, bfw2, GW2 ?

Thank you 

jacques

**Comment by heckflosse** [comment]
@Desmis 
>Perhaps a problem between GW, bfw, bfw2, GW2 ?

Yes, we should have a look a that. My segfault fix might be wrong...

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I think the problem is (for a part) and maybe it's not enough
Replace  at begining after "if (call == 2)  and also after in the code  with "yEn", "xEn", and in Denoise_local

       //     int bfh = int (lp.ly + lp.lyT) + del; //bfw bfh real size of square zone
       //     int bfw = int (lp.lx + lp.lxL) + del;
            
        const int ystart = rtengine::max(static_cast<int>(lp.yc - lp.lyT) - cy, 0);
        const int yend = rtengine::min(static_cast<int>(lp.yc + lp.ly) - cy, original->H);
        const int xstart = rtengine::max(static_cast<int>(lp.xc - lp.lxL) - cx, 0);
        const int xend = rtengine::min(static_cast<int>(lp.xc + lp.lx) - cx, original->W);
        const int bfh = yend - ystart;
        const int bfw = xend - xstart;
        int begy = ystart; //lp.yc - lp.lyT;
        int begx = xstart; //lp.xc - lp.lxL;

I think to verify, it works, and also reduce memory usage (by reducing bfw, bfh..)

have a good day  :)

jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo


For your information, I created the "localdenois" branch where I promote the work done with Wayne Sutton on labels and tooltips (big work).

In addition I changed "denoise" (TIF / JPEG), now the mask works, and the reduction in memory requirement is around 30% .... Of course we must be able to do much better by separating the decompositions  :). 
On your D850.Nef memory requirements is more than 8GB...

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, how can I trigger this case?
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/iplocallab.cc#L8133

**Comment by Desmis** [comment]
@heckflosse 

Ingo

it is enable when "Detail threshold Luminance Chroma (DCT ƒ)  > 0"

I hope this help


jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Can I push a change in "DEV"

It concern **"Labels and tooltip"** and a **bug** in iplocalalb.cc for Color and light curve HH
I replace -
 const float valparam = float ((lochhCurve[500.f * Color::huelab_to_huehsv2(hhforcurv)] - 0.5f));  //get H=f(H)
by
 const float valparam = 2.f * float ((lochhCurve[500.f * Color::huelab_to_huehsv2(hhforcurv)] - 0.5f)) + static_cast<double>(hhforcurv);

And of course nothing else :)
Thank you

Jacques

**Comment by heckflosse** [comment]
@Desmis 
>Can I push a change in "DEV"
It concern "Labels and tooltip" and a bug in iplocalalb.cc for Color and light curve HH
I replace -
const float valparam = float ((lochhCurve[500.f * Color::huelab_to_huehsv2(hhforcurv)] - 0.5f)); //get H=f(H)
by
const float valparam = 2.f * float ((lochhCurve[500.f * Color::huelab_to_huehsv2(hhforcurv)] - 0.5f)) + static_cast(hhforcurv);
And of course nothing else :)

Jacques, feel free to push this. As long as it does not increase memory usage to huge amounts (which I don't think it will do), just do it ;-)

In your other branch, I still try to reduce memory usage btw... but it will take a while...

Ingo

**Comment by Desmis** [comment]
@heckflosse 

Push commit done :)

Than you

And no problem to wait...  :)

jacques

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I just push 2 changes (found in branch localdenois) . These 2 bugs lead to bad behavior of gUI for mask common and bad results for exposure in some cases

The 2 conflicts are very easy to solve...
I prefer to leave your hand on this branch

Thank you by advance  for your work on denoise :+1: 

jacques

**Comment by Beep6581** [comment]
@Desmis is the intention still to merge this PR?

**Comment by Desmis** [comment]
@Beep6581 

No, there are no plans to merge this PR.
Everything in this branch was either commit or PR related.

I kept this PR open, as a memory aid, not to forget that Ingo @heckflosse has planned to improve memory management in LA Denoise (planned in 6.0?) - even if the memory requirement has already been reduced a little bit.

:)

Jacques

**Comment by Thanatomanic** [comment]
> I kept this PR open, as a memory aid, not to forget that Ingo @heckflosse has planned to improve memory management in LA Denoise (planned in 6.0?) - even if the memory requirement has already been reduced a little bit.

This is much better addressed in an issue regarding the memory usage which is then assigned to Ingo. If this is worthwhile, can you make that @Desmis ?
 Closing this PR.

**Comment by Thanatomanic** [comment]
@Desmis Please also decide if you want to delete the `localgflc` branch or keep it.

**Pull request closed without merging**
