### PR TITLE
Clip negative values to zero in raw processing, #5561

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Review by Floessie — APPROVED** [review]
Fine codewise. :+1: 

Maybe the different `max()` and `min()` calls in `rawimagesource.cc` should be unified while you're at it (theres are even `MAX()` calls, whereever that comes from).

I've tested all demosaicers with an HDRMerged DNG and couldn't spot any obvious outliers.

**Comment by heckflosse** [comment]
@Floessie 
> MAX() calls, whereever that comes from

<glib/gmacros.h>

**Comment by Beep6581** [comment]
I compared `dev` vs `review_demosaicers` using 61 test images and various PP3s. There were no visual differences. When using `compare` (imagemagick) the differences ranged from none to this:
screenshot_20191213_160717
(red means there is a difference, though it was only numerical - cannot see any difference in these images with my eyes)

**Comment by Beep6581** [comment]
No problem with unclipped.

**Review by Beep6581 — APPROVED** [review]

**Pull request merged**
