### PR TITLE
Fix for some Lensfun corrections not available

### LINKED ISSUE #5530: Lens corrections for Panasonic 42.5mm f/1.7 are not available
When opening an image that was shot with the Panasonic 42.5mm f/1.7, the corrections for geometric distortion and chromatic aberration are not available (this happens with the two cameras I have: the Panasonic G80 and the GX80). The lens is recognised, but the correction checkboxes are greyed out. Also, a warning tooltip is shown next to the "manually selected" part, with the text "Warning: the crop factor used for lens profiling is larger than the crop factor of the camera, the results might be wrong." I am not sure whether this warning is related to the unavailability of the lens corrections, but I thought I'd tell it just in case it's relevant. The issue is illustrated in this screenshot:

Schermafdruk van 2019-11-18 13-21-47

Interestingly, when opening an image taken with the 42.5mm and applying the "Auto-Matched Curve - ISO Low" profile, the lens corrections *are* applied. But then when I make any change (such as tweaking the white balance), the image reverts back to the uncorrected view. When I apply the "Neutral" profile, the lens corrections are not applied, and I have no way to apply them. I have attached the RAW file that is being developed in the screenshot above: [20191117_210313.RW2.zip](https://github.com/Beep6581/RawTherapee/files/3858466/20191117_210313.RW2.zip)

I am using RawTherapee version 5.7 from the AppImage (but this issue happened in earlier versions too):
```
Version: 5.7
Branch: releases
Commit: f335efe
Commit date: 
Compiler: cc 7.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11  -Werror=unused-label -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
```

I am on Debian 10 (buster): `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

I have run `lensfun-update-data` to make sure the latest version of the Lensfun database is used. The issue does not occur with any of the other lenses I have.

### PR DESCRIPTION
**Pull request by Lawrence37**
There's a possible bug in Lensfun which prevents it from matching certain lenses such as the Panasonic Lumix G 42.5mm f/1.7. I've added an additional lens search that does an exact match with the lens make and name.

Closes #5530.

### CODE REVIEW

**Comment by kmilos** [comment]
> There's a possible bug in Lensfun

Please report upstream?

**Comment by Beep6581** [comment]
Please merge ASAP if for 5.10.

**Comment by Lawrence37** [comment]
Putting this on the v6.0 milestone to get more testing done.

**Comment by Lawrence37** [comment]
Lensfun bug causing this issue: https://github.com/lensfun/lensfun/issues/2052
The lenses that cannot be found by looking up their model name directly are:
- Panasonic Lumix G 42.5mm f/1.7
- Samyang 12mm f/3.1 VDSLR ED AS NCS Fish-eye

Additionally, Lensfun returns the wrong lens for several other models. This pull request fixes all lens identifications if they are manually chosen. Automatic detection may or may not work depending on the lens model extracted from the metadata and how Lensfun behaves.

**Comment by Lawrence37** [comment]
The bug also affects camera selection. The latest commit works around the problem.

**Pull request merged**
