### PR TITLE
Local adjustments - Chromaticity curve C(h)

### PR DESCRIPTION
**Pull request by Desmis**
Fixed bad behavior.
https://discuss.pixls.us/t/problem-color-local-adjustment-cromaticity-curves/42345

Jacques

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 
For the sake of principled rigor, can you validate this PR. The error which must date from more than 5 years ago is just one coefficient too many (2.f)

Thank you

Jacques

**Comment by Lawrence37** [comment]
Why was it multiplied by 2? Could the problem be missing parentheses? I think it makes sense to have the expression be `2 * (x - 0.5)`. If `x` is in the range [0, 1], then the expression evaluates to the range [-1, 1] which corresponds to a chroma adjustment from -100% (complete desaturation) to +100% (double the chroma).

**Comment by Desmis** [comment]
@Lawrence37 
This is simply an error on my part. This code must have been around 9 years old. 
As you said elsewhere, the evaluation of Local Adjustments  (it is only today that someone spotted this anomaly) and its improvements are only at the beginning

Thank you

Jacques

**Comment by Lawrence37** [comment]
I'm thinking there was a reason for multiplying by 2. It makes sense to have an adjustment range from -100% to +100%. In this PR, the range is -50% to +50%. There is no problem with that. I just wonder what the original intent was.

**Comment by Lawrence37** [comment]
@Desmis I'm ok with the current pull request, or you can add the 2x multiplication. Your choice.

**Pull request merged**
