### PR TITLE
Modifications to store histogram settings across sessions

### LINKED ISSUE #4749: Store histogram settings across sessions
Hi,

Related to PR #4618 I tested with master commit 5471b34a

There is an issue with the new histogram state memorization. Here are the steps:
- enable luminance histogram
- restart RT
- luminance is again disabled, but should stay enabled.

Other params seems correctly saved.

Thank’s !

Exact build version info:
Version: nightly-556-g5471b34a
Branch: dev
Commit: 5471b34a
Commit date: 2018-08-23
Compiler: x86_64-pc-linux-gnu-gcc 8.2.0
Processor: Intel(R)\ Core(TM)\ i5-4690\ CPU\ @\ 3.50GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Gentoo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11  -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON

### PR DESCRIPTION
**Pull request by Thanatomanic**
This should fix #4749 and store all histogram related sessions in `options`.
Please check for silly stuff.

### CODE REVIEW

**Comment by Thanatomanic** [comment]
Can we merge this?

**Comment by Thanatomanic** [comment]
Wait.. @Beep6581 How did I manage to merge this, when I don't think I ever clicked on Merge? I did merge #4771 though...

**Comment by Beep6581** [comment]
@Thanatomanic psychokinesis? ;)

Tested `5.4-816-g`ea992fc91. I opened RT, opened an image in SETM-VT mode, hid all of the histograms, hid the RGB indicator bar, showed the chroma histogram and set log-log mode. I restarted RT, opened the test image in SETM-VT, and now the red, green and blue histograms were visible but not chroma - bug. It did correctly remember the log-log mode and the RGB bar being hidden.

**Comment by Beep6581** [comment]
Sooo... One cannot simply checkout `thanatonic/histogram-settings` and merge that into `dev`, because then nothing happens, nothing is merged. I guess the reason for that is subsequent revert commit. So in order to test this branch, assuming one added `thanatonic` as a remote, one must:
```bash
git checkout dev
git cherry-pick thanatonic/histogram-settings
```

**Comment by Beep6581** [comment]
I found no issues with the patch, +1 to merge into `dev`.

**Pull request merged**
