### PR TITLE
Local adjustments - Fix apply/paste actions with LA

### PR DESCRIPTION
**Pull request by Pandagrapher**
The Pull Request fixes the following issues:
- Fixes LA lost when applying partial profile (#6150)
- Fixes LA behavior when using apply/paste actions: spots are now totally replaced and not anymore merged (#6136, #6411)
- Fixes a crash in specific situations when saving/copying a partial number of spots
- Partial paste dialog: Fixes Locallab button remaining inconsistent if all the spots are deselected

@jade-nl @Lawrence37 @epadepa

### CODE REVIEW

**Comment by ghost** [comment]
Ah, good to notice that this one is being picked up!

I just merged, build and tested your PR: This does not, however, fix #6411.

If I repeat the exact steps shown in 6411 I end up with the same unwanted result: Double entries, old and new, were I expect the current ones to be overwritten by the newly imported ones.

**Comment by Pandagrapher** [comment]
@jade-nl Thanks for your testing. However I just tested again and I cannot reproduce the issue #6411 with this PR. Are you sure you have the `f3d7f6a` commit? (because the `6a03d57` one was only fixing the issue during copy/paste actions)

**Comment by ghost** [comment]
@Pandagrapher : Apologies! Problem is found on my side of things.

Turns out that I made a typo which was not picked up by my semi-automated merge/build script (script is now fixed....).

(Correctly) Merged, build and tested your changes: Works nicely and this fixes #6411

Thanks for the time and effort.

PS: Although the other fixed issues aren't mine I'll test those as well. Will be later today or maybe during the upcoming weekend.

**Comment by ghost** [comment]
Tested and this PR also fixes #6136 on my side of things.

@arturoisilvia mentions the following as an expected result: _They should not be or be off._

The actual result is that the situation is restored to what is in the loaded pp3 file (amount of tools, status etc.). All else present is removed (the *not be* part).

---

Tested #6150 as well: Also fixed on my side: Local Adjustment spots are _not removed_ when using fill mode set to *preserve (partial)* and they _are removed_ when mode is set to *fill*.

---

All test were done on Linux (Debian).

**Comment by Pandagrapher** [comment]
@jade-nl Thanks for all your testings

If no one objects, I gonna merge the PR tomorrow

**Pull request merged**
