### PR TITLE
Fix wrong suffix in `SaveAsDialog` (#4446)

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

this is the patch from #4446 now as a PR:

1. Fix the "double extension" warning I broke in b84e570.
2. Change suffix on format change.

Best,
Flössie

### CODE REVIEW

**Comment by Floessie** [comment]
@TooWaBoo AFAIK, you already merged this branch into your fork. Is it working like you would expect it to work, or is there something that should be changed?

**Comment by Beep6581** [comment]
@Floessie I tried to break it and tried various combinations of valid extensions, such as `.jpg`/`.jpeg` and `.tif`/`.tiff`, and found no issues.

**Review by Beep6581 — APPROVED** [review]
I found no issues, +1 for merge, and thank you for fixing it!

**Comment by Floessie** [comment]
@TooWaBoo Sorry, DrSlony was faster. :wink:

**Pull request merged**
