### PR TITLE
Use `_WIN32` instead of `WIN32` to detect Windows

### PR DESCRIPTION
**Pull request by ss23**
`WIN32` is not defined when building a 64-bit executable on Windows with Clang. `_WIN32` is the more appropriate option here.

http://web.archive.org/web/20191012035921/http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system contains a handy table/matrix of the options and why this is best.

### CODE REVIEW

**Comment by Lawrence37** [comment]
`WIN32` is used in many other parts of the code besides `rtengine/mytime.h`. For example:
https://github.com/ss23/RawTherapee/blob/54fc69afe34989b4ec4ebae26b305e1142adadbb/rtengine/dynamicprofile.cc#L224

**Comment by ss23** [comment]
Right you are, @Lawrence37. I have gone through and updated all the cases where I believe it makes sense to do so now.

**Comment by Lawrence37** [comment]
I'm curious which ones don't make sense to update. Grep shows 141 instances of `WIN32`. About 10 of those are not relevant, so that leaves roughly 130. So far you've changed 96 of them.

**Comment by ss23** [comment]
Sorry @Lawrence37, I missed a bunch of them still. I did a grep for `ifdef` and `defined(` but not `ifndef`. I've now searched for just `[^_]WIN32`, so hopefully got all of them this time... The main one I was thinking of as not relevant is the check in `cJSON.h` and the cmake related files.

It's times like these I'm glad that other people can review my changes and I don't have direct commit access :)

**Comment by Lawrence37** [comment]
Ok, that makes sense.

**Review by Lawrence37 — APPROVED** [review]
Looks good to me

**Pull request merged**
