### PR TITLE
dcraw.cc: Fix bug for tiff_ifd.new_sub_file_type

### LINKED ISSUE #6682: DNG decoding regression
# Bug Report:
To get around the problems with CR3 files I converted my RAWs to DNG with Adobe DNG Converter (probably Version 14.4.0.1121). When imported in RT 5.8 (with imported Profiles for the Canon R6 and the Eos R lenses) the picture loads fine. When opened in 5.9 the picture gets corrupted as shown in the jpg. this error happend to me several other times in the experimental versions last year in August/September, but I didn't get around to report those. 
When opening the original CR3 or a new converted DNG (with an older Version of Adobe DNG (version not recorded, possibly 14.3)) of the same RAW in 5.9 I don't get the error. When reconverting with the newest Version of Adobe DNG Converter (15.2.0.1381) the same corruption occurs.

When opening the file after again in 5.8 the picture shows normal.
Opening the file on a different device (Windows 10) in 5.9 nets the same result as on the original computer.

### Files
[corrupted.zip](https://github.com/Beep6581/RawTherapee/files/10725063/corrupted.zip)
[new convertion.zip](https://github.com/Beep6581/RawTherapee/files/10725065/new.convertion.zip)
[original.zip](https://github.com/Beep6581/RawTherapee/files/10725073/original.zip)
[corrupted_jpg.zip](https://github.com/Beep6581/RawTherapee/files/10725136/corrupted_jpg.zip)

#### Edit 13-02: 
added further pictures with same error:
[converted-3.zip](https://github.com/Beep6581/RawTherapee/files/10725404/converted-3.zip)
[new_conversion-3_14-4.zip](https://github.com/Beep6581/RawTherapee/files/10725410/new_conversion-3_14-4.zip)
[original-2.zip](https://github.com/Beep6581/RawTherapee/files/10725420/original-2.zip)
[original-3.zip](https://github.com/Beep6581/RawTherapee/files/10725422/original-3.zip)
[converted-2.zip](https://github.com/Beep6581/RawTherapee/files/10725398/converted-2.zip)
[new_conversion-2_14-4.zip](https://github.com/Beep6581/RawTherapee/files/10725408/new_conversion-2_14-4.zip)

### Windows Version:
Windows 10 22H2 19045.2486

### Version of RT 5.8:
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

### Version of RT 5.9:
Version: 5.9
Branch: 5.9
Commit: 9b8583988
Commit date: 2022-11-27
Compiler: cc 12.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.6-341.x86_64 x86_64
Build date: Sun, 27 Nov 2022 18:38:56 +0000 UTC
Build epoch: 1669574336
Build UUID: 9d19d210-c668-4aa2-8af6-2d527fd55d1c

### LINKED ISSUE #6747: Support Smartphone OPPO Find X3 Pro Camera
Hi,

I can't open dng photos from my Smartphone so i uploaded photos from OPPO Find X3 Pro in dng format. I hope these photos are enough for getting support.

https://filebin.net/u8d5kimbof7g2y3k

### PR DESCRIPTION
**Pull request by SimonSegerblomRex**
Fixes #6682
Fixes #6747

### CODE REVIEW

**Comment by SimonSegerblomRex** [comment]
Do you think this will work @sgotti? (Or is there any risk of regressing bd118a4a40cd67f6d2e48db5655bd11d3aac0ff8?)

**Comment by SimonSegerblomRex** [comment]
I think it's safe to merge this. Is there any way to retrigger the build that timed out?

**Comment by Lawrence37** [comment]
You'll need to merge with dev to update the workflow file which uses the Ubuntu 20.04 runner instead of Ubuntu 18.04 which is no longer available.

**Comment by SimonSegerblomRex** [comment]
Fixes #6747 as well

**Review by Lawrence37 — APPROVED** [review]
Using the steps described in #6443 to generate the DNG, I can confirm the wrong black levels are used by 5.8, correct in 5.9, and still correct in this branch. The images provided in the two linked issues open correctly too.

**Comment by Lawrence37** [comment]
Merged. Thanks for the fix @SimonSegerblomRex!

**Pull request merged**
