### PR TITLE
Some checkpoints in the startup of RT to measure bottlenecks

### PR DESCRIPTION
**Pull request by Thanatomanic**
**Please do not merge with `dev`.**

_(maybe I should have made a branch instead of a PR..? My git magic fails me...)_

This is only to get some input from others on their startup times for RT. Personally I am quite unhappy that I have to wait ~7 seconds before everything I see a screen with pictures (see #5055 as well). So I went and investigate a little bit where the bottlenecks are.

**Could others please show what their command line results are when starting up?**
Mine are as follows (MinGW64, MYS2 on Windows 10):

```
Roel@RPC MINGW64 ~/rtdev/build
$ ./release/rawtherapee
Done everything before loading options - 1.621000
Done loading options - 714.177979
Done gtk_init - 564.547974
Start making RTWindow
Done first steps - 1.848000
Done loading theme - 81.649002
Done rest until init mainNB - 3.842000
Done mainNB->append_page (*fpanel, *fpanelLabelGrid); - 934.763000
Done mainNB->append_page (*bpanel, *lbq); - 6.280000
Done mainNB->set_current_page (mainNB->page_num (*fpanel)); - 703.935974
Done even more steps !simpleEditor - 1.192000
Done pldBridge = new PLDBridge - 0.047000
Done add (*mainNB); - 124.635002
Done show_all (); - 4996.270020
Done bpanel->init - 0.662000
Done making RTWindow
```

Values are all in milliseconds.

First observations:
* Loading time is insensitive to the amount of images in the folder that opens.
* Turning on verbose mode doesn't change much
* Value of "Done loading options" can be reduced to ~130 ms when no flat-field or darkframe images have to be processed

### CODE REVIEW

**Comment by heckflosse** [comment]
@Thanatomanic I'm already compiling your branch. Will take a while.
From my experience, at least on Windows, a lot of processing time is needed to create the batch editor tab in filebrowser/filepanel.

**Comment by heckflosse** [comment]
@Thanatomanic You should fix the code. Currently it fails to build on linux because of `#include of mytime.h` not having correct case, which does not matter on windows.

**Comment by heckflosse** [comment]
@Thanatomanic 
Windows 7, with CLUT, FF and DF pointing to empty folders

in SETM
```
Done everything before loading options - 2.088000
Done loading options - 140.688004
Done gtk_init - 215.000000
Start making RTWindow
Done first steps - 0.564000
Done loading theme - 100.514999
Done rest until init mainNB - 4.453000
Done mainNB->append_page (*fpanel, *fpanelLabelGrid); - 1013.245972
Done mainNB->append_page (*bpanel, *lbq); - 15.113000
Done mainNB->set_current_page (mainNB->page_num (*fpanel)); - 829.684021
Done even more steps !simpleEditor - 1.278000
Done pldBridge = new PLDBridge - 0.071000
Done add (*mainNB); - 159.959000
Done show_all (); - 4254.986816
Done bpanel->init - 0.348000
Done making RTWindow
```

in METM
```
Done everything before loading options - 2.033000
Done loading options - 125.334000
Done gtk_init - 217.261993
Start making RTWindow
Done first steps - 0.548000
Done loading theme - 100.009003
Done rest until init mainNB - 4.681000
Done mainNB->append_page (*fpanel, *fpanelLabelGrid); - 1018.791016
Done mainNB->append_page (*bpanel, *lbq); - 15.304000
Done mainNB->set_current_page (mainNB->page_num (*fpanel)); - 0.105000
Done even more steps !simpleEditor - 1.290000
Done pldBridge = new PLDBridge - 0.058000
Done add (*mainNB); - 78.563004
Done show_all (); - 2402.712891
Done bpanel->init - 0.344000
Done making RTWindow
```

**Comment by gaaned92** [comment]
Windows 10, with CLUT, FF and DF pointing to empty folders

SETM

```
Done everything before loading options - 1.410000
Done loading options - 253.227005
Done gtk_init - 119,126999
Start making RTWindow
Done first steps - 0,912000
Done loading theme - 64,976997
Done rest until init mainNB - 2,844000
Done mainNB->append_page (*fpanel, *fpanelLabelGrid); - 678,906006
Done mainNB->append_page (*bpanel, *lbq); - 4,456000
Done mainNB->set_current_page (mainNB->page_num (*fpanel)); - 579,281006
Done even more steps !simpleEditor - 0,813000
Done pldBridge = new PLDBridge - 0,045000
Done add (*mainNB); - 95,764000
Done show_all (); - 3619,895996
Done bpanel->init - 0,448000
Done making RTWindow
```

METM

```
Done everything before loading options - 1.439000
Done loading options - 253.800003
Done gtk_init - 118,709000
Start making RTWindow
Done first steps - 0,917000
Done loading theme - 64,212997
Done rest until init mainNB - 2,868000
Done mainNB->append_page (*fpanel, *fpanelLabelGrid); - 670,958008
Done mainNB->append_page (*bpanel, *lbq); - 4,531000
Done mainNB->set_current_page (mainNB->page_num (*fpanel)); - 0,081000
Done even more steps !simpleEditor - 0,812000
Done pldBridge = new PLDBridge - 0,043000
Done add (*mainNB); - 46,959999
Done show_all (); - 1912,781006
Done bpanel->init - 0,448000
Done making RTWindow
```

@heckflosse wrote
`From my experience, at least on Windows, a lot of processing time is needed to create the batch editor tab in filebrowser/filepanel.`

That could explain why ART is  faster to start

**Comment by Thanatomanic** [comment]
FWIW: I know this PR has turned stale and even fails, but please keep it here for a while. It's a little reminder for me that I want to do something about this - if at all possible of course 😄

**Pull request closed without merging**
