### PR TITLE
Remove deprecated GTK3 code, fixes #6103

### LINKED ISSUE #6103: Replace deprecated GTK code
See https://developer.gnome.org/gtk3/stable/DeprecatedObjects.html. There are several instances where RT uses deprecated code. Before we step up to use GTK4 at some point in the future, it would be good to at least have no more legacy GTK3 code. 

- [x] GtkStyle — Deprecated object that holds style information for widgets [4 hits]
- [x] GtkHScale — A horizontal slider widget for selecting a value from a range [3 hits]
- [x] GtkHBox — A horizontal container box [100+ hits]
- [x] GtkVBox — A vertical container box [100+ hits]
- [x] GtkHPaned — A container with two panes arranged horizontally [4 hits]
- [x] GtkVPaned — A container with two panes arranged vertically [5 hits]
- [x] GtkTable — Pack widgets in regular patterns [18 hits]
- [x] GtkHSeparator — A horizontal separator [100+ hits]
- [x] GtkVSeparator — A vertical separator [50+ hits]
- [x] GtkHScrollbar — A horizontal scrollbar [1 hit]
- [x] GtkVScrollbar — A vertical scrollbar [1 hit]
- [x] Stock Items — Prebuilt common menu/toolbar items and corresponding icons [4 hits, Gtk::Stock]
- [x] ~~Themeable Stock Images — Manipulating stock icons [2 hits, Gtk::ICON_SIZE_BUTTON]~~ update only needed/possible when moving to `gtkmm4`

I'll soon create a branch to work on this.

Edit:
- [x] Figure out what is going on here, because the `PACK_SHRINK` inside the `VBox` looks really weird https://github.com/Beep6581/RawTherapee/blob/6454737d0ce48e8d1004018bdda347dd0526dd4c/rtgui/preferences.cc#L727

### PR DESCRIPTION
**Pull request by Thanatomanic**
See https://github.com/Beep6581/RawTherapee/issues/6103 for discussion. This removes deprecated `Gtk` elements and replaces them by their updated counterparts. In some cases this required a little more fiddling with the code, notable with `Gtk::Table` -> `Gtk::Grid` and whenever we have derived classes from `Gtk::VBox`.

Please test to see if you spot GUI elements that suddenly do not expand properly into the available room, or seem disoriented.

### CODE REVIEW

**Comment by heckflosse** [comment]
@Thanatomanic What a massive amount of work. Thanks :+1:. I will test tomorrow

**Comment by heckflosse** [comment]
@Thanatomanic Builds and works fine. :+1: for merge from me

**Comment by Lawrence37** [comment]
Looks fine to me.

**Comment by Beep6581** [comment]
I tested for an hour and found no fault. :+1: for merge.

**Pull request merged**
