### PR TITLE
Halide

### PR DESCRIPTION
**Pull request by bobobo1618**
Add Halide implementation of [IGD](http://www.eie.polyu.edu.hk/~enyhchan/J-JEI-Low_complexity_color_demosaicing_algorithm_based_on_IG.pdf)  (https://github.com/Beep6581/RawTherapee/issues/2934) to RawTherapee along with build system for generating the code.

### CODE REVIEW

**Comment by heckflosse** [comment]
@bobobo1618 : Thanks a lot for this work!!! There are some Issues to solve before merging (Some artifacts, allow to build on Windows and mac, maybe additional issues too). So we won't merge it at current state. But I'm willing to support you (if needed) to solve the remaining issues.

Ingo

**Comment by bobobo1618** [comment]
Mac works as is (that's what I develop using), Linux appears to require a couple of extra libraries to be linked (`-ldl -lpthread`) but I don't know how to use platform specific flags and Windows is a pain so I haven't tried yet.

Do you mean image artifacts? I contacted the authors and they said that they're a result of the way the algorithm handles gradients. I don't think I'll be able to get rid of them. I'd suggest keeping the algorithm as is, just as a way to demonstrate Halide and then port a higher quality algorithm (AMAZE if someone can explain it) to Halide later.

**Comment by adamreichold** [comment]
@bobobo1618 I just wanted to add that I was able to build this using the latest binary distribution from the project and running on Arch Linux amd64. However, I did have to prepend `dl` to link libraries of the RT GUI binary. Also my system does not support OpenCL and building with the default `OPTION_HALIDE_OPENCL=ON` resulted in the program crashing, i.e.
````
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffa9b08700 (LWP 16208)]
0x00007ffff0e0b5f8 in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff0e0b5f8 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff0e0ca7a in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x0000000000e17f80 in Halide::Runtime::Internal::default_error_handler(void*, char const*) ()
No symbol table info available.
#3  0x0000000000e1b30a in Halide::Runtime::Internal::OpenCL::load_libopencl(void*) ()
No symbol table info available.
#4  0x0000000000e1de6d in halide_opencl_device_malloc ()
No symbol table info available.
#5  0x0000000000e1a588 in halide_device_malloc ()
No symbol table info available.
#6  0x0000000000e1a465 in halide_copy_to_device ()
No symbol table info available.
#7  0x0000000000dbb7d1 in rtengine::RawImageSource::igd_halide_demosaic (this=0x7fffcc001110, winx=0, winy=0, 
    winw=4284, winh=2844) at /home/adam/RawTherapee/rtengine/igd_halide_demosaic.cpp:84
````
Shouldn't failure to load the OpenCL libraries should result in a CPU fallback being used? With OpenCL being disabled at build time, I however was able to build and run this without immediate problems. Also I wonder if it really is intended that we would ship so much of Halide within the RT source tree, e.g. shouldn't the headers come the system includes?

@heckflosse I personally also like @bobobo1618's proposal to concentrate on the build system and integration issues at first and basically ignore questions of the algorithm's result quality for now as the change should make it easier experimenting with different algorithms but without being bogged down in low-level optimization issues. I also think that the pull request would benefit greatly from being rebased on the current master with some of the commits getting squashed.

**Comment by adamreichold** [comment]
@bobobo1618 Concerning platform-specific flags, you could try to align necessary platform-specific build system changes with Halide's generate CMake manifest, e.g. use a case analysis like
````
if (WIN32)
# Windows
elseif(XCODE)
# Mac OS X
else()
# Unix
endif()
````

**Comment by bobobo1618** [comment]
> Shouldn't failure to load the OpenCL libraries should result in a CPU fallback being used?

That would be ideal but that's up to the runtime and I'm unsure how to test for OpenCL support in C++ (this is the first serious C++ I've really written), particularly across different platforms. I was under the impression OpenCL was always supported though. Doesn't it run on the CPU as well as the GPU? How can it lack support?

> I wonder if it really is intended that we would ship so much of Halide within the RT source tree

I removed the runtime headers (the ones I've included) and switched them to the ones provided by Halide with the binary package (I didn't know it included headers at first). I did the same with the `GenGen.cpp` source. The CMake module has to be included though.

> you could try to align necessary platform-specific build system changes with Halide's generator CMake manifest

I've used that save for `XCODE OR ${CMAKE_SYSTEM_NAME} MATCHES "Darwin"` for Mac, since Mac doesn't always mean XCode.

>  I also think that the pull request would benefit greatly from being rebased on the current master with some of the commits getting squashed.

Done. Squashed the lot.

**Comment by heckflosse** [comment]
There's a simple matter of fact: We can't merge this PR if we don't know whether it builds and works fine on Linux (32/64) and Windows (32/64).

Ingo

**Comment by bobobo1618** [comment]
That's definitely true. I can test Mac and possibly Linux (Fedora) but someone else will have to test Windows.

**Comment by adamreichold** [comment]
> That would be ideal but that's up to the runtime and I'm unsure how to test for OpenCL support in C++ (this is the first serious C++ I've really written), particularly across different platforms.

I'd say its up to the runtime to check, but from the stack trace my guess is that you need to override the default error handler `Halide::Runtime::Internal::default_error_handler` so that is does not call `abort` but just switches to a fallback CPU-only generator.

> I was under the impression OpenCL was always supported though. Doesn't it run on the CPU as well as the GPU? How can it lack support?

At least on Linux it is not, e.g. on my system there is no OpenCL implementation (and no ICD) installed at all, so even trying to load those libraries will fail. And even then, I don't think a GPU-based OpenCL implementation is mandated to provide a CPU-based fallback. Of course, one could make a fallback OpenCL implementation like [POCL](http://pocl.sourceforge.net/) a dependency of RawTherapee, but I don't think this is the best decision. As I understand it, Halide already is the abstraction layer we could use to generate optimized code for different targets and also gives us some control over the trade-offs made for the various code generators. So we probably do not want to have the default code lower our algorithm into OpenCL C to just compile that for the host CPU only losing information along the way. Instead the Halide generator should directly output something making use of all the CPU features even if they for example can not be mapped to OpenCL.

@heckflosse I would be willing to help testing this on Linux/64 (Is Linux/32 still a valid use case for performance critical applications like RT?). As I said above, after disabling OpenCL is does build and run on my box. I will give it a try using POCL and Mesa's R600g OpenCL implementation and also do a code review now that it's rebased as soon as I find some spare time.

**Comment by Beep6581** [comment]
Hi @bobobo1618 are you still willing to maintain this if it passes the requirements?

**Comment by bobobo1618** [comment]
After the concerns @adamreichold raised, I'm not sure if I'm technically able to do so. C++ isn't really my area of expertise and while I was able to get this working now, I'm not confident that I'll be able to keep it working if something changes.

**Comment by heckflosse** [comment]
@adamreichold what do you think? Close or keep it open?

**Comment by Beep6581** [comment]
I will close this PR, but @bobobo1618 this does not mean that we express no interest in it, it only means we don't want an unmergeable PR lingering around. As for your Halide implementation, you could keep it in your repo until the required changes are done some time in the future, or we could even make a halide branch which would simply clone your code if there is any benefit in doing that. For now lets keep using issue #2934.

**Pull request closed without merging**
