### PR TITLE
added support for Fuji X-A3 (ported from Libraw)

### PR DESCRIPTION
**Pull request by agriggio**
See #4447

### CODE REVIEW

**Review by heckflosse — APPROVED** [review]
:+1:

**Comment by Beep6581** [comment]
@agriggio the patch introduces this warning during an otherwise quiet compilation:
```
/home/morgan/programs/code-rawtherapee/rtengine/rawimage.cc: In member function ‘int rtengine::RawImage::loadRaw(bool, unsigned int, bool, rtengine::ProgressListener*, double)’:
/home/morgan/programs/code-rawtherapee/rtengine/rawimage.cc:463:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (raw_width * raw_height * 7 / 4 == raw_size) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

**Comment by Beep6581** [comment]
@agriggio @heckflosse this still appears in current dev.

**Comment by heckflosse** [comment]
@Beep6581 I will take a look now

**Comment by heckflosse** [comment]
@Beep6581 I don't get the warning using gcc 7.3.0

**Comment by Beep6581** [comment]
I'm using GCC-6.4.0, and compiled into a clean `build` folder using `build-rawtherapee`.

**Comment by agriggio** [comment]
@heckflosse @Beep6581 I am a bit perplexed about getting a warning for a `==` comparison... anyway, you should be able to silence it by just casting to unsigned explicitly:

```
 if (unsigned(raw_width * raw_height * 7 / 4) == raw_size) {
```

**Comment by Floessie** [comment]
... but in C++, please. (Hint: `static_cast<>`) :wink:

**Comment by heckflosse** [comment]
This should work without a cast:

```
        if (raw_width * raw_height * 7 == 4 * raw_size) {
```
Edit: Or this one:
```
        if (raw_width * raw_height * 7u / 4u == raw_size) {
```

**Comment by agriggio** [comment]
<pedantic_mode>
@Floessie I'm reasonably sure that what I wrote is perfectly valid C++... 
</pedantic_mode>

**EDIT** see section "5.2.3 Explicit type conversion (functional notation)" of the standard

**Comment by Floessie** [comment]
@agriggio 
> I am a bit perplexed about getting a warning for a == comparison...

Me, too. Here's the [rationale](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38046).

@heckflosse 
>`if (raw_width * raw_height * 7 == 4 * raw_size) {`

Not obvious at first glance, but then I recalled x86 `DIV` and `IDIV` from 25 years ago...

@agriggio 
> I'm reasonably sure that wrote is perfectly valid C++...

I don't mind. `clang-tidy` will mend it...

**Comment by Beep6581** [comment]
I tested `  if (raw_width * raw_height * 7u / 4u == raw_size) {` and the warning was gone.

**Pull request merged**
