### PR TITLE
Fix missing explicit include

### PR DESCRIPTION
**Pull request by hfiguiere**
- Also avoid rtgui include

For the context, I'm trying to build rtengine without depending on gtkmm, and with glibmm-2.68, and these are the "trivial" changes that don't impact the current code.

Let me know if you have further questions.

### CODE REVIEW

**Comment by Floessie** [comment]
@hfiguiere Thanks for your contribution! :+1: Alphabetical order is a bit off, but most are files that have not been sorted yet.

@Beep6581 I tested the PR on various Debian VMs (Buster/10, Testing/Bookworm/12, and Experimental) with GCC and Clang. No problems detected. :+1: for merge.

Best,
Flössie

**Comment by Beep6581** [comment]
And no issues here in Manjaro/GCC-12.2.1. Will merge tonight.

**Comment by hfiguiere** [comment]
Since this wasn't merged I added a few more

**Comment by hfiguiere** [comment]
Let me know if you want me to squash these to have only one commit

**Review by Lawrence37 — APPROVED** [review]

**Comment by Lawrence37** [comment]
Merging this because there is minimal risk.

**Pull request merged**
