### PR TITLE
Remove lj92 library

### PR DESCRIPTION
**Pull request by SimonSegerblomRex**
Both `dcraw` and `lj92` contain lossless JPEG decoders. After the recent fixes in #6190 and #6214 they both work fine in most cases, but I don't see any reason to keep `lj92` now. `dcraw` has been the default when `Make` doesn't contain "Canon"/"BlackMagic" and it also supports DNG version 1.0 (with non-spec lossless JPEG encoded 16 bit diff values).

I noticed the discussion in #4462 about replacing `dcraw` with `rawspeed`. Keep in mind that `rawspeed` currently (darktable-org/rawspeed#189, darktable-org/rawspeed#258) only supports predictor mode 1.

For future reference:
Take a look at [this version](https://github.com/ilia3101/MLV-App/blob/11a93832f6543402452104375d03df138cb9ceb9/src/mlv/liblj92/lj92.c) of `lj92` if you need a lossless JPEG **encoder** (that works for 16 bit diff values). ([Here's](https://github.com/thorfdbg/libjpeg) another encoder.)

### CODE REVIEW

**Review by SimonSegerblomRex — COMMENTED** [review]
I don't see any big performance differences between the two implementations. Images seem to load with about the same speed (but I haven't done any real benchmarking). All images at [raw.pixls.us](https://raw.pixls.us/#repo) (searching for "blackmagic" or "mlv") get decoed properly with the `dcraw` implementation (as well as the `lj92` one).

**Comment by Thanatomanic** [comment]
I see no big problems here, if nobody complains I'll merge this on Friday.

**Comment by Thanatomanic** [comment]
@SimonSegerblomRex You can still add your name to the `AUTHORS.txt` file if you want

**Comment by SimonSegerblomRex** [comment]
> @SimonSegerblomRex You can still add your name to the `AUTHORS.txt` file if you want

Thanks @Thanatomanic! I hope I'll be able to make some more substantial contribution to the project in the future.

**Pull request merged**
