### PR TITLE
Add reset button for Crop

### PR DESCRIPTION
**Pull request by Thanatomanic**
This resolves issue #4668

I've introduced this as a simple textual button below the 'Select crop' button, because I didn't see any immediate position where I could put a reset 'arrow' like for other tools.

### CODE REVIEW

**Comment by TooWaBoo** [comment]
The "Reset Crop" button has a wrong icon. If you can't see the icons in your build, read this: https://github.com/Beep6581/RawTherapee/issues/4847#issuecomment-426822150
grafik

`Line 138: resetCrop->set_image (*Gtk::manage (new RTImage ("undo-small.png")));`
grafik

**Comment by TooWaBoo** [comment]
@Thanatomanic 
Did you forget to make the change according to my suggestion? 😃

**Comment by Thanatomanic** [comment]
@TooWaBoo Didn't forget, just didn't do :wink:

**Comment by Beep6581** [comment]
I'm not sure an undo icon is right here, resetting != undoing, what do you think about the "refresh" icon?
https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/images/themed/png/light/refresh-small.png

**Comment by Thanatomanic** [comment]
But, all other "Reset to default" buttons use the undo-icon. Why would this be any different?

image

**Comment by Thanatomanic** [comment]
@Beep6581 Or would you even be inclined to change the undo icon for all other reset buttons too?

**Comment by Beep6581** [comment]
After having spent endless days on this I'm inclined to not want to think about that any more :sweat_smile: 

IIRC I tried the "refresh" icon for all sliders and it looked "too much". You're right, let's leave it.

**Comment by Thanatomanic** [comment]
In that case, any objections to merge?

**Comment by Beep6581** [comment]
I will test tonight.

**Comment by Beep6581** [comment]
@Thanatomanic sorry for the delay, I finally found the time to compile a few branches - takes a while on a 0.9GHz laptop ;)

* "Reset crop" works fine on single images.
* The button has no effect in batch mode. Would be nice if it worked in batch mode, but if that's not doable for 5.5 for whatever reason then I think it should be hidden in batch mode, along with the "Select crop" button.
* We can make more efficient use of vertical screen space by placing the "Select crop" and "Reset crop" buttons horizontally next to each other. I would then also change the button labels to "Select" (or "Draw") and "Reset", dropping the noun "crop" as it's not necessary, none of the other labels in the Crop tool use that word, and the labels need to stay short, especially for some long-worded languages. Here is a proposed patch:
```diff
diff --git a/rtdata/languages/Catala b/rtdata/languages/Catala
index c3a7ea1d0..fd5c4c01e 100644
--- a/rtdata/languages/Catala
+++ b/rtdata/languages/Catala
@@ -667,7 +667,6 @@ TP_CROP_GUIDETYPE;Tipus de guia:
 TP_CROP_H;Alt
 TP_CROP_LABEL;Cropa
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Selecc. cropar
 TP_CROP_W;Ample
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Chinese (Simplified) b/rtdata/languages/Chinese (Simplified)
index 077da51c0..69d29a00e 100644
--- a/rtdata/languages/Chinese (Simplified)	
+++ b/rtdata/languages/Chinese (Simplified)	
@@ -776,7 +776,6 @@ TP_CROP_GUIDETYPE;辅助方式:
 TP_CROP_H;高
 TP_CROP_LABEL;剪裁
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;选择预设
 TP_CROP_W;宽
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Chinese (Traditional) b/rtdata/languages/Chinese (Traditional)
index 2b2477748..ab9aa37d2 100644
--- a/rtdata/languages/Chinese (Traditional)	
+++ b/rtdata/languages/Chinese (Traditional)	
@@ -343,7 +343,6 @@ TP_CROP_GTRULETHIRDS;1/3法則
 TP_CROP_GUIDETYPE;輔助方式:
 TP_CROP_H;高
 TP_CROP_LABEL;剪裁
-TP_CROP_SELECTCROP;    選擇預設
 TP_CROP_W;寬
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Czech b/rtdata/languages/Czech
index 18af7bf65..184c43971 100644
--- a/rtdata/languages/Czech
+++ b/rtdata/languages/Czech
@@ -1451,7 +1451,6 @@ TP_CROP_GUIDETYPE;Druh vodítek:
 TP_CROP_H;Výška
 TP_CROP_LABEL;Ořez
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Vyznačit výřez
 TP_CROP_W;Šířka
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Dansk b/rtdata/languages/Dansk
index 547c5a6e6..25de02a4f 100644
--- a/rtdata/languages/Dansk
+++ b/rtdata/languages/Dansk
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;Reglen om tredjedele
 TP_CROP_GUIDETYPE;Hjælpelinjer:
 TP_CROP_H;H
 TP_CROP_LABEL;Beskær
-TP_CROP_SELECTCROP;    Vælg beskæring
 TP_CROP_W;B
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Deutsch b/rtdata/languages/Deutsch
index dd0655242..85a48da1f 100644
--- a/rtdata/languages/Deutsch
+++ b/rtdata/languages/Deutsch
@@ -1574,7 +1574,6 @@ TP_CROP_GUIDETYPE;Hilfslinien:
 TP_CROP_H;Höhe
 TP_CROP_LABEL;Ausschnitt
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Ausschnitt wählen
 TP_CROP_W;Breite
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/English (UK) b/rtdata/languages/English (UK)
index 800e23527..4b021aceb 100644
--- a/rtdata/languages/English (UK)	
+++ b/rtdata/languages/English (UK)	
@@ -1534,7 +1534,6 @@ TP_WBALANCE_EQBLUERED_TOOLTIP;Allows to deviate from the normal behaviour of "wh
 !TP_CROP_H;Height
 !TP_CROP_LABEL;Crop
 !TP_CROP_PPI;PPI=
-!TP_CROP_SELECTCROP;Select Crop
 !TP_CROP_W;Width
 !TP_CROP_X;X
 !TP_CROP_Y;Y
diff --git a/rtdata/languages/English (US) b/rtdata/languages/English (US)
index fc2fa83dd..1bfd57514 100644
--- a/rtdata/languages/English (US)	
+++ b/rtdata/languages/English (US)	
@@ -1496,7 +1496,6 @@
 !TP_CROP_H;Height
 !TP_CROP_LABEL;Crop
 !TP_CROP_PPI;PPI=
-!TP_CROP_SELECTCROP;Select Crop
 !TP_CROP_W;Width
 !TP_CROP_X;X
 !TP_CROP_Y;Y
diff --git a/rtdata/languages/Espanol b/rtdata/languages/Espanol
index 5402f6579..5e02ce872 100644
--- a/rtdata/languages/Espanol
+++ b/rtdata/languages/Espanol
@@ -1095,7 +1095,6 @@ TP_CROP_GUIDETYPE;Clase de guía:
 TP_CROP_H;Al
 TP_CROP_LABEL;Recortar
 TP_CROP_PPI;Ptos/Pulgada=
-TP_CROP_SELECTCROP;Seleccionar recorte
 TP_CROP_W;Ancho
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Euskara b/rtdata/languages/Euskara
index 851536a29..70831efcc 100644
--- a/rtdata/languages/Euskara
+++ b/rtdata/languages/Euskara
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;Herenen erregela
 TP_CROP_GUIDETYPE;Gida mota:
 TP_CROP_H;H
 TP_CROP_LABEL;Moztu
-TP_CROP_SELECTCROP;    Mozketa hautatu
 TP_CROP_W;W
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Francais b/rtdata/languages/Francais
index 9c1fcce59..edb8f9f47 100644
--- a/rtdata/languages/Francais
+++ b/rtdata/languages/Francais
@@ -1454,7 +1454,6 @@ TP_CROP_GUIDETYPE;Type de guide:
 TP_CROP_H;H
 TP_CROP_LABEL;Recadrage
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;    Sélection du recadrage
 TP_CROP_W;L
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Greek b/rtdata/languages/Greek
index 086710b52..7184767f1 100644
--- a/rtdata/languages/Greek
+++ b/rtdata/languages/Greek
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;Κανόνας τρίτων
 TP_CROP_GUIDETYPE;Είδος βοηθών:
 TP_CROP_H;H
 TP_CROP_LABEL;Αποκοπή
-TP_CROP_SELECTCROP;    Επιλογή αποκοπής
 TP_CROP_W;W
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Hebrew b/rtdata/languages/Hebrew
index c7477fd09..0e210b55b 100644
--- a/rtdata/languages/Hebrew
+++ b/rtdata/languages/Hebrew
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;כלל השליש
 TP_CROP_GUIDETYPE;סוג מדריך
 TP_CROP_H;גובה
 TP_CROP_LABEL;גזור
-TP_CROP_SELECTCROP;בחור גזירה
 TP_CROP_W;רוחב
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Italiano b/rtdata/languages/Italiano
index ca048d956..81f233141 100644
--- a/rtdata/languages/Italiano
+++ b/rtdata/languages/Italiano
@@ -964,7 +964,6 @@ TP_CROP_GUIDETYPE;Tipo di guida:
 TP_CROP_H;A
 TP_CROP_LABEL;Ritaglio
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP; Seleziona Area
 TP_CROP_W;L
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Japanese b/rtdata/languages/Japanese
index fe8b79022..36ba00a41 100644
--- a/rtdata/languages/Japanese
+++ b/rtdata/languages/Japanese
@@ -1526,7 +1526,6 @@ TP_CROP_GUIDETYPE;ガイドタイプ:
 TP_CROP_H;高さ
 TP_CROP_LABEL;切り抜き
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP; 選択範囲切り抜き
 TP_CROP_W;W 幅
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Latvian b/rtdata/languages/Latvian
index 6689e4f95..57ee37181 100644
--- a/rtdata/languages/Latvian
+++ b/rtdata/languages/Latvian
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;Trešdaļas
 TP_CROP_GUIDETYPE;Vadlīnijas:
 TP_CROP_H;A
 TP_CROP_LABEL;Kadrējums
-TP_CROP_SELECTCROP;    Norādīt kadrējumu
 TP_CROP_W;P
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Magyar b/rtdata/languages/Magyar
index d0f806fea..932132ea0 100644
--- a/rtdata/languages/Magyar
+++ b/rtdata/languages/Magyar
@@ -635,7 +635,6 @@ TP_CROP_GUIDETYPE;Segédvonal típusa:
 TP_CROP_H;M
 TP_CROP_LABEL;Kivágás
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;    Kijelölés egérrel
 TP_CROP_W;Sz
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Nederlands b/rtdata/languages/Nederlands
index f5948ef26..97502d22d 100644
--- a/rtdata/languages/Nederlands
+++ b/rtdata/languages/Nederlands
@@ -1341,7 +1341,6 @@ TP_CROP_GUIDETYPE;Hulplijnen:
 TP_CROP_H;Hoogte
 TP_CROP_LABEL;Bijsnijden
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Selecteer gebied
 TP_CROP_W;Breedte
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Norsk BM b/rtdata/languages/Norsk BM
index 4a76fdcda..5a5c5014d 100644
--- a/rtdata/languages/Norsk BM	
+++ b/rtdata/languages/Norsk BM	
@@ -334,7 +334,6 @@ TP_CROP_GTRULETHIRDS;Tredjedelsreglen
 TP_CROP_GUIDETYPE;Guidetype:
 TP_CROP_H;H
 TP_CROP_LABEL;Beskjæring
-TP_CROP_SELECTCROP;Velg beskjæringsområde
 TP_CROP_W;B
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Polish b/rtdata/languages/Polish
index f54de5593..bb3061ead 100644
--- a/rtdata/languages/Polish
+++ b/rtdata/languages/Polish
@@ -1050,7 +1050,6 @@ TP_CROP_GUIDETYPE;Typ pomocy:
 TP_CROP_H;Wysokość
 TP_CROP_LABEL;Kadrowanie
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Wybierz kadr
 TP_CROP_W;Szerokość
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Polish (Latin Characters) b/rtdata/languages/Polish (Latin Characters)
index d3e62a777..b3a0acf1d 100644
--- a/rtdata/languages/Polish (Latin Characters)	
+++ b/rtdata/languages/Polish (Latin Characters)	
@@ -1050,7 +1050,6 @@ TP_CROP_GUIDETYPE;Typ pomocy:
 TP_CROP_H;Wysokosc
 TP_CROP_LABEL;Kadrowanie
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Wybierz kadr
 TP_CROP_W;Szerokosc
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Portugues (Brasil) b/rtdata/languages/Portugues (Brasil)
index 7acb91cce..ec58543aa 100644
--- a/rtdata/languages/Portugues (Brasil)	
+++ b/rtdata/languages/Portugues (Brasil)	
@@ -1488,7 +1488,6 @@ TP_CROP_GUIDETYPE;Tipo de guia:
 TP_CROP_H;Altura
 TP_CROP_LABEL;Cortar
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Selecione para Cortar
 TP_CROP_W;Largura
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtdata/languages/Russian b/rtdata/languages/Russian
index 36b63772e..d1d64567e 100644
--- a/rtdata/languages/Russian
+++ b/rtdata/languages/Russian
@@ -990,7 +990,6 @@ TP_CROP_GUIDETYPE;Тип направляющей:
 TP_CROP_H;Высота
 TP_CROP_LABEL;Кадрирование
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Включить режим обрезки
 TP_CROP_W;Ширина
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Serbian (Cyrilic Characters) b/rtdata/languages/Serbian (Cyrilic Characters)
index e69c9b874..ce621b607 100644
--- a/rtdata/languages/Serbian (Cyrilic Characters)	
+++ b/rtdata/languages/Serbian (Cyrilic Characters)	
@@ -929,7 +929,6 @@ TP_CROP_GUIDETYPE;Вођицe:
 TP_CROP_H;В
 TP_CROP_LABEL;Исецање
 TP_CROP_PPI;ППИ=
-TP_CROP_SELECTCROP;    Изабери област
 TP_CROP_W;Ш
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Serbian (Latin Characters) b/rtdata/languages/Serbian (Latin Characters)
index 727cdeb9a..2f104d6f1 100644
--- a/rtdata/languages/Serbian (Latin Characters)	
+++ b/rtdata/languages/Serbian (Latin Characters)	
@@ -929,7 +929,6 @@ TP_CROP_GUIDETYPE;Vođice:
 TP_CROP_H;V
 TP_CROP_LABEL;Isecanje
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;    Izaberi oblast
 TP_CROP_W;Š
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Slovak b/rtdata/languages/Slovak
index 022c715e3..dada2fc0e 100644
--- a/rtdata/languages/Slovak
+++ b/rtdata/languages/Slovak
@@ -389,7 +389,6 @@ TP_CROP_GTRULETHIRDS;Pravidlo tretín
 TP_CROP_GUIDETYPE;Type vodidiel:
 TP_CROP_H;V
 TP_CROP_LABEL;Orezanie
-TP_CROP_SELECTCROP;    Vyberte Orez
 TP_CROP_W;Š
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Suomi b/rtdata/languages/Suomi
index 722bf1b0b..4828f02a6 100644
--- a/rtdata/languages/Suomi
+++ b/rtdata/languages/Suomi
@@ -335,7 +335,6 @@ TP_CROP_GTRULETHIRDS;Kolmijako
 TP_CROP_GUIDETYPE;Sommittelumalli:
 TP_CROP_H;Kork.
 TP_CROP_LABEL;Rajaus
-TP_CROP_SELECTCROP;Valitse alue
 TP_CROP_W;Lev.
 TP_CROP_X;   x
 TP_CROP_Y;   y
diff --git a/rtdata/languages/Swedish b/rtdata/languages/Swedish
index 44c5dd475..1e6d7fe84 100644
--- a/rtdata/languages/Swedish
+++ b/rtdata/languages/Swedish
@@ -1228,7 +1228,6 @@ TP_CROP_GUIDETYPE;Guidetyp:
 TP_CROP_H;Höjd
 TP_CROP_LABEL;Beskär
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Välj beskärningsområde
 TP_CROP_W;Bredd
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/Turkish b/rtdata/languages/Turkish
index a3dd1d5ea..cdf0473b0 100644
--- a/rtdata/languages/Turkish
+++ b/rtdata/languages/Turkish
@@ -335,7 +335,6 @@ TP_CROP_GTRULETHIRDS;Üçler kuralı
 TP_CROP_GUIDETYPE;Kılavuz türü:
 TP_CROP_H;Y
 TP_CROP_LABEL;Kırp
-TP_CROP_SELECTCROP;    Kırpma alanı seç
 TP_CROP_W;G
 TP_CROP_X;x
 TP_CROP_Y;y
diff --git a/rtdata/languages/default b/rtdata/languages/default
index bb1e29723..49641fd63 100644
--- a/rtdata/languages/default
+++ b/rtdata/languages/default
@@ -1497,8 +1497,8 @@ TP_CROP_GUIDETYPE;Guide type:
 TP_CROP_H;Height
 TP_CROP_LABEL;Crop
 TP_CROP_PPI;PPI=
-TP_CROP_SELECTCROP;Select Crop
-TP_CROP_RESETCROP;Reset Crop
+TP_CROP_SELECTCROP;Select
+TP_CROP_RESETCROP;Reset
 TP_CROP_W;Width
 TP_CROP_X;X
 TP_CROP_Y;Y
diff --git a/rtgui/crop.cc b/rtgui/crop.cc
index f66a730c1..4d86a1a19 100644
--- a/rtgui/crop.cc
+++ b/rtgui/crop.cc
@@ -127,18 +127,19 @@ Crop::Crop():
 
     pack_start (*hb2, Gtk::PACK_SHRINK, 4);
 
+    Gtk::HBox* hb5 = Gtk::manage (new Gtk::HBox());
+
     selectCrop = Gtk::manage (new Gtk::Button (M("TP_CROP_SELECTCROP")));
     selectCrop->get_style_context()->add_class("independent");
     selectCrop->set_image (*Gtk::manage (new RTImage ("crop-small.png")));
 
-    pack_start (*selectCrop, Gtk::PACK_SHRINK, 2);
-
     resetCrop = Gtk::manage (new Gtk::Button (M("TP_CROP_RESETCROP")));
     resetCrop->get_style_context()->add_class("independent");
     resetCrop->set_image (*Gtk::manage (new RTImage ("undo-small.png")));
 
-    pack_start (*resetCrop, Gtk::PACK_SHRINK, 2);
-
+    hb5->pack_start (*selectCrop, Gtk::PACK_EXPAND_WIDGET, 2);
+    hb5->pack_start (*resetCrop, Gtk::PACK_EXPAND_WIDGET, 2);
+    pack_start(*hb5, Gtk::PACK_SHRINK, 4);
 
     Gtk::HBox* hb3 = Gtk::manage (new Gtk::HBox ());
 
```

screenshot_20181027_172508

**Comment by Thanatomanic** [comment]
@Beep6581 Thanks for the patch. Combining the two buttons on one line seems reasonable.
Though, I doubt that I can make the necessary changes for the Batch mode in time for v5.5. Hiding the options is something more easily done. Tomorrow afternoon I am back home and I'll work on this.

**Comment by Thanatomanic** [comment]
@Beep6581 I managed to get batch crop reset _almost_ working. To be able to access the original image size, I made a new function in `thumbnail.cc`. However, if you start out with a cropped image, a proper reset only works after you click 'Reset' twice. 
Not sure why...
Ping @heckflosse could you take a look maybe?

Aside: the batch 'Select' crop button is fully disfunctional, though I never changed anything for that?

**Comment by heckflosse** [comment]
When 'Automatically zoom to fit the crop area' is enabled in preferences, resetting the crop should zoom to fit the new whole crop, but does not.

**Comment by Thanatomanic** [comment]
@heckflosse Can you give me push in the right direction to fix this?

**Comment by heckflosse** [comment]
@Thanatomanic I'm looking now how to fix that.

**Comment by heckflosse** [comment]
@Thanatomanic I searched for a while but still found no easy way to call `CropWindow::zoomFitCrop ()` from `crop.cc`. ping @Hombre57

**Comment by Hombre57** [comment]
@heckflosse @Thanatomanic 

What should be the synchronicity here ? The `EvCrop` from the reset button will trigger a reprocessing of the preview, and the `zoomFit` will do that too (unless you create a dedicated function, but again, you have to take care of the synchronicity). The method below won't avoid a double processing, it would require more analysis.

The easiest way to implement that would be to add a dedicated event for the crop reset event. Since the `EditorPanel` is registered as a `PParamsChangeListener` (editorpanel.cc, l. 829), it could trigger a function to `iareapanel->imageArea` inside `EditorPanel::procParamsChanged`.

**Comment by heckflosse** [comment]
@Hombre57 

> The EvCrop from the reset button will trigger a reprocessing of the preview

As I wrote above: `When 'Automatically zoom to fit the crop area' is enabled in preferences, resetting the crop should zoom to fit the new whole crop, but does not.`

**Comment by Hombre57** [comment]
@heckflosse Sorry but I only read this : 

> I searched for a while but still found no easy way to call CropWindow::zoomFitCrop () from crop.cc.

In which case, the answer is : pressing the reset button will update the size of the crop. If the size change, then use `listener->panelChanged` with `EvCropReset`, and then the `iareapanel->imageArea->cropReset` function will call `CropWindow::zoomFitCrop` depending on the `options` parameter.

Now are you saying there's a bug in the source and that it should already work ?

**Comment by heckflosse** [comment]
@Hombre57 From a users perspective I would have expected that reseting the crop would zoom to fit the new (whole image) crop when 'Automatically zoom to fit the crop area' is enabled in preferences.
I don't say there is a bug in source.

**Comment by Hombre57** [comment]
@Thanatomanic @heckflosse I'll have a look tomorrow.

**Comment by Hombre57** [comment]
@heckflosse @Thanatomanic 

> When **Automatically zoom to fit the crop area** is enabled in preferences, resetting the crop should zoom to fit the new whole crop, but does not.

When looking at the code, what this option is controlling is that you fit the cropped part of the image, not the whole image when asking a **Zoom to fit**. It shouldn't be understood that it will automatically fit if you change the crop (what the label may suggest), nor when reseting it or disabling the tool. So I wouldn't take any action on this IMHO.

**Comment by Thanatomanic** [comment]
@Hombre57 @heckflosse I read through the comments only just now.
If you change the crop manually and were working in 'Zoom to fit', the zoom also does not get updated. It might be desirable to have that functionality, but I tend to agree with Hombre here and take no further action at the moment. It could be proposed as another issue.

Keep in mind, there is still some outstanding issue with the new Reset button:

> I made a new function in `thumbnail.cc`. However, if you start out with a cropped image, a proper reset only works after you click 'Reset' twice.
> Not sure why...
> Ping @heckflosse could you take a look maybe?
> 
> Aside: the batch 'Select' crop button is fully disfunctional, though I never changed anything for that?

**Comment by Hombre57** [comment]
@Thanatomanic I'll have a look at this problem. The crop button should be hidden in batch mode, too complex to handle when multiple image of different size are selected, and cases where you want to draw the crop in batch mode are very rare, if not non existent.

**Comment by Hombre57** [comment]
@Thanatomanic I'd like to help on this but it works just fine here (Gtkmm: V3.22.2). However I just saw that RT is full of `signal_pressed()` event connection (37 occurrences), which are deprecated and have to be replaced by `signal_button_press_event()` event. Let's do it for 5.6.

**Comment by Hombre57** [comment]
Here is a patch to remove the buttons in batch mode :

```patch
diff --git a/rtgui/crop.cc b/rtgui/crop.cc
index 369b5cd..9e30e9a 100644
--- a/rtgui/crop.cc
+++ b/rtgui/crop.cc
@@ -127,7 +127,7 @@
 
     pack_start (*hb2, Gtk::PACK_SHRINK, 4);
     
-    Gtk::HBox* hb5 = Gtk::manage (new Gtk::HBox());
+    buttonsBox = Gtk::manage (new Gtk::HBox());
 
     selectCrop = Gtk::manage (new Gtk::Button (M("TP_CROP_SELECTCROP")));
     selectCrop->get_style_context()->add_class("independent");
@@ -137,9 +137,9 @@
     resetCrop->get_style_context()->add_class("independent");
     resetCrop->set_image (*Gtk::manage (new RTImage ("undo-small.png")));
 
-    hb5->pack_start (*selectCrop, Gtk::PACK_EXPAND_WIDGET, 2);
-    hb5->pack_start (*resetCrop, Gtk::PACK_EXPAND_WIDGET, 2);
-    pack_start(*hb5, Gtk::PACK_SHRINK, 4);
+    buttonsBox->pack_start (*selectCrop, Gtk::PACK_EXPAND_WIDGET, 2);
+    buttonsBox->pack_start (*resetCrop, Gtk::PACK_EXPAND_WIDGET, 2);
+    pack_start(*buttonsBox, Gtk::PACK_SHRINK, 4);
 
     Gtk::HBox* hb3 = Gtk::manage (new Gtk::HBox ());
 
@@ -1323,4 +1323,5 @@
     orientation->append (M("GENERAL_UNCHANGED"));
     guide->append (M("GENERAL_UNCHANGED"));
     removeIfThere (this, ppibox);
+    removeIfThere (this, buttonsBox);
 }
diff --git a/rtgui/crop.h b/rtgui/crop.h
index 6ab0a5a..43e2e6d 100644
--- a/rtgui/crop.h
+++ b/rtgui/crop.h
@@ -103,6 +103,7 @@
     MyComboBoxText* ratio;
     MyComboBoxText* orientation;
     MyComboBoxText* guide;
+    Gtk::HBox* buttonsBox;
     Gtk::Button* selectCrop;
     Gtk::Button* resetCrop;
     CropPanelListener* clistener;
```

**Comment by Thanatomanic** [comment]
@Hombre57 Thanks for the patch, I've applied it with a minor modification because I believe `HBox` and `VBox` will become deprecated in favor of `Gtk::Box(Gtk::ORIENTATION_HORIZONTAL)` and vertical respectively.

@heckflosse What do you think about the 'zoom to fit' issue? Otherwise, ready for test and good to merge?

**Comment by Hombre57** [comment]
IIRC, the `Gtk::Box` class will be replaced by `Gtk::Grid`, but not sure when. But I'm fine with your change :+1:

**Comment by TooWaBoo** [comment]
@Thanatomanic 
I've played with your work a bit and changed all boxes to grid, add classes `grid-spacing` and `grid-row-separator` for css spacing and removed all hardcoded spacing. I hope this is OK. 😀

unbenanntnew

~~Here are the canged files:~~

I've tested your changes and found one issue: Unnecessary objects are not removed in batch mode.
Feature request: If ratio is selected the crop area should be centered when clicking on the reset button.

**Comment by TooWaBoo** [comment]
Some changes
Changed width of the spinbuttons from pixel to chars and the behaviour when stretching the widget.
unbenannt
Here are the files: [Crop.zip](https://github.com/Beep6581/RawTherapee/files/2577477/Crop.zip)

I also suggest to change the label `x:` and `y:` to `Left:` and `Top:` .

**Comment by Thanatomanic** [comment]
@TooWaBoo I'll adapt your excellent adjustments! Thanks :smile:

**Comment by TooWaBoo** [comment]
My pleasure. 😊

**Comment by TooWaBoo** [comment]
@Thanatomanic 
I could solve the `#batch mode remove ppi box issue`. 😁
Make the following changes in my zip files:

`Line 189`
`Gtk::Grid* ppigrid = Gtk::manage(new Gtk::Grid());`
`change to`
~~ppigrid = new Gtk::Grid ();~~
`ppigrid = Gtk::manage(new Gtk::Grid());`

`ppigrid `is already declared in `crop.h`. `Gtk::Grid* ppigrid = Gtk::manage(new Gtk::Grid());` creates a new variable (I guess a local one) with the same name. You have to assign the grid to the existing variable (I guess a global one) and this is done by `Gtk::manage(new Gtk::Grid());`

**Comment by Floessie** [comment]
@TooWaBoo My gut feeling tells me that you shouldn't remove the `Gtk::manage()`, though I haven't looked into the code...

**Comment by TooWaBoo** [comment]
@Floessie 
Thanks, I trust your feelings. 😁

**Comment by Thanatomanic** [comment]
@TooWaBoo I pushed your changes, could you test?

**Comment by TooWaBoo** [comment]
@Thanatomanic 
Tested and found one bug. I've seen in the code that you want to remove the `select` and` reset` button too. Now we have an `#whydoesthisdamnselectandresetbuttonisshowninbatchmode` issue. 😁
This will fix it.
```
Line1558
    removeIfThere (methodgrid, selectCrop);
    removeIfThere (methodgrid, resetCrop);
change to
    removeIfThere (methodgrid, selectCrop, false);
    removeIfThere (methodgrid, resetCrop, false);
```

**Comment by Thanatomanic** [comment]
@TooWaBoo Did the buttons show up for you in batch mode? Even without your fix they didn't for me ..

image

**Comment by TooWaBoo** [comment]
Strange, I did a fresh download from your fork, compiled again and now it works.
grafik
Why is the label "Width" in your screenshot centered, the combobox empty and some objects are aligned incorrect?

**Comment by Thanatomanic** [comment]
> Why is the label "Width" in your screenshot centered, the combobox empty and some objects are aligned incorrect?

Maybe this is a CSS update you already have but I haven't ?

Edit: the empty combo-box I don't know...

**Comment by TooWaBoo** [comment]
I didn't change anything. Downloaded from your fork, compliled it and started RT.
I guess you are not using the same version as in Github.😏

**Comment by TooWaBoo** [comment]
Tested and didn't find any issues. Can be merged. 😀

**Comment by Beep6581** [comment]
@Thanatomanic we should merge this if it's to go into 5.5, else bump it to 5.6.

**Comment by Thanatomanic** [comment]
@beep6581 A merge is fine by me if it's tested enough. Together with TooWaBoo that makes at least two people who agree.

@heckflosse had an unresolved remark earlier in the discussion. Can you still comment, or agree to merge?

**Comment by Thanatomanic** [comment]
@Beep6581 Woah, what did I break? Where are all these commits and stray posts coming from? I think I messed up big time trying to rebase my branch...

**Comment by Beep6581** [comment]
@Thanatomanic yeah I was surprised to find 81 commits over 95 files to add a reset button, must be quite the button! ;)

**Comment by Beep6581** [comment]
@Thanatomanic I checked in CLI and the current status of the branch diffed against `dev` looks fine. It's just the history that's confusing (or my understanding of git too shallow).

**Comment by Thanatomanic** [comment]
I think I will not squash and merge this PR because somehow the history got polluted, and I'm not sure how that will look like in the commit history. Closing this and opening a new, fresh PR, or even remake the branch...

**Pull request closed without merging**
