### PR TITLE
Locallab GUI improvements/bugfixes

### PR DESCRIPTION
**Pull request by Pandagrapher**
Bugfixes:
- Issue #5269: When deleting a spot, the remaining one just before is now selected
- Other: Corrects line ending on controlspotpanel.h/.cc files

Improvements:
- Issue #5270: Adds ability to show/hide all the spot (ctrl+click on show/hide button)
- Issue #5220: Added spot are now centered/resized according to preview area
- Issue #5298: Adds ability to move spot using spot center area

Pierre

### CODE REVIEW

**Comment by Desmis** [comment]
I come back from a travel..vacation
@Pandagrapher  all seems to works fine. Very good job. Thank you very much for these nice improvments :)

@heckflosse @Floessie @Hombre57 @Beep6581 @Pandagrapher 
If no objections I will merge this PULL REQUEST with Beep6581/newlocallab tomorrow

Jacques

**Comment by heckflosse** [comment]
No objection from me

**Comment by Pandagrapher** [comment]
@Desmis 
It's ok for me

**Comment by Desmis** [comment]
Merge done :)
I have also, add "transition differentiation"

jacques

**Comment by heckflosse** [comment]
@Desmis Can I push a fix for the bug reported [here](https://discuss.pixls.us/t/local-lab-build/1430/751)

Edit: @Desmis Jacques, you've been faster :+1:

**Comment by Desmis** [comment]
@heckflosse 

Ingo

Look at my code, you can change, no problem at all :)

jacques

**Pull request merged**
