### PR TITLE
Fix CMake and AboutThisBuild with git  (see issue #2860)

### PR DESCRIPTION
**Pull request by innir**
Tools to generate the release info are not updated jet, namely
tools/generateReleaseInfo{.bat}.
Only tested on Linux, OS X and Windows are untested.

### CODE REVIEW

**Comment by Beep6581** [comment]
I'm away mostly until Sunday, will test then. Thanks!

**Comment by gaaned92** [comment]
I don't know where I am supposed to answer, here or in the issue.

I build a 32 bit windows version with this PR
>Branch: pr/2865
Version: 4.2.298
Changeset: 3b9b484ec162d5bf2a0aa6c86a0efb7f2a69895b
Compiler: gcc 4.6.1
Processor: generic x86
System: Windows
Bit depth: 32 bits
Gtkmm: V2.22.0
Build type: release
Build flags:  -m32  -mthreads -mstackrealign  -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

The windowsinnosetup.iss is not updated making installer generation impossible.



Remark 2 : for a noob, git seems more intricate than mercurial. I was unable to patch the local repository with the patch generated by appending ".patch " to the PR URL. 
Finally I found a way to transform the PR in a new local branch and  build the branch!
Could some expert explain thoroughly how to download a PR (or a patch) , include it in the local code, and finally after test, delete the modification.

André

**Comment by heckflosse** [comment]
Hi André, near the bottom of this page there is a link 'command line instructions'
Following step1 you can siwtch to the code from PR
Then build and test as usual.
After testing just use
git checkout master
build and you're back to master branch

Ingo

**Comment by innir** [comment]
> The windowsinnosetup.iss is not updated making installer generation impossible.

Ups, I know how to solve this, I'll update the pull request later

**Comment by heckflosse** [comment]
André. I guess you don't see the link 'command line instructions' because you don't have push rights.
So here's Step1 for this case:

git checkout -b innir-master master
git pull https://github.com/innir/RawTherapee.git master

**Comment by innir** [comment]
André, WindowsInnoSetup.iss should be generated now  (I didn't test it as I'm not on Windows)

**Comment by innir** [comment]
For now I only adopted tools/generateReleaseInfo and deleted tools/generateReleaseInfo.bat. I don't think we need the windows version here and I don't know how to do the fiddling with `sed` on Windows.
Now the build system should work again.

**Comment by Hombre57** [comment]
Philip, I'm trying to test your patch but my toolchain for RT/Gtk2 seems to be broken again. I'll try too solve that today, please wait one more day.

**Comment by michaelezra** [comment]
I hope I did not mess up something with branches as I am figuring this out, please let me know if I did:)
Anyway, I was able to compile RT from git on winx64 and here is AboutThisBuild.txt:
Branch: innir-master
Version: 4.2.308
Changeset: 990e47d0e2987a3ffafdadec278b00b430539785
Compiler: gcc 4.9.2
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: RELWITHDEBINFO
Build flags: -m64 -mwin32 -mthreads -msse -msse2 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O2 -g -Wno-aggressive-loop-optimizations
Link flags: -mwin32 -mthreads -static-libgcc  -march=native -s -O2
OpenMP support: ON
MMAP support: ON

The WindowsInnoSetup.iss works fine:)

**Comment by michaelezra** [comment]
Here is a trial winx64 build: http://www.michaelezra.com/Projects/RT/Builds/RawTherapee_WinVista_64_4.2.308.exe.zip

**Comment by Beep6581** [comment]
Works well here in Gentoo
```
Branch: innir-master
Version: 4.2.308
Changeset: 06e8a14bce41ea5aeff1b1c59170d82e918f7852
Compiler: cc 4.9.3
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

I'll commit a small improvement tomorrow.

**Comment by innir** [comment]
Thanks for the tests!
Why not just merging the pull request and commit your improvement later?

**Comment by Hombre57** [comment]
Toolchain up and running again! Patch tested and works fine on Win7/64bits. What ? I come after the battle ?

Branch: innir
Version: 4.2.304
Changeset: 5fd92cdcc33983b710ebb754bc2e32ab0ca82aa5
Compiler: gcc 5.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: Debug
Build flags: -mthreads -mwin32 -m64 -msse2 -mfpmath=sse -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -DGTK_DISABLE_SINGLE_INCLUDES -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGSEAL_ENABLE -O0 -g2 -Wall -fno-omit-frame-pointer
Link flags: -mthreads -mtune=generic -O0 -fno-omit-frame-pointer
OpenMP support: ON
MMAP support: ON


I can't say if the InnoSetup script is still valid, but at least it contains the correct version number.

**Comment by Hombre57** [comment]
Sorry, wrong button, didn't figured out that "Close" meant "Close PR"...

**Pull request merged**
