### PR TITLE
macOS bundle update

### PR DESCRIPTION
**Pull request by Benitoite**
Copies libraries using `ditto`, preserving binary resources
Codesigns each in Contents/Framework

### CODE REVIEW

**Comment by rfranke** [comment]
You changed a couple of `cp *.dylib` to `ditto *.dylib`. Why are those operations needed at all? Shouldn't the recursive
```
CheckLink "${EXECUTABLE}"
```
just do it?

**Comment by Beep6581** [comment]
Is this PR needed to get a 5.8 build for macOS?

**Comment by Benitoite** [comment]
> Is this PR needed to get a 5.8 build for macOS?

@Beep6581 Yes...  will have a test build ready tonite of 5.7-dev, after work.

@rfranke  Yes...  Over the years some libraries had failed in that loop and band-aids were placed.

**Comment by Benitoite** [comment]
Here is a build to test on macOS 10.9+ with latest pull from `gtk/gtk-3-24`

[outdated link removed]

```
Version: 5.7-438-gd6fb05938
Branch: dev
Commit: d6fb05938
Commit date: 2020-02-02
Compiler: clang 11.0.0.11000033
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.95.0
Build type: release
Build flags: -Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11 -std=c++11 -mtune=generic -Werror=unused-label -Werror=delete-incomplete -mmacosx-version-min=10.9 -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

```

**Comment by rfranke** [comment]
If you need these changes to build a functioning 5.8 app, then I'm of course fine with it.

Unfortunately it doesn't help me -- it adds a problem with libexpat, see #5552. I have never been able to package a functioning RT app on my system, even though the cmake process runs nicely and builds a fully functioning executable in the build directory. I hope that my problems with packaging an app are not intrinsic to macOS, but can somehow be solved by rigorously following `otool -L` links and cmake settings.

Another question: Why did you "harden app to /Applications"?
In my case, I have the officially released binaries under /Applications and test own bundles in the build directory -- this doesn't work anymore now.

**Comment by rfranke** [comment]
OK, the libexpat problem disappears if I copy RawTherapee.app to /Applications, i.e. is related to the now hardcoded directories in the changed:
```
msg "Registering @rpath into the executable:"
echo "   install_name_tool -add_rpath /Applications/RawTherapee.app/Contents/Frameworks '${MACOS}/bin/rawtherapee-bin'" | bash -v
echo "   install_name_tool -add_rpath /Applications/RawTherapee.app/Contents/Frameworks '${EXECUTABLE}-cli'" | bash -v
for frameworklibs in ${CONTENTS}/Frameworks/* ; do
    echo "   install_name_tool -delete_rpath /opt/local/lib '${frameworklibs}'" | bash -v
    echo "   install_name_tool -add_rpath /Applications/RawTherapee.app/Contents/Frameworks '${frameworklibs}'" | bash -v
done
```
What is the reason for this hard coding, including also `/opt/local/lib`, i.e. MacPorts?

Three problems are remaining for my self built app package. They are not present after `make install`, but appear with `make macosx_bundle`. They are the same with or without this PR:

1. the directory browser does not show small triangles anymore
2. cannot access memory cards when starting the app (it works when starting from a console)
3. need to remove `export DYLD_LIBRARY_PATH="${lib}"` to avoid the error
```
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libarchive.2.dylib
  Expected in: /Applications/RawTherapee.app/Contents/Frameworks/libiconv.2.dylib
 in /usr/lib/libarchive.2.dylib
Abort trap: 6
```

**Comment by Benitoite** [comment]
@rfranke 
1. do share/icons make it over? 
2. How are you trying to access the memory card? Try clicking where the little triangle is supposed to be.
3. Changed to `DYLD_FALLBACK_LIBRARY_PATH`

I've put in hardcoded paths for sandboxing with hardened runtime.  It is a more secure paradigm and less prone to corruptions (only one signatory at a time / no simultaneities in the com.rawtherapee container).

**Comment by rfranke** [comment]
1. Yes, Resources/share/icons contains `Adwaita` and `hicolor`.

2. Access to memory card has to do with System Preferences... -> Security & Privacy settings. Other apps trigger a popup dialog asking for permission and register themselves there. RT does not do this :-(
When starting from command line, then the terminal takes care about permissions.

3. `DYLD_FALLBACK_LIBRARY_PATH` works :-)

What is the motivation for new hardcoded paths?

**Comment by Benitoite** [comment]
@rfranke The entitlement to utilize relative paths is not allowable in the `-o runtime` signature used on objects desitined for notarization.

**Comment by rfranke** [comment]
The last commit efd28baa3a440e5b110c14e8cc3f9f629df79f3c looks good -- shall fix a remaining issue with liblensfun in my app package. I won't be able to do further tests the next three days.

**Comment by Benitoite** [comment]
After much rebuilding, there is a new build to test (now on the 5.8 tag)

https://kd6kxr.keybase.pub/RawTherapee_OSX_10.9_64_5.8.zip

**Pull request merged**
