### PR TITLE
Update Deutsch locale

### PR DESCRIPTION
**Pull request by TooWaBoo**

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Can anybody merge this, please?
Should I ping someone for new updates in the future?

**Comment by Beep6581** [comment]
I don't merge Deutsch updates since we have native German-speakers on the team.

**Comment by TooWaBoo** [comment]
OK, so I will ping @heckflosse

**Comment by Beep6581** [comment]
@TooWaBoo @heckflosse and I agreed in IRC that I (or anyone) will blindly merge the Deutsch updates in the future, and any eventual corrections can be done afterwards.

**Comment by TooWaBoo** [comment]
OK

**Pull request merged**
