### PR TITLE
Add `IdleRegister` to deal with destruction while idle func is queued

### LINKED ISSUE #3673: rawtherapee: crash when F4 is pressed to move to the next image
Built from source:

Version: 5.0-r1-gtk3
Branch: dev
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: cc 6.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: relwithdebinfo
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O2 -g -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

On Debian Testing (up-to-date)

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _int_realloc (av=av@entry=0x7f98f0000020, oldp=oldp@entry=0x7f98f0001ba0, 
    oldsize=oldsize@entry=64, nb=nb@entry=96) at malloc.c:4327
4327	malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9955d89fc0 (LWP 27633))]

(gdb) bt
#0  _int_realloc (av=av@entry=0x7f98f0000020, oldp=oldp@entry=0x7f98f0001ba0, 
    oldsize=oldsize@entry=64, nb=nb@entry=96) at malloc.c:4327
#1  0x00007f994f18e539 in __GI___libc_realloc (oldmem=0x7f98f0001bb0, bytes=80)
    at malloc.c:3080
#2  0x00007f994bb36342 in ?? () from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#3  0x00007f994bb3754e in ?? () from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#4  0x00007f994bb38f62 in pixman_region32_union ()
   from /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#5  0x00007f9952fe04f7 in cairo_region_union ()
   from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00007f9953b689cc in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007f995418d092 in gtk_widget_queue_draw_area ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007f995419458a in gtk_widget_queue_draw ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007f99541949a8 in gtk_widget_queue_resize ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007f9954176665 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007f99550d3f75 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f99550e5f82 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f99550eebcc in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f99550eefaf in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f995403a425 in gtk_list_store_remove ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007f995403ab9f in gtk_list_store_clear ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00005571cac0c509 in History::initHistory (this=0x5571d07f1800)
    at /source/RawTherapee.git/rtgui/history.cc:160
#18 0x00005571cac114a0 in History::procParamsChanged (this=0x5571d07f1800, 
    params=0x5571d1da0850, ev=<optimized out>, descr=..., paramsEdited=0x0)
    at /source/RawTherapee.git/rtgui/history.cc:238
#19 0x00005571cacef677 in ToolPanelCoordinator::profileChange (
    this=<optimized out>, nparams=<optimized out>, 
    event=rtengine::EvPhotoLoaded, descr=..., paramsEdited=<optimized out>)
    at /source/RawTherapee.git/rtgui/toolpanelcoord.cc:456
#20 0x00005571cacba4b2 in ProfilePanel::initProfile (this=0x5571d0785f00, 
    profileFullPath=..., lastSaved=lastSaved@entry=0x5571d2ebef80)
    at /source/RawTherapee.git/rtgui/profilepanel.cc:766
#21 0x00005571caadd723 in EditorPanel::open (this=0x5571ce6184c0, 
    tmb=0x7f991c07c4e0, isrc=<optimized out>)
    at /source/RawTherapee.git/rtgui/editorpanel.cc:868
#22 0x00005571caad85c7 in FilePanel::imageLoaded (this=0x5571cbf26d90, 
    thm=0x7f991c07c4e0, pc=<optimized out>)
    at /source/RawTherapee.git/rtgui/filepanel.cc:288
#23 0x00005571caad993f in sigc::internal::signal_emit0<bool, sigc::nil>::emit (
    impl=0x5571cfaf4970) at /usr/include/sigc++-2.0/sigc++/signal.h:709
#24 sigc::signal0<bool, sigc::nil>::emit (this=0x7f98f8008880)
    at /usr/include/sigc++-2.0/sigc++/signal.h:2804
#25 ProgressConnector<rtengine::InitialImage*>::emitEndSignalUI (
    data=0x7f98f8008880)
    at /source/RawTherapee.git/rtgui/progressconnector.h:78
#26 0x00007f9954dfa6aa in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f9954dfaa60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f9954dfad82 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f995403dce5 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007f99525b0fb1 in Gtk::Main::run(Gtk::Window&) ()
   from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
#31 0x00005571caa685fd in main (argc=<optimized out>, argv=<optimized out>)
    at /source/RawTherapee.git/rtgui/main.cc:377
```

### PR DESCRIPTION
**Pull request by Floessie**
This adds a little helper class to `guiutils.*` that unregisters
in-flight idle functions queued by `IdleRegister::add()`. It's best
to call `IdleRegister::destroy()` in the destructor of the class
owning the `IdleRegister` instance. Otherwise make sure, it is the
last member which will be deleted first.

`Resize` now makes use of this new facility in `setDimensions()`, which
also fixes #3673.

### CODE REVIEW

**Comment by Floessie** [comment]
@Hombre57 @heckflosse @Beep6581 That's it for this PR. Please test. Replacing `gdk_threads(enter|leave)()` in other places shouldn't be part of this PR, as #3673 needs to be fixed soon.

**Comment by Hombre57** [comment]
@Floessie Very nice work ! But do you have some recommendations on how to test this branch ?

**Comment by Beep6581** [comment]
@Floessie I locally merged `dev` into `idle_register` and tested, found no issues.

**Comment by harshula** [comment]
@Floessie Thanks for fixing the crash so quickly! I tested a build with your patch. No crashes.

**Pull request merged**
