### PR TITLE
Update TooWaBlue theme to v 2.54/2.55, vertical togglebuttons

### PR DESCRIPTION
**Pull request by TooWaBoo**
Reason: "New middle gray preview background color and vertical togglebuttons" #4029 
@Beep6581 
Merge this together with above PR, please.

### CODE REVIEW

**Comment by Beep6581** [comment]
@TooWaBoo good that you noticed a problem yourself, I was going to bring this up once a patch was decided on, but... what problem does this address? There were two that I noticed:
1. All of the crop mask and background color buttons take up too much space,
2. The "R" button specifically becomes much wider than the other G, B, L and F buttons when it directly follows the separator in the `bgcolor-h` branch, as you can see in this screenshot: https://user-images.githubusercontent.com/5844619/29497373-ea77030e-85e6-11e7-89aa-37f6192879d2.png

**Comment by TooWaBoo** [comment]
I've fixed the "R" and "Focus" button. The G,B,L... buttons have the same width like in the current theme. I know, they are a bit big, but this is a compromize for higher dpi. They would become too small on those monitors, 'cause the images won't grow.

**Comment by TooWaBoo** [comment]
I was wrong, the width of the G,B,L... buttons have changed, 'cause the images became bigger. I'll change it.

**Comment by TooWaBoo** [comment]
Now it looks like this: 
grafik

**Pull request merged**
