### PR TITLE
Enhanced version of the "L*a*b* regions" color toning

### PR DESCRIPTION
**Pull request by agriggio**
Adding mask blur and and ASC-CDL controls. As discussed on IRC, for consideration for 5.5. Note that there's no problem of backwards compatibility as the new tool has not been released yet (in an "official" version, I mean).

A quick video of the new features:
https://filebin.net/5hf4veuwgjxu385n/Peek_2018-11-21_11-01.mp4?t=qmayc4cd

### CODE REVIEW

**Comment by Beep6581** [comment]
If you would like this in 5.5 then please commit by tomorrow, else we will have to bump it to 5.6.

**Comment by agriggio** [comment]
I can merge right away

**Comment by Beep6581** [comment]
@agriggio could you add a note about the ASC-CDL feature to our release notes discussion in the forum?

**Comment by agriggio** [comment]
ok

**Pull request merged**
