### PR TITLE
Add a 13:18 photo paper crop aspect ratio

### PR DESCRIPTION
**Pull request by shapirus**
There is a standard photo paper format 13x18 cm. This commit makes it easier to process pictures to be printed on this paper.

### CODE REVIEW

**Comment by Thanatomanic** [comment]
I see no reason why we couldn't add this, except maybe that the list gets longer.

**Comment by shapirus** [comment]
This time it sounds okay, because it's a standard paper format, but ideally, this should be user-configurable, because some people will have their custom, non-standard, not useful for other users, aspect ratios that they will use more than once, and doing this every time via unchecking the 'lock ratio' option and then entering numbers and selecting 'current ratio' is tedious.

Probably a new feature such as "right click -> add custom aspect ratio" could be implemented, or at least a possibility to define new custom ratios via a config file. Do you think it's a good idea to open a feature request issue about this?

**Comment by Thanatomanic** [comment]
@shapirus This issue has already been filed here https://github.com/Beep6581/RawTherapee/issues/5693, feel free to chime in on a good solution for this.

**Comment by shapirus** [comment]
Nice, thank you.

Also, I have just realized that I will probably need to change the actual aspect ratio calculation a little, because it's a question of the actual dimensions of the paper. It's called both 13x18 cm and 5"x7" on the market as though it were interchangeable, while mathematically 13/18 != 5/7, so the actual ratio is a question. I will receive some paper (marketed as 13x18) later this week and make a change, if necessary.

It may be possible that we will have to add support for both formats, if they are slightly different, for example, in EU and US.

p.s. so far it sounds like the actual paper size is:

1) based on imperial units (I have just measured some 10x15 cm paper that I have, which is really more like 4"x6", but not precisely);
2) may vary

which really suggests that the list of supported crop aspect ratios should be customizable. We may still add some suitable-for-most defaults, however.

**Pull request merged**
