### PR TITLE
Check for double backslash to enable output to network paths

### PR DESCRIPTION
**Pull request by johenning**
Fixes Issue #4044

### CODE REVIEW

**Comment by Hombre57** [comment]
I don't manage to use a network path here ("\\127.0.0.1\Mes vidéos" on Win7), while it work when I type this path in a windows' explorer. How do you manage to use this kind of path ?

Beside that, could you update your identation please ? We uses spaces only, 4 spaces per tab.

**Comment by johenning** [comment]
I'm not sure I follow. As far as I know, "\127.0.0.1\..." is not a network path. \ is equivalent to C:\ and thus refers to C:\127.0.0.1
In any case, I am only modifying the behavior if the path starts with a double backslash. Any path like yours is treated just like it was before.

I will update the indentation, didn't pay attention to that.

**Comment by Hombre57** [comment]
@johenning Sorry, it was a typo, I meant "\\127.0.0.1\Mes vidéos" which is the kind of network path you're using. RT doesn't **browse** to that path at first, which I find strange since it works for you... So I can't test your patch for now.

**Comment by johenning** [comment]
@Hombre57 If you type \\\\\ it shows up correctly ;)

Could you try "\\\127.0.0.1\Mes vidéos\\"? It doesn't seem to work without the trailing backslash. Also make sure the path contains at least one recognized file, as folders aren't displayed.

**Comment by Hombre57** [comment]
@johenning I've tried and it works fine, minus an error message : "(rawtherapee.exe:5584): Gtk-CRITICAL **: gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed"

However that shouldn't prevent merging this PR.

**Pull request merged**
