### PR TITLE
Speedup for Flat-Field correction, fixes #3253, also introduces chang…

### LINKED ISSUE #3253: Speedup for Flat-Field correction
Issue opened to get an Issue number. I'll post first speedups tomorrow or after the weekend

### PR DESCRIPTION
**Pull request by heckflosse**
…ed formatting to switch statements caused by new astyle profile

Of course I will remove the StopWatches before merging

### CODE REVIEW

**Comment by Floessie** [comment]
@heckflosse Here is how to get rid of that ugly macros:
```patch
diff --git a/rtengine/ffmanager.cc b/rtengine/ffmanager.cc
index c5461f3..f3f78cb 100644
--- a/rtengine/ffmanager.cc
+++ b/rtengine/ffmanager.cc
@@ -16,18 +16,39 @@
  *  You should have received a copy of the GNU General Public License
  *  along with RawTherapee.  If not, see <http://www.gnu.org/licenses/>.
  */
+
+#include <algorithm>
+
 #include "ffmanager.h"
 #include "../rtgui/options.h"
 #include "rawimage.h"
 #include "imagedata.h"
 
-#define PIX_SORT(a,b) { if ((a)>(b)) {temp=(a);(a)=(b);(b)=temp;} }
-#define med5(a0,a1,a2,a3,a4,median) { \
-p[0]=a0; p[1]=a1; p[2]=a2; p[3]=a3; p[4]=a4; \
-PIX_SORT(p[0],p[1]) ; PIX_SORT(p[3],p[4]) ; PIX_SORT(p[0],p[3]) ; \
-PIX_SORT(p[1],p[4]) ; PIX_SORT(p[1],p[2]) ; PIX_SORT(p[2],p[3]) ; \
-PIX_SORT(p[1],p[2]) ; median=p[2] ;}
+namespace
+{
 
+template<typename T>
+void condSwap(T& a, T&b)
+{
+    if (b < a) {
+        std::swap(a, b);
+    }
+}
+
+template<typename T>
+T med5(T a0, T a1, T a2, T a3, T a4)
+{
+    condSwap(a0, a1);
+    condSwap(a3, a4);
+    condSwap(a0, a3);
+    condSwap(a1, a4);
+    condSwap(a1, a2);
+    condSwap(a2, a3);
+    condSwap(a1, a2);
+    return a2;
+}
+
+}
 
 namespace rtengine
 {
@@ -217,7 +238,6 @@ void ffInfo::updateRawImage()
 #endif
 
         for (int i = 0; i < H; i++) {
-            int p[5], temp;
             int iprev = i < 2 ? i + 2 : i - 2;
             int inext = i > H - 3 ? i - 2 : i + 2;
 
@@ -225,8 +245,7 @@ void ffInfo::updateRawImage()
                 int jprev = j < 2 ? j + 2 : j - 2;
                 int jnext = j > W - 3 ? j - 2 : j + 2;
 
-                med5(ri->data[iprev][j], ri->data[i][jprev], ri->data[i][j],
-                     ri->data[i][jnext], ri->data[inext][j], cfatmp[i * W + j]);
+                cfatmp[i * W + j] = med5(ri->data[iprev][j], ri->data[i][jprev], ri->data[i][j], ri->data[i][jnext], ri->data[inext][j]);
             }
         }
 
```

Only compile-tested, though.

HTH,
Flössie

**Comment by heckflosse** [comment]
@Floessie I know, but that's only one occurrence of this median macro stuff. Wouldn't it be better to clean all of them in a separate branch?

**Comment by Floessie** [comment]
@heckflosse Sure, I wasn't aware of the fact, that this was copy-pasted here. I can take care of that. Where shall I put the code? `rtengine/utils.h`, or `rtengine/rt_math.h`, or somewhere else?

**Comment by heckflosse** [comment]
@Floessie Maybe use the already existing rtengine/median.h ?

**Comment by heckflosse** [comment]
@Floessie There are also some wrong named median functions in code iirc. For example med3 often is in fact a median of 9 (median of 3x3). We should clean up that too.

**Comment by heckflosse** [comment]
@Floessie If you work on this, you should start with an overview of all occurrences of median functions in rt to avoid unnecessary work.

Example:
rtengine\dirpyrLab_denoise.cc has med3 and med3x3. But the whole file is deprecated. We can eliminate it from rt source and remove the corresponding line in rtengine/improcfun.h too.

**Comment by heckflosse** [comment]
@Floessie Last Hijack of this PR. Let's open a new Issue for further discussion of median stuff

**Pull request merged**
