### PR TITLE
some tweaks to the colour propagation method for highlight recovery

### PR DESCRIPTION
**Pull request by agriggio**
I've been experimenting with some tweaks to the colour propagation algorithm, with the aim to make it "smoother" and more realistic (or at least eye pleasing to my eyes :-) in some corner cases. In general, I think that the current behaviour is too aggressive on the fully-blown highlights (i.e. when all the channels are clipped), leading to unrealistic results when pushed to the extremes. Also, it can produce some artifacts in some other corner cases.

My changes are conceptually simple, and produce results that look better to me. Here is a quick gallery, feedback is highly welcome!

https://filebin.net/album/wg6dhhbns6zn72bi

As usual, I went for functionality, not considering performance too much. There's definitely room for improvement there.

### CODE REVIEW

**Comment by Beep6581** [comment]
Looks good!

**Comment by sguyader** [comment]
Great! I tend to use color propagation quite a lot.

**Comment by agriggio** [comment]
any objection to merging? or should we wait a bit more?

**Comment by Beep6581** [comment]
Wise man once wrote, 
> the best way to know (and to find bugs) is to test this more extensively

:+1:

**Comment by heckflosse** [comment]
@agriggio I don't know which of the latest commits causes this, but I get an error now in `5.4-102-g15813abb`:

```
Z:/H2/rt54new/rtengine/rtthumbnail.cc: In static member function 'static rtengine::Thumbnail* rtengine::Thumbnail::loadQuickFromRaw(const Glib::ustring&, rtengine::RawMetaDataLocation&, rtengine::eSensorType&, int&, int&, int, bool, bool)':
Z:/H2/rt54new/rtengine/rtthumbnail.cc:336:27: error: 'forHistogramMatching' was not declared in this scope
     if (inspectorMode && !forHistogramMatching && settings->thumbnail_inspector_mode == Settings::ThumbnailInspectorMode::RAW) {
                           ^~~~~~~~~~~~~~~~~~~~
Z:/H2/rt54new/rtengine/rtthumbnail.cc:400:14: error: 'forHistogramMatching' was not declared in this scope
         if (!forHistogramMatching && settings->thumbnail_inspector_mode == Settings::ThumbnailInspectorMode::RAW_IF_NOT_JPEG_FULLSIZE && float(std::max(w, h))/float(std::max(ri->get_width(), ri->get_height())) < 0.9f) {
              ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [rtengine/CMakeFiles/rtengine.dir/build.make:1983: rtengine/CMakeFiles/rtengine.dir/rtthumbnail.cc.obj] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[1]: *** [CMakeFiles/Makefile2:179: rtengine/CMakeFiles/rtengine.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
```

**Comment by agriggio** [comment]
@heckflosse hmmm, looking. Thanks for spotting, and sorry

**Comment by agriggio** [comment]
should be fixed now

**Comment by heckflosse** [comment]
Fix confirmed. Thank you

**Pull request merged**
