### PR TITLE
Update TooWaBlue themes

### PR DESCRIPTION
**Pull request by TooWaBoo**

### CODE REVIEW

**Comment by Beep6581** [comment]
@TooWaBoo since the purpose of the new theme is not just to look nice, as is the case with the other themes, but to actually fulfill a technical need, maybe we should use a more descriptive name?

Maybe @Desmis and Elle have a better idea, here are some of mine:
* Middle Gray
* Average Surround

**Comment by Desmis** [comment]
I think "average surround" is a good idea...

We should modify Rawpedia for Ciecam, to mention it, as a technical optimization of "viewing conditions"

jacques

**Comment by TooWaBoo** [comment]
@Beep6581 

You can change the name to everything you want. It's up to you to decide.

**Comment by Beep6581** [comment]
Theme renamed and RawPedia updated:
http://rawpedia.rawtherapee.com/Preferences#Theme

**Pull request merged**
