### PR TITLE
moved softlight later in the pipeline

### PR DESCRIPTION
**Pull request by agriggio**
Gives a better result, more suitable to the final fine-tuning

### CODE REVIEW

**Comment by Beep6581** [comment]
> Gives a better result

@agriggio I don't know how to test for a better result, but it compiles and works fine, no issues found.

**Comment by agriggio** [comment]
well, if you trust me on this, I'll just merge :-)

**Comment by Thanatomanic** [comment]
No comments here, +1 for merge

**Comment by Beep6581** [comment]
@agriggio I trust you, +1 for merge :)

**Pull request merged**
