### PR TITLE
Improve wavelet contrast with sliders instead of curve issue 5791

### PR DESCRIPTION
**Pull request by Desmis**
I have change the behavior...
The main problem since  origin, is a GUI problem...
I think now it is solved

jacques

### CODE REVIEW

**Comment by ff2000** [comment]
Thank you @Desmis, the sliders are functional now.
However there seems to be a bug with opening previously edited files.
I created a video: https://youtu.be/P_ZATVKy5q4
File first edited with RT-5.8, then opened in RT from this PR. You see that the gras area left of the tree doesn't show the effect of the wavelet tool, instead the trees are affected. I have to disable and reenable the contrast tool to get it displayed correctly.

**Comment by Desmis** [comment]
@ff2000 

I think it will **be almost impossible to ensure compatibility** .... The operation is different...
To sum up, in 2014 I imagined an operation with the inverted "shadows threshold" slider...not intuitive at all

When @TechXavAL  begin to write documentation, he showed the difficulties of understanding.

After several stages **I had the wrong idea of the curve, which I fully assume**.

All these difficulties come from the GUI and my weak knowledge in this field.

Since one week, I got down to the GUI and found this solution which seems to work properly and is intuitive.

In the first step, I take into account the position of "wavelet level"
This value this sets the maximum of the 2 sliders
Then, the current value of "Finer levels" is passed to "Coarser levels" to set the minimum value

Now to sum up:
for "finer levels" : Only levels beyond the chosen value will be affected by the highlight luminance range. 
for "coarser levels": Only levels above the chosen value and selected 'wavelet levels' will be affected by the shadow luminance range.

**Comment by ff2000** [comment]
> I think it will **be almost impossible to ensure compatibility** .... The operation is different...

I understand that, I don't mind if the effect of the tools in RT-git is slightly different from RT-5.8.
The problem I raised in the previous reply to this PR is on a different issue.
The original issue #5791 seems to be fixed. There is just one small issue left when loading a file previously edited in RT-5.8. I can workaround the issue by disabling and then enabling the wavelet contrast tool, as shown in the video.

**Comment by Beep6581** [comment]
@Desmis could you delete your branches which have been merged and are no longer needed?

**Comment by Desmis** [comment]
@Beep6581 
Done :)

**Pull request merged**
