### PR TITLE
French for Perspective - Film negative - Cam16 and Jz

### PR DESCRIPTION
**Pull request by Desmis**

### CODE REVIEW

**Comment by Desmis** [comment]
it's just the translation for !
Perspective
Fim negative
Color appearance (Cam16 & JzczHz)

Jacques

**Comment by Desmis** [comment]
@Thanatomanic 
Hello
Can I merge this Pull-Request or do I have to wait ?

This is an updated French translation of
* Film negative (already untranslated for 5.8)
* Perspective
* last modifications made on "Local adjustments" (Cam16, JzCzH, sigmoid...)
Jacques

**Comment by Thanatomanic** [comment]
Feel free to merge Jacques!

**Comment by Desmis** [comment]
OK, I just mege now :)

Thank you

jacques

**Pull request merged**
