### PR TITLE
locallab: speedup for blur, also some cleanups

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by heckflosse** [comment]
Processing times with this pp3 on a D850 NEF
[Nikon - D850 - 14bit compressed (Lossless) (3_2).NEF.pp3.txt](https://github.com/Beep6581/RawTherapee/files/3073497/Nikon.-.D850.-.14bit.compressed.Lossless.3_2.NEF.pp3.txt)

```
                               before              after
open                            50 ms              40 ms
zoom in to 100%(z)            2390 ms              70 ms
open detail window            2490 ms               3 ms
full processing               1830 ms            1530 ms
```

**Comment by Desmis** [comment]
@heckflosse 
I just tested

Same sppedup as others speedup, same improvments as you

No differences visble on TIF

Very very very small diffreences with layers diffrences

Good job, as usual :)

jacques

**Comment by heckflosse** [comment]
@Desmis Jacques, thanks for testing :+1:

**Comment by Desmis** [comment]
@heckflosse 
Hello Ingo
I found a bug with "Blur"

When the spot is completely outside the preview (zoom...), the system crash.
Could you have a look :)

Thank you

**Comment by heckflosse** [comment]
@Desmis I will have a look

**Comment by heckflosse** [comment]
@Desmis Jacques, can I push a fix?

**Comment by Desmis** [comment]
You can :)

Le lun. 15 avr. 2019 15:44, Ingo Weyrich <notifications@github.com> a
écrit :

**Comment by heckflosse** [comment]
pushed

**Comment by Desmis** [comment]
@heckflosse 
Ingo
Confirm fixed, thank you :)

jacques

**Pull request merged**
