### PR TITLE
Review JzCzHz - Various changes to locallabtools2 - default - french

### PR DESCRIPTION
**Pull request by Desmis**
Hello
I did a full review of the experimental JzCzHz module.
I found anomalies (often inconsistent) with similar "Log encoding" topics
I touched up slightly "locallabtools2" and also "language" default (english) and french.

I think now everything is OK in terms of titles, labels, tooltips

Jacques

### CODE REVIEW

**Comment by Desmis** [comment]
@Thanatomanic 

If no one objects, I will merge this Pull Request soon 


This is the only change regarding "default", because the **text was wrong**, using the same "tooltip" as "Log encoding", where there is an "Automatic" button . This change applies to the 2 modules Cam16 and JzCzHz ("auto" button in "Scene" conditions")

TP_LOCALLAB_LOGAUTOGRAYJZ_TOOLTIP;Automatically calculates the ‘Mean luminance’ for the scene conditions.

Jacques

**Comment by Thanatomanic** [comment]
Go ahead @Desmis !

**Comment by Desmis** [comment]
@Thanatomanic 
OK thank you
Even if I don't speak German, I made the small adaptation. On the other hand the Japanese??


I will merge soon, as soon as the builds are finished

Jacques

**Comment by Thanatomanic** [comment]
I will venture a guess that it should be:
`TP_LOCALLAB_LOGAUTOGRAYJZ_TOOLTIP;撮影画像の環境に関する平均輝度が自動的に計算されます。`
This gives a good translation in Google Translate.

What do you think @Yz2house?

**Comment by Desmis** [comment]
@Thanatomanic 
i think it can be done after merge this PR... Very easy to do

Jacques

**Pull request merged**
