### PR TITLE
Turn Listeners into abstract interfaces

### PR DESCRIPTION
**Pull request by Floessie**
Hi,

When working on #4446 I deliberately changed `SaveAsDialog::formatChanged(Glib::ustring)` to `SaveAsDialog::formatChanged(const Glib::ustring&)` unaware of the fact it was derived. It compiled without a warning and I had to find out for myself, why the dialog behaved strangely.

The problem was the fact, that the `FormatChangeListener` had a default implementation for `formatChanged()`. I then found out, that many of the Listeners are implemented in the same way, making it impossible to detect a signature miss.

One solution would be the marking of all derived methods with `override`, which can be automatically and globally done by `clang-tidy`. But this would only manifest the status quo and not reveal signature misses we have today or tomorrow.

So I went for a IMHO better solution: I made almost all Listeners abstract. This uncovered Listeners that weren't used anymore and will force future changes to comply with the base class. Fortunately, there were no signature misses in the code so far.

"Almost all" means, there were two or three Listeners that are more than just callback classes. I'll have to think a bit more about them.

During this code revision I also made the usual `const` and whitespace corrections. One outcome is that `LUT<T>::operator =()` is finally `const` correct. :tada:

There are still things to improve, and I'll probably add some commits here. Please feel free to do the same.

I know this is a big one, but it's certainly worth it. :smile: 

Best,
Flössie

### CODE REVIEW

**Review by heckflosse — COMMENTED** [review]
@Floessie is rtetest.cc still needed or can we throw it away?

**Comment by Floessie** [comment]
@heckflosse Ingo, I think you're right, I found no reference to it at first glance.

**Comment by Floessie** [comment]
I won't be at home next week, so this will lose momentum. If someone likes to chime in, these are the items still left on my agenda:

- [`CurveListener`](https://github.com/Beep6581/RawTherapee/blob/abstract-listeners/rtgui/curvelistener.h#L26): Moving `multi` down to the implementations is easy. `blendPipetteValues()` is more of a problem.
- [`PointerMotionListener`](https://github.com/Beep6581/RawTherapee/blob/abstract-listeners/rtgui/pointermotionlistener.h#L22): Ideas welcome how to cope with `sig_cycle_(rgb|hsv)` (@Thanatomanic?).
- [`ThesholdAdjusterListener`](https://github.com/Beep6581/RawTherapee/blob/abstract-listeners/rtgui/thresholdadjuster.h#L32): This is already turned into an abstract interface, but this interface is too broad. IMHO an `enum class Type` and four `double`s would do, but I've not yet digged deeper.

Best,
Flössie

**Comment by Thanatomanic** [comment]
@Floessie Interesting you ping me, because I have difficulty grasping the point of your PR. It looks good if it got rid of unused stuff and is 'better' code now, but to say I can contribute here is a stretch 😉 

FWIW, if your changes make no functional difference but improve the code nevertheless, it could be merged now and improve the remaining points later?

**Comment by Floessie** [comment]
@Thanatomanic 
> It looks good if it got rid of unused stuff and is 'better' code now

Well spotted. :smile: I pinged you, because I had a vage recollection that you're well involved into sigc++ signals and might have a good idea on how to organize this differently (and didn't want to bother Hombre). Never mind. After all, it's more an organizational than a signalling problem.

> FWIW, if your changes make no functional difference but improve the code nevertheless, it could be merged now and improve the remaining points later?

I wouldn't mind. It shouldn't make a functional difference and is purely janitorial.

**Comment by Beep6581** [comment]
From a 5.5 release point of view, and considering that it affects 159 files, it would be better to merge this sooner rather than later.

**Comment by Floessie** [comment]
@Beep6581 If there's a consensus it's up to you to hit the merge button.

**Comment by Beep6581** [comment]
@agriggio @heckflosse @Hombre57 @Thanatomanic please :+1: the comment if you agree to merge.

**Comment by Beep6581** [comment]
Ping @agriggio

**Comment by agriggio** [comment]
sorry, I didn't notice this, my bad :-(
no objections to merge :+1:

**Comment by Beep6581** [comment]
Merged.

@Floessie I left the branch in case you needed it, feel free to hit the "Delete branch" button otherwise.

**Comment by Floessie** [comment]
@Beep6581 I can open a new branch if necessary. Thanks!

**Pull request merged**
