### PR TITLE
Multithreaded sony_arw2_load_raw()

### PR DESCRIPTION
**Pull request by heckflosse**
I will remove the timing code before I merge.
Reviews are welcome.

### CODE REVIEW

**Comment by heckflosse** [comment]
On irc @Beep6581 (sony shooter) gave a :+1: to merge this pr for 5.3

@agriggio @Floessie What's your opinion?

**Comment by Floessie** [comment]
@heckflosse Ingo, I trust your expertise on this. I hope, you've tested the `!defined( _OPENMP )` and/or `!defined( MYFILE_MMAP )` case. The `new (std::nothrow)` construct is something new for me to memorize. Thanks. So, if it still compiles without those defines, I see nothing to argue against merging.

**Comment by agriggio** [comment]
haven't had time to test, but I have nothing against merging! :+1:

**Comment by heckflosse** [comment]
@Floessie I tested the `!defined` cases.

**Pull request merged**
