### PR TITLE
Add BENCHFUN to more places

### PR DESCRIPTION
**Pull request by gatoatigrado**
I was interested in improving performance, and I think getting better benchmarks might be helpful. I tried `WITH_PROF=ON`, but the output I got wasn't very useful -- a large chunk of time is missing, and calls like `sony_arw2_load_raw()` are quite off (`BENCHFUN` and print statements reveal it taking a few hundred milliseconds, not 4.78 seconds). So I added BENCHFUN to a few more functions which look like they'll take time. One downside of this, however, is that sometimes timers are nested ... I could add some more code to display more user-friendly output of that if desired.

(NOTE: gprof invocation is here, LMK if I'm doing something wrong --
 https://gist.github.com/gatoatigrado/6fc0cc7dcac58ef759aa8d2cce17b3e9)

An example of the new output is here (https://gist.github.com/gatoatigrado/c0009ec97b64ecbc8def720c28a0de3e), and here are some pie charts (just from google sheets)

flickr06
flickr06
flickr06

Overall ExecCMSTransform is taking the most time ... if you all want to point me to a thread on that, I'd love to discuss. I see a note here (https://github.com/Beep6581/RawTherapee/issues/1559) that things got faster in version 2.4, but I seem to have version 2.6 installed so probably I'm already seeing that benefit.

Finally, I noticed that multi-core operation is not very much faster; my timings with OpenMP were like 23.4s user time on the default RawTherapee profile (sum over all cores, using a Haswell i7-4790K), whereas single-threaded operation is around 8.2s user time on the default RawTherapee profile. Since my use case can parallelize across images, I think I might do that & just use the single-threaded version. But maybe multi-threading can be made more efficient (coarser tasks?).

Cheers!

### CODE REVIEW

**Comment by heckflosse** [comment]
@gatoatigrado 
lcms (ExecCMSTransform) is indeed a bottleneck.
sony_arw2_load_raw() scales well on my machine (if the arw is loaded from SSD or file system cache).
If the arw is loaded from network or HD, it does not scale well

Can you elaborate which functions do not scale well on your machine?

**Comment by heckflosse** [comment]
@gatoatigrado 

> amaze_demosaic_RT took 1446 ms

that sounds too much for amaze demosaicing an arw file.
I just tried on my rusty AMD FX-8350 amaze demosaicing a 42.3 MP arw from Sony 7RM3.
That takes 700 ms

**Comment by heckflosse** [comment]
@gatoatigrado I just saw that you used rawtherapee-cli for your tests. That of course has some overhead you won't have when you process the images in rt queue. Can you verify your measurements in rt queue?

**Comment by heckflosse** [comment]
@gatoatigrado About amaze demosaic: Long time ago we optimized amaze demosaic to perform well on my AMD FX8350 and also on an I7 6 cores/ 12 threads. One critical part here is the tile size, #defined by AMAZETS in amaze_demosaic_RT.cc 
[For reference](https://github.com/Beep6581/RawTherapee/issues/2920)

**Comment by gatoatigrado** [comment]
Hi @heckflosse, thanks for all of the comments. Since I am relatively new, I wouldn't be surprised if my setup is just wrong. FWIW I am building with,

```
cmake -DCMAKE_BUILD_TYPE="relwithdebinfo" \
      -DPROC_TARGET_NUMBER="2" \
      -DBUILD_BUNDLE="ON" \
      -DCACHE_NAME_SUFFIX="5-dev" \
      -DWITH_LTO="OFF" -DWITH_PROF=ON -DOPTION_OMP=OFF ..
```

Just to clarify, the 700ms you mention before is from running AMaZE on a single thread?

I can try just `release` instead of `relwithdebinfo` if you think that'd make a significant difference? IIUC the debug symbols are just stored separately and shouldn't affect performance though.

Please point me to docs or let me know how to use rt queue, I am not familiar. I don't see why the CLI version would be slower if I am getting benchmark results for the particular function though?

Alternately, if you wish to re-run my benchmark, my input is from an A7R (jelly of your mk 3 ;) i totally want one), a test file is here: https://drive.google.com/file/d/1CTX2np2yCVGxNHZohhC1ZkJ09Qe753W3/view?usp=sharing

the command line is

```
/tmp> which rawtherapee-cli
.../RawTherapee/build/relwithdebinfo/rawtherapee-cli
/tmp> time rawtherapee-cli -Y -t -c /tmp/test.arw                                       
```

Some kind of "not retained" trigger was being hit so I had to hack `main-cli.cc`, please LMK what a better way would be (https://gist.github.com/gatoatigrado/168b7f7d820c2ef9522f2d9f3a677578)

As far as `ExecCMSTransform`, I tried making just 1 call on a whim, but it didn't help. Is that just doing a colorspace transform? I don't understand why that'd be expensive...

As far as multi-threaded scaling, I can look more soon; gprof seemed to suggest `rtengine::wavelet_level<float>::AnalysisFilterHaarHorizontal` was taking an amount of time, so perhaps the task granularity for that is wrong or something.

**Comment by heckflosse** [comment]
@gatoatigrado 

> calls like sony_arw2_load_raw() are quite off (BENCHFUN and print statements reveal it taking a few hundred milliseconds, not 4.78 seconds)

In your gprof output, look at the `self seconds` column, not on the `cumulative seconds`

**Comment by heckflosse** [comment]
> Just to clarify, the 700ms you mention before is from running AMaZE on a single thread?

No, 8 threads

Edit: single thread is > 3000 ms, but my machine is limited by memory bandwidth. For that reason I don't get better scaling most of the time (except for really expensive computations (i.e. exp or log) where memory bandwidth does not matter)

**Comment by gatoatigrado** [comment]
OK, then I think the 1400ms I was getting on a single thread is pretty good. I saw the "self time" column, but still can't make sense of that (the LCMS call is too small, I'm guessing its library isn't included -- https://gist.github.com/gatoatigrado/f6870f1ba7ac6eb39a7b559d776e0593). Here is a gprof2dot output, but it also looks wonky,

graph

I'm going to try and get Google's periodic interrupt-based stacktrace profiler (https://github.com/gperftools/gperftools) to work ...

**Comment by heckflosse** [comment]
Of course, for a single function the cli version is not slower, but your time command (which you used to compare single vs. multithreaded execution) also included the start time of rt (where for example lookup tables are build an so on)

**Comment by heckflosse** [comment]
> my input is from an A7R (jelly of your mk 3 ;)
> OK, then I think the 1400ms I was getting on a single thread is pretty good.


I don't own a mk3. I used a arw from such a camera to test ;-)
Your 1400ms for a single thread are pretty good. What's the processing time if you enable all cores?

Your arw needs ~2600 ms using a single thread and ~530 ms using 8 threads on my machine (in amaze demosaic function)

About the queue: Just start rawtherapee (without the -cli), add your pictures to the queue and press the start button in queue tab.

**Comment by heckflosse** [comment]
addtoqueue

startqueue

**Comment by heckflosse** [comment]
Also I would not use -DWITH_PROF=ON at all

**Comment by heckflosse** [comment]
> As far as ExecCMSTransform, I tried making just 1 call on a whim, but it didn't help. Is that just doing a colorspace transform? I don't understand why that'd be expensive...

It's a while ago I checked why lcms is slow. At that time it turned out to be slow because it uses function pointers and expensive (exp, log, whatever) functions, which (using standard c++ libs) won't be vectorized.
But it's more than 2 years ago, that I checked that. Maybe lcms code has changed meanwhile, don't know.

**Comment by heckflosse** [comment]
@gatoatigrado btw: here's my configuration

```
cmake -DCMAKE_BUILD_TYPE="Release" -DPROC_TARGET_NUMBER="2" -DBUILD_BUNDLE="ON" -DCACHE_NAME_SUFFIX=5-dev ..
```

**Comment by gatoatigrado** [comment]
Thanks! For rt queue, I think I am running into the same issue I had to hack around with the "not retained" issue. I did get the Google profiler to work though, here's the commands (no binary modification necessary apparently),

```
> aptitude install libgoogle-perftools-dev
> export CPUPROFILE=/tmp/prof.out CPUPROFILE_FREQUENCY=1000
> rm /tmp/prof.out; LD_PRELOAD=/usr/lib/libprofiler.so rawtherapee-cli -Y -t -c /tmp/test.arw && ls /tmp/prof.out
> google-pprof --svg $(which rawtherapee-cli) /tmp/prof.out > profile.svg && google-chrome profile.svg
```

Here is a graph for single-threaded performance,

rawtherapee_profile svg

Here is a graph for multi-threaded performance,

openmp-profile svg

It looks like the LittleCMS calls are proportionally smaller in multi-threaded, but AMaZE and rgbProc are larger, so those probably scale worse. LittleCMS is still the biggest though. I don't know what `cmsGetProfileInfoASCII` is, but anything with ASCII in the name doesn't sound super fast ....

**Comment by heckflosse** [comment]
@gatoatigrado That's very interesting. I knew that lcms was a bottleneck, but that cmsGetProfileInfoASCII bottleneck new to me. Though I don't know how to improve that atm, as it's not in RT code. I will investigate nevertheless...

**Comment by heckflosse** [comment]
> It looks like the LittleCMS calls are proportionally smaller in multi-threaded, but AMaZE and rgbProc are larger, so those probably scale worse.

Yes, that's imho caused by LittleCMS calls using expensive functions (exp, log) which are not so much influenced by memory bandwidth as the simple operations in demosaic and rgbproc.

**Comment by heckflosse** [comment]
Anyway, I forgot to mention, that I really appreciate your efforts to speed up RT and that I'm not against adding more timing code (BENCHFUN)

👍

**Comment by gatoatigrado** [comment]
Thanks :). I compiled lcms from source and got a new profile, which doesn't have the "ASCII", so maybe that's a misnomer (but the time is still high).

openmp-profile svg

(this is with OpenMP).

as a general comment (I haven't dug into lcms yet), vectorization can still help for expensive functions; a coworker wrote some fast approximations for neural networks, cf https://github.com/google/sling/blob/master/sling/myelin/kernel/avx-math.cc#L245 . maybe we can do something similar.

**Comment by heckflosse** [comment]
> vectorization can still help for expensive functions

But not for external libraries which are used by RT (like lcms), or?

In rt code we we already use vectorized math functions (exp, log, sincos...) but we can't change lcms code. That's a different project...

**Comment by heckflosse** [comment]
@gatoatigrado Your graph is very interesting!

**Comment by gatoatigrado** [comment]
Yeah, I'm not exactly sure if I'll be able to make an intervention. I'm a little tempted to train a replacement in TensorFlow, but that seems like not very convenient since it'd be fixed to a particular ICC profile.

It seems the existing code calls a lot of function pointers, with non-vectorized arguments,

```
static
void _LUTeval16(register const cmsUInt16Number In[], register cmsUInt16Number Out[],  register const void* D)
{
    cmsStage *mpe;
...
             mpe ->EvalPtr(&Storage[Phase][0], &Storage[NextPhase][0], mpe);
...
}
```

iiuc this `EvalPtr` is a function pointer,

```
    _cmsStageEvalFn     EvalPtr;        // Points to fn that evaluates the stage (always in floating point)
```

```
typedef void (* _cmsStageEvalFn)     (const cmsFloat32Number In[], cmsFloat32Number Out[], const cmsStage* mpe);
```

In my experience this style is pretty much guaranteed to be slow. If it were C++ it might be possible to template in the function being called ... I don't know how receptive the lcms maintainer is to that kind of change.

**Comment by gatoatigrado** [comment]
OK, I manually inlined a few functions in LCMS and it dropped the time from ~740ms to ~670ms.

New profiling script: https://gist.github.com/gatoatigrado/158c52a8ed5f15b1b12e151d3a23ea41
LCMS diff that inlines a few functions: https://gist.github.com/gatoatigrado/5ed4f608f06a5e68586ad3e850478b10 (I think CLion changed the encoding, so ignore those weird changes to "Cache" or something)

Old traces look like this:

flickr06

New traces look like this:

flickr06

Runs:

```
# Old
oliver:/tmp> for i in {1..3}; do python ~/bin/alias/rt_profile.py 2>&1 | grep ExecCMSTransform; done
ExecCMSTransform took 740 ms
ExecCMSTransform took 748 ms
ExecCMSTransform took 758 ms
# New
oliver:/tmp> for i in {1..3}; do python ~/bin/alias/rt_profile.py 2>&1 | grep ExecCMSTransform; done
ExecCMSTransform took 677 ms
ExecCMSTransform took 668 ms
ExecCMSTransform took 666 ms
```

I guess this partly demonstrates that there is a lot of low-hanging fruit in LCMS performance-wise, but doesn't exactly give us a quick solution. I will try to do some TensorFlow modeling as well ... perhaps if we can find a convex optimization problem, running something like libsvm inline would be reasonable.

Also I think we should probably migrate this discussion to an issue ... since the Google profiler seems to provide useful graphs, perhaps we could just close/discard this pull request? Either way is fine ... I guess BENCHFUN means people don't have to install the Google profiler (I dunno how Mac/Windows compatibility is too).

**Comment by heckflosse** [comment]
@gatoatigrado I just prepared a commit which allows to set `-DWITH_BENCHMARK=ON` in cmake command (means BENCHMARK is #defined then). I'll push it soon.

**Comment by heckflosse** [comment]
@gatoatigrado I think we have two different use cases here:

1. people who know what they are doing (certainly you, maybe also me ;), Maybe also other rt developers. I have to dig into the google profiler a bit more, I have to admit.

2. normal users, which experience performance issues. For them we can provide a build with `-DWITH_BENCHMARK=ON` to detect bottlenecks, if we, as you suggested, plant some more `BENCHFUN` into the code.

**Comment by Beep6581** [comment]
When this gets merged, the compilation docs need to be updated to reflect the possibility of the
`-DWITH_BENCHMARK=ON` flag.

**Comment by heckflosse** [comment]
@gatoatigrado I committed https://github.com/Beep6581/RawTherapee/commit/11ad1dace8458a4373f74f3e37d98f2b8e56e255 a while ago

**Comment by Beep6581** [comment]
@gatoatigrado thank you for the PR! The documentation and the build scripts have been updated:
http://rawpedia.rawtherapee.com/Linux#CMake
09d020cca3020e4051cc2329d60d598af26a9806

The placement of some of these definitions can be improved, so we will now close this PR and add them in optimal places in other commits.

**Pull request closed without merging**
