### PR TITLE
Add resizing options "long edge" and "short edge"

### PR DESCRIPTION
**Pull request by Bezierr**
Compared to previous pull request, change in GUI as discussed in #5182.
Tested and apart from the (pre-existing) issue also described in #5182, everything seems to work.

### CODE REVIEW

**Comment by Thanatomanic** [comment]
Hi @Bezierr I really like what you made here. I would be up for a merge! 
Maybe @heckflosse or @Lawrence37 can take a look just to be sure?

**Comment by Lawrence37** [comment]
Looks good.

**Comment by Thanatomanic** [comment]
Thanks @Bezierr for your work. I'll make a small change to RawPedia to reflect your changes in a moment (http://rawpedia.rawtherapee.com/Resize)

**Comment by Bezierr** [comment]
You're welcome. Glad that I could contribute a little something.

**Pull request merged**
