### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via  codespell v2.0.dev0  
```
codespell -q 3 -S ./rtdata/languages -L alph,amin,autor,ba,bloc,bord,byteorder,cas,chang,childs,currentry,developpement,dof,dum,fo,foto,fro,hist,inbetween,interm,ist,iten,ith,lonly,makro,nd,ois,optio,portugues,preserv,reall,skipp,som,spred,substracted,tbe,thre,tim,ueadn,uint,unselect,vektor
```

### CODE REVIEW

**Comment by Thanatomanic** [comment]
Great! This is a one-commit PR right? Nothing further to add?

**Comment by luzpaz** [comment]
@Thanatomanic correct :smile:

**Comment by heckflosse** [comment]
@luzpaz With your next PR feel free to add your name to this section

```
Other contributors (profiles, ideas, mockups, testing, forum activity, translations, tutorials etc.), in last name alphabetical order:
```
of Authors.txt

**Comment by Floessie** [comment]
@luzpaz Thanks a lot!

Just one more question: Can codespell be applied to a file like [this](https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/default) as well? Or are there better tools?

**Pull request merged**
