### PR TITLE
Use ratings from image metadata

### PR DESCRIPTION
**Pull request by erjiang**
This patch modifies RT to use the Rating metadata from an image file if no Rank info is available from its pp3 sidecar file. This allows photographers to set star ratings in-camera (maybe during a photo shoot) and then see, filter by, and modify the ratings later in RT.

This currently does not support Rating=-1 which means "Rejected". Maybe a future patch can use Rating=-1 to mean InTrash=true in RT.

This is my first time modifying code in RT so please let me know what I should change.

### CODE REVIEW

**Comment by heckflosse** [comment]
@erjiang Can you provide some raw files with rating via filebin.net? Then I will test your branch.

**Comment by erjiang** [comment]
Unfortunately uploading to filebin.net doesn't seem to be working for me right now. I've attached a couple images to this issue instead:

[IMG_0905.CR2.zip](https://github.com/Beep6581/RawTherapee/files/3254721/IMG_0905.CR2.zip)
[IMG_1924.CR2.zip](https://github.com/Beep6581/RawTherapee/files/3254720/IMG_1924.CR2.zip)

Both of these photos have a Rating set using the in-camera software. `exiftool -Rating` should show it. Let me know if there's anything else I can provide.

**Comment by erjiang** [comment]
@heckflosse Hello, just wanted to check in and see if you had time to review this PR. Thanks!

**Comment by heckflosse** [comment]
@erjiang I'll test your branch now

**Comment by heckflosse** [comment]
@erjiang Works fine :+1:

**Review by Floessie — COMMENTED** [review]
Good work! :+1: 

The new code is well adapted to the inconsistencies in our code base. I kept it that way but fixed a few things nearby:

```patch
diff --git a/rtengine/imagedata.cc b/rtengine/imagedata.cc
index 26fe80f03..faa7ad5ed 100644
--- a/rtengine/imagedata.cc
+++ b/rtengine/imagedata.cc
@@ -69,37 +69,40 @@ FramesMetaData* FramesMetaData::fromFile (const Glib::ustring& fname, std::uniqu
     return new FramesData (fname, std::move(rml), firstFrameOnly);
 }
 
-FrameData::FrameData (rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory* rootDir, rtexif::TagDirectory* firstRootDir)
-    : frameRootDir(frameRootDir_), iptc(nullptr), time(), timeStamp(), iso_speed(0), aperture(0.), focal_len(0.), focal_len35mm(0.), focus_dist(0.f),
-      shutter(0.), expcomp(0.), make("Unknown"), model("Unknown"), orientation("Unknown"), rating(0), lens("Unknown"),
-      sampleFormat(IIOSF_UNKNOWN), isPixelShift(false), isHDR(false)
+FrameData::FrameData(rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory* rootDir, rtexif::TagDirectory* firstRootDir) :
+    frameRootDir(frameRootDir_),
+    iptc(nullptr),
+    time{},
+    timeStamp{},
+    iso_speed(0),
+    aperture(0.),
+    focal_len(0.),
+    focal_len35mm(0.),
+    focus_dist(0.f),
+    shutter(0.),
+    expcomp(0.),
+    make("Unknown"),
+    model("Unknown"),
+    orientation("Unknown"),
+    rating(0),
+    lens("Unknown"),
+    sampleFormat(IIOSF_UNKNOWN),
+    isPixelShift(false),
+    isHDR(false)
 {
-    memset (&time, 0, sizeof(time));
-
     if (!frameRootDir) {
         return;
     }
 
-    rtexif::Tag* tag;
-    rtexif::TagDirectory* newFrameRootDir = frameRootDir;
-
-    memset(&time, 0, sizeof(time));
-    timeStamp = 0;
-    iso_speed = 0;
-    aperture = 0.0;
-    focal_len = 0.0;
-    focal_len35mm = 0.0;
-    focus_dist = 0.0f;
-    shutter = 0.0;
-    expcomp = 0.0;
     make.clear();
     model.clear();
     serial.clear();
     orientation.clear();
     lens.clear();
-    rating = 0;
 
-    tag = newFrameRootDir->findTag("Make");
+    rtexif::TagDirectory* newFrameRootDir = frameRootDir;
+
+    rtexif::Tag* tag = newFrameRootDir->findTag("Make");
     if (!tag) {
         newFrameRootDir = rootDir;
         tag = newFrameRootDir->findTag("Make");
@@ -198,17 +201,11 @@ FrameData::FrameData (rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
     }
     char sXMPRating[64];
     if (newFrameRootDir->getXMPTagValue("xmp:Rating", sXMPRating)) {
-        rating = atoi(sXMPRating);
-    }
-    // guard against out-of-range values
-    if (rating > 5) {
-        rating = 5;
-    }
-    // Currently, Rating=-1 is not supported. A value of -1 should mean
-    // "Rejected" according to the specification. Maybe in the future, Rating=-1
-    // sets InTrash=true?
-    if (rating < 0) {
-        rating = 0;
+        // Guard against out-of-range values (<0, >5)
+        rating = rtengine::max(0, rtengine::min(5, atoi(sXMPRating)));
+        // Currently, Rating=-1 is not supported. A value of -1 should mean
+        // "Rejected" according to the specification. Maybe in the future, Rating=-1
+        // sets InTrash=true?
     }
 
     tag = newFrameRootDir->findTagUpward("MakerNote");
@@ -1197,15 +1194,21 @@ std::string FramesData::getOrientation(unsigned int frame) const
         }
     );
 }
-int FramesData::getRating (unsigned int frame) const
+
+int FramesData::getRating(unsigned int frame) const
 {
-    return frames.empty() || frame >= frames.size()  ? 0 : frames.at(frame)->getRating ();
+    return getFromFrame<int>(
+        frames,
+        frame,
+        [](const FrameData& frame_data)
+        {
+            return frame_data.getRating();
+        }
+    );
 }
 
-
 //------inherited functions--------------//
 
-
 std::string FramesMetaData::apertureToString (double aperture)
 {
 
diff --git a/rtengine/imagedata.h b/rtengine/imagedata.h
index 097a5cc80..d06820296 100644
--- a/rtengine/imagedata.h
+++ b/rtengine/imagedata.h
@@ -127,7 +127,7 @@ public:
     std::string getModel (unsigned int frame = 0) const override;
     std::string getLens (unsigned int frame = 0) const override;
     std::string getSerialNumber (unsigned int frame = 0) const;
-    std::string getOrientation (unsigned int frame = 0) const;
+    std::string getOrientation (unsigned int frame = 0) const override;
     int getRating (unsigned int frame = 0) const override;
 };
 
diff --git a/rtgui/cacheimagedata.cc b/rtgui/cacheimagedata.cc
index 47318990d..1756f523b 100644
--- a/rtgui/cacheimagedata.cc
+++ b/rtgui/cacheimagedata.cc
@@ -24,12 +24,37 @@
 
 #include "../rtengine/procparams.h"
 
-CacheImageData::CacheImageData ()
-    : md5(""), supported(false), format(FT_Invalid), rankOld(-1), inTrashOld(false), recentlySaved(false),
-      timeValid(false), year(0), month(0), day(0), hour(0), min(0), sec(0), exifValid(false), frameCount(1),
-      fnumber(0.0), shutter(0.0), focalLen(0.0), focalLen35mm(0.0), focusDist(0.f), iso(0), rating(0), isHDR (false),
-      isPixelShift (false), sensortype(rtengine::ST_NONE), sampleFormat(rtengine::IIOSF_UNKNOWN),
-      redAWBMul(-1.0), greenAWBMul(-1.0), blueAWBMul(-1.0), rotate(0), thumbImgType(0)
+CacheImageData::CacheImageData() :
+    supported(false),
+    format(FT_Invalid),
+    rankOld(-1),
+    inTrashOld(false),
+    recentlySaved(false),
+    timeValid(false),
+    year(0),
+    month(0),
+    day(0),
+    hour(0),
+    min(0),
+    sec(0),
+    exifValid(false),
+    frameCount(1),
+    fnumber(0.0),
+    shutter(0.0),
+    focalLen(0.0),
+    focalLen35mm(0.0),
+    focusDist(0.f),
+    iso(0),
+    rating(0),
+    isHDR (false),
+    isPixelShift (false),
+    sensortype(rtengine::ST_NONE),
+    sampleFormat(rtengine::IIOSF_UNKNOWN),
+    redAWBMul(-1.0),
+    greenAWBMul(-1.0),
+    blueAWBMul(-1.0),
+    rotate(0),
+    thumbImgType(0)
 {
 }
 
```

@erjiang If you don't mind please add that patch to your branch. Thanks.

Best,
Flössie

**Comment by erjiang** [comment]
@Floessie Sorry for the delay! I've applied the patch you've provided to the embedded-ratings branch. Anything else that needs to be changed?

**Comment by erjiang** [comment]
@Floessie Wanted to bump this and see if there's anything else that needs to be done. Thanks!

**Comment by Floessie** [comment]
@erjiang Sorry for being so late...

> Wanted to bump this and see if there's anything else that needs to be done.

Not from my point of view. Maybe @Beep6581 should have another look...

**Comment by Beep6581** [comment]
@erjiang 

Tested using various copies of a DNG file with XMP and Exif tags written to it using ExifTool 11.29, as my camera does not seem to allow me to rate images. The DNG file was created using Adobe DNG Converter 11.3 from a Sony ILCE-7M2 compressed ARW.

Test DNGs:
http://rawtherapee.com/shared/test_images/rating/

Sample ExifTool command:
```bash
exiftool -overwrite_original -'xmp:rating=3' -'exif:rating=2' "xmp_rating=3_exif_rating=2.dng"
```

Verified using:
```bash
ls -1 *.dng
'exif_rating=0.dng'
'exif_rating=0_xmp_rating=5.dng'
'exif_rating=5.dng'
'exif_rating=5_xmp_rating=4.dng'
org.dng
'xmp_rating=0.dng'
'xmp_rating=-1.dng'
'xmp_rating=-1_exif_rating=3.dng'
'xmp_rating=3_exif_rating=2.dng'
'xmp_rating=5.dng'

for f in *.dng; do echo "$f"; exiftool -G0 -*:rating "$f"; echo; done
exif_rating=0.dng
[EXIF]          Rating                          : 0
[MakerNotes]    Rating                          : 0

exif_rating=0_xmp_rating=5.dng
[XMP]           Rating                          : 5
[EXIF]          Rating                          : 0
[MakerNotes]    Rating                          : 0

exif_rating=5.dng
[EXIF]          Rating                          : 5
[MakerNotes]    Rating                          : 0

exif_rating=5_xmp_rating=4.dng
[XMP]           Rating                          : 4
[EXIF]          Rating                          : 5
[MakerNotes]    Rating                          : 0

org.dng
[MakerNotes]    Rating                          : 0

xmp_rating=0.dng
[XMP]           Rating                          : 0
[MakerNotes]    Rating                          : 0

xmp_rating=-1.dng
[XMP]           Rating                          : -1
[MakerNotes]    Rating                          : 0

xmp_rating=-1_exif_rating=3.dng
[XMP]           Rating                          : -1
[EXIF]          Rating                          : 3
[MakerNotes]    Rating                          : 0

xmp_rating=3_exif_rating=2.dng
[XMP]           Rating                          : 3
[EXIF]          Rating                          : 2
[MakerNotes]    Rating                          : 0

xmp_rating=5.dng
[XMP]           Rating                          : 5
[MakerNotes]    Rating                          : 0
```

All good so far in the File Browser:
screenshot_20190715_153736

No rating in resulting JPEG files when metadata copy mode = strip.
Original ranking transmitted when copy mode = copy unchanged.
RT-modified star ranking is not transmitted to saved JPEG file using any copy mode. Bug?

screenshot_20190715_153835

> This allows photographers to (...) modify the ratings later in RT.

When I open `xmp_rating=3_exif_rating=2.dng` and set the star ranking to 5 stars and save to JPEG using metadata copy mode = "apply modifications" or "copy unchanged", the resulting JPEG file only contains the following:

```bash
for f in *.jpg; do echo "$f"; exiftool -G0 -*:rating "$f"; echo; done
xmp_rating=3_exif_rating=2_rt_stars=5_applymodifications.jpg
[EXIF]          Rating                          : 2

xmp_rating=3_exif_rating=2_rt_stars=5_copyunchanged.jpg
[XMP]           Rating                          : 3
[EXIF]          Rating                          : 2

xmp_rating=3_exif_rating=2_rt_stars=5.jpg
[EXIF]          Rating                          : 2
```

Is that a bug? If not, how is a user to save the star ranking from RT to a JPEG file?

**Comment by erjiang** [comment]
I think there never was a way for RT to apply Rating metadata to an image export, and this patch does not add one either. So the result is:

Pre patch:
* Cannot read Rating from metadata.
* Cannot write new Rating to metadata.

Post patch:
* Can read Rating from metadata.
* Cannot write new Rating to metadata.

I guess the question is: do we need to also add in ability for user rating to be written in export's metadata before merging this patch?

**Comment by Beep6581** [comment]
@erjiang I am +1 for merging this as-is.

It would be nice and seems like a logical continuation if RT's star ranking was written to the saved files when in metadata copy mode "apply modifications". I opened issue #5380

**Review by Beep6581 — APPROVED** [review]

**Comment by Beep6581** [comment]
Merged, thank you @erjiang !

**Comment by Beep6581** [comment]
I documented it here:
http://rawpedia.rawtherapee.com/File_Browser#Rating

**Comment by Floessie** [comment]
@erjiang If your time permits, could you have a look at the `metadata-exiv2` branch? It needs a proper implementation based on `libexiv2`...

**Comment by erjiang** [comment]
@Floessie I'll see what I can do, but could you give me some context? What is the goal of the metadata-exiv2 branch? And do you just want me to look at the code that handles ratings in that branch?

**Comment by Beep6581** [comment]
@erjiang see #3801

**Comment by Floessie** [comment]
@erjiang When merging `dev`, the core of your work was lost and I had no time yet to port your code. After all, the one who implements something is the one who is the fastest to re-implement it. :wink:

**Pull request merged**
