### PR TITLE
added option to manually save the collapsed/expanded state of tools

### PR DESCRIPTION
**Pull request by agriggio**
a screenshot is worth more than a thousand words...

screenshot from 2017-08-21 18 44 49

### CODE REVIEW

**Comment by Desmis** [comment]
@agriggio 

Alberto.
I just test this option.
It works fine.

This option will be very useful to hide the parts of the menu that you do not want to see or use :)

Thank you
Jacques

**Comment by agriggio** [comment]
Hi Jacques, thanks for testing! I'll merge as soon as I go through astyle :-)

**Comment by Beep6581** [comment]
@agriggio version 3? :) #4010

**Comment by agriggio** [comment]
downloading now...

**Pull request merged**
