### PR TITLE
Update TooWaBlue theme (resizing to physical dimensions)

### PR DESCRIPTION
**Pull request by TooWaBoo**
Changes for "resizing to physical dimensions"

### CODE REVIEW

**Comment by heckflosse** [comment]
Added 5.5 milestone because #4894 also has 5.5 milestone set

**Comment by TooWaBoo** [comment]
The theme works with the current dev too and can be merged. No need to wait for "resizing to physical dimensions".

**Comment by heckflosse** [comment]
@TooWaBoo Ok. I will let @Beep6581 merge this

**Comment by Beep6581** [comment]
Roger

**Pull request merged**
