### PR TITLE
Fallback to RGB histogram if RAW histogram was enabled and a non-RAW is opened

### LINKED ISSUE #4813: If raw histogram is active, fall back to RGB histograms when opening non-raw image
When an raster image (Jpeg, Tiif or PNG) is opened in RT, the histogram is totally flat, whatever the kind is toggled (log or linear).
Bug present in current dev in Linux (but was present already in previous build from several days ago):
```
Version: 5.4-860-g5d00cb05b
Branch: dev
Commit: 5d00cb05b
Commit date: 2018-09-17
Compiler: cc 8.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.95.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
```

### PR DESCRIPTION
**Pull request by Thanatomanic**
I am trying to fix #4813 but I hope somebody can enlighten me on how to elegantly solve a programmatic issue. 

Please see line 766 in `rtgui/histogrampanel.cc` (can I link there directly?)

### CODE REVIEW

**Comment by Beep6581** [comment]
@Thanatomanic 

https://github.com/Thanatomanic/RawTherapee/blob/nonrawhistofix/rtgui/histogrampanel.cc#L766

**Comment by Beep6581** [comment]
Would be nice to squeeze this in for 5.5, to finish off the histogram improvements.

**Comment by Thanatomanic** [comment]
Ping @floessie and @heckflosse

**Comment by heckflosse** [comment]
@Thanatomanic I will test this when I have tested #4877

**Comment by Beep6581** [comment]
@Thanatomanic it seems this PR was never ready for merging, and now it has merge conflicts. I will close it - please handle it in an issue and open a PR once ready for merging.

**Pull request closed without merging**
