### PR TITLE
Add ability to export to an external editor within the same folder as the original file - issue 6195

### PR DESCRIPTION
**Pull request by Desmis**
Add ability to export to an external editor within the same folder as the original file #6195

### CODE REVIEW

**Comment by Desmis** [comment]
If nobody objects, I will merge this PR tomorrow :)

jacques

**Comment by Thanatomanic** [comment]
@Desmis I would like to push a minor fix to prevent the LGTM alert, is that okay?

**Comment by Desmis** [comment]
no problem you can :)

**Comment by Desmis** [comment]
@Thanatomanic 

Thank you, now works fine :)

Jacques

**Comment by heckflosse** [comment]
:+1: for merge

**Comment by Desmis** [comment]
@Thanatomanic  @heckflosse  @Lawrence37 
OK, thank you :)

I merge soon.

Jacques

**Pull request merged**
