### PR TITLE
Icons revised

### PR DESCRIPTION
**Pull request by Beep6581**
Cleanup, standardization, and all icons are now based on a vector source.
This adds the ability to have HiDPI icons.
Issues #4469 #3547

### CODE REVIEW

**Comment by TooWaBoo** [comment]
Will 16px icons also be available for the Toolbox?
The 24px icons are to big for 96dpi.

**Comment by TooWaBoo** [comment]
I suggest to use a gear icon for preferences like this: setting-gear-preferences-optimize-301e1939f0f2aa4c-512x512

**Comment by Beep6581** [comment]
@TooWaBoo yes, it's very easy now to add new icons or variations of icons. Please show screenshots at 96DPI.
The gear is used for processing.

**Comment by TooWaBoo** [comment]
grafikgrafik
grafikgrafik
grafikgrafik

**Comment by TooWaBoo** [comment]
grafik

**Comment by TooWaBoo** [comment]
If you want to play with different dpi-settings, you can use this style in your theme:
`* {-gtk-dpi: 96;}`

**Comment by Beep6581** [comment]
@TooWaBoo let's discuss this in #4469

**Pull request merged**
